"""Deferred PostgreSQL original vehicle transport acceptance, synthetic only.

Owner machine: python tests/postgres_vehicle_transport.py --pg-bin <trusted-bin>
Optional preparation check: --prepare-only (SQLite only, NOT PostgreSQL acceptance).
This script never accepts an existing server URL or company source. It creates and
stops its own local temporary cluster through the existing acceptance harness.
"""
from pathlib import Path
import argparse
import json
import os
import subprocess
import sys
import tempfile
import traceback
import uuid

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def synthetic_source(work):
    # Select the isolated fixture before ANY app/db/settings import. In particular,
    # importing this module or asking --help must not bind a user's configured DB.
    from tests import conftest as cf
    from fastapi.testclient import TestClient
    from tests import test_vehicle_transport as v, test_vehicle_transport_finance as f
    from tests import test_reconciliation as monthly
    from app.db import engine
    fixture = cf.isolated_database.__wrapped__()
    next(fixture)
    try:
        with TestClient(cf.app) as client:
            cf.login(client)
            _, row, _, locations = v.posted(client)
            account = f.account(client, 1)
            claim = f.claim(client, row)
            f.approve(client, row, claim['id'])
            f.cash(client, row, claim['id'], account)
            incoming = v.get(client, row)['claims'][0]['payments'][0]['id']
            monthly.batch(client)
            v.found_plan(client, row, 2)
            v.verify_transport()
            return str(engine.url), {
                'exception_id': row['id'], 'location_id': locations[2], 'vin': v.old.VIN,
                'claim_id': claim['id'], 'account_id': account, 'incoming_id': incoming,
                'password': cf.PASSWORD, 'synthetic_only': True,
            }
    finally:
        try:
            next(fixture)
        except StopIteration:
            pass


def run_native_target(state_file):
    """Private child entry, called only for the cluster generated by main()."""
    from sqlalchemy.engine import make_url
    url = make_url(os.environ['DATABASE_URL'])
    state = json.loads(Path(state_file).read_text(encoding='utf-8'))
    if (not state.get('synthetic_only') or not state.get('worker_nonce')
            or os.environ.get('HUAKANGOS_OWNED_ACCEPTANCE') != state['worker_nonce']
            or url.host != '127.0.0.1' or url.database != 'hk_transfer'
            or not (url.username or '').startswith('hk_') or url.get_backend_name() != 'postgresql'):
        raise ValueError('Not the generated synthetic acceptance target')
    # No conftest import here: target APIs must really use the generated PostgreSQL.
    from concurrent.futures import ThreadPoolExecutor
    from fastapi.testclient import TestClient
    from app.main import app
    from app.db import engine, today
    from app.reconciliation_service import CURRENT_DEFINITION_VERSION
    from sqlalchemy import text
    endpoint = '/api/vehicle-transport-exceptions/' + str(state['exception_id'])

    def login(client, name, sid):
        response = client.post('/api/auth/login', json={'username': name, 'password': state['password']},
                               headers={'X-App-Request': '1'})
        assert response.status_code == 200, response.text
        client.headers['X-CSRF-Token'] = client.cookies['dealer_csrf']
        client.headers['X-Store-ID'] = str(sid)

    def request(client, path, method='GET', body=None, status=200):
        response = client.request(method, path, **({'json': body} if body is not None else {}))
        assert response.status_code == status, response.text
        return response.json()

    def proof(client, financial=False):
        row = request(client, endpoint)
        response = client.post('/api/flow/cases/' + str(row['case_id']) + '/files',
            files={'file': ('synthetic-original.txt', '合成PG原事实核对凭据'.encode(), 'text/plain')},
            data={'category': 'receipt' if financial else 'evidence'})
        assert response.status_code == 200, response.text
        return response.json()['id']

    def command(client, action, values):
        row = request(client, endpoint)
        return request(client, endpoint + '/actions/' + action, 'POST', {
            'request_id': uuid.uuid4().hex, 'version': row['version'],
            'case_version': row['case_version'], 'exception_version': row['exception_version'],
            'values': values})

    with TestClient(app) as client:
        login(client, 'inventory', 2)
        evidence = proof(client)
        current = request(client, endpoint)
        values = {'vin': state['vin'], 'location_id': state['location_id'], 'confirmed': True,
                  'evidence_id': evidence, 'reason': '两个实际PG会话竞争同一原车找回仅可成功一次'}
        # Log both clients in before taking the concurrent original-case commands.
        with TestClient(app) as first, TestClient(app) as second:
            for other in (first, second):
                login(other, 'inventory', 2)
            def receive(other):
                return other.post(endpoint + '/actions/found_receive', json={
                    'request_id': uuid.uuid4().hex, 'version': current['version'],
                    'case_version': current['case_version'], 'exception_version': current['exception_version'], 'values': values})
            with ThreadPoolExecutor(max_workers=2) as pool:
                results = list(pool.map(receive, (first, second)))
            assert sorted(x.status_code for x in results) == [200, 409], [(x.status_code, x.text) for x in results]
        login(client, 'finance', 1)
        def claim_action(action, **extra):
            current = request(client, endpoint)
            claim = next(x for x in current['claims'] if x['id'] == state['claim_id'])
            value = dict(claim_id=claim['id'], claim_version=claim['version'], evidence_id=proof(client, True),
                         reason='本人核实原车找回后的原赔付调整与原路实际退回', **extra)
            if action == 'recovery_approve':
                value['plan_id'] = claim['pending_plan_id']
            return command(client, action, value)
        claim_action('recovery_plan', target_cents=0, due_date=today().isoformat())
        login(client, 'manager', 1)
        claim_action('recovery_approve')
        login(client, 'finance', 1)
        claim_action('recovery_refund', original_id=state['incoming_id'], account_id=state['account_id'],
                     amount_cents=100, business_date=today().isoformat(), reference='PG-REFUND-' + uuid.uuid4().hex, confirmed=True)
        statement = request(client, '/api/reconciliation/batches', 'POST', {
            'request_id': uuid.uuid4().hex, 'start': today().isoformat(), 'end': today().isoformat(),
            'reason': '实际PG原损失找回和原款退款后冻结同源月结'}, 201)
        assert statement['definition_version'] == CURRENT_DEFINITION_VERSION
        assert statement['summary']['period_cash_in_cents'] == statement['summary']['period_cash_out_cents'] == 100
        with engine.connect() as db:
            assert db.scalar(text('SELECT count(*) FROM vehicle_transport_found_receipts')) == 1
            assert db.scalar(text("SELECT count(*) FROM vehicles WHERE approval_state='approved'")) == 1
            assert db.scalar(text("SELECT purchase_cost_cents FROM vehicles WHERE approval_state='approved'")) == 10000001
            assert db.scalar(text('SELECT count(*) FROM cash_entries')) == 2
    (Path(state_file).parent / 'native-result.json').write_text(json.dumps({
        'status': 'passed', 'mode': 'actual-generated-postgresql', 'synthetic_only': True,
        'checks': ['two_registered_api_connections_one_found_receipt', 'one_active_original_vin_generation',
                   'original_claim_independent_zero_and_original_refund', 'same_source_current_monthly']}, indent=2), encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--pg-bin', type=Path)
    mode.add_argument('--prepare-only', action='store_true')
    args = parser.parse_args()
    work = Path(tempfile.mkdtemp(prefix='huakangos-vehicle-pg-')).resolve()
    if work.is_relative_to(ROOT):
        raise ValueError('Acceptance files must be outside the repository')
    report = {'status': 'running', 'synthetic_only': True,
              'actual_postgresql': False, 'temporary_directory': str(work)}
    print('Acceptance artifacts: ' + str(work), flush=True)
    try:
        source, state = synthetic_source(work)
        report['sqlite_source_prepared'] = True
        if args.prepare_only:
            report.update(status='prepared_only', note='SQLite source only; NOT PostgreSQL acceptance')
            return 0
        from tests.postgres_acceptance import temporary_postgres, run_binary, database_manifest, verify_sequences
        from scripts.migrate_database import transfer
        from app.db import make_engine
        with temporary_postgres(args.pg_bin.resolve(), work) as (exe, env, urls, version):
            report['server_version'] = version
            report['copied_rows'] = transfer(source, urls['hk_transfer'])
            state['worker_nonce'] = uuid.uuid4().hex
            state_file = work / 'owned-synthetic-state.json'
            state_file.write_text(json.dumps(state), encoding='utf-8'); state_file.chmod(0o600)
            child_env = {k: v for k, v in os.environ.items() if not k.upper().startswith('PG')}
            child_env.update(DATABASE_URL=urls['hk_transfer'], APP_ENV='test', FILE_SCAN_MODE='structure_only',
                ALLOW_AI_EXTERNAL='false', DEEPSEEK_API_KEY='', SCHEDULER_ENABLED='false', COOKIE_SECURE='false',
                ALLOWED_HOSTS='testserver,localhost,127.0.0.1', LEGACY_BUSINESS_WRITE='false',
                HUAKANGOS_OWNED_ACCEPTANCE=state['worker_nonce'])
            code = 'from tests.postgres_vehicle_transport import run_native_target; import sys; run_native_target(sys.argv[1])'
            with (work / 'native.log').open('wb') as log:
                completed = subprocess.run([sys.executable, '-c', code, str(state_file)], cwd=ROOT, env=child_env,
                    stdout=log, stderr=subprocess.STDOUT, timeout=300,
                    creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0))
            state_file.unlink(missing_ok=True)
            if completed.returncode:
                raise RuntimeError('Native PostgreSQL API verification failed; see native.log')
            report['native'] = json.loads((work / 'native-result.json').read_text(encoding='utf-8'))
            target = make_engine(urls['hk_transfer'])
            try:
                expected, files = database_manifest(target)
            finally:
                target.dispose()
            dump = work / 'vehicle-original.dump'
            run_binary(exe['pg_dump'], ['-Fc', '-d', 'hk_transfer', '-f', dump], work, env)
            run_binary(exe['pg_restore'], ['--exit-on-error', '-d', 'hk_restored', dump], work, env)
            restored = make_engine(urls['hk_restored'])
            try:
                actual, restored_files = database_manifest(restored)
                assert actual == expected and restored_files == files
                report['restored_tables'] = len(actual)
                report['verified_sequences'] = verify_sequences(restored)
            finally:
                restored.dispose()
            # Full business-origin validation after typed round-trip; the target
            # SQLite is new/empty, not a rewrite of the pre-command source.
            back = work / 'post-pg-restored.sqlite'
            transfer(urls['hk_restored'], 'sqlite:///' + back.as_posix())
            import sqlite3
            from app.backup_integrity import validate_sqlite
            with sqlite3.connect(back) as db:
                checks = validate_sqlite(db)
                assert checks['verified_vehicle_transport_found'] == 1
                report['roundtrip_business_checks'] = checks
            report.update(status='passed', actual_postgresql=True)
    except Exception as error:
        report.update(status='failed', failure_type=type(error).__name__)
        (work / 'failure.txt').write_text(traceback.format_exc(), encoding='utf-8')
    finally:
        (work / 'result.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
        print(json.dumps({k: report[k] for k in ('status', 'actual_postgresql', 'temporary_directory')}, ensure_ascii=False), flush=True)
    return 0 if report['status'] == 'passed' else 1


if __name__ == '__main__':
    raise SystemExit(main())
