"""Frozen legal identity in generated bytes, legacy hashes and scoped signatures."""
import io,json,uuid,zipfile
from types import SimpleNamespace
import pytest
from sqlalchemy import select,func
from fastapi import HTTPException
from app.db import SessionLocal
from app.models import User,CashEntry
from app.flow_models import Case,FileAsset,DocTemplate,StockMove
from app.flow_documents import ENTITY_FIELDS,snapshot,fingerprint,verify_signed
from app.tenancy import set_scope,project_user
from tests.conftest import login
from tests.test_business_entities import setup_policy,approved,config
from tests.test_sales_quotes import approve as sales_approve
from tests.test_vehicle_catalog import setup as catalog_setup,classify
from tests.test_workflow import approved_doc,evidence,action,master
from tests.test_retail import setup as stock_setup,technician
from tests.test_retail_bundles import publish,sale

def sales_source(c):
    from app.db import today
    from datetime import timedelta
    _,series,model=catalog_setup(c);classify(c,series,model)
    customer=master(c,'customers',{'name':'纯合成文档客户','phone':'13900005991','contact_allowed':True,'note':''})
    quote={'model_id':model['id'],'model_version':model['version'],'amount_cents':10000,'delivery_due':today().isoformat(),
        'valid_until':(today()+timedelta(days=7)).isoformat(),'addon':False,'insurance':False,'agency':False,'terms':'本版合成文档条款','reason':'生成待配车报价样本'}
    response=c.post('/api/sales-quotes/orders',json={'request_id':uuid.uuid4().hex,'customer_id':customer['id'],'quote':quote});assert response.status_code==201,response.text
    return response.json(),quote,customer

def original_file(c,row,kind):
    key=approved_doc(c,row,kind)
    with SessionLocal() as db:
        f=db.scalar(select(FileAsset).where(FileAsset.id==key));return key,dict(f.snapshot),f.source_fingerprint,bytes(f.content)

def document(c,row,kind,status=200):
    r=c.post('/api/flow/cases/'+str(row['id'])+'/documents',json={'kind':kind});assert r.status_code==status,r.text;return r.json()

def actor(db,username='admin',store=1):
    set_scope(db,[store],store);u=db.scalar(select(User).where(User.username==username));return project_user(u,u.role)

def text_doc(content):
    from docx import Document
    doc=Document(io.BytesIO(content));return '\n'.join(p.text for p in doc.paragraphs)+'\n'+'\n'.join(cell.text for t in doc.tables for row in t.rows for cell in row.cells)

def update_name(c,rev,name):
    approved(c,'revision',{'entity_id':rev['entity_id'],'expected_entity_version':rev['entity_version'],'code':rev['code'],'tax_identifier':rev['tax_identifier'],'legal_name':name,'registered_address':'修订后的合成登记地址，不覆盖原业务'})
    new=next(r for r in config(c)['revisions'] if r['legal_name']==name)
    approved(c,'store_binding',{'revision_id':new['revision_id'],'effective_from':__import__('app.db',fromlist=['today']).today().isoformat()})
    return new

def test_unknown_history_keeps_original_hash_and_production_formal_refuses_cache(client,monkeypatch):
    customer=master(client,'customers',{'name':'已取消的历史维修客户','phone':'13900005992','contact_allowed':True,'note':''})
    r=client.post('/api/repair-orders',json={'request_id':uuid.uuid4().hex,'customer_id':customer['id'],'plate':'合成OLD111','problem':'尚未施工的历史维修'});assert r.status_code==201,r.text
    row=r.json();fid,old,hashed,content=original_file(client,row,'repair_sheet')
    assert not set(ENTITY_FIELDS)&old.keys()
    r=client.post(f'/api/repair-orders/{row["id"]}/actions/cancel',json={'request_id':uuid.uuid4().hex,'version':row['version'],'values':{'reason':'实际未开工取消'}});assert r.status_code==200,r.text
    setup_policy(client)
    with SessionLocal() as db:
        user=actor(db);source=db.scalar(select(Case).where(Case.id==row['id']))
        assert snapshot(db,source,'repair_sheet',user=user)==old and fingerprint(snapshot(db,source,'repair_sheet',user=user))==hashed
    assert document(client,row,'repair_sheet')['id']==fid
    import app.config as cfg
    monkeypatch.setattr(cfg,'settings',SimpleNamespace(**(vars(cfg.settings)|{'environment':'production'})))
    r=document(client,row,'repair_sheet',409);assert '冻结的经营主体' in r['detail']
    with SessionLocal() as db:f=db.scalar(select(FileAsset).where(FileAsset.id==fid));assert bytes(f.content)==content and f.source_fingerprint==hashed and f.snapshot==old

def test_current_entity_revision_never_changes_old_snapshot_bytes_or_signed_source(client):
    rev,_=setup_policy(client);row,quote,customer=sales_source(client);row=sales_approve(client,row)
    fid,old,hashed,content=original_file(client,row,'contract');signed=evidence(client,row,'signed_contract',fid)
    assert old['经营主体法定名称']==rev['legal_name'] and old['主体资料版本编号']==rev['revision_id']
    assert old['主体识别号']==rev['tax_identifier'] and 'SYNTH-BANK' not in json.dumps(old,ensure_ascii=False)
    assert not {'entity_version','account_id','channel_identifier','contact_phone'}&old.keys()
    new=update_name(client,rev,'修订后的纯合成主体名称')
    with SessionLocal() as db:
        user=actor(db);source=db.scalar(select(Case).where(Case.id==row['id']))
        assert snapshot(db,source,'contract',user=user)==old
        assert verify_signed(db,source,signed,'contract',user=user).id==signed
        with pytest.raises(HTTPException):snapshot(db,source,'contract')
    assert document(client,row,'contract')['id']==fid
    response=client.post('/api/sales-quotes/orders',json={'request_id':uuid.uuid4().hex,'customer_id':customer['id'],'quote':quote});assert response.status_code==201,response.text
    next_row=sales_approve(client,response.json());_,current,_,new_bytes=original_file(client,next_row,'contract')
    assert current['经营主体法定名称']==new['legal_name'] and current['主体资料版本编号']==new['revision_id']
    assert old['经营主体法定名称'] in text_doc(content) and new['legal_name'] not in text_doc(content)
    assert new['legal_name'] in text_doc(new_bytes)

def test_repair_and_retail_use_frozen_entity_and_business_projection_hides_accounts(client,monkeypatch):
    rev,_=setup_policy(client);items,customer,work,_=stock_setup(client,True);rule=publish(client,items,work)
    retail=sale(client,rule,customer)
    response=client.post('/api/repair-orders',json={'request_id':uuid.uuid4().hex,'customer_id':customer['id'],'plate':'合成DOC123','problem':'合成有据维修事项'});assert response.status_code==201,response.text
    repair=response.json()
    for row,kind in ((retail,'retail_quote'),(repair,'repair_sheet')):
        _,info,_,content=original_file(client,row,kind);assert info['经营主体法定名称']==rev['legal_name']
        assert all(str(info[k]) in text_doc(content) for k in ENTITY_FIELDS)
        assert 'SYNTH-BANK' not in text_doc(content)
        import app.config as cfg
        with monkeypatch.context() as m:
            m.setattr(cfg,'settings',SimpleNamespace(**(vars(cfg.settings)|{'environment':'production'})));assert document(client,row,kind)['id']
    login(client,'inventory');result=document(client,repair,'business')
    with SessionLocal() as db:
        file=db.scalar(select(FileAsset).where(FileAsset.id==result['id']));assert file.snapshot['经营主体法定名称']==rev['legal_name'] and '约定金额（元）' not in file.snapshot
        assert 'channel_identifier' not in str(file.snapshot) and 'SYNTH-BANK' not in text_doc(bytes(file.content))
    document(client,repair,'repair_sheet',403)

def test_production_unknown_repair_and_boutique_formal_refused_and_draft_explicit(client,monkeypatch):
    items,customer,work,_=stock_setup(client,True);retail=sale(client,publish(client,items,work),customer)
    response=client.post('/api/repair-orders',json={'request_id':uuid.uuid4().hex,'customer_id':customer['id'],'plate':'合成OLD123','problem':'无主体的历史维修'});assert response.status_code==201,response.text
    repair=response.json()
    order,_,_=sales_source(client);order=sales_approve(client,order)
    for row,kind in ((retail,'retail_quote'),(repair,'repair_sheet'),(order,'contract')):original_file(client,row,kind)
    import app.config as cfg
    monkeypatch.setattr(cfg,'settings',SimpleNamespace(**(vars(cfg.settings)|{'environment':'production'})))
    for row,kind in ((retail,'retail_quote'),(repair,'repair_sheet'),(order,'contract')):document(client,row,kind,409)
    # A clearly unapproved style sample is not a formal business document.
    t=next(t for t in client.get('/api/flow/master/templates').json()['items'] if t['kind']=='repair_sheet')
    r=client.put(f'/api/flow/master/templates/{t["id"]}',json={'version':t['version'],'values':{'title':t['title'],'clauses':t['clauses'],'approved':False}});assert r.status_code==200,r.text
    result=document(client,repair,'repair_sheet')
    with SessionLocal() as db:
        f=db.scalar(select(FileAsset).where(FileAsset.id==result['id']));assert not f.template_approved and '样式草稿' in text_doc(bytes(f.content))

def test_source_permission_store_and_current_user_are_required(client):
    setup_policy(client);row,_,_=sales_source(client);row=sales_approve(client,row);fid,info,_,_=original_file(client,row,'contract')
    login(client,'sales');assert client.post('/api/flow/cases/'+str(row['id'])+'/documents',json={'kind':'contract'}).status_code==404
    with SessionLocal() as db:
        source=db.scalar(select(Case).where(Case.id==row['id']));user=actor(db,'sales')
        with pytest.raises(HTTPException):snapshot(db,source,'contract',user=user)
    login(client);response=client.post('/api/stores',json={'code':'DOCOTHER','name':'另一合成文档门店'});assert response.status_code==201,response.text
    client.headers['X-Store-ID']='2';assert client.post('/api/flow/cases/'+str(row['id'])+'/documents',json={'kind':'contract'}).status_code==404
    with SessionLocal() as db:
        source=db.scalar(select(Case).where(Case.id==row['id']));user=actor(db,store=2)
        with pytest.raises(HTTPException):snapshot(db,source,'contract',user=user)
    client.headers['X-Store-ID']='all';assert client.post('/api/flow/cases/'+str(row['id'])+'/documents',json={'kind':'contract'}).status_code==409
