"""Frozen v7 source fields. Changes require an explicit next definition version."""

FROZEN_FIELDS = {'addon_acceptances': ('case_id',
                       'quote_id',
                       'amount_cents',
                       'value_cents',
                       'business_date',
                       'evidence_id',
                       'actor_id'),
 'addon_approvals': ('quote_id',
                     'minimum_cents',
                     'allow_below_minimum',
                     'reason',
                     'evidence_id',
                     'actor_id'),
 'addon_authorizations': ('quote_id', 'evidence_id', 'actor_id'),
 'addon_dispatches': ('case_id',
                      'line_id',
                      'line_key',
                      'target_id',
                      'stock_move_id',
                      'quantity_milli',
                      'value_cents',
                      'goods_cents',
                      'installation_cents',
                      'evidence_id',
                      'actor_id'),
 'addon_inspections': ('installation_id', 'passed', 'result', 'evidence_id', 'actor_id'),
 'addon_installations': ('dispatch_id', 'quantity_milli', 'result', 'evidence_id', 'actor_id'),
 'addon_lines': ('quote_id',
                 'line_key',
                 'item_id',
                 'work_item_id',
                 'sku',
                 'name',
                 'unit',
                 'work_code',
                 'work_name',
                 'quantity_milli',
                 'goods_unit_cents',
                 'installation_unit_cents',
                 'goods_cents',
                 'installation_cents'),
 'addon_orders': ('source_order_id',
                  'customer_id',
                  'source_snapshot',
                  'delivery_blocking',
                  'reason',
                  'actor_id'),
 'addon_payments': ('case_id',
                    'payment_link_id',
                    'credit_link_id',
                    'resolution_id',
                    'evidence_id',
                    'actor_id'),
 'addon_quotes': ('case_id',
                  'revision',
                  'goods_cents',
                  'installation_cents',
                  'discount_cents',
                  'digest',
                  'reason',
                  'actor_id'),
 'addon_rectifications': ('inspection_id', 'result', 'evidence_id', 'actor_id'),
 'addon_reservations': ('case_id',
                        'line_id',
                        'line_key',
                        'item_id',
                        'quantity_milli',
                        'purpose',
                        'actor_id'),
 'addon_resolution_facts': ('resolution_id', 'action', 'result', 'evidence_id', 'actor_id'),
 'addon_resolutions': ('case_id',
                       'quote_id',
                       'kind',
                       'lines',
                       'reason',
                       'digest',
                       'evidence_id',
                       'requested_by'),
 'addon_return_postings': ('case_id',
                           'resolution_id',
                           'line_id',
                           'line_key',
                           'dispatch_id',
                           'installation_id',
                           'stock_move_id',
                           'quantity_milli',
                           'value_cents',
                           'goods_cents',
                           'installation_cents',
                           'retained_cents',
                           'acceptance_id',
                           'business_date',
                           'evidence_id',
                           'actor_id'),
 'addon_targets': ('case_id', 'vehicle_id', 'vin', 'source_version', 'actor_id'),
 'addon_vehicle_handovers': ('case_id',
                             'resolution_id',
                             'aftercare_case_id',
                             'vehicle_operation_id',
                             'new_vehicle_id',
                             'vin',
                             'attachments',
                             'incremental_value_cents',
                             'evidence_id',
                             'actor_id'),
 'insurance_commission_payments': ('case_id',
                                   'confirmation_id',
                                   'original_id',
                                   'amount_cents',
                                   'direction',
                                   'cash_id',
                                   'account_id',
                                   'reference',
                                   'business_date',
                                   'evidence_id',
                                   'actor_id'),
 'insurance_commission_reviews': ('confirmation_id',
                                  'decision',
                                  'reason',
                                  'business_date',
                                  'evidence_id',
                                  'actor_id'),
 'insurance_commissions': ('case_id',
                           'revision',
                           'target_cents',
                           'previous_cents',
                           'reason',
                           'evidence_id',
                           'actor_id'),
 'insurance_consents': ('quote_id', 'digest', 'evidence_id', 'actor_id'),
 'insurance_customer_refunds': ('plan_id',
                                'original_tender_id',
                                'reversal_tender_id',
                                'amount_cents',
                                'evidence_id',
                                'actor_id'),
 'insurance_direct_entries': ('case_id',
                              'purpose',
                              'original_id',
                              'amount_cents',
                              'external_reference',
                              'business_date',
                              'evidence_id',
                              'actor_id'),
 'insurance_orders': ('source_order_id',
                      'customer_vehicle_id',
                      'renewal_task_id',
                      'delivery_blocking',
                      'customer_name',
                      'vin',
                      'vehicle_snapshot',
                      'reason'),
 'insurance_pass_entries': ('case_id',
                            'tender_id',
                            'purpose',
                            'original_id',
                            'amount_cents',
                            'cash_id',
                            'account_id',
                            'reference',
                            'business_date',
                            'evidence_id',
                            'actor_id'),
 'insurance_quote_cancellations': ('quote_id', 'reason', 'actor_id'),
 'insurance_quotes': ('case_id',
                      'revision',
                      'insurer_id',
                      'insurer_snapshot',
                      'lines',
                      'premium_cents',
                      'expected_commission_cents',
                      'collection_mode',
                      'start_date',
                      'end_date',
                      'valid_until',
                      'terms',
                      'reason',
                      'digest',
                      'actor_id'),
 'insurance_renewal_links': ('case_id', 'previous_policy_id', 'actor_id'),
 'insurance_results': ('submission_id',
                       'case_id',
                       'insurer_id',
                       'outcome',
                       'policy_number',
                       'result',
                       'business_date',
                       'observation_id',
                       'evidence_id',
                       'actor_id'),
 'insurance_reviews': ('quote_id', 'decision', 'reason', 'evidence_id', 'actor_id'),
 'insurance_submissions': ('quote_id',
                           'external_reference',
                           'business_date',
                           'evidence_id',
                           'actor_id'),
 'insurance_tenders': ('case_id',
                       'payment_link_id',
                       'credit_link_id',
                       'original_id',
                       'amount_cents',
                       'evidence_id',
                       'actor_id'),
 'insurance_termination_applications': ('plan_id', 'business_date', 'evidence_id', 'actor_id'),
 'insurance_termination_cancellations': ('plan_id', 'reason', 'actor_id'),
 'insurance_termination_consents': ('plan_id', 'digest', 'evidence_id', 'actor_id'),
 'insurance_termination_reviews': ('plan_id', 'decision', 'reason', 'evidence_id', 'actor_id'),
 'insurance_terminations': ('case_id',
                            'quote_id',
                            'revision',
                            'retained_cents',
                            'returns',
                            'external_result',
                            'reason',
                            'digest',
                            'evidence_id',
                            'actor_id'),
 'procurement_return_valuations': ('quantity_before_milli',
                                   'value_before_cents',
                                   'inventory_cost_cents',
                                   'supplier_credit_cents',
                                   'variance_cents')}

JSON_FIELDS = {'addon_acceptances': (),
 'addon_approvals': (),
 'addon_authorizations': (),
 'addon_dispatches': (),
 'addon_inspections': (),
 'addon_installations': (),
 'addon_lines': (),
 'addon_orders': ('source_snapshot',),
 'addon_payments': (),
 'addon_quotes': (),
 'addon_rectifications': (),
 'addon_reservations': (),
 'addon_resolution_facts': (),
 'addon_resolutions': ('lines',),
 'addon_return_postings': (),
 'addon_targets': (),
 'addon_vehicle_handovers': ('attachments',),
 'insurance_commission_payments': (),
 'insurance_commission_reviews': (),
 'insurance_commissions': (),
 'insurance_consents': (),
 'insurance_customer_refunds': (),
 'insurance_direct_entries': (),
 'insurance_orders': ('vehicle_snapshot',),
 'insurance_pass_entries': (),
 'insurance_quote_cancellations': (),
 'insurance_quotes': ('insurer_snapshot', 'lines'),
 'insurance_renewal_links': (),
 'insurance_results': (),
 'insurance_reviews': (),
 'insurance_submissions': (),
 'insurance_tenders': (),
 'insurance_termination_applications': (),
 'insurance_termination_cancellations': (),
 'insurance_termination_consents': (),
 'insurance_termination_reviews': (),
 'insurance_terminations': ('returns',),
 'procurement_return_valuations': ()}

CURRENT_NAMES = frozenset(FROZEN_FIELDS)
