"""V12: local immutable original-VIN sources, never an expansion of v1--11.

Physical fact, original asset cost, bilateral liability and actual cash are
separate books. Claim payments reference cash already included exactly once.
No mutable header state is attributed retroactively to a sealed period.
"""
FROZEN_FIELDS = {'vehicle_transport_claim_payments': ('account_id',
                                      'actor_id',
                                      'amount_cents',
                                      'business_date',
                                      'cash_id',
                                      'claim_id',
                                      'created_at',
                                      'direction',
                                      'evidence_id',
                                      'original_id',
                                      'plan_id',
                                      'reference'),
 'vehicle_transport_claim_plans': ('actor_id',
                                   'claim_id',
                                   'created_at',
                                   'due_date',
                                   'evidence_id',
                                   'reason',
                                   'revision',
                                   'target_cents'),
 'vehicle_transport_claim_reviews': ('actor_id',
                                     'business_date',
                                     'created_at',
                                     'decision',
                                     'evidence_id',
                                     'plan_id',
                                     'reason'),
 'vehicle_transport_claim_withdrawals': ('actor_id', 'created_at', 'evidence_id', 'plan_id', 'reason'),
 'vehicle_transport_claims': ('counterparty_kind',
                              'counterparty_snapshot',
                              'created_at',
                              'exception_id',
                              'insurer_id',
                              'requested_by',
                              'supplier_id'),
 'vehicle_transport_disposals': ('actor_id',
                                 'business_date',
                                 'created_at',
                                 'evidence_id',
                                 'exception_id',
                                 'plan_id',
                                 'reason',
                                 'vin'),
 'vehicle_transport_exceptions': ('created_at',
                                  'evidence_id',
                                  'kind',
                                  'origin_status',
                                  'original_id',
                                  'reason',
                                  'requested_by',
                                  'transfer_id'),
 'vehicle_transport_found_receipts': ('actor_id',
                                      'business_date',
                                      'case_id',
                                      'created_at',
                                      'evidence_id',
                                      'exception_id',
                                      'location_id',
                                      'loss_id',
                                      'observation_id',
                                      'plan_id',
                                      'transfer_id',
                                      'value_cents',
                                      'vehicle_id'),
 'vehicle_transport_found_settlements': ('amount_cents',
                                         'business_date',
                                         'counterparty_store_id',
                                         'loss_id',
                                         'receipt_id',
                                         'transfer_id'),
 'vehicle_transport_found_unavailable': ('actor_id',
                                         'created_at',
                                         'evidence_id',
                                         'exception_id',
                                         'kind',
                                         'observation_id',
                                         'plan_id',
                                         'reason',
                                         'vin'),
 'vehicle_transport_loss_settlements': ('amount_cents',
                                        'business_date',
                                        'counterparty_store_id',
                                        'exception_id',
                                        'loss_id',
                                        'transfer_id'),
 'vehicle_transport_losses': ('actor_id',
                              'business_date',
                              'case_id',
                              'created_at',
                              'destination_bearer_cents',
                              'evidence_id',
                              'exception_id',
                              'kind',
                              'original_id',
                              'plan_id',
                              'source_bearer_cents',
                              'transfer_id',
                              'value_cents'),
 'vehicle_transport_observations': ('actor_id',
                                    'actual_at',
                                    'created_at',
                                    'evidence_id',
                                    'exception_id',
                                    'kind',
                                    'reason',
                                    'vin'),
 'vehicle_transport_plans': ('actor_id',
                             'created_at',
                             'destination_bearer_cents',
                             'destination_observation_id',
                             'evidence_id',
                             'exception_id',
                             'found_observation_id',
                             'kind',
                             'loss_method',
                             'origin_digest',
                             'reason',
                             'receiving_store_id',
                             'revision',
                             'source_bearer_cents',
                             'source_observation_id'),
 'vehicle_transport_reviews': ('actor_id', 'created_at', 'decision', 'evidence_id', 'plan_id', 'reason'),
 'vehicle_transport_withdrawals': ('actor_id', 'created_at', 'evidence_id', 'plan_id', 'reason')}

SOURCE_FIELDS = {'vehicle_transport_claim_payments': ('account_id',
                                      'actor_id',
                                      'amount_cents',
                                      'business_date',
                                      'cash_id',
                                      'claim_id',
                                      'created_at',
                                      'direction',
                                      'evidence_id',
                                      'id',
                                      'original_id',
                                      'plan_id',
                                      'reference',
                                      'store_id'),
 'vehicle_transport_claim_plans': ('actor_id',
                                   'claim_id',
                                   'created_at',
                                   'due_date',
                                   'evidence_id',
                                   'id',
                                   'reason',
                                   'revision',
                                   'store_id',
                                   'target_cents'),
 'vehicle_transport_claim_reviews': ('actor_id',
                                     'business_date',
                                     'created_at',
                                     'decision',
                                     'evidence_id',
                                     'id',
                                     'plan_id',
                                     'reason',
                                     'store_id'),
 'vehicle_transport_claim_withdrawals': ('actor_id',
                                         'created_at',
                                         'evidence_id',
                                         'id',
                                         'plan_id',
                                         'reason',
                                         'store_id'),
 'vehicle_transport_claims': ('counterparty_kind',
                              'counterparty_snapshot',
                              'created_at',
                              'exception_id',
                              'id',
                              'insurer_id',
                              'requested_by',
                              'store_id',
                              'supplier_id'),
 'vehicle_transport_disposals': ('actor_id',
                                 'business_date',
                                 'created_at',
                                 'evidence_id',
                                 'exception_id',
                                 'id',
                                 'plan_id',
                                 'reason',
                                 'store_id',
                                 'vin'),
 'vehicle_transport_exceptions': ('created_at',
                                  'evidence_id',
                                  'id',
                                  'kind',
                                  'origin_status',
                                  'original_id',
                                  'reason',
                                  'requested_by',
                                  'store_id',
                                  'transfer_id'),
 'vehicle_transport_found_receipts': ('actor_id',
                                      'business_date',
                                      'case_id',
                                      'created_at',
                                      'evidence_id',
                                      'exception_id',
                                      'id',
                                      'location_id',
                                      'loss_id',
                                      'observation_id',
                                      'plan_id',
                                      'store_id',
                                      'transfer_id',
                                      'value_cents',
                                      'vehicle_id'),
 'vehicle_transport_found_settlements': ('amount_cents',
                                         'business_date',
                                         'counterparty_store_id',
                                         'id',
                                         'loss_id',
                                         'receipt_id',
                                         'store_id',
                                         'transfer_id'),
 'vehicle_transport_found_unavailable': ('actor_id',
                                         'created_at',
                                         'evidence_id',
                                         'exception_id',
                                         'id',
                                         'kind',
                                         'observation_id',
                                         'plan_id',
                                         'reason',
                                         'store_id',
                                         'vin'),
 'vehicle_transport_loss_settlements': ('amount_cents',
                                        'business_date',
                                        'counterparty_store_id',
                                        'exception_id',
                                        'id',
                                        'loss_id',
                                        'store_id',
                                        'transfer_id'),
 'vehicle_transport_losses': ('actor_id',
                              'business_date',
                              'case_id',
                              'created_at',
                              'destination_bearer_cents',
                              'evidence_id',
                              'exception_id',
                              'id',
                              'kind',
                              'original_id',
                              'plan_id',
                              'source_bearer_cents',
                              'store_id',
                              'transfer_id',
                              'value_cents'),
 'vehicle_transport_observations': ('actor_id',
                                    'actual_at',
                                    'created_at',
                                    'evidence_id',
                                    'exception_id',
                                    'id',
                                    'kind',
                                    'reason',
                                    'store_id',
                                    'vin'),
 'vehicle_transport_plans': ('actor_id',
                             'created_at',
                             'destination_bearer_cents',
                             'destination_observation_id',
                             'evidence_id',
                             'exception_id',
                             'found_observation_id',
                             'id',
                             'kind',
                             'loss_method',
                             'origin_digest',
                             'reason',
                             'receiving_store_id',
                             'revision',
                             'source_bearer_cents',
                             'source_observation_id',
                             'store_id'),
 'vehicle_transport_reviews': ('actor_id',
                               'created_at',
                               'decision',
                               'evidence_id',
                               'id',
                               'plan_id',
                               'reason',
                               'store_id'),
 'vehicle_transport_withdrawals': ('actor_id', 'created_at', 'evidence_id', 'id', 'plan_id', 'reason', 'store_id')}

DATETIME_FIELDS = {'vehicle_transport_claim_payments': ('created_at',),
 'vehicle_transport_claim_plans': ('created_at',),
 'vehicle_transport_claim_reviews': ('created_at',),
 'vehicle_transport_claim_withdrawals': ('created_at',),
 'vehicle_transport_claims': ('created_at',),
 'vehicle_transport_disposals': ('created_at',),
 'vehicle_transport_exceptions': ('created_at',),
 'vehicle_transport_found_receipts': ('created_at',),
 'vehicle_transport_found_settlements': (),
 'vehicle_transport_found_unavailable': ('created_at',),
 'vehicle_transport_loss_settlements': (),
 'vehicle_transport_losses': ('created_at',),
 'vehicle_transport_observations': ('actual_at', 'created_at'),
 'vehicle_transport_plans': ('created_at',),
 'vehicle_transport_reviews': ('created_at',),
 'vehicle_transport_withdrawals': ('created_at',)}

JSON_FIELDS = {'vehicle_transport_claim_payments': (),
 'vehicle_transport_claim_plans': (),
 'vehicle_transport_claim_reviews': (),
 'vehicle_transport_claim_withdrawals': (),
 'vehicle_transport_claims': ('counterparty_snapshot',),
 'vehicle_transport_disposals': (),
 'vehicle_transport_exceptions': (),
 'vehicle_transport_found_receipts': (),
 'vehicle_transport_found_settlements': (),
 'vehicle_transport_found_unavailable': (),
 'vehicle_transport_loss_settlements': (),
 'vehicle_transport_losses': (),
 'vehicle_transport_observations': (),
 'vehicle_transport_plans': (),
 'vehicle_transport_reviews': (),
 'vehicle_transport_withdrawals': ()}

PERIOD_NAMES = {'vehicle_transport_disposals', 'vehicle_transport_found_receipts', 'vehicle_transport_losses', 'vehicle_transport_claim_payments'}
CURRENT_NAMES = set(FROZEN_FIELDS) - PERIOD_NAMES

def source_summary(entries, start, end):
    result={'count':len(entries),'amount_cents':0,'value_cents':0,'quantity_milli_by_item':{},'units_by_kind':{}}
    for entry in entries:
        name=entry['source'];data=entry['data']
        basis='period' if name in PERIOD_NAMES else 'current'
        if entry['basis']!=basis or set(data)!=set(SOURCE_FIELDS[name]):
            raise ValueError('冻结原车运输来源字段或期间口径不一致')
        if basis=='period' and not start<=data.get('business_date','')<=end:
            raise ValueError('冻结原车实际过账不属于所选期间')
        for field in ('amount_cents','value_cents'):
            if field in data:
                value=data[field]
                if type(value) is not int:raise ValueError('原车核算金额必须是整数分')
                result[field]+=value*(-1 if field=='amount_cents' and data.get('direction')=='out' else 1)
    return result


def validate_frozen_summary(manifest, summary, start, end):
    for name in FROZEN_FIELDS:
        if summary.get(name)!=source_summary([e for e in manifest if e['source']==name],start,end):
            raise ValueError('冻结原车运输摘要与所列原事实不一致')
