"""database-scoped demo marker
Revision ID: 59100965745a
Revises: 9c14d5019c1f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '59100965745a'
down_revision: Union[str, Sequence[str], None] = '9c14d5019c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metadata',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_metadata')
    # ### end Alembic commands ###
