"""initial relational schema
Revision ID: 9c14d5019c1f
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9c14d5019c1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('ai_requested', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('deterministic_summary', sa.Text(), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('ai_status', sa.String(length=30), nullable=False),
    sa.Column('ai_result', sa.JSON(), nullable=True),
    sa.Column('ai_error', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date', 'source_revision', 'config_hash', 'ai_requested', name='uq_report_input')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_business_date'), ['business_date'], unique=False)

    op.create_table('job_leases',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin','manager','sales','inventory','service','finance','auditor')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_rule_code'), ['rule_code'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=80), nullable=False),
    sa.Column('insurer', sa.String(length=100), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=False),
    sa.Column('policy_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('premium_cents', sa.BigInteger(), nullable=False),
    sa.Column('commission_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('approval_state', sa.String(length=15), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("approval_state IN ('draft','submitted','approved','rejected','void')", name='ck_policy_approval'),
    sa.CheckConstraint('premium_cents > 0 AND commission_cents >= 0 AND end_date >= start_date', name='ck_policy_values'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_no'),
    sa.UniqueConstraint('policy_number')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_approval_state'), ['approval_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_business_date'), ['business_date'], unique=False)

    op.create_table('vehicles',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('purchase_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('list_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('approval_state', sa.String(length=15), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("approval_state IN ('draft','submitted','approved','rejected','void')", name='ck_vehicle_approval'),
    sa.CheckConstraint('purchase_cost_cents >= 0 AND list_price_cents >= 0', name='ck_vehicle_money'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_no'),
    sa.UniqueConstraint('vin')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_approval_state'), ['approval_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_business_date'), ['business_date'], unique=False)

    op.create_table('repairs',
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=False),
    sa.Column('service_advisor', sa.String(length=80), nullable=False),
    sa.Column('repair_type', sa.String(length=20), nullable=False),
    sa.Column('repair_stage', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('labor_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('parts_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('discount_cents', sa.BigInteger(), nullable=False),
    sa.Column('cost_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('approval_state', sa.String(length=15), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("(repair_stage = 'open' AND completion_date IS NULL) OR (repair_stage = 'completed' AND completion_date IS NOT NULL AND completion_date >= business_date)", name='ck_repair_completion'),
    sa.CheckConstraint("approval_state IN ('draft','submitted','approved','rejected','void')", name='ck_repair_approval'),
    sa.CheckConstraint("repair_stage IN ('open','completed')", name='ck_repair_stage'),
    sa.CheckConstraint('labor_amount_cents >= 0 AND parts_amount_cents >= 0 AND discount_cents >= 0 AND cost_amount_cents >= 0 AND discount_cents <= labor_amount_cents + parts_amount_cents', name='ck_repair_money'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_no')
    )
    with op.batch_alter_table('repairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repairs_approval_state'), ['approval_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_repairs_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_repairs_completion_date'), ['completion_date'], unique=False)

    op.create_table('sales',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('active_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=False),
    sa.Column('salesperson', sa.String(length=80), nullable=False),
    sa.Column('sale_stage', sa.String(length=15), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('contract_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('purchase_cost_snapshot_cents', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('approval_state', sa.String(length=15), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("(approval_state = 'approved' AND active_vehicle_id IS NOT NULL AND active_vehicle_id = vehicle_id) OR (approval_state != 'approved' AND active_vehicle_id IS NULL)", name='ck_sale_allocation'),
    sa.CheckConstraint("(sale_stage = 'ordered' AND delivery_date IS NULL) OR (sale_stage = 'delivered' AND delivery_date IS NOT NULL AND delivery_date >= business_date)", name='ck_sale_delivery'),
    sa.CheckConstraint("approval_state IN ('draft','submitted','approved','rejected','void')", name='ck_sale_approval'),
    sa.CheckConstraint("sale_stage IN ('ordered','delivered')", name='ck_sale_stage'),
    sa.CheckConstraint('contract_amount_cents > 0', name='ck_sale_money'),
    sa.ForeignKeyConstraint(['active_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_vehicle_id'),
    sa.UniqueConstraint('doc_no')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_approval_state'), ['approval_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('cash_entries',
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('counter_account', sa.String(length=100), nullable=False),
    sa.Column('counterparty', sa.String(length=120), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('voucher_no', sa.String(length=100), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('approval_state', sa.String(length=15), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("approval_state IN ('draft','submitted','approved','rejected','void')", name='ck_cash_approval'),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_cash_direction'),
    sa.CheckConstraint('(CASE WHEN sale_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN repair_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN policy_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN vehicle_id IS NOT NULL THEN 1 ELSE 0 END) <= 1', name='ck_cash_one_link'),
    sa.CheckConstraint('amount_cents > 0', name='ck_cash_money'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_no')
    )
    with op.batch_alter_table('cash_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_entries_approval_state'), ['approval_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_entries_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_entries_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_entries_repair_id'), ['repair_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_entries_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_entries_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_entries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_cash_entries_sale_id'))
        batch_op.drop_index(batch_op.f('ix_cash_entries_repair_id'))
        batch_op.drop_index(batch_op.f('ix_cash_entries_policy_id'))
        batch_op.drop_index(batch_op.f('ix_cash_entries_business_date'))
        batch_op.drop_index(batch_op.f('ix_cash_entries_approval_state'))

    op.drop_table('cash_entries')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_sales_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_sales_business_date'))
        batch_op.drop_index(batch_op.f('ix_sales_approval_state'))

    op.drop_table('sales')
    with op.batch_alter_table('repairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repairs_completion_date'))
        batch_op.drop_index(batch_op.f('ix_repairs_business_date'))
        batch_op.drop_index(batch_op.f('ix_repairs_approval_state'))

    op.drop_table('repairs')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_business_date'))
        batch_op.drop_index(batch_op.f('ix_vehicles_approval_state'))

    op.drop_table('vehicles')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_business_date'))
        batch_op.drop_index(batch_op.f('ix_policies_approval_state'))

    op.drop_table('policies')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_expires_at'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_rule_code'))

    op.drop_table('findings')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))

    op.drop_table('audit_logs')
    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))

    op.drop_table('login_attempts')
    op.drop_table('job_leases')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_business_date'))

    op.drop_table('daily_reports')
    # ### end Alembic commands ###
