"""Frozen principal-plus-gift recharge bundles; source ledgers remain separate."""
from alembic import op
import sqlalchemy as sa

revision = "a127_recharge_bundle"
down_revision = "z026_opening_import"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharge_bundle_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_store_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('principal_cents_per_share', sa.BigInteger(), nullable=False),
    sa.Column('allowed_store_ids', sa.JSON(), nullable=False),
    sa.Column('sale_starts_on', sa.Date(), nullable=False),
    sa.Column('sale_ends_on', sa.Date(), nullable=False),
    sa.Column('refund_policy', sa.String(length=40), nullable=False),
    sa.Column('refund_terms', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("refund_policy IN ('whole_unused_before_expiry','whole_unused_anytime')", name='ck_recharge_bundle_refund_policy'),
    sa.CheckConstraint('rule_version>0 AND principal_cents_per_share>0 AND sale_starts_on<=sale_ends_on', name='ck_recharge_bundle_rule_value'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issuer_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer_store_id', 'code', 'rule_version', name='uq_recharge_bundle_rule')
    )
    op.create_table('recharge_bundle_rule_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_rule_id', sa.Integer(), nullable=False),
    sa.Column('benefit_rule_id', sa.Integer(), nullable=False),
    sa.Column('units_per_share', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('units_per_share>0', name='ck_recharge_bundle_component_units'),
    sa.ForeignKeyConstraint(['benefit_rule_id'], ['benefit_rules.id'], ),
    sa.ForeignKeyConstraint(['bundle_rule_id'], ['recharge_bundle_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_rule_id', 'benefit_rule_id', name='uq_recharge_bundle_rule_component')
    )
    op.create_index(op.f('ix_recharge_bundle_rule_components_bundle_rule_id'), 'recharge_bundle_rule_components', ['bundle_rule_id'], unique=False)
    op.create_table('recharge_bundle_orders',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("purpose IN ('purchase','refund') AND status IN ('draft','approved','completed','cancelled')", name='ck_recharge_bundle_order'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_recharge_bundle_orders_member_id'), 'recharge_bundle_orders', ['member_id'], unique=False)
    op.create_index(op.f('ix_recharge_bundle_orders_store_id'), 'recharge_bundle_orders', ['store_id'], unique=False)
    op.create_table('recharge_bundle_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('principal_entry_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('shares>0', name='ck_recharge_bundle_purchase_shares'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['principal_entry_id'], ['group_entries.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['recharge_bundle_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('principal_entry_id')
    )
    op.create_index(op.f('ix_recharge_bundle_purchases_member_id'), 'recharge_bundle_purchases', ['member_id'], unique=False)
    op.create_index(op.f('ix_recharge_bundle_purchases_store_id'), 'recharge_bundle_purchases', ['store_id'], unique=False)
    op.create_table('recharge_bundle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('rule_component_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('grant_entry_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grant_entry_id'], ['benefit_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['recharge_bundle_purchases.id'], ),
    sa.ForeignKeyConstraint(['rule_component_id'], ['recharge_bundle_rule_components.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['benefit_wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_entry_id'),
    sa.UniqueConstraint('purchase_id', 'rule_component_id', name='uq_recharge_bundle_purchase_component'),
    sa.UniqueConstraint('wallet_id')
    )
    op.create_index(op.f('ix_recharge_bundle_components_purchase_id'), 'recharge_bundle_components', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_recharge_bundle_components_store_id'), 'recharge_bundle_components', ['store_id'], unique=False)
    op.create_table('recharge_bundle_refunds',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_entry_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status='applied' AND executed_entry_id IS NOT NULL) OR (status!='applied' AND executed_entry_id IS NULL)", name='ck_recharge_bundle_refund_post'),
    sa.CheckConstraint("shares>0 AND amount_cents>0 AND status IN ('requested','reserved','applied','released')", name='ck_recharge_bundle_refund'),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['executed_entry_id'], ['group_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['recharge_bundle_purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('executed_entry_id')
    )
    op.create_index(op.f('ix_recharge_bundle_refunds_member_id'), 'recharge_bundle_refunds', ['member_id'], unique=False)
    op.create_index(op.f('ix_recharge_bundle_refunds_purchase_id'), 'recharge_bundle_refunds', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_recharge_bundle_refunds_store_id'), 'recharge_bundle_refunds', ['store_id'], unique=False)
    op.create_table('recharge_bundle_refund_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('units>0', name='ck_recharge_bundle_refund_units'),
    sa.ForeignKeyConstraint(['component_id'], ['recharge_bundle_components.id'], ),
    sa.ForeignKeyConstraint(['refund_id'], ['recharge_bundle_refunds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id', 'component_id', name='uq_recharge_bundle_refund_component')
    )
    op.create_index(op.f('ix_recharge_bundle_refund_components_refund_id'), 'recharge_bundle_refund_components', ['refund_id'], unique=False)
    op.create_index(op.f('ix_recharge_bundle_refund_components_store_id'), 'recharge_bundle_refund_components', ['store_id'], unique=False)
    op.create_table('recharge_bundle_refund_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_component_id', sa.Integer(), nullable=False),
    sa.Column('benefit_entry_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_entry_id'], ['benefit_entries.id'], ),
    sa.ForeignKeyConstraint(['refund_component_id'], ['recharge_bundle_refund_components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefit_entry_id'),
    sa.UniqueConstraint('refund_component_id')
    )
    op.create_index(op.f('ix_recharge_bundle_refund_postings_store_id'), 'recharge_bundle_refund_postings', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("金融来源账不可降级删除，请恢复已验证的原版本备份")
