"""Frozen evidence-based claims and reimbursement records."""
from alembic import op
import sqlalchemy as sa
revision="b228_claims"
down_revision="a127_recharge_bundle"
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims_request_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_claim_request')
    )
    op.create_index(op.f('ix_claims_request_receipts_store_id'), 'claims_request_receipts', ['store_id'], unique=False)
    op.create_table('claims_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('payment_route', sa.String(length=30), nullable=False),
    sa.Column('party_name', sa.String(length=120), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('source_snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("party_type IN ('insurer','manufacturer','internal') AND payment_route IN ('repair_receivable','customer_direct','customer_via_store','internal')", name='ck_claim_order_kind'),
    sa.ForeignKeyConstraint(['id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['master_insurers.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['flow_references.id'], ),
    sa.ForeignKeyConstraint(['source_case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_orders_source_case_id'), 'claims_orders', ['source_case_id'], unique=False)
    op.create_index(op.f('ix_claims_orders_store_id'), 'claims_orders', ['store_id'], unique=False)
    op.create_table('claims_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('quote_digest', sa.String(length=64), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_claim_assessment_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['repair_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_claim_assessment_revision')
    )
    op.create_index(op.f('ix_claims_assessments_case_id'), 'claims_assessments', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_assessments_store_id'), 'claims_assessments', ['store_id'], unique=False)
    op.create_table('claims_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('unused_cents', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('unused_cents >= 0', name='ck_claim_closure_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_claims_closures_store_id'), 'claims_closures', ['store_id'], unique=False)
    op.create_table('claims_return_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('selections', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_claim_return_plan_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_return_plans_case_id'), 'claims_return_plans', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_return_plans_store_id'), 'claims_return_plans', ['store_id'], unique=False)
    op.create_table('claims_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['claims_assessments.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_claims_approvals_store_id'), 'claims_approvals', ['store_id'], unique=False)
    op.create_table('claims_customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('return_plan_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents > 0 AND purpose IN ('reimbursement','return')", name='ck_claim_customer_payment_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['claims_customer_payments.id'], ),
    sa.ForeignKeyConstraint(['return_plan_id'], ['claims_return_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_customer_payments_case_id'), 'claims_customer_payments', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_customer_payments_store_id'), 'claims_customer_payments', ['store_id'], unique=False)
    op.create_table('claims_return_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['claims_return_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_claims_return_approvals_store_id'), 'claims_return_approvals', ['store_id'], unique=False)
    op.create_table('claims_return_cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['claims_return_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_claims_return_cancellations_store_id'), 'claims_return_cancellations', ['store_id'], unique=False)
    op.create_table('claims_transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('supplement_result_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('submitted_on', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['claims_assessments.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplement_result_id')
    )
    op.create_index(op.f('ix_claims_transmissions_case_id'), 'claims_transmissions', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_transmissions_store_id'), 'claims_transmissions', ['store_id'], unique=False)
    op.create_table('claims_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('transmission_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('result_on', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("outcome IN ('approved','partial','rejected','need_documents') AND amount_cents >= 0", name='ck_claim_result'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['claims_assessments.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['claims_transmissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transmission_id')
    )
    op.create_index(op.f('ix_claims_results_case_id'), 'claims_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_results_store_id'), 'claims_results', ['store_id'], unique=False)
    op.create_table('claims_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('approved_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('approved_cents >= 0', name='ck_claim_binding_amount'),
    sa.ForeignKeyConstraint(['allocation_id'], ['repair_allocations.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['claims_assessments.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['claims_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_claims_bindings_store_id'), 'claims_bindings', ['store_id'], unique=False)
    op.create_table('claims_reimbursement_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_claim_reimbursement_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['claims_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_claims_reimbursement_approvals_store_id'), 'claims_reimbursement_approvals', ['store_id'], unique=False)
    op.create_table('claims_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('original_cents', sa.BigInteger(), nullable=False),
    sa.Column('reduction_cents', sa.BigInteger(), nullable=False),
    sa.Column('refund_cents', sa.BigInteger(), nullable=False),
    sa.Column('internal_bearer', sa.String(length=120), nullable=False),
    sa.Column('refunds', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('original_cents >= reduction_cents AND reduction_cents > 0 AND refund_cents >= 0', name='ck_claim_resolution_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['allocation_id'], ['repair_allocations.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['claims_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_claims_resolutions_store_id'), 'claims_resolutions', ['store_id'], unique=False)
    op.create_table('claims_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['claims_resolutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id')
    )
    op.create_index(op.f('ix_claims_applications_store_id'), 'claims_applications', ['store_id'], unique=False)
    op.create_table('claims_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('return_plan_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("purpose IN ('thirdparty_refund','pass_receive','pass_pay','customer_return','party_return','unused_refund')", name='ck_claim_cash_purpose'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['claims_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['claims_cash.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['flow_payment_links.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['claims_resolutions.id'], ),
    sa.ForeignKeyConstraint(['return_plan_id'], ['claims_return_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_link_id')
    )
    op.create_index(op.f('ix_claims_cash_case_id'), 'claims_cash', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_cash_store_id'), 'claims_cash', ['store_id'], unique=False)
    op.create_table('claims_resolution_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['claims_resolutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id')
    )
    op.create_index(op.f('ix_claims_resolution_approvals_store_id'), 'claims_resolution_approvals', ['store_id'], unique=False)
    op.create_table('claims_responsibility_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('payer_type', sa.String(length=20), nullable=False),
    sa.Column('payer_name', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(payer_type IN ('insurer','manufacturer') AND allocation_id IS NOT NULL AND amount_cents<0) OR (payer_type='internal' AND allocation_id IS NULL AND amount_cents>0)", name='ck_claim_responsibility_sign'),
    sa.ForeignKeyConstraint(['allocation_id'], ['repair_allocations.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['claims_applications.id'], ),
    sa.ForeignKeyConstraint(['source_case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_responsibility_entries_application_id'), 'claims_responsibility_entries', ['application_id'], unique=False)
    op.create_index(op.f('ix_claims_responsibility_entries_source_case_id'), 'claims_responsibility_entries', ['source_case_id'], unique=False)
    op.create_index(op.f('ix_claims_responsibility_entries_store_id'), 'claims_responsibility_entries', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("核赔和实际报销记录不可自动删除；请恢复完整备份")
