"""Frozen vehicle import source/review links, no duplicated stock or cash ledger."""
from alembic import op
import sqlalchemy as sa
revision='c329_vehicle_imports'
down_revision='b228_claims'
branch_labels=None
depends_on=None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_import_batches',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=False),
    sa.Column('source_case_version', sa.Integer(), nullable=False),
    sa.Column('replacement_batch_id', sa.Integer(), nullable=True),
    sa.Column('prepared_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('funds','ship','receive') AND status IN ('invalid','prepared','trial_passed','reviewed','confirmed','cancelled')", name='ck_vimport_state'),
    sa.CheckConstraint('row_count BETWEEN 1 AND 200 AND amount_cents >= 0', name='ck_vimport_totals'),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['replacement_batch_id'], ['vehicle_import_batches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_import_batches_case_id'), 'vehicle_import_batches', ['case_id'], unique=False)
    op.create_index(op.f('ix_vehicle_import_batches_store_id'), 'vehicle_import_batches', ['store_id'], unique=False)
    op.create_table('vehicle_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.String(length=80), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('manifest_row_id', sa.Integer(), nullable=True),
    sa.Column('origin_key', sa.String(length=64), nullable=False),
    sa.Column('vehicle_key', sa.String(length=64), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('row_number BETWEEN 2 AND 201', name='ck_vimport_row_number'),
    sa.ForeignKeyConstraint(['batch_id'], ['vehicle_import_batches.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['vehicle_purchase_lines.id'], ),
    sa.ForeignKeyConstraint(['manifest_row_id'], ['vehicle_import_rows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_vimport_row')
    )
    op.create_index(op.f('ix_vehicle_import_rows_origin_key'), 'vehicle_import_rows', ['origin_key'], unique=False)
    op.create_index(op.f('ix_vehicle_import_rows_store_id'), 'vehicle_import_rows', ['store_id'], unique=False)
    op.create_index(op.f('ix_vehicle_import_rows_batch_id'), 'vehicle_import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_vehicle_import_rows_vehicle_key'), 'vehicle_import_rows', ['vehicle_key'], unique=False)
    op.create_table('vehicle_import_claims',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['vehicle_import_rows.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_vehicle_import_claims_row_id'), 'vehicle_import_claims', ['row_id'], unique=False)
    op.create_index(op.f('ix_vehicle_import_claims_store_id'), 'vehicle_import_claims', ['store_id'], unique=False)
    op.create_table('vehicle_import_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('funds_request_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(CASE WHEN funds_request_id IS NULL THEN 0 ELSE 1 END + CASE WHEN shipment_id IS NULL THEN 0 ELSE 1 END + CASE WHEN receipt_id IS NULL THEN 0 ELSE 1 END)=1', name='ck_vimport_result_kind'),
    sa.ForeignKeyConstraint(['funds_request_id'], ['vehicle_purchase_funds_requests.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['vehicle_purchase_receipts.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['vehicle_import_rows.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['vehicle_purchase_shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funds_request_id'),
    sa.UniqueConstraint('receipt_id'),
    sa.UniqueConstraint('row_id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_index(op.f('ix_vehicle_import_results_store_id'), 'vehicle_import_results', ['store_id'], unique=False)
    op.create_table('vehicle_import_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['vehicle_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'actor_id', 'request_key', name='uq_vimport_request')
    )
    op.create_index(op.f('ix_vehicle_import_requests_store_id'), 'vehicle_import_requests', ['store_id'], unique=False)


def downgrade():
    op.drop_table('vehicle_import_requests')
    op.drop_table('vehicle_import_results')
    op.drop_table('vehicle_import_claims')
    op.drop_table('vehicle_import_rows')
    op.drop_table('vehicle_import_batches')
