"""Workflow, dossier, material and membership ledgers. Additive; old rows untouched."""
from alembic import op
import sqlalchemy as sa
revision = 'c803_workflow'
down_revision = 'b702_multistore_feedback'
branch_labels = None
depends_on = None
def upgrade():
    # Rebuild only the constraint, preserving every account and foreign key.
    with op.batch_alter_table('users') as batch:
        batch.drop_constraint('ck_user_role',type_='check')
        batch.create_check_constraint('ck_user_role',"role IN ('admin','manager','sales','inventory','service','finance','auditor','reception','technician','customer_service')")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_accounts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_flow_account_name')
    )
    op.create_index(op.f('ix_flow_accounts_store_id'), 'flow_accounts', ['store_id'], unique=False)
    op.create_table('flow_items',
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('inventory_value_cents', sa.BigInteger(), nullable=False),
    sa.Column('reorder_milli', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_milli >= 0 AND unit_cost_cents >= 0 AND reorder_milli >= 0 AND inventory_value_cents >= 0', name='ck_flow_stock_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_flow_item_sku')
    )
    op.create_index(op.f('ix_flow_items_store_id'), 'flow_items', ['store_id'], unique=False)
    op.create_table('flow_references',
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'category', 'name', name='uq_flow_reference')
    )
    op.create_index(op.f('ix_flow_references_category'), 'flow_references', ['category'], unique=False)
    op.create_index(op.f('ix_flow_references_store_id'), 'flow_references', ['store_id'], unique=False)
    op.create_table('flow_customers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('contact_allowed', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_customers_store_id'), 'flow_customers', ['store_id'], unique=False)
    op.create_table('flow_doc_templates',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('clauses', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'kind', name='uq_flow_template')
    )
    op.create_index(op.f('ix_flow_doc_templates_store_id'), 'flow_doc_templates', ['store_id'], unique=False)
    op.create_table('flow_cases',
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('flow_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents >= 0 AND (cost_cents IS NULL OR cost_cents >= 0)', name='ck_flow_case_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['flow_customers.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_flow_cases_business_date'), 'flow_cases', ['business_date'], unique=False)
    op.create_index(op.f('ix_flow_cases_completed_date'), 'flow_cases', ['completed_date'], unique=False)
    op.create_index(op.f('ix_flow_cases_customer_id'), 'flow_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_flow_cases_kind'), 'flow_cases', ['kind'], unique=False)
    op.create_index(op.f('ix_flow_cases_parent_id'), 'flow_cases', ['parent_id'], unique=False)
    op.create_index(op.f('ix_flow_cases_state'), 'flow_cases', ['state'], unique=False)
    op.create_index(op.f('ix_flow_cases_store_id'), 'flow_cases', ['store_id'], unique=False)
    op.create_table('flow_members',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance_cents >= 0 AND points >= 0', name='ck_flow_member_balance'),
    sa.ForeignKeyConstraint(['customer_id'], ['flow_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_flow_members_store_id'), 'flow_members', ['store_id'], unique=False)
    op.create_table('flow_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('before_state', sa.String(length=30), nullable=False),
    sa.Column('after_state', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_events_case_id'), 'flow_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_flow_events_occurred_at'), 'flow_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_flow_events_store_id'), 'flow_events', ['store_id'], unique=False)
    op.create_table('flow_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=150), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('template_approved', sa.Boolean(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_files_case_id'), 'flow_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_flow_files_store_id'), 'flow_files', ['store_id'], unique=False)
    op.create_table('flow_member_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['flow_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_member_entries_case_id'), 'flow_member_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_flow_member_entries_member_id'), 'flow_member_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_flow_member_entries_store_id'), 'flow_member_entries', ['store_id'], unique=False)
    op.create_table('flow_request_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_flow_request_key')
    )
    op.create_index(op.f('ix_flow_request_receipts_store_id'), 'flow_request_receipts', ['store_id'], unique=False)
    op.create_table('flow_stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['flow_items.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['flow_stock_moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_stock_moves_business_date'), 'flow_stock_moves', ['business_date'], unique=False)
    op.create_index(op.f('ix_flow_stock_moves_case_id'), 'flow_stock_moves', ['case_id'], unique=False)
    op.create_index(op.f('ix_flow_stock_moves_item_id'), 'flow_stock_moves', ['item_id'], unique=False)
    op.create_index(op.f('ix_flow_stock_moves_store_id'), 'flow_stock_moves', ['store_id'], unique=False)
    op.create_table('flow_tasks',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('open','done','cancelled')", name='ck_flow_task_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'key', name='uq_flow_task_key')
    )
    op.create_index(op.f('ix_flow_tasks_assignee_id'), 'flow_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_flow_tasks_case_id'), 'flow_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_flow_tasks_due_date'), 'flow_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_flow_tasks_status'), 'flow_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_flow_tasks_store_id'), 'flow_tasks', ['store_id'], unique=False)
    op.create_table('flow_vehicle_holds',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_flow_vehicle_holds_store_id'), 'flow_vehicle_holds', ['store_id'], unique=False)
    op.create_table('flow_payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents > 0 AND direction IN ('in','out')", name='ck_flow_payment'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['flow_payment_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id'),
    sa.UniqueConstraint('store_id', 'account_id', 'reference', name='uq_flow_payment_reference')
    )
    op.create_index(op.f('ix_flow_payment_links_case_id'), 'flow_payment_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_flow_payment_links_store_id'), 'flow_payment_links', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Do not discard workflow history. Restore a verified backup instead.')
