"""Frozen store boutique bundle composition and original sale allocation."""
from alembic import op
import sqlalchemy as sa

revision = "d430_retail_bundles"
down_revision = "c329_vehicle_imports"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_bundle_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sale_starts_on', sa.Date(), nullable=False),
    sa.Column('sale_ends_on', sa.Date(), nullable=False),
    sa.Column('price_cents_per_set', sa.BigInteger(), nullable=False),
    sa.Column('refund_terms', sa.String(length=1500), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('rule_version>0 AND price_cents_per_set>0 AND sale_starts_on<=sale_ends_on', name='ck_retail_bundle_rule'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'code', 'rule_version', name='uq_retail_bundle_rule')
    )
    op.create_index(op.f('ix_retail_bundle_rules_store_id'), 'retail_bundle_rules', ['store_id'], unique=False)
    op.create_table('retail_bundle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_milli_per_set', sa.BigInteger(), nullable=False),
    sa.Column('goods_reference_cents', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=True),
    sa.Column('work_code', sa.String(length=60), nullable=False),
    sa.Column('work_name', sa.String(length=120), nullable=False),
    sa.Column('installation_reference_cents', sa.BigInteger(), nullable=False),
    sa.Column('goods_cents_per_set', sa.BigInteger(), nullable=False),
    sa.Column('installation_cents_per_set', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('sequence>0 AND quantity_milli_per_set>0 AND goods_reference_cents>=0 AND installation_reference_cents>=0 AND goods_cents_per_set>=0 AND installation_cents_per_set>=0', name='ck_retail_bundle_component'),
    sa.ForeignKeyConstraint(['item_id'], ['flow_items.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['retail_bundle_rules.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['master_work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'item_id', name='uq_retail_bundle_item'),
    sa.UniqueConstraint('rule_id', 'sequence', name='uq_retail_bundle_sequence')
    )
    op.create_index(op.f('ix_retail_bundle_components_rule_id'), 'retail_bundle_components', ['rule_id'], unique=False)
    op.create_index(op.f('ix_retail_bundle_components_store_id'), 'retail_bundle_components', ['store_id'], unique=False)
    op.create_table('retail_bundle_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('sets>0 AND terms_accepted', name='ck_retail_bundle_sale'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['retail_orders.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['retail_bundle_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_retail_bundle_sales_rule_id'), 'retail_bundle_sales', ['rule_id'], unique=False)
    op.create_index(op.f('ix_retail_bundle_sales_store_id'), 'retail_bundle_sales', ['store_id'], unique=False)
    op.create_table('retail_bundle_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('goods_reference_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_reference_cents', sa.BigInteger(), nullable=False),
    sa.Column('goods_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_milli>0 AND goods_reference_cents>=goods_cents AND goods_cents>=0 AND installation_reference_cents>=installation_cents AND installation_cents>=0', name='ck_retail_bundle_allocation'),
    sa.ForeignKeyConstraint(['component_id'], ['retail_bundle_components.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['retail_lines.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['retail_bundle_sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id'),
    sa.UniqueConstraint('sale_id', 'component_id', name='uq_retail_bundle_allocation')
    )
    op.create_index(op.f('ix_retail_bundle_allocations_sale_id'), 'retail_bundle_allocations', ['sale_id'], unique=False)
    op.create_index(op.f('ix_retail_bundle_allocations_store_id'), 'retail_bundle_allocations', ['store_id'], unique=False)
    op.create_table('retail_bundle_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['retail_bundle_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_id', name='uq_retail_bundle_receipt')
    )
    op.create_index(op.f('ix_retail_bundle_receipts_store_id'), 'retail_bundle_receipts', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retail_bundle_receipts_store_id'), table_name='retail_bundle_receipts')
    op.drop_table('retail_bundle_receipts')
    op.drop_index(op.f('ix_retail_bundle_allocations_store_id'), table_name='retail_bundle_allocations')
    op.drop_index(op.f('ix_retail_bundle_allocations_sale_id'), table_name='retail_bundle_allocations')
    op.drop_table('retail_bundle_allocations')
    op.drop_index(op.f('ix_retail_bundle_sales_store_id'), table_name='retail_bundle_sales')
    op.drop_index(op.f('ix_retail_bundle_sales_rule_id'), table_name='retail_bundle_sales')
    op.drop_table('retail_bundle_sales')
    op.drop_index(op.f('ix_retail_bundle_components_store_id'), table_name='retail_bundle_components')
    op.drop_index(op.f('ix_retail_bundle_components_rule_id'), table_name='retail_bundle_components')
    op.drop_table('retail_bundle_components')
    op.drop_index(op.f('ix_retail_bundle_rules_store_id'), table_name='retail_bundle_rules')
    op.drop_table('retail_bundle_rules')
    # ### end Alembic commands ###
