"""Frozen customer service fees and pass-through original cash paths."""
from alembic import op
import sqlalchemy as sa

revision = "e531_service_orders"
down_revision = "d430_retail_bundles"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_income_items',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('standard_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('standard_fee_cents>=0', name='ck_service_income_fee'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'code', name='uq_service_income_code')
    )
    op.create_index(op.f('ix_service_income_items_store_id'), 'service_income_items', ['store_id'], unique=False)
    op.create_table('service_payees',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('account_reference', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'code', name='uq_service_payee_code')
    )
    op.create_index(op.f('ix_service_payees_store_id'), 'service_payees', ['store_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_service_request')
    )
    op.create_index(op.f('ix_service_requests_store_id'), 'service_requests', ['store_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(length=20), nullable=False),
    sa.Column('source_order_id', sa.Integer(), nullable=True),
    sa.Column('delivery_blocking', sa.Boolean(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("subtype IN ('agency','other_income')", name='ck_service_order_subtype'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['source_order_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_orders_source_order_id'), 'service_orders', ['source_order_id'], unique=False)
    op.create_index(op.f('ix_service_orders_store_id'), 'service_orders', ['store_id'], unique=False)
    op.create_table('service_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('pass_cents', sa.BigInteger(), nullable=False),
    sa.Column('discount_cents', sa.BigInteger(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('fee_cents>=0 AND pass_cents>=0 AND discount_cents>=0 AND fee_cents+pass_cents>0', name='ck_service_quote_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_service_quote_revision')
    )
    op.create_index(op.f('ix_service_quotes_case_id'), 'service_quotes', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_quotes_store_id'), 'service_quotes', ['store_id'], unique=False)
    op.create_table('service_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['service_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_service_authorizations_store_id'), 'service_authorizations', ['store_id'], unique=False)
    op.create_table('service_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False),
    sa.Column('agency_project_id', sa.Integer(), nullable=True),
    sa.Column('income_item_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('payee_snapshot', sa.JSON(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('discount_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("bucket IN ('fee','pass') AND quantity_milli>0 AND unit_price_cents>=0 AND discount_cents>=0 AND amount_cents>=0", name='ck_service_line_values'),
    sa.ForeignKeyConstraint(['agency_project_id'], ['master_agency_projects.id'], ),
    sa.ForeignKeyConstraint(['income_item_id'], ['service_income_items.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['service_payees.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['service_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'line_key', name='uq_service_quote_line')
    )
    op.create_index(op.f('ix_service_lines_quote_id'), 'service_lines', ['quote_id'], unique=False)
    op.create_index(op.f('ix_service_lines_store_id'), 'service_lines', ['store_id'], unique=False)
    op.create_table('service_price_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('minimum_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('allow_below_minimum', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['service_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_service_price_approvals_store_id'), 'service_price_approvals', ['store_id'], unique=False)
    op.create_table('service_quote_cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['service_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_service_quote_cancellations_store_id'), 'service_quote_cancellations', ['store_id'], unique=False)
    op.create_table('service_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('supplement_result_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('submitted_on', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['service_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplement_result_id')
    )
    op.create_index(op.f('ix_service_submissions_case_id'), 'service_submissions', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_submissions_store_id'), 'service_submissions', ['store_id'], unique=False)
    op.create_table('service_terminations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('returns', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['service_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_service_termination_revision')
    )
    op.create_index(op.f('ix_service_terminations_case_id'), 'service_terminations', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_terminations_store_id'), 'service_terminations', ['store_id'], unique=False)
    op.create_table('service_external_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("outcome IN ('approved','rejected','need_documents')", name='ck_service_external_outcome'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['service_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_service_external_results_store_id'), 'service_external_results', ['store_id'], unique=False)
    op.create_table('service_fulfillments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['service_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'line_key', name='uq_service_fulfillment_line')
    )
    op.create_index(op.f('ix_service_fulfillments_case_id'), 'service_fulfillments', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_fulfillments_store_id'), 'service_fulfillments', ['store_id'], unique=False)
    op.create_table('service_termination_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['service_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_service_termination_applications_store_id'), 'service_termination_applications', ['store_id'], unique=False)
    op.create_table('service_termination_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['service_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_service_termination_approvals_store_id'), 'service_termination_approvals', ['store_id'], unique=False)
    op.create_table('service_termination_cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['service_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_service_termination_cancellations_store_id'), 'service_termination_cancellations', ['store_id'], unique=False)
    op.create_table('service_termination_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['service_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_service_termination_consents_store_id'), 'service_termination_consents', ['store_id'], unique=False)
    op.create_table('service_charge_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("bucket IN ('fee','pass') AND amount_cents<0", name='ck_service_adjustment_sign'),
    sa.ForeignKeyConstraint(['application_id'], ['service_termination_applications.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['service_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_charge_adjustments_case_id'), 'service_charge_adjustments', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_charge_adjustments_store_id'), 'service_charge_adjustments', ['store_id'], unique=False)
    op.create_table('service_tender_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=True),
    sa.Column('credit_link_id', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("bucket IN ('fee','pass') AND amount_cents!=0 AND ((payment_link_id IS NOT NULL AND credit_link_id IS NULL) OR (payment_link_id IS NULL AND credit_link_id IS NOT NULL))", name='ck_service_tender_source'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['credit_link_id'], ['business_finance_credit_links.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['service_lines.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['service_tender_slices.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['flow_payment_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tender_slices_case_id'), 'service_tender_slices', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_tender_slices_credit_link_id'), 'service_tender_slices', ['credit_link_id'], unique=False)
    op.create_index(op.f('ix_service_tender_slices_payment_link_id'), 'service_tender_slices', ['payment_link_id'], unique=False)
    op.create_index(op.f('ix_service_tender_slices_store_id'), 'service_tender_slices', ['store_id'], unique=False)
    op.create_table('service_pass_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("purpose IN ('disburse','thirdparty_return') AND amount_cents>0", name='ck_service_pass_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['service_lines.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['service_pass_entries.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['service_tender_slices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id')
    )
    op.create_index(op.f('ix_service_pass_entries_case_id'), 'service_pass_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_pass_entries_store_id'), 'service_pass_entries', ['store_id'], unique=False)
    op.create_table('service_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('original_tender_id', sa.Integer(), nullable=False),
    sa.Column('reversal_tender_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents>0', name='ck_service_refund_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_tender_id'], ['service_tender_slices.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['service_terminations.id'], ),
    sa.ForeignKeyConstraint(['reversal_tender_id'], ['service_tender_slices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reversal_tender_id')
    )
    op.create_index(op.f('ix_service_refunds_store_id'), 'service_refunds', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_refunds')
    op.drop_table('service_pass_entries')
    op.drop_table('service_tender_slices')
    op.drop_table('service_charge_adjustments')
    op.drop_table('service_termination_consents')
    op.drop_table('service_termination_cancellations')
    op.drop_table('service_termination_approvals')
    op.drop_table('service_termination_applications')
    op.drop_table('service_fulfillments')
    op.drop_table('service_external_results')
    op.drop_table('service_terminations')
    op.drop_table('service_submissions')
    op.drop_table('service_quote_cancellations')
    op.drop_table('service_price_approvals')
    op.drop_table('service_lines')
    op.drop_table('service_authorizations')
    op.drop_table('service_quotes')
    op.drop_table('service_orders')
    op.drop_table('service_requests')
    op.drop_table('service_payees')
    op.drop_table('service_income_items')
    # ### end Alembic commands ###
