"""Frozen typed vehicle quotations, independent review and original adjustments."""
from alembic import op
import sqlalchemy as sa

revision="g733_sales_quotes"
down_revision="f632_vehicle_catalog"
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('prior_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_snapshot', sa.JSON(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('delivery_due', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('terms', sa.String(length=1500), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('revision>0 AND amount_cents>0', name='ck_sales_quote_amount'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['master_vehicle_models.id'], ),
    sa.ForeignKeyConstraint(['prior_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_sales_quote_revision')
    )
    op.create_index(op.f('ix_sales_quotes_case_id'), 'sales_quotes', ['case_id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_store_id'), 'sales_quotes', ['store_id'], unique=False)
    op.create_table('sales_quote_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('approved','rejected')", name='ck_sales_quote_review'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_sales_quote_reviews_store_id'), 'sales_quote_reviews', ['store_id'], unique=False)
    op.create_table('sales_quote_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("outcome IN ('activated','withdrawn','rejected')", name='ck_sales_quote_resolution'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_sales_quote_resolutions_store_id'), 'sales_quote_resolutions', ['store_id'], unique=False)
    op.create_table('sales_quote_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('paid_before_cents', sa.BigInteger(), nullable=False),
    sa.Column('advance_before_cents', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('paid_before_cents>=0 AND advance_before_cents>=0 AND advance_before_cents<=paid_before_cents', name='ck_sales_quote_consent_paid'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id')
    )
    op.create_index(op.f('ix_sales_quote_consents_quote_id'), 'sales_quote_consents', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_consents_store_id'), 'sales_quote_consents', ['store_id'], unique=False)
    op.create_table('sales_vehicle_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_vehicle_releases_case_id'), 'sales_vehicle_releases', ['case_id'], unique=False)
    op.create_index(op.f('ix_sales_vehicle_releases_store_id'), 'sales_vehicle_releases', ['store_id'], unique=False)
    op.create_table('sales_quote_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents>0 AND ((kind='cash_refund' AND payment_id IS NOT NULL AND credit_id IS NULL) OR (kind='advance_return' AND payment_id IS NULL AND credit_id IS NOT NULL))", name='ck_sales_quote_adjustment'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credit_id'], ['business_finance_credit_links.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['flow_payment_links.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_sales_quote_adjustments_quote_id'), 'sales_quote_adjustments', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_adjustments_store_id'), 'sales_quote_adjustments', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_quote_adjustments_store_id'), table_name='sales_quote_adjustments')
    op.drop_index(op.f('ix_sales_quote_adjustments_quote_id'), table_name='sales_quote_adjustments')
    op.drop_table('sales_quote_adjustments')
    op.drop_index(op.f('ix_sales_vehicle_releases_store_id'), table_name='sales_vehicle_releases')
    op.drop_index(op.f('ix_sales_vehicle_releases_case_id'), table_name='sales_vehicle_releases')
    op.drop_table('sales_vehicle_releases')
    op.drop_index(op.f('ix_sales_quote_consents_store_id'), table_name='sales_quote_consents')
    op.drop_index(op.f('ix_sales_quote_consents_quote_id'), table_name='sales_quote_consents')
    op.drop_table('sales_quote_consents')
    op.drop_index(op.f('ix_sales_quote_resolutions_store_id'), table_name='sales_quote_resolutions')
    op.drop_table('sales_quote_resolutions')
    op.drop_index(op.f('ix_sales_quote_reviews_store_id'), table_name='sales_quote_reviews')
    op.drop_table('sales_quote_reviews')
    op.drop_index(op.f('ix_sales_quotes_store_id'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_case_id'), table_name='sales_quotes')
    op.drop_table('sales_quotes')
    # ### end Alembic commands ###
