"""Frozen insurance principal, external facts and actual commission."""
from alembic import op
import sqlalchemy as sa

revision="i935_insurance_orders"
down_revision="h834_procurement_cost"
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_requests',
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_insurance_request')
    )
    op.create_index(op.f('ix_insurance_requests_store_id'), 'insurance_requests', ['store_id'], unique=False)
    op.create_table('insurance_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_order_id', sa.Integer(), nullable=True),
    sa.Column('customer_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('renewal_task_id', sa.Integer(), nullable=True),
    sa.Column('delivery_blocking', sa.Boolean(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('vehicle_snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_vehicle_id'], ['care_customer_vehicles.id'], ),
    sa.ForeignKeyConstraint(['id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['renewal_task_id'], ['care_cases.case_id'], ),
    sa.ForeignKeyConstraint(['source_order_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_orders_renewal_task_id'), 'insurance_orders', ['renewal_task_id'], unique=False)
    op.create_index(op.f('ix_insurance_orders_source_order_id'), 'insurance_orders', ['source_order_id'], unique=False)
    op.create_index(op.f('ix_insurance_orders_store_id'), 'insurance_orders', ['store_id'], unique=False)
    op.create_table('insurance_commissions',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('target_cents', sa.BigInteger(), nullable=False),
    sa.Column('previous_cents', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('target_cents>=0 AND previous_cents>=0', name='ck_insurance_commission'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_insurance_commission_revision')
    )
    op.create_index(op.f('ix_insurance_commissions_case_id'), 'insurance_commissions', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_commissions_store_id'), 'insurance_commissions', ['store_id'], unique=False)
    op.create_table('insurance_direct_entries',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents>0 AND ((purpose='paid' AND original_id IS NULL) OR (purpose='returned' AND original_id IS NOT NULL))", name='ck_insurance_direct'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['insurance_direct_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_reference', name='uq_insurance_direct_reference')
    )
    op.create_index(op.f('ix_insurance_direct_entries_case_id'), 'insurance_direct_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_direct_entries_store_id'), 'insurance_direct_entries', ['store_id'], unique=False)
    op.create_table('insurance_quotes',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('insurer_snapshot', sa.JSON(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('premium_cents', sa.BigInteger(), nullable=False),
    sa.Column('expected_commission_cents', sa.BigInteger(), nullable=False),
    sa.Column('collection_mode', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('terms', sa.String(length=1500), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("premium_cents>0 AND expected_commission_cents>=0 AND end_date>=start_date AND collection_mode IN ('store_collect','customer_direct')", name='ck_insurance_quote_values'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['master_insurers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_insurance_quote_revision')
    )
    op.create_index(op.f('ix_insurance_quotes_case_id'), 'insurance_quotes', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_quotes_store_id'), 'insurance_quotes', ['store_id'], unique=False)
    op.create_table('insurance_tenders',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=True),
    sa.Column('credit_link_id', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents!=0 AND ((payment_link_id IS NOT NULL AND credit_link_id IS NULL) OR (payment_link_id IS NULL AND credit_link_id IS NOT NULL)) AND ((amount_cents>0 AND original_id IS NULL) OR (amount_cents<0 AND original_id IS NOT NULL))', name='ck_insurance_tender'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['credit_link_id'], ['business_finance_credit_links.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['insurance_tenders.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['flow_payment_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_link_id'),
    sa.UniqueConstraint('payment_link_id')
    )
    op.create_index(op.f('ix_insurance_tenders_case_id'), 'insurance_tenders', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_tenders_original_id'), 'insurance_tenders', ['original_id'], unique=False)
    op.create_index(op.f('ix_insurance_tenders_store_id'), 'insurance_tenders', ['store_id'], unique=False)
    op.create_table('insurance_commission_payments',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('confirmation_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents>0 AND ((direction='in' AND original_id IS NULL) OR (direction='out' AND original_id IS NOT NULL))", name='ck_insurance_commission_payment'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['confirmation_id'], ['insurance_commissions.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['insurance_commission_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id')
    )
    op.create_index(op.f('ix_insurance_commission_payments_case_id'), 'insurance_commission_payments', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_commission_payments_store_id'), 'insurance_commission_payments', ['store_id'], unique=False)
    op.create_table('insurance_commission_reviews',
    sa.Column('confirmation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('approved','rejected')", name='ck_insurance_commission_review'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmation_id'], ['insurance_commissions.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_id')
    )
    op.create_index(op.f('ix_insurance_commission_reviews_store_id'), 'insurance_commission_reviews', ['store_id'], unique=False)
    op.create_table('insurance_consents',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['insurance_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_insurance_consents_store_id'), 'insurance_consents', ['store_id'], unique=False)
    op.create_table('insurance_pass_entries',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents>0 AND ((purpose='disburse' AND original_id IS NULL) OR (purpose='insurer_return' AND original_id IS NOT NULL))", name='ck_insurance_pass'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['insurance_pass_entries.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['insurance_tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id')
    )
    op.create_index(op.f('ix_insurance_pass_entries_case_id'), 'insurance_pass_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_pass_entries_store_id'), 'insurance_pass_entries', ['store_id'], unique=False)
    op.create_index(op.f('ix_insurance_pass_entries_tender_id'), 'insurance_pass_entries', ['tender_id'], unique=False)
    op.create_table('insurance_quote_cancellations',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['insurance_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_insurance_quote_cancellations_store_id'), 'insurance_quote_cancellations', ['store_id'], unique=False)
    op.create_table('insurance_reviews',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('approved','rejected')", name='ck_insurance_review_decision'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['insurance_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_insurance_reviews_store_id'), 'insurance_reviews', ['store_id'], unique=False)
    op.create_table('insurance_submissions',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['insurance_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_submissions_quote_id'), 'insurance_submissions', ['quote_id'], unique=False)
    op.create_index(op.f('ix_insurance_submissions_store_id'), 'insurance_submissions', ['store_id'], unique=False)
    op.create_table('insurance_terminations',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('retained_cents', sa.BigInteger(), nullable=False),
    sa.Column('returns', sa.JSON(), nullable=False),
    sa.Column('external_result', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("retained_cents>=0 AND external_result IN ('terminated','not_issued')", name='ck_insurance_termination'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['insurance_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_insurance_termination_revision')
    )
    op.create_index(op.f('ix_insurance_terminations_case_id'), 'insurance_terminations', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_terminations_store_id'), 'insurance_terminations', ['store_id'], unique=False)
    op.create_table('insurance_customer_refunds',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('original_tender_id', sa.Integer(), nullable=False),
    sa.Column('reversal_tender_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents>0', name='ck_insurance_customer_refund'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_tender_id'], ['insurance_tenders.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_terminations.id'], ),
    sa.ForeignKeyConstraint(['reversal_tender_id'], ['insurance_tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reversal_tender_id')
    )
    op.create_index(op.f('ix_insurance_customer_refunds_plan_id'), 'insurance_customer_refunds', ['plan_id'], unique=False)
    op.create_index(op.f('ix_insurance_customer_refunds_store_id'), 'insurance_customer_refunds', ['store_id'], unique=False)
    op.create_table('insurance_results',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('policy_number', sa.String(length=120), nullable=True),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("outcome IN ('issued','rejected','need_documents') AND ((outcome='issued' AND policy_number IS NOT NULL) OR (outcome!='issued' AND policy_number IS NULL))", name='ck_insurance_result'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['master_insurers.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['care_vehicle_observations.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['insurance_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id'),
    sa.UniqueConstraint('store_id', 'insurer_id', 'policy_number', name='uq_insurance_policy_number'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_insurance_results_case_id'), 'insurance_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_insurance_results_store_id'), 'insurance_results', ['store_id'], unique=False)
    op.create_table('insurance_termination_applications',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_insurance_termination_applications_store_id'), 'insurance_termination_applications', ['store_id'], unique=False)
    op.create_table('insurance_termination_cancellations',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_insurance_termination_cancellations_store_id'), 'insurance_termination_cancellations', ['store_id'], unique=False)
    op.create_table('insurance_termination_consents',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_insurance_termination_consents_store_id'), 'insurance_termination_consents', ['store_id'], unique=False)
    op.create_table('insurance_termination_reviews',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('approved','rejected')", name='ck_insurance_termination_decision'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_terminations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_insurance_termination_reviews_store_id'), 'insurance_termination_reviews', ['store_id'], unique=False)
    op.create_table('insurance_renewal_links',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('previous_policy_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['insurance_orders.id'], ),
    sa.ForeignKeyConstraint(['previous_policy_id'], ['insurance_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_insurance_renewal_links_previous_policy_id'), 'insurance_renewal_links', ['previous_policy_id'], unique=False)
    op.create_index(op.f('ix_insurance_renewal_links_store_id'), 'insurance_renewal_links', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('insurance_renewal_links')
    op.drop_table('insurance_termination_reviews')
    op.drop_table('insurance_termination_consents')
    op.drop_table('insurance_termination_cancellations')
    op.drop_table('insurance_termination_applications')
    op.drop_table('insurance_results')
    op.drop_table('insurance_customer_refunds')
    op.drop_table('insurance_terminations')
    op.drop_table('insurance_submissions')
    op.drop_table('insurance_reviews')
    op.drop_table('insurance_quote_cancellations')
    op.drop_table('insurance_pass_entries')
    op.drop_table('insurance_consents')
    op.drop_table('insurance_commission_reviews')
    op.drop_table('insurance_commission_payments')
    op.drop_table('insurance_tenders')
    op.drop_table('insurance_quotes')
    op.drop_table('insurance_direct_entries')
    op.drop_table('insurance_commissions')
    op.drop_table('insurance_orders')
    op.drop_table('insurance_requests')
