"""Frozen sales accessory work and original physical dispositions."""
from alembic import op
import sqlalchemy as sa
revision="j036_addon_lines"
down_revision="i935_insurance_orders"
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_addon_request')
    )
    op.create_index(op.f('ix_addon_receipts_store_id'), 'addon_receipts', ['store_id'], unique=False)
    op.create_table('addon_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot', sa.JSON(), nullable=False),
    sa.Column('delivery_blocking', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['flow_customers.id'], ),
    sa.ForeignKeyConstraint(['id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['source_order_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_orders_store_id'), 'addon_orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_addon_orders_source_order_id'), 'addon_orders', ['source_order_id'], unique=False)
    op.create_table('addon_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('goods_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_cents', sa.BigInteger(), nullable=False),
    sa.Column('discount_cents', sa.BigInteger(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('goods_cents>=0 AND installation_cents>=0 AND discount_cents>=0 AND goods_cents+installation_cents>0', name='ck_addon_quote_money'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_addon_quote_revision')
    )
    op.create_index(op.f('ix_addon_quotes_store_id'), 'addon_quotes', ['store_id'], unique=False)
    op.create_index(op.f('ix_addon_quotes_case_id'), 'addon_quotes', ['case_id'], unique=False)
    op.create_table('addon_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_addon_targets_store_id'), 'addon_targets', ['store_id'], unique=False)
    op.create_table('addon_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['addon_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_addon_acceptances_case_id'), 'addon_acceptances', ['case_id'], unique=False)
    op.create_index(op.f('ix_addon_acceptances_store_id'), 'addon_acceptances', ['store_id'], unique=False)
    op.create_table('addon_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('minimum_cents', sa.BigInteger(), nullable=False),
    sa.Column('allow_below_minimum', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['addon_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_addon_approvals_store_id'), 'addon_approvals', ['store_id'], unique=False)
    op.create_table('addon_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['addon_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_addon_authorizations_store_id'), 'addon_authorizations', ['store_id'], unique=False)
    op.create_table('addon_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('work_code', sa.String(length=60), nullable=False),
    sa.Column('work_name', sa.String(length=120), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('goods_unit_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_unit_cents', sa.BigInteger(), nullable=False),
    sa.Column('goods_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_milli>0 AND goods_unit_cents>=0 AND installation_unit_cents>=0 AND goods_cents>=0 AND installation_cents>=0', name='ck_addon_line_values'),
    sa.ForeignKeyConstraint(['item_id'], ['flow_items.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['addon_quotes.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['master_work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'line_key', name='uq_addon_quote_line')
    )
    op.create_index(op.f('ix_addon_lines_store_id'), 'addon_lines', ['store_id'], unique=False)
    op.create_index(op.f('ix_addon_lines_quote_id'), 'addon_lines', ['quote_id'], unique=False)
    op.create_table('addon_resolutions',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('return','cancel','vehicle_gift')", name='ck_addon_resolution_kind'),
    sa.CheckConstraint("status IN ('requested','approved','consented','rectification','reinspection','handback','rejected','completed','cancelled')", name='ck_addon_resolution_status'),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['addon_quotes.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_resolutions_store_id'), 'addon_resolutions', ['store_id'], unique=False)
    op.create_index(op.f('ix_addon_resolutions_case_id'), 'addon_resolutions', ['case_id'], unique=False)
    op.create_table('addon_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('stock_move_id', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('goods_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_milli>0 AND value_cents>=0 AND goods_cents>=0 AND installation_cents>=0', name='ck_addon_dispatch'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['addon_lines.id'], ),
    sa.ForeignKeyConstraint(['stock_move_id'], ['flow_stock_moves.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['addon_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_move_id')
    )
    op.create_index(op.f('ix_addon_dispatches_case_id'), 'addon_dispatches', ['case_id'], unique=False)
    op.create_index(op.f('ix_addon_dispatches_store_id'), 'addon_dispatches', ['store_id'], unique=False)
    op.create_table('addon_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(quantity_milli>0 AND purpose='reserve') OR (quantity_milli<0 AND purpose IN ('dispatch','cancel'))", name='ck_addon_reservation'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['flow_items.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['addon_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_reservations_item_id'), 'addon_reservations', ['item_id'], unique=False)
    op.create_index(op.f('ix_addon_reservations_case_id'), 'addon_reservations', ['case_id'], unique=False)
    op.create_index(op.f('ix_addon_reservations_store_id'), 'addon_reservations', ['store_id'], unique=False)
    op.create_table('addon_resolution_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['addon_resolutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_resolution_facts_store_id'), 'addon_resolution_facts', ['store_id'], unique=False)
    op.create_index(op.f('ix_addon_resolution_facts_resolution_id'), 'addon_resolution_facts', ['resolution_id'], unique=False)
    op.create_table('addon_vehicle_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('aftercare_case_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_operation_id', sa.Integer(), nullable=False),
    sa.Column('new_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('incremental_value_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('incremental_value_cents=0', name='ck_addon_gift_no_invented_value'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['aftercare_case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['new_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['addon_resolutions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_operation_id'], ['vehicle_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id')
    )
    op.create_index(op.f('ix_addon_vehicle_handovers_case_id'), 'addon_vehicle_handovers', ['case_id'], unique=False)
    op.create_index(op.f('ix_addon_vehicle_handovers_store_id'), 'addon_vehicle_handovers', ['store_id'], unique=False)
    op.create_table('addon_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_milli>0', name='ck_addon_installation'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['addon_dispatches.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_installations_dispatch_id'), 'addon_installations', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_addon_installations_store_id'), 'addon_installations', ['store_id'], unique=False)
    op.create_table('addon_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=True),
    sa.Column('credit_link_id', sa.Integer(), nullable=True),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(payment_link_id IS NOT NULL AND credit_link_id IS NULL) OR (payment_link_id IS NULL AND credit_link_id IS NOT NULL)', name='ck_addon_payment_source'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['credit_link_id'], ['business_finance_credit_links.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['flow_payment_links.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['addon_resolutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_link_id'),
    sa.UniqueConstraint('payment_link_id')
    )
    op.create_index(op.f('ix_addon_payments_case_id'), 'addon_payments', ['case_id'], unique=False)
    op.create_index(op.f('ix_addon_payments_store_id'), 'addon_payments', ['store_id'], unique=False)
    op.create_table('addon_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['addon_installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_inspections_installation_id'), 'addon_inspections', ['installation_id'], unique=False)
    op.create_index(op.f('ix_addon_inspections_store_id'), 'addon_inspections', ['store_id'], unique=False)
    op.create_table('addon_return_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('line_key', sa.String(length=40), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('stock_move_id', sa.Integer(), nullable=True),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('goods_cents', sa.BigInteger(), nullable=False),
    sa.Column('installation_cents', sa.BigInteger(), nullable=False),
    sa.Column('retained_cents', sa.BigInteger(), nullable=False),
    sa.Column('acceptance_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_milli>0 AND value_cents>=0 AND goods_cents>=0 AND installation_cents>=0 AND retained_cents>=0 AND retained_cents<=installation_cents', name='ck_addon_return_posting'),
    sa.ForeignKeyConstraint(['acceptance_id'], ['addon_acceptances.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['addon_orders.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['addon_dispatches.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['addon_installations.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['addon_lines.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['addon_resolutions.id'], ),
    sa.ForeignKeyConstraint(['stock_move_id'], ['flow_stock_moves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_move_id')
    )
    op.create_index(op.f('ix_addon_return_postings_case_id'), 'addon_return_postings', ['case_id'], unique=False)
    op.create_index(op.f('ix_addon_return_postings_resolution_id'), 'addon_return_postings', ['resolution_id'], unique=False)
    op.create_index(op.f('ix_addon_return_postings_store_id'), 'addon_return_postings', ['store_id'], unique=False)
    op.create_table('addon_rectifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['addon_inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_index(op.f('ix_addon_rectifications_store_id'), 'addon_rectifications', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addon_rectifications')
    op.drop_table('addon_return_postings')
    op.drop_table('addon_inspections')
    op.drop_table('addon_payments')
    op.drop_table('addon_installations')
    op.drop_table('addon_vehicle_handovers')
    op.drop_table('addon_resolution_facts')
    op.drop_table('addon_reservations')
    op.drop_table('addon_dispatches')
    op.drop_table('addon_resolutions')
    op.drop_table('addon_lines')
    op.drop_table('addon_authorizations')
    op.drop_table('addon_approvals')
    op.drop_table('addon_acceptances')
    op.drop_table('addon_targets')
    op.drop_table('addon_quotes')
    op.drop_table('addon_orders')
    op.drop_table('addon_receipts')
    # ### end Alembic commands ###
