"""Original-VIN transport investigations, actual losses, found receipts and cash."""
from alembic import op
import sqlalchemy as sa

revision = 'r80e_vehicle_transport'
down_revision = 'q79d_gate_visits'
branch_labels = None
depends_on = None

def upgrade():
    # Frozen schema for this revision; never import current application metadata.
    op.create_table('vehicle_transport_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_vehicle_transport_request')
    )
    op.create_index(op.f('ix_vehicle_transport_requests_store_id'), 'vehicle_transport_requests', ['store_id'], unique=False)
    op.create_table('vehicle_transport_exceptions',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('active_transfer_id', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('origin_status', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("origin_status IN ('transit','rejected','return_transit') AND kind IN ('missing','vin_mismatch','damage') AND status IN ('investigating','review','approved','posted','resolved','recovered') AND ((status IN ('resolved','recovered') AND active_transfer_id IS NULL) OR (status NOT IN ('resolved','recovered') AND active_transfer_id IS NOT NULL AND active_transfer_id=transfer_id))", name='ck_vehicle_transport_exception'),
    sa.ForeignKeyConstraint(['active_transfer_id'], ['vehicle_transfers.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['vehicle_movements.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['vehicle_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_transfer_id')
    )
    op.create_index(op.f('ix_vehicle_transport_exceptions_transfer_id'), 'vehicle_transport_exceptions', ['transfer_id'], unique=False)
    op.create_table('vehicle_transport_claims',
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_kind', sa.String(length=12), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('insurer_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_snapshot', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(counterparty_kind='carrier' AND supplier_id IS NOT NULL AND insurer_id IS NULL) OR (counterparty_kind='insurer' AND insurer_id IS NOT NULL AND supplier_id IS NULL)", name='ck_vehicle_transport_claim_party'),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['master_insurers.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['master_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_transport_claims_exception_id'), 'vehicle_transport_claims', ['exception_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transport_claims_store_id'), 'vehicle_transport_claims', ['store_id'], unique=False)
    op.create_table('vehicle_transport_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('actual_at', sa.DateTime(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('dispatch_verified','not_located','original_seen','unusable_held','other_vin_seen','found_usable') AND actual_at<=created_at", name='ck_vehicle_transport_observation'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_transport_observations_exception_id'), 'vehicle_transport_observations', ['exception_id'], unique=False)
    op.create_table('vehicle_transport_claim_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('target_cents', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('revision>0 AND target_cents>=0', name='ck_vehicle_transport_claim_target'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['vehicle_transport_claims.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'revision', name='uq_vehicle_transport_claim_revision')
    )
    op.create_index(op.f('ix_vehicle_transport_claim_plans_claim_id'), 'vehicle_transport_claim_plans', ['claim_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transport_claim_plans_store_id'), 'vehicle_transport_claim_plans', ['store_id'], unique=False)
    op.create_table('vehicle_transport_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_observation_id', sa.Integer(), nullable=False),
    sa.Column('destination_observation_id', sa.Integer(), nullable=False),
    sa.Column('found_observation_id', sa.Integer(), nullable=True),
    sa.Column('receiving_store_id', sa.Integer(), nullable=True),
    sa.Column('source_bearer_cents', sa.BigInteger(), nullable=False),
    sa.Column('destination_bearer_cents', sa.BigInteger(), nullable=False),
    sa.Column('loss_method', sa.String(length=12), nullable=False),
    sa.Column('origin_digest', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("revision>0 AND source_bearer_cents>=0 AND destination_bearer_cents>=0 AND ((kind='resume' AND loss_method='none' AND source_bearer_cents=0 AND destination_bearer_cents=0 AND found_observation_id IS NULL AND receiving_store_id IS NULL) OR (kind='loss' AND loss_method IN ('missing','destroyed') AND found_observation_id IS NULL AND receiving_store_id IS NULL) OR (kind='found_receive' AND loss_method='none' AND source_bearer_cents=0 AND destination_bearer_cents=0 AND found_observation_id IS NOT NULL AND receiving_store_id IS NOT NULL))", name='ck_vehicle_transport_plan'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_observation_id'], ['vehicle_transport_observations.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['found_observation_id'], ['vehicle_transport_observations.id'], ),
    sa.ForeignKeyConstraint(['receiving_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['source_observation_id'], ['vehicle_transport_observations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exception_id', 'revision', name='uq_vehicle_transport_plan_revision')
    )
    op.create_index(op.f('ix_vehicle_transport_plans_exception_id'), 'vehicle_transport_plans', ['exception_id'], unique=False)
    op.create_table('vehicle_transport_claim_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents>0 AND ((direction='in' AND original_id IS NULL) OR (direction='out' AND original_id IS NOT NULL))", name='ck_vehicle_transport_claim_cash'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['vehicle_transport_claims.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['vehicle_transport_claim_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_claim_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id'),
    sa.UniqueConstraint('store_id', 'account_id', 'reference', name='uq_vehicle_transport_claim_cash_reference')
    )
    op.create_index(op.f('ix_vehicle_transport_claim_payments_claim_id'), 'vehicle_transport_claim_payments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transport_claim_payments_store_id'), 'vehicle_transport_claim_payments', ['store_id'], unique=False)
    op.create_table('vehicle_transport_claim_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('approve','reject')", name='ck_vehicle_transport_claim_review'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_claim_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_vehicle_transport_claim_reviews_store_id'), 'vehicle_transport_claim_reviews', ['store_id'], unique=False)
    op.create_table('vehicle_transport_claim_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_claim_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_vehicle_transport_claim_withdrawals_store_id'), 'vehicle_transport_claim_withdrawals', ['store_id'], unique=False)
    op.create_table('vehicle_transport_disposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exception_id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('vehicle_transport_found_unavailable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('missing_again','not_usable')", name='ck_vehicle_transport_found_unavailable'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['vehicle_transport_observations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_vehicle_transport_found_unavailable_exception_id'), 'vehicle_transport_found_unavailable', ['exception_id'], unique=False)
    op.create_table('vehicle_transport_losses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('source_bearer_cents', sa.BigInteger(), nullable=False),
    sa.Column('destination_bearer_cents', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("value_cents>=0 AND source_bearer_cents>=0 AND destination_bearer_cents>=0 AND source_bearer_cents+destination_bearer_cents=value_cents AND kind IN ('missing','destroyed')", name='ck_vehicle_transport_loss'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['vehicle_movements.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_plans.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['vehicle_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exception_id'),
    sa.UniqueConstraint('plan_id'),
    sa.UniqueConstraint('transfer_id')
    )
    op.create_index(op.f('ix_vehicle_transport_losses_store_id'), 'vehicle_transport_losses', ['store_id'], unique=False)
    op.create_table('vehicle_transport_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('approve','reject')", name='ck_vehicle_transport_review'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'store_id', name='uq_vehicle_transport_review_party')
    )
    op.create_index(op.f('ix_vehicle_transport_reviews_plan_id'), 'vehicle_transport_reviews', ['plan_id'], unique=False)
    op.create_table('vehicle_transport_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('vehicle_transport_found_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('loss_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('value_cents>=0', name='ck_vehicle_transport_found_receipt'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['master_locations.id'], ),
    sa.ForeignKeyConstraint(['loss_id'], ['vehicle_transport_losses.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['vehicle_transport_observations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['vehicle_transport_plans.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['vehicle_transfers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exception_id'),
    sa.UniqueConstraint('loss_id'),
    sa.UniqueConstraint('plan_id'),
    sa.UniqueConstraint('transfer_id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicle_transport_found_receipts_store_id'), 'vehicle_transport_found_receipts', ['store_id'], unique=False)
    op.create_table('vehicle_transport_loss_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('loss_id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_store_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents!=0', name='ck_vehicle_transport_loss_settlement'),
    sa.ForeignKeyConstraint(['counterparty_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['vehicle_transport_exceptions.id'], ),
    sa.ForeignKeyConstraint(['loss_id'], ['vehicle_transport_losses.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['vehicle_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loss_id', 'store_id', name='uq_vehicle_transport_loss_settlement')
    )
    op.create_index(op.f('ix_vehicle_transport_loss_settlements_store_id'), 'vehicle_transport_loss_settlements', ['store_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transport_loss_settlements_transfer_id'), 'vehicle_transport_loss_settlements', ['transfer_id'], unique=False)
    op.create_table('vehicle_transport_found_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('loss_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_store_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents!=0', name='ck_vehicle_transport_found_settlement'),
    sa.ForeignKeyConstraint(['counterparty_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['loss_id'], ['vehicle_transport_losses.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['vehicle_transport_found_receipts.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['vehicle_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id', 'store_id', name='uq_vehicle_transport_found_settlement')
    )
    op.create_index(op.f('ix_vehicle_transport_found_settlements_store_id'), 'vehicle_transport_found_settlements', ['store_id'], unique=False)
    op.create_index(op.f('ix_vehicle_transport_found_settlements_transfer_id'), 'vehicle_transport_found_settlements', ['transfer_id'], unique=False)
    with op.batch_alter_table('vehicle_transfers') as batch:
        batch.drop_constraint('ck_vehicle_transfer_status', type_='check')
        batch.create_check_constraint('ck_vehicle_transfer_status', "status IN ('requested','approved','transit','rejected','return_transit','accepted','returned','cancelled','lost','recovered')")
    with op.batch_alter_table('interstore_clearing_buckets') as batch:
        batch.drop_constraint('ck_clearing_parties', type_='check')
        batch.create_check_constraint('ck_clearing_parties', "origin_kind IN ('material','material_loss','material_found','vehicle','vehicle_loss','vehicle_found') AND payer_store_id!=receiver_store_id")

def downgrade():
    raise RuntimeError('Do not erase original vehicle loss, finding, or actual payment records. Restore a verified full pre-upgrade backup instead.')
