"""Frozen group membership lifecycle and source-linked earned points."""
from alembic import op
import sqlalchemy as sa

revision = "s319_membership"
down_revision = "r218_warehouse"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_store_ids', sa.JSON(), nullable=False),
    sa.Column('validity_months', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('fee_owner', sa.String(length=30), nullable=False),
    sa.Column('refund_policy', sa.String(length=30), nullable=False),
    sa.Column('points_enabled', sa.Boolean(), nullable=False),
    sa.Column('points_numerator', sa.BigInteger(), nullable=False),
    sa.Column('points_denominator_fen', sa.BigInteger(), nullable=False),
    sa.Column('points_benefit_rule_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("fee_owner='collecting_store' AND refund_policy IN ('none','before_start')", name='ck_membership_rule_policy'),
    sa.CheckConstraint('NOT points_enabled OR points_benefit_rule_id IS NOT NULL', name='ck_membership_rule_points'),
    sa.CheckConstraint('rule_version>0 AND validity_months BETWEEN 1 AND 120 AND fee_cents>=0 AND points_numerator>0 AND points_denominator_fen>0', name='ck_membership_rule_values'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['points_benefit_rule_id'], ['benefit_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'rule_version', name='uq_membership_rule_version')
    )
    op.create_table('membership_cards',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('issuer_store_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("generation>0 AND status IN ('active','lost','replaced')", name='ck_membership_card_status'),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['issuer_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['membership_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('member_id', 'generation', name='uq_membership_card_generation'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('previous_id')
    )
    op.create_index('uq_membership_active_card', 'membership_cards', ['member_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.create_table('membership_orders',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("purpose IN ('topup','benefit_issue','card_issue','card_loss','card_replace','renew','tier_change','renew_refund','points_adjust')", name='ck_membership_order_purpose'),
    sa.CheckConstraint("status IN ('draft','review','approved','completed','cancelled')", name='ck_membership_order_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_membership_orders_store_id'), 'membership_orders', ['store_id'], unique=False)
    op.create_table('membership_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.CheckConstraint("starts_on<=ends_on AND kind IN ('renew','tier_change')", name='ck_membership_period'),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['membership_rules.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('membership_points_claims',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('basis_cents', sa.BigInteger(), nullable=False),
    sa.Column('target_units', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('basis_cents>=0 AND target_units>=0', name='ck_membership_points_claim'),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['membership_rules.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('membership_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_events_store_id'), 'membership_events', ['store_id'], unique=False)
    op.create_table('membership_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(original_id IS NULL AND amount_cents>0) OR (original_id IS NOT NULL AND amount_cents<0)', name='ck_membership_fee_sign'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['membership_fees.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['membership_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('cash_id'),
    sa.UniqueConstraint('original_id'),
    sa.UniqueConstraint('store_id', 'account_id', 'reference', name='uq_membership_fee_reference')
    )
    op.create_index(op.f('ix_membership_fees_store_id'), 'membership_fees', ['store_id'], unique=False)
    op.create_table('membership_period_voids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['membership_periods.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('period_id')
    )
    op.create_table('membership_points_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('basis_cents', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('units!=0 AND basis_cents>=0', name='ck_membership_points_change'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['membership_points_claims.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['benefit_wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id')
    )
    op.create_table('membership_points_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('units>0', name='ck_membership_points_debt'),
    sa.ForeignKeyConstraint(['change_id'], ['membership_points_changes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id')
    )
    op.create_table('membership_points_recoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('benefit_entry_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('units>0', name='ck_membership_points_recovery'),
    sa.ForeignKeyConstraint(['benefit_entry_id'], ['benefit_entries.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['membership_points_changes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefit_entry_id')
    )
    op.create_table('membership_points_debt_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('benefit_entry_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('units>0', name='ck_membership_points_debt_payment'),
    sa.ForeignKeyConstraint(['benefit_entry_id'], ['benefit_entries.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['membership_points_debts.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefit_entry_id')
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('membership_points_debt_payments')
    op.drop_table('membership_points_recoveries')
    op.drop_table('membership_points_debts')
    op.drop_table('membership_points_changes')
    op.drop_table('membership_period_voids')
    op.drop_table('membership_fees')
    op.drop_table('membership_events')
    op.drop_table('membership_points_claims')
    op.drop_table('membership_periods')
    op.drop_table('membership_orders')
    op.drop_table('membership_cards')
    op.drop_table('membership_rules')
