"""Named cross-store historical record/per-file authorization; no source changes."""
from alembic import op
import sqlalchemy as sa
revision = 's91f_dossier_grants'
down_revision = 'r80e_vehicle_transport'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossier_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=False),
    sa.Column('to_store_id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('source_case_version', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('recipient_role', sa.String(length=20), nullable=False),
    sa.Column('recipient_access_version', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requester_role', sa.String(length=20), nullable=False),
    sa.Column('requester_access_version', sa.Integer(), nullable=False),
    sa.Column('include_record', sa.Boolean(), nullable=False),
    sa.Column('include_financials', sa.Boolean(), nullable=False),
    sa.Column('include_contact', sa.Boolean(), nullable=False),
    sa.Column('record_snapshot', sa.JSON(), nullable=False),
    sa.Column('scope_digest', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("from_store_id != to_store_id AND source_case_version > 0 AND recipient_access_version > 0 AND requester_access_version > 0 AND version > 0 AND expires_at > created_at AND status IN ('pending','approved','rejected','cancelled','revoked')", name='ck_dossier_grant'),
    sa.CheckConstraint('(include_financials = false OR include_record = true) AND (include_contact = false OR include_record = true)', name='ck_dossier_record_scope'),
    sa.ForeignKeyConstraint(['from_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['to_store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_grants_expires_at'), 'dossier_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_dossier_grants_from_store_id'), 'dossier_grants', ['from_store_id'], unique=False)
    op.create_index(op.f('ix_dossier_grants_recipient_id'), 'dossier_grants', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_dossier_grants_source_case_id'), 'dossier_grants', ['source_case_id'], unique=False)
    op.create_index(op.f('ix_dossier_grants_status'), 'dossier_grants', ['status'], unique=False)
    op.create_index(op.f('ix_dossier_grants_to_store_id'), 'dossier_grants', ['to_store_id'], unique=False)
    op.create_table('dossier_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('grant_version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('actor_access_version', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('scope_digest', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("grant_version > 0 AND actor_access_version > 0 AND ((action IN ('record','directory') AND file_id IS NULL) OR (action='file' AND file_id IS NOT NULL))", name='ck_dossier_access'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['dossier_grants.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_accesses_grant_id'), 'dossier_accesses', ['grant_id'], unique=False)
    op.create_table('dossier_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('actor_access_version', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('scope_digest', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("previous_version > 0 AND actor_access_version > 0 AND action IN ('approve','reject','cancel','revoke')", name='ck_dossier_decision'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['dossier_grants.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_id', 'previous_version', name='uq_dossier_decision_version')
    )
    op.create_index(op.f('ix_dossier_decisions_grant_id'), 'dossier_decisions', ['grant_id'], unique=False)
    op.create_table('dossier_grant_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['dossier_grants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_id', 'file_id', name='uq_dossier_grant_file')
    )
    op.create_index(op.f('ix_dossier_grant_files_grant_id'), 'dossier_grant_files', ['grant_id'], unique=False)
    op.create_table('dossier_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('scope_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['dossier_grants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_dossier_receipt')
    )
    op.create_index(op.f('ix_dossier_receipts_store_id'), 'dossier_receipts', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("档案授权含原范围与读取证据，不支持破坏性降级；请恢复整库及私有附件备份")
