"""Frozen business finance allocations and approved source-capture returns."""
from alembic import op
import sqlalchemy as sa

revision='x824_business_finance'
down_revision='w723_aftercare'
branch_labels=None
depends_on=None


def upgrade():
    bind=op.get_bind()
    unique=sa.inspect(bind).get_unique_constraints('flow_payment_links')
    selected=[c for c in unique if c['column_names'] in [['cash_id'],['store_id','account_id','reference']]]
    if len(selected)!=2:raise RuntimeError('Expected two original payment uniqueness constraints; inspect the isolated migration copy')
    with op.batch_alter_table('flow_payment_links',naming_convention={'uq':'uq_%(table_name)s_%(column_0_name)s'}) as batch:
        for constraint in selected:
            name=constraint['name'] or 'uq_flow_payment_links_'+constraint['column_names'][0]
            batch.drop_constraint(name,type_='unique')
        batch.create_index('ix_flow_payment_links_cash_id',['cash_id'])
        batch.create_index('ix_flow_payment_reference',['store_id','account_id','reference'])
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_finance_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'request_key', name='uq_business_finance_request')
    )
    op.create_index(op.f('ix_business_finance_receipts_store_id'), 'business_finance_receipts', ['store_id'], unique=False)
    op.create_table('business_finance_orders',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("purpose IN ('advance','advance_apply','advance_refund','statement','correction','other_return')", name='ck_finance_order_purpose'),
    sa.CheckConstraint("status IN ('draft','approved','completed','cancelled','superseded')", name='ck_finance_order_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_business_finance_orders_store_id'), 'business_finance_orders', ['store_id'], unique=False)
    op.create_table('business_finance_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('starts_on<=ends_on AND revision>0', name='ck_finance_statement_period'),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['flow_customers.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['business_finance_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('previous_id'),
    sa.UniqueConstraint('store_id', 'customer_id', 'starts_on', 'ends_on', 'revision', name='uq_finance_statement_version')
    )
    op.create_index(op.f('ix_business_finance_statements_store_id'), 'business_finance_statements', ['store_id'], unique=False)
    op.create_table('business_finance_advances',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('initial_cents', sa.BigInteger(), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('reserved_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('initial_cents>0 AND 0<=reserved_cents AND reserved_cents<=balance_cents AND balance_cents<=initial_cents', name='ck_finance_advance_available'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['flow_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('cash_id')
    )
    op.create_index(op.f('ix_business_finance_advances_customer_id'), 'business_finance_advances', ['customer_id'], unique=False)
    op.create_index(op.f('ix_business_finance_advances_store_id'), 'business_finance_advances', ['store_id'], unique=False)
    op.create_table('business_finance_cash_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('collection','correction_reverse','correction_record') AND amount_cents>0", name='ck_finance_cash_batch'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id')
    )
    op.create_index(op.f('ix_business_finance_cash_batches_case_id'), 'business_finance_cash_batches', ['case_id'], unique=False)
    op.create_index(op.f('ix_business_finance_cash_batches_store_id'), 'business_finance_cash_batches', ['store_id'], unique=False)
    op.create_table('business_finance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_finance_events_case_id'), 'business_finance_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_business_finance_events_store_id'), 'business_finance_events', ['store_id'], unique=False)
    op.create_table('business_finance_return_receivables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('stock_move_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents>0 AND quantity_milli>0 AND value_cents>=0', name='ck_finance_return_receivable'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['stock_move_id'], ['flow_stock_moves.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['master_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('stock_move_id')
    )
    op.create_index(op.f('ix_business_finance_return_receivables_store_id'), 'business_finance_return_receivables', ['store_id'], unique=False)
    op.create_table('business_finance_statement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('due_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('due_cents>0', name='ck_finance_statement_due'),
    sa.ForeignKeyConstraint(['source_case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['business_finance_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_id', 'source_case_id', name='uq_finance_statement_source')
    )
    op.create_index(op.f('ix_business_finance_statement_lines_statement_id'), 'business_finance_statement_lines', ['statement_id'], unique=False)
    op.create_index(op.f('ix_business_finance_statement_lines_store_id'), 'business_finance_statement_lines', ['store_id'], unique=False)
    op.create_table('business_finance_advance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advance_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('cash_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(purpose IN ('receive','return') AND amount_cents>0) OR (purpose IN ('apply','refund') AND amount_cents<0)", name='ck_finance_advance_entry'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['advance_id'], ['business_finance_advances.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['business_finance_advance_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_id')
    )
    op.create_index(op.f('ix_business_finance_advance_entries_advance_id'), 'business_finance_advance_entries', ['advance_id'], unique=False)
    op.create_index(op.f('ix_business_finance_advance_entries_store_id'), 'business_finance_advance_entries', ['store_id'], unique=False)
    op.create_table('business_finance_applications',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('advance_id', sa.Integer(), nullable=False),
    sa.Column('target_case_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('apply','refund') AND amount_cents>0", name='ck_finance_application_value'),
    sa.CheckConstraint("status IN ('requested','reserved','applied','released')", name='ck_finance_application_status'),
    sa.ForeignKeyConstraint(['advance_id'], ['business_finance_advances.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['target_case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_business_finance_applications_advance_id'), 'business_finance_applications', ['advance_id'], unique=False)
    op.create_index(op.f('ix_business_finance_applications_store_id'), 'business_finance_applications', ['store_id'], unique=False)
    op.create_index(op.f('ix_business_finance_applications_target_case_id'), 'business_finance_applications', ['target_case_id'], unique=False)
    op.create_table('business_finance_cash_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=False),
    sa.Column('statement_line_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents>0', name='ck_finance_cash_allocation'),
    sa.ForeignKeyConstraint(['batch_id'], ['business_finance_cash_batches.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['flow_payment_links.id'], ),
    sa.ForeignKeyConstraint(['statement_line_id'], ['business_finance_statement_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_link_id')
    )
    op.create_index(op.f('ix_business_finance_cash_allocations_batch_id'), 'business_finance_cash_allocations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_business_finance_cash_allocations_case_id'), 'business_finance_cash_allocations', ['case_id'], unique=False)
    op.create_index(op.f('ix_business_finance_cash_allocations_store_id'), 'business_finance_cash_allocations', ['store_id'], unique=False)
    op.create_table('business_finance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('original_cash_id', sa.Integer(), nullable=False),
    sa.Column('reversing_batch_id', sa.Integer(), nullable=False),
    sa.Column('corrected_batch_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['corrected_batch_id'], ['business_finance_cash_batches.id'], ),
    sa.ForeignKeyConstraint(['original_cash_id'], ['cash_entries.id'], ),
    sa.ForeignKeyConstraint(['reversing_batch_id'], ['business_finance_cash_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('corrected_batch_id'),
    sa.UniqueConstraint('original_cash_id'),
    sa.UniqueConstraint('reversing_batch_id')
    )
    op.create_index(op.f('ix_business_finance_corrections_store_id'), 'business_finance_corrections', ['store_id'], unique=False)
    op.create_table('group_aftercare_holds',
    sa.Column('aftercare_case_id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('original_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('discount_cents', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('principal','benefit') AND units>0 AND credit_cents>0 AND discount_cents>=0", name='ck_group_aftercare_hold_value'),
    sa.CheckConstraint("status IN ('reserved','released','applied')", name='ck_group_aftercare_hold_status'),
    sa.ForeignKeyConstraint(['aftercare_case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['aftercare_plans.id'], ),
    sa.ForeignKeyConstraint(['source_case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['benefit_wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'kind', 'original_id', name='uq_group_aftercare_origin')
    )
    op.create_index(op.f('ix_group_aftercare_holds_store_id'), 'group_aftercare_holds', ['store_id'], unique=False)
    op.create_table('business_finance_credit_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents!=0', name='ck_finance_credit_nonzero'),
    sa.ForeignKeyConstraint(['application_id'], ['business_finance_applications.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['business_finance_advance_entries.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['business_finance_credit_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index(op.f('ix_business_finance_credit_links_case_id'), 'business_finance_credit_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_business_finance_credit_links_store_id'), 'business_finance_credit_links', ['store_id'], unique=False)
    op.create_table('group_aftercare_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('principal','benefit')", name='ck_group_aftercare_posting_kind'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['hold_id'], ['group_aftercare_holds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hold_id'),
    sa.UniqueConstraint('kind', 'entry_id', name='uq_group_aftercare_posting')
    )
    op.create_index(op.f('ix_group_aftercare_postings_store_id'), 'group_aftercare_postings', ['store_id'], unique=False)
    op.create_table('business_finance_advance_returns',
    sa.Column('aftercare_case_id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('original_credit_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('returned_credit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_cents>0 AND status IN ('reserved','applied','released')", name='ck_finance_advance_return'),
    sa.ForeignKeyConstraint(['aftercare_case_id'], ['flow_cases.id'], ),
    sa.ForeignKeyConstraint(['original_credit_id'], ['business_finance_credit_links.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['aftercare_plans.id'], ),
    sa.ForeignKeyConstraint(['returned_credit_id'], ['business_finance_credit_links.id'], ),
    sa.ForeignKeyConstraint(['source_case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'original_credit_id', name='uq_finance_advance_return'),
    sa.UniqueConstraint('returned_credit_id')
    )
    op.create_index(op.f('ix_business_finance_advance_returns_store_id'), 'business_finance_advance_returns', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Business finance contains split cash and immutable original-source facts; use a reviewed backup restore, never silently downgrade')
