"""Frozen reviewed opening balances and physical inventory source facts."""
from alembic import op
import sqlalchemy as sa

revision="z026_opening_import"
down_revision="y925_private_files"
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_imports',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('prepared','trial_passed','approved','confirmed','cancelled')", name='ck_opening_import_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['opening_batches.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['flow_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_opening_imports_store_id'), 'opening_imports', ['store_id'], unique=False)
    op.create_table('opening_attestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('approve','inventory','finance')", name='ck_opening_attestation_kind'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['opening_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'kind', name='uq_opening_attestation_kind')
    )
    op.create_index(op.f('ix_opening_attestations_import_id'), 'opening_attestations', ['import_id'], unique=False)
    op.create_index(op.f('ix_opening_attestations_store_id'), 'opening_attestations', ['store_id'], unique=False)
    op.create_table('opening_account_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('source_reference', sa.String(length=160), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_cents>=0 AND row_number>0', name='ck_opening_account_value'),
    sa.ForeignKeyConstraint(['account_id'], ['flow_accounts.id'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['opening_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('import_id', 'row_number', name='uq_opening_account_row')
    )
    op.create_index(op.f('ix_opening_account_entries_import_id'), 'opening_account_entries', ['import_id'], unique=False)
    op.create_index(op.f('ix_opening_account_entries_store_id'), 'opening_account_entries', ['store_id'], unique=False)
    op.create_table('opening_vehicle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('source_reference', sa.String(length=160), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('value_cents>=0 AND row_number>0', name='ck_opening_vehicle_value'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['flow_files.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['group_identities.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['opening_imports.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['master_locations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['master_vehicle_models.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'row_number', name='uq_opening_vehicle_row'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_opening_vehicle_entries_import_id'), 'opening_vehicle_entries', ['import_id'], unique=False)
    op.create_index(op.f('ix_opening_vehicle_entries_store_id'), 'opening_vehicle_entries', ['store_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('opening_vehicle_entries')
    op.drop_table('opening_account_entries')
    op.drop_table('opening_attestations')
    op.drop_table('opening_imports')
