"""Build the XC round-by-round trial scripts from the reviewed trial sources.

Reads only docs/trial-source/*.json plus the published requirement/workflow catalogue.
No application, database or model is invoked. --check validates exact generated bytes.
"""
import argparse
import html
import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/trial-source'
CATALOGUE = ROOT / 'docs/workflow-source'
OUT = ROOT / 'docs/试用脚本'
PORTABLE = ROOT / 'docs/试用操作手册-XC.html'
INDEX_NAME = '总表.md'
# Must stay identical to app/security.py ROLES keys; tests/test_trial_scripts.py compares them.
ROLES = {'admin', 'manager', 'sales', 'inventory', 'service', 'finance', 'auditor',
         'reception', 'technician', 'customer_service'}
# Same labels as web/workflowcontent.js so the scripts read like the pages do.
ROLE_LABELS = {'admin': '管理员', 'manager': '店长', 'sales': '销售', 'service': '服务顾问',
               'customer_service': '客服', 'reception': '接待', 'inventory': '库管',
               'technician': '技师', 'finance': '财务', 'auditor': '复核人员'}
CHANNELS = ('manual', 'search', 'assistant')
BRANCH_KINDS = ('refusal', 'duplicate', 'stale', 'cross-store', 'edge')
STEP_KEYS = ('no', 'actor', 'account', 'workflow', 'route', 'channel', 'entry', 'search', 'assistant', 'action', 'expect')
ROUND_COUNT = 41


def read(path):
    return json.loads(Path(path).read_text('utf-8-sig'))


def text(value, label):
    assert isinstance(value, str) and value.strip(), label
    return value.strip()


def requirement_workflow_maps():
    """Published authority: requirement register, group mapping and workflow sources."""
    register = read(ROOT / 'docs/requirements.json')
    requirements = {row['id']: row for row in register['requirements']}
    assert len(requirements) == 193, 'requirement register changed'
    coverage = read(CATALOGUE / 'coverage.json')
    groups = {}
    for row in coverage['mapping']:
        entry = groups.setdefault((row['module'], row['group']), {'requirements': [], 'workflows': []})
        entry['requirements'].append({'id': row['id'], 'title': row['title']})
        for workflow_id in row['workflow_ids']:
            if workflow_id not in entry['workflows']:
                entry['workflows'].append(workflow_id)
    workflows = {}
    for name in ('business.json', 'services.json'):
        for item in read(CATALOGUE / name):
            assert item['id'] not in workflows, 'duplicate workflow ' + item['id']
            workflows[item['id']] = item
    assert all(workflow_id in workflows for entry in groups.values() for workflow_id in entry['workflows'])
    return requirements, groups, workflows


def normalise(value):
    """Same normalisation as web/workflowcontent.js so a search term means the same thing."""
    value = unicodedata.normalize('NFKC', str(value or '')).lower().replace('预定', '预订')
    return ''.join(ch for ch in value if not ch.isspace() and unicodedata.category(ch)[0] not in ('P', 'S'))


def search_haystack(workflow, requirements):
    parts = [workflow['title'], workflow['category'], workflow['summary'], workflow['entry']['label']]
    parts += list(workflow.get('keywords') or [])
    parts += [step['where'] for step in workflow.get('manual') or []]
    parts += [issue['when'] for issue in workflow.get('exceptions') or []]
    for requirement_id in workflow['requirement_ids']:
        row = requirements[requirement_id]
        parts += [requirement_id, row['title'], row['group']]
    return normalise(' '.join(parts))


def search_hits(term, workflow, requirements):
    hay = search_haystack(workflow, requirements)
    words = [normalise(word) for word in str(term or '').split()]
    return all(word and word in hay for word in words)


def search_rank(term, workflows, requirements):
    """Order the catalogue the way the in-page search box does, ignoring the per-role bonus."""
    query = normalise(term)
    hits = [workflow for workflow in workflows if search_hits(term, workflow, requirements)]

    def score(workflow):
        title = normalise(workflow['title'])
        keys = [normalise(key) for key in workflow['keywords']]
        entry = normalise(workflow['entry']['label']).removeprefix(normalise('打开'))
        requirements_text = [normalise(rid + ' ' + requirements[rid]['title'])
                             for rid in workflow['requirement_ids']]
        return ((100 if title == query else 0) + (60 if entry == query else 0)
                + (40 if title.startswith(query) else 0) + (25 if query in title else 0)
                + (20 if query in keys else 0)
                + (12 if any(query in text for text in requirements_text) else 0))

    return sorted(hits, key=lambda workflow: (-score(workflow), workflow['title']))


def app_routes():
    """Route tokens actually dispatched by the front end; scripts must not invent pages."""
    source = (ROOT / 'web/app.js').read_text('utf-8')
    found = set(re.findall(r"type==='([a-z][a-z0-9/-]*)'", source))
    found |= set(re.findall(r"nav\('([a-z][a-z0-9/-]*)'", source))
    return {route for route in found if route}


def make_data():
    world = read(SOURCE / 'world.json')
    rounds_source = read(SOURCE / 'rounds.json')
    requirements, groups, workflows = requirement_workflow_maps()
    routes = app_routes()

    assert world['schema_version'] == 1 and rounds_source['schema_version'] == 1, 'unsupported source schema'
    assert world['code'] == rounds_source['code'], 'world and rounds must share one code'
    text(world['title'], 'world title')
    text(rounds_source['title'], 'rounds title')
    accounts = world['accounts']
    assert accounts, 'world needs at least one account'
    usernames = set()
    for account in accounts:
        text(account['username'], 'account username')
        assert account['username'] not in usernames, 'duplicate account ' + account['username']
        usernames.add(account['username'])
        assert account['role'] in ROLES, account['username'] + ' has an unknown role'
        text(account['display_name'], 'account display name')
    for convention in world['conventions']:
        for key in ('label', 'value', 'note'):
            text(convention[key], 'convention ' + key)
    for section in world['sections']:
        text(section['title'], 'section title')
        assert section['kind'] in ('table', 'list', 'text'), section['title']
        if section['kind'] == 'table':
            assert section['columns'] and section['rows'], 'empty table in ' + section['title']
            assert all(len(row) == len(section['columns']) for row in section['rows']), 'column mismatch in ' + section['title']
        elif section['kind'] == 'list':
            assert section['items'], 'empty list in ' + section['title']
        else:
            text(section['text'], 'section text')

    rounds = rounds_source['rounds']
    assert len(rounds) == ROUND_COUNT, 'expected %d rounds' % ROUND_COUNT
    seen_groups, seen_slugs = set(), set()
    for index, item in enumerate(rounds, start=1):
        assert item['id'] == 'R%02d' % index, 'rounds must be listed in order: ' + item['id']
        assert item['status'] in ('outline', 'detailed'), item['id']
        key = (item['module'], item['group'])
        assert key in groups, 'unknown module/group: %s / %s' % key
        assert key not in seen_groups, 'group appears twice: %s' % (key,)
        seen_groups.add(key)
        text(item['title'], item['id'] + ' title')
        text(item['slug'], item['id'] + ' slug')
        assert item['slug'] not in seen_slugs, 'duplicate slug ' + item['slug']
        seen_slugs.add(item['slug'])
        text(item['scenario'], item['id'] + ' scenario')
        assert item['prerequisites'], item['id'] + ' prerequisites'
        for note in item['prerequisites']:
            text(note, item['id'] + ' prerequisite')
        mapping = groups[key]
        item['requirements'] = list(mapping['requirements'])
        item['workflows'] = [workflows[workflow_id] for workflow_id in mapping['workflows']]
        if item['status'] == 'outline':
            continue
        assert item.get('data'), item['id'] + ' data'
        for row in item['data']:
            for field in ('label', 'value', 'note'):
                text(row[field], item['id'] + ' data field')
        assert item.get('steps'), item['id'] + ' steps'
        numbers = set()
        for step in item['steps']:
            for field in STEP_KEYS:
                assert field in step, '%s step misses %s' % (item['id'], field)
            text(step['no'], item['id'] + ' step number')
            assert step['no'] not in numbers, 'duplicate step ' + step['no']
            numbers.add(step['no'])
            assert step['channel'] in CHANNELS, step['no']
            text(step['actor'], step['no'] + ' actor')
            text(step['action'], step['no'] + ' action')
            text(step['expect'], step['no'] + ' expect')
            assert step['workflow'] in workflows, step['no'] + ' unknown workflow'
            workflow = workflows[step['workflow']]
            assert step['workflow'] in mapping['workflows'], step['no'] + ' workflow outside this group'
            assert isinstance(step.get('optional', False), bool), step['no'] + ' optional'
            if step['account']:
                assert step['account'] in usernames, step['no'] + ' unknown account'
            route = step['route']
            if route:
                known = routes | {item['entry']['route'] for item in workflows.values()}
                assert route in known, step['no'] + ' unknown route ' + route
            if step['search']:
                assert search_hits(step['search'], workflow, requirements), \
                    '%s search %r does not reach %s' % (step['no'], step['search'], step['workflow'])
                ranked = [flow['id'] for flow in search_rank(step['search'], list(workflows.values()), requirements)][:3]
                assert step['workflow'] in ranked, \
                    '%s search %r leads to %s, not %s' % (step['no'], step['search'], ranked, step['workflow'])
            if step['assistant']:
                text(workflow['assistant']['prompt'], step['no'] + ' assistant prompt')
        for branch in item.get('branches') or []:
            assert branch['kind'] in BRANCH_KINDS, item['id'] + ' branch kind'
            text(branch['action'], item['id'] + ' branch action')
            text(branch['expect'], item['id'] + ' branch expectation')
        for note in item.get('observations') or []:
            text(note, item['id'] + ' observation')
        assert item.get('observations'), item['id'] + ' observations'
        assert item.get('checks'), item['id'] + ' checks'
        for note in item['checks']:
            text(note, item['id'] + ' check')
        text(item['report_check'], item['id'] + ' report check')
    return {'world': world, 'rounds': rounds, 'requirements': requirements,
            'groups': groups, 'workflows': workflows,
            'detailed': [item for item in rounds if item['status'] == 'detailed']}


def table(columns, rows):
    lines = ['| ' + ' | '.join(columns) + ' |', '|' + '---|' * len(columns)]
    for row in rows:
        lines.append('| ' + ' | '.join(str(cell) for cell in row) + ' |')
    return '\n'.join(lines)


def world_markdown(world, level=2):
    out = ['%s 虚拟世界设定 · %s' % ('#' * level, world['title']), '',
           '%s 账号' % ('#' * (level + 1)), '',
           table(['登录账号', '员工姓名', '岗位代码', '门店', '用途'],
                 [[a['username'], a['display_name'], a['role'], a['store'], a['purpose']] for a in world['accounts']]),
           '', '%s 约定' % ('#' * (level + 1)), '',
           table(['项目', '取值', '说明'],
                 [[c['label'], c['value'], c['note']] for c in world['conventions']])]
    for section in world['sections']:
        out += ['', '%s %s' % ('#' * (level + 1), section['title']), '']
        if section['kind'] == 'table':
            out.append(table(section['columns'], section['rows']))
        elif section['kind'] == 'list':
            out += ['- ' + item for item in section['items']]
        else:
            out.append(section['text'])
    return '\n'.join(out) + '\n'


def requirement_rows(item):
    return [[row['id'], row['title']] for row in item['requirements']]


def workflow_rows(item):
    return [[workflow['title'], workflow['entry']['label'], workflow['entry']['route'],
             '、'.join(ROLE_LABELS[role] for role in workflow['entry']['roles'])]
            for workflow in item['workflows']]


def requirement_range(item):
    first, last = item['requirements'][0]['id'], item['requirements'][-1]['id']
    return first if first == last else '%s–%s' % (first, last)


def index_markdown(data):
    world, rounds = data['world'], data['rounds']
    out = ['# XC 逐轮试用总表', '',
           text(data['world']['notice'], 'notice'), '',
           '本表对应《全新搭建：功能需求表》里每一个带冒号的大功能（41 组，另含无冒号的系统管理模块），覆盖 193 项原需求（HK-001–HK-193）。'
           '每轮脚本单独成文件；状态为“脚本已就绪”的轮次可以直接照做，其余轮次在你跑到前一轮时补全。', '',
           '## 41 轮总表', '',
           table(['轮次', '模块', '带冒号大功能', '需求编号', '工作流', '状态', '本轮要办的事'],
                 [[item['id'], item['module'], item['group'],
                   requirement_range(item),
                   len(item['workflows']),
                   '脚本已就绪' if item['status'] == 'detailed' else '待补脚本',
                   item['title']] for item in rounds]),
           '', '## 累计数据索引', '',
           '每轮跑完后由维护人根据你的记录表登记，后续轮次引用这里的数据（单号、VIN、卡号、金额）。', '',
           table(['轮次', '单据或编号', '值', '说明'], [['（跑完后登记）', '', '', '']]),
           '', '## 反馈与交付', '',
           '- 反馈格式、PR 审核方式、重启与刷新协议：见《试用运转说明-XC》。',
           '- 每条卡点登记在《试用记录/试用问题台账.md》。',
           '- 需要重启预览时，本表所在提交的 PR 会写明。', '']
    _ = out[0] if False else None
    out += [world_markdown(world), '']
    return '\n'.join(out)


def round_markdown(item, world):
    title = '%s %s · %s —— %s' % (item['id'], item['module'], item['group'], item['title'])
    out = ['# ' + title, '',
           '**状态**：%s' % ('脚本已就绪，可以直接照做' if item['status'] == 'detailed' else '待补脚本（先看总表了解范围）'), '',
           '## 本轮虚拟需求', '', item['scenario'], '',
           '## 本轮覆盖的需求', '', table(['需求编号', '需求名称'], requirement_rows(item)), '',
           '## 用到的流程（也可在“操作指引”里按名称查看）', '',
           table(['流程', '入口按钮', '页面', '可见岗位'], workflow_rows(item)), '',
           '## 开始前准备', ''] + ['- ' + note for note in item['prerequisites']]
    if item.get('fallback'):
        out += ['', '**前置不足时**：' + item['fallback']]
    if item['status'] != 'detailed':
        out += ['', '## 下一步', '',
                '本轮脚本（数据、步骤、观察点、核对清单）将在你跑到前一轮时补全；先按总表了解范围，'
                '或用“操作指引”和搜索框自行办理。', '']
        return '\n'.join(out)
    out += ['', '## 本轮数据', '', table(['项目', '填写值', '说明'],
                                       [[row['label'], row['value'], row['note']] for row in item['data']]),
            '', '## 操作步骤', '',
            '每步先核对右上角的账号、岗位和当前门店。手动 / 搜索 / 助手三种通道任选，可以混用，但同一件事不要重复提交。', '']
    for step in item['steps']:
        out += ['### %s%s' % (step['no'], '（可选）' if step.get('optional') else ''),
                '', '- **谁**：%s' % step['actor']]
        if step['entry']:
            out.append('- **手动**：%s' % step['entry'])
        if step['search']:
            out.append('- **搜索**：搜索框输入“%s”' % step['search'])
        if step['assistant']:
            out.append('- **助手**：%s' % step['assistant'])
        out += ['- **做什么**：%s' % step['action'], '- **应看到**：%s' % step['expect'],
                '- **单号/记录**：', '']
    if item.get('branches'):
        out += ['## 分支与找坑（可选，每轮至少挑一条）', '',
                table(['类型', '怎么做', '应该看到'],
                      [[branch['kind'], branch['action'], branch['expect']] for branch in item['branches']]), '']
    out += ['## 新用户观察点', ''] + ['- ' + note for note in item['observations']]
    out += ['', '## 结束核对', ''] + ['- ' + note for note in item['checks']]
    out += ['', '**报表核对**：' + item['report_check'], '',
            '## 记录表', '', table(['步号', '谁', '单号', '结果', '问题一句话'],
                                  [[step['no'], step['actor'], '', '', ''] for step in item['steps']]), '']
    return '\n'.join(out)


def page(data):
    world, rounds = data['world'], data['rounds']
    rows = ''.join(
        '<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (
            html.escape(item['id']), html.escape(item['module']), html.escape(item['group']),
            requirement_range(item), len(item['workflows']),
            '脚本已就绪' if item['status'] == 'detailed' else '待补脚本', html.escape(item['title']))
        for item in rounds)
    accounts = ''.join('<tr>%s</tr>' % ''.join('<td>%s</td>' % html.escape(str(cell)) for cell in
                                              [a['username'], a['display_name'], a['role'], a['store'], a['purpose']])
                       for a in world['accounts'])
    conventions = ''.join('<tr>%s</tr>' % ''.join('<td>%s</td>' % html.escape(str(cell)) for cell in
                                                  [c['label'], c['value'], c['note']]) for c in world['conventions'])
    sections = []
    for section in world['sections']:
        if section['kind'] == 'table':
            body = ''.join('<tr>%s</tr>' % ''.join('<td>%s</td>' % html.escape(str(cell)) for cell in row)
                           for row in section['rows'])
            inner = '<table><thead><tr>%s</tr></thead><tbody>%s</tbody></table>' % (
                ''.join('<th>%s</th>' % html.escape(str(column)) for column in section['columns']), body)
        elif section['kind'] == 'list':
            inner = '<ul>%s</ul>' % ''.join('<li>%s</li>' % html.escape(item) for item in section['items'])
        else:
            inner = '<p>%s</p>' % html.escape(section['text'])
        sections.append('<section><h3>%s</h3>%s</section>' % (html.escape(section['title']), inner))
    articles = []
    for item in data['detailed']:
        steps = ''.join(
            '<li><strong>%s</strong>%s<p class="who">%s</p>%s%s%s<p class="do">%s</p><p class="expect">%s</p></li>' % (
                html.escape(step['no']), '（可选）' if step.get('optional') else '', html.escape(step['actor']),
                '<p class="chan">手动：%s</p>' % html.escape(step['entry']) if step['entry'] else '',
                '<p class="chan">搜索：%s</p>' % html.escape(step['search']) if step['search'] else '',
                '<p class="chan">助手：%s</p>' % html.escape(step['assistant']) if step['assistant'] else '',
                html.escape(step['action']), html.escape(step['expect']))
            for step in item['steps'])
        branches = ''.join('<li><strong>%s</strong> %s <em>%s</em></li>' % (
            html.escape(branch['kind']), html.escape(branch['action']), html.escape(branch['expect']))
            for branch in item.get('branches') or [])
        observations = ''.join('<li>%s</li>' % html.escape(note) for note in item['observations'])
        checks = ''.join('<li>%s</li>' % html.escape(note) for note in item['checks'])
        requirements = ''.join('<li>%s %s</li>' % (html.escape(row['id']), html.escape(row['title']))
                               for row in item['requirements'])
        data_rows = ''.join('<tr>%s</tr>' % ''.join('<td>%s</td>' % html.escape(str(cell)) for cell in
                                                   [row['label'], row['value'], row['note']]) for row in item['data'])
        data_block = ('<h3>本轮数据</h3><table><thead><tr><th>项目</th><th>填写值</th><th>说明</th></tr></thead>'
                      '<tbody>%s</tbody></table>' % data_rows) if data_rows else ''
        record_block = ('<h3>记录表</h3><table><thead><tr><th>步号</th><th>谁</th><th>单号</th><th>结果</th>'
                        '<th>问题一句话</th></tr></thead><tbody>%s</tbody></table>'
                        % ''.join('<tr><td>%s</td><td>%s</td><td></td><td></td><td></td></tr>'
                                  % (html.escape(step['no']), html.escape(step['actor'])) for step in item['steps']))
        articles.append(
            '<article id="%s"><h2>%s %s · %s —— %s</h2><p class="scenario">%s</p>'
            '<h3>覆盖需求</h3><ul class="tight">%s</ul>'
            '<h3>开始前准备</h3><ul>%s</ul>%s%s<h3>操作步骤</h3><ol class="steps">%s</ol>'
            '<h3>分支与找坑</h3><ul>%s</ul><h3>新用户观察点</h3><ul>%s</ul>'
            '<h3>结束核对</h3><ul>%s</ul><p class="report">报表核对：%s</p>%s</article>' % (
                item['id'], item['id'], html.escape(item['module']), html.escape(item['group']),
                html.escape(item['title']), html.escape(item['scenario']), requirements,
                ''.join('<li>%s</li>' % html.escape(note) for note in item['prerequisites']),
                '<p class="fallback">前置不足时：%s</p>' % html.escape(item['fallback']) if item.get('fallback') else '',
                data_block, steps, branches, observations, checks, html.escape(item['report_check']), record_block))
    css = ("body{font:15px/1.7 system-ui,'Microsoft YaHei',sans-serif;margin:0;color:#1c2024;background:#f5f6f8}"
           ".wrap{max-width:1000px;margin:0 auto;padding:24px}"
           "h1{font-size:22px}h2{font-size:19px;border-top:1px solid #d9dde2;padding-top:16px}"
           "h3{font-size:16px;margin:18px 0 6px}table{border-collapse:collapse;width:100%;background:#fff;font-size:14px}"
           "th,td{border:1px solid #d9dde2;padding:6px 8px;text-align:left;vertical-align:top}"
           "th{background:#eef1f4}ul,ol{padding-left:22px}.tight li{margin:0}"
           ".steps li{margin-bottom:14px}.who{color:#55606b;margin:2px 0}.chan{margin:2px 0;color:#2c5f8a}"
           ".do{margin:4px 0}.expect{margin:2px 0;color:#1f6b3a}.scenario{font-size:15px;background:#fff;padding:10px 12px;border-left:3px solid #2c5f8a}"
           ".fallback,.report{background:#fff7e6;padding:8px 10px}.notice{background:#fff;padding:10px 12px}"
           "@media print{body{background:#fff}article{page-break-after:always}}")
    nav = ''.join('<li><a href="#%s">%s %s</a></li>' % (item['id'], item['id'], html.escape(item['title']))
                  for item in data['detailed'])
    return ('<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1"><title>XC 逐轮试用脚本</title>'
            '<style>%s</style></head><body><div class="wrap">'
            '<h1>XC 逐轮试用脚本</h1><p class="notice">%s</p>'
            '<h2>41 轮总表</h2><table><thead><tr><th>轮次</th><th>模块</th><th>带冒号大功能</th>'
            '<th>需求编号</th><th>工作流</th><th>状态</th><th>本轮要办的事</th></tr></thead><tbody>%s</tbody></table>'
            '<h2>虚拟世界设定</h2><h3>账号</h3><table><thead><tr><th>登录账号</th><th>员工姓名</th>'
            '<th>岗位代码</th><th>门店</th><th>用途</th></tr></thead><tbody>%s</tbody></table>'
            '<h3>约定</h3><table><thead><tr><th>项目</th><th>取值</th><th>说明</th></tr></thead><tbody>%s</tbody></table>'
            '%s<h2>已就绪的轮次</h2><ul>%s</ul>%s</div></body></html>\n' % (
                css, html.escape(world['notice']), rows, accounts, conventions, ''.join(sections), nav,
                ''.join(articles)))


def build(check=False):
    data = make_data()
    outputs = {OUT / INDEX_NAME: index_markdown(data), PORTABLE: page(data)}
    for item in data['detailed']:
        outputs[OUT / ('%s-%s.md' % (item['id'], item['slug']))] = round_markdown(item, data['world'])
    for path, content in outputs.items():
        if check:
            assert path.is_file() and path.read_text('utf-8') == content, 'Generated file differs: ' + str(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    summary = {'rounds': len(data['rounds']), 'detailed': len(data['detailed']),
               'outline': len(data['rounds']) - len(data['detailed']),
               'requirements': len(data['requirements']), 'workflows': len(data['workflows']),
               'outputs': sorted(str(path.relative_to(ROOT)) for path in outputs)}
    print(json.dumps(summary, ensure_ascii=False))
    return summary


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    build(args.check)
