"""Build deployed and portable illustrated guides from reviewed workflow sources.

No application/database/model is invoked. --check validates exact generated bytes.
"""
import argparse
import base64
import hashlib
import html
import json
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'docs/workflow-source'
ROLES={'admin','manager','sales','service','customer_service','reception','inventory','technician','finance','auditor'}
ROUTE=re.compile(r'^[a-z][a-z0-9-]*(?:/[a-zA-Z0-9_-]+)*$')
def read(path):return json.loads(path.read_text('utf-8-sig'))
def require_text(value,label):
    assert isinstance(value,str) and value.strip() and len(value)<5000,label
def make_data(draft=False):
    register=read(ROOT/'docs/requirements.json')
    requirements={row['id']:row for row in register['requirements']}
    assert len(requirements)==193
    assert hashlib.sha256((ROOT/register['source']).read_bytes()).hexdigest()==register['source_sha256']
    workflows=[]
    for name in ('business.json','services.json'):
        rows=read(SOURCE/name);assert isinstance(rows,list),name;workflows.extend(rows)
    shots=read(SOURCE/'screenshots.json') if (SOURCE/'screenshots.json').exists() else {}
    ids=set();mapping={key:[] for key in requirements};images={}
    for item in workflows:
        assert re.fullmatch(r'wf-[a-z0-9-]+',item['id']) and item['id'] not in ids,item['id'];ids.add(item['id'])
        for key in ('title','category','summary'):require_text(item[key],item['id']+'/'+key)
        for key in ('keywords','prerequisites','completion'):
            assert isinstance(item[key],list) and item[key],(item['id'],key)
            for value in item[key]:require_text(value,key)
        assert set(item['roles'])<=ROLES and item['roles'],item['id']
        assert ROUTE.fullmatch(item['entry']['route']) and len(item['entry']['route'])<180,item['id']
        assert set(item['entry']['roles'])<=ROLES and item['entry']['roles'],item['id']
        assert item['entry']['mode'] in {'read','write'},item['id']
        require_text(item['entry']['label'],item['id'])
        assert item['requirement_ids'] and len(set(item['requirement_ids']))==len(item['requirement_ids']),item['id']
        item['requirements']=[]
        for key in item['requirement_ids']:
            assert key in requirements,key;mapping[key].append(item['id'])
            item['requirements'].append({k:requirements[key][k] for k in ('id','title','module','group')})
        for name,rows in [('manual',item['manual']),('assistant',item['assistant']['steps'])]:
            assert isinstance(rows,list) and len(rows)>=2,(item['id'],name)
            for step in rows:
                for key in ('actor','action','expected')+ (('where',) if name=='manual' else ()):
                    require_text(step[key],item['id']+'/'+key)
        assert item['assistant']['mode'] in {'prepare','guide'}
        require_text(item['assistant']['prompt'],item['id'])
        assert isinstance(item['exceptions'],list) and item['exceptions'],item['id']
        for issue in item['exceptions']:
            require_text(issue['when'],item['id']);require_text(issue['action'],item['id'])
        shot=item['screenshot'];assert ROUTE.fullmatch(shot['route']),item['id']
        if shot['route'] in shots:
            evidence=shots[shot['route']];path=evidence['src']
            assert re.fullmatch(r'workflow-assets/[a-z0-9-]+\.png',path),path
            image=ROOT/'web'/path;assert image.is_file(),path
            image_bytes=image.read_bytes()
            assert image_bytes.startswith(b'\x89PNG\r\n\x1a\n'),path
            assert evidence.get('synthetic_only') is True and evidence.get('role') in ROLES,evidence
            assert evidence.get('reviewed_for_publication') is True,path
            assert hashlib.sha256(image_bytes).hexdigest()==evidence.get('sha256'),path
            assert item['id'] in evidence.get('workflow_ids',[]),item['id']
            shot.update(src=path,role=evidence['role'],capture_kind=evidence.get('capture_kind','entry'))
            images[path]=base64.b64encode(image_bytes).decode('ascii')
        else:
            assert draft,'Missing screenshot: '+shot['route']
            shot.pop('src',None)
    assert all(mapping.values()),'Unmapped requirements: '+str([k for k,v in mapping.items() if not v])
    data={'schema_version':1,'title':'huakangos 工作流手册','source_sha256':register['source_sha256'],
          'screenshots_synthetic_only':True,'business_accepted':False,
          'requirements':[{'id':k,'title':r['title'],'module':r['module'],'group':r['group'],'workflow_ids':mapping[k]} for k,r in requirements.items()],
          'workflows':workflows}
    return data,images
def json_text(value):return json.dumps(value,ensure_ascii=False,indent=2).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
def page(data,images,portable):
    css=(ROOT/'web/styles.css').read_text('utf-8')+'\n'+(ROOT/'web/workflowguides.css').read_text('utf-8')
    scripts=[(ROOT/'web'/f).read_text('utf-8') for f in ('workflowactions.js','workflowcontent.js','workflowhandbook.js')]
    page_data=dict(data)
    if portable:page_data['images']={k:'data:image/png;base64,'+v for k,v in images.items()}
    styles='<style>'+css+'</style>' if portable else '<link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="workflowguides.css">'
    js=''.join('<script>'+s.replace('</script','<\\/script')+'</script>' for s in scripts) if portable else '<script src="workflowactions.js" defer></script><script src="workflowcontent.js" defer></script><script src="workflowhandbook.js" defer></script>'
    return '<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>huakangos 工作流手册</title>'+styles+'</head><body><div class="wf-handbook-app"><header class="wf-handbook-header"><strong>华慷集团 · huakangos</strong><a href="#">全部流程</a></header><main id="workflow-handbook-main"></main></div><script type="application/json" id="workflow-data">'+json_text(page_data)+'</script>'+js+'</body></html>\n'
def build(check=False,draft=False):
    data,images=make_data(draft)
    outputs={ROOT/'web/workflow-guides.json':json_text(data)+'\n',ROOT/'web/workflow-handbook.html':page(data,images,False),ROOT/'docs/全量工作流手册.html':page(data,images,True)}
    mapping={'requirements':193,'workflows':len(data['workflows']),'illustrated_workflows':sum(bool(w['screenshot'].get('src')) for w in data['workflows']),
             'unique_screenshots':len(images),'source_sha256':data['source_sha256'],'business_accepted':False,'mapping':data['requirements']}
    outputs[ROOT/'docs/workflow-source/coverage.json']=json_text(mapping)+'\n'
    for path,text in outputs.items():
        if check:assert path.is_file() and path.read_text('utf-8')==text,'Generated file differs: '+str(path)
        else:path.write_text(text,encoding='utf-8')
    print(json.dumps({k:v for k,v in mapping.items() if k!='mapping'},ensure_ascii=False))
if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');parser.add_argument('--draft',action='store_true')
    args=parser.parse_args();build(args.check,args.draft)
