'use strict';
const addonNames={quote:'明细报价／授权增项',approve:'独立批准当前价格',authorize:'客户授权当前版',dispatch:'原VIN实际领料',install:'本批实际安装',quality:'实际检查／复检',rectify:'处理原检查缺陷',accept:'客户接收本版加装',receive:'实际加装款到账',resolution:'原实物与费用处置',resolution_approve:'独立批准处置',resolution_consent:'客户同意处置',resolution_cancel:'撤回未执行处置',resolution_reject:'决定拒收并交回',return_receive:'拆回商品可售验收',return_rectify:'整改拆回商品',return_handback:'拒收实物交回客户',refund:'按原款实际退款',cancel:'取消未授权申请'};
const addonKinds={cancel:'取消未领项目',return:'实际拆回原商品',vehicle_gift:'商品不退款，随原车无偿移交'};
const addonStates={requested:'等待独立批准',approved:'等待客户同意',consented:'客户已同意，等待实物办理',rectification:'不合格，等待整改',reinspection:'等待重新验收',handback:'已拒收，等待实际交回',rejected:'已实际交回客户',completed:'本处置已完成',cancelled:'已撤回未执行处置'};
async function addonOrdersPage(id){
 if(!id){const d=await api('/api/addon-orders?page='+state.page);return heading('销售加装明细','',canWrite()&&['admin','sales','service'].includes(state.user.role)?b('addon-new','建立销售加装','','primary'):'')+storeNotice()+panel('本店加装',table(['加装单','原销售','状态',''],d.items.map(r=>[E(r.number),E(r.source_number),pill(r.state),b('open','办理',`data-route="addon-orders/${r.id}"`)])));}
 const r=await api('/api/addon-orders/'+id);state.addonOrder=r;state.row=await api('/api/flow/cases/'+id);state.addonCatalog=['admin','sales','service','manager'].includes(state.user.role)?await api('/api/addon-orders/catalog'):null;
 const button=(k,extra='')=>canWrite()&&r.actions.includes(k)?b('addon-action',addonNames[k],`data-key="${k}" ${extra}`):'',task=k=>r.tasks.some(t=>t.key==='addon_'+k),active=r.plans.find(p=>['requested','approved','consented','rectification','reinspection','handback'].includes(p.status));
 let h=heading('销售加装明细',r.number,b('open','返回加装列表','data-route="addon-orders"'))+storeNotice()+`<div class="notice">${pill(r.state)} · ${r.delivery_blocking?'本单明确约定交车前完成':'允许原车交付后继续办理'}<br>原销售 ${E(r.source_number)}${r.target?'<br>实际安装VIN：'+E(r.target.vin):'<br>实际领料时核对原销售已配车辆VIN'}<br>本版不使用集团权益抵付。上传只关联原件，经办人分别确认真实事实。</div>`;
 h+=actionPanel(`<div class="row">${!active?button('quote'):''}${task('approve')?button('approve'):''}${task('authorize')?button('authorize'):''}${task('dispatch')?button('dispatch'):''}${task('accept')?button('accept'):''}${task('receive')?button('receive'):''}${r.quote?.authorized&&!active?button('resolution'):''}${!r.quote?.authorized?button('cancel'):''}</div><p>${r.state==='completed'?'本次加装已结清；需要纠正时追加原单处置。':'按对应岗位待办推进，任何检查不合格都不能确认客户接收。'}</p>`);
 if(r.totals){const t=r.totals;h+=panel('商品、安装与真实资金',`<div class="formgrid"><div>原报价<strong>${money(t.quoted_cents)} 元</strong></div><div>当前收费<strong>${money(t.charge_cents)} 元</strong></div><div>保留安装费<strong>${money(t.retained_installation_cents)} 元</strong></div><div>客户净付<strong>${money(t.paid_cents)} 元</strong></div><div>尚欠<strong>${money(t.receivable_cents)} 元</strong></div><div>应退未退<strong>${money(t.refund_due_cents)} 元</strong></div></div>`);}
 if(r.quote)h+=panel('报价第 '+r.quote.revision+' 版',memberPriceSummary(r.quote.member_pricing)+`<p>${E(r.quote.reason||'')}</p><p>${r.quote.approved?'主管已批准':'待独立主管批准'} · ${r.quote.authorized?'客户已授权本版':'尚无本版客户授权'}</p>`);
 if(r.quote_history?.length)h+=panel('冻结报价与授权历史',`<details><summary>查看全部 ${r.quote_history.length} 个原版本</summary>${r.quote_history.map(x=>`<h3>第 ${x.quote.revision} 版</h3><p>${E(x.quote.reason)}</p>${table(['原商品／安装','数量','商品（元）','安装（元）'],x.lines.map(l=>[E(l.name)+' / '+E(l.work_name),number(l.quantity_milli/1000),money(l.goods_cents),money(l.installation_cents)+(l.gift?'；赠送：'+E(l.gift.reason)+'；本销售门店承担成本':'')]))}<p>${x.approval?'已独立批准，最低合计 '+money(x.approval.minimum_cents)+' 元；'+E(x.approval.reason):'未获批准'} · ${x.authorization?'客户已授权本版':'无本版客户授权'}</p>`).join('')}</details>`);
 for(const l of r.lines)h+=panel(l.name,`<p>${E(l.sku)} · ${number(l.quantity_milli/1000)} ${E(l.unit)}；已占用未领 ${number(l.held_milli/1000)} ${E(l.unit)}</p><p>安装项目：${E(l.work_name)}</p>${l.goods_cents!==undefined?`<p>冻结商品 ${money(l.goods_cents)} 元；安装 ${money(l.installation_cents)} 元。</p>${l.gift?'<p>零价赠送：'+E(l.gift.reason)+'。商品及安装成本由本销售门店承担。</p>':''}`:''}`);
 for(const d of r.dispatches){h+=panel('原领料批次 '+d.id,`<p>${E(r.lines.find(l=>l.line_key===d.line_key)?.name)}：实际领出 ${number(d.quantity_milli/1000)}；尚未安装 ${number(d.uninstalled_milli/1000)}；尚未处置 ${number(d.remaining_milli/1000)}。</p>${d.uninstalled_milli>0&&!active?button('install',`data-dispatch="${d.id}"`):''}`);for(const i of r.installations.filter(i=>i.dispatch_id===d.id)){const checks=r.inspections.filter(c=>c.installation_id===i.id),last=checks.at(-1);h+=panel('实际安装批次 '+i.id,`<p>${number(i.quantity_milli/1000)} · ${E(i.result)}</p>${checks.map(c=>`<p>${c.passed?'检查通过':'检查不合格'}：${E(c.result)}${c.rectified?(checks.some(n=>n.id>c.id)?'；已整改并完成复检':'；已整改，等待对应复检'):''}</p>`).join('')||'<p>尚未实际检查。</p>'}${i.remaining_milli>0&&!active&&(!last||!last.passed&&last.rectified)?button('quality',`data-installation="${i.id}"`):''}${i.remaining_milli>0&&!active&&last&&!last.passed&&!last.rectified?button('rectify',`data-inspection="${last.id}"`):''}`);}}
 for(const p of r.plans){h+=panel('原单处置 '+p.id+' · '+addonKinds[p.kind],`<p>${E(addonStates[p.status])}</p>${p.reason?'<p>'+E(p.reason)+'</p>':''}`+p.lines.map(l=>`<p>${E(r.lines.find(x=>x.line_key===l.line_key)?.name)} · ${number(l.quantity_milli/1000)}${l.goods_cents!==undefined?`：商品原额 ${money(l.goods_cents)} 元；安装保留 ${money(l.retained_cents)} 元`:''}</p>`).join('')+`<div class="row">${p.status==='requested'?button('resolution_approve',`data-plan="${p.id}"`):''}${p.status==='approved'?button('resolution_consent',`data-plan="${p.id}"`):''}${p.kind==='return'&&['consented','reinspection'].includes(p.status)?button('return_receive',`data-plan="${p.id}"`):''}${p.status==='rectification'?button('return_rectify',`data-plan="${p.id}"`)+button('resolution_reject',`data-plan="${p.id}"`):''}${p.status==='handback'?button('return_handback',`data-plan="${p.id}"`):''}${['requested','approved','consented'].includes(p.status)?button('resolution_cancel',`data-plan="${p.id}"`):''}${p.refund_available_cents>0?button('refund',`data-plan="${p.id}"`):''}</div>`+p.facts.map(f=>`<p>${E(addonNames[f.action])}：${E(f.result||'已由对应岗位核对')}</p>`).join(''));}
 if(r.handovers.length)h+=panel('随车实物附属清单',r.handovers.map(x=>`<p>实际接回VIN ${E(x.vin)}；新车辆代次记录 ${x.new_vehicle_id}。未恢复物资库存，未增加车辆成本。</p>`+x.attachments.map(a=>`<p>${E(a.name)} · ${number(a.quantity_milli/1000)}</p>`).join('')).join(''));
 if(r.payments.length)h+=panel('原款与实际退款',r.payments.map(p=>`<p>${p.superseded?'原收款（已更正）':p.cash_kind==='correction_reverse'?'误记冲回（非实际退款）':p.cash_kind==='correction_record'?'更正后实际收款':p.direction==='in'?'实际收款':'原款退款'} ${money(p.amount_cents)} 元${p.original_id?' · 原款 '+p.original_id:''}${p.reference?' · '+E(p.reference):''}</p>`).join(''));
 h+=panel('原件与岗位交接',b('upload','上传本次实际原件')+`<p>价格、客户授权及处置同意选择“客户授权”；领料选择“业务凭据”；安装、检查、实物验收选择“检查凭据”；真实收退款选择“收款凭据”。</p>`+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.security?.label||'待扫描')}</p><div class="row">${b('filescaninfo','检查记录',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'扫描通过后可用'}</div></div></div>`).join('')+state.row.tasks.map(t=>`<p>${E(t.title)} · ${E(t.assignee_name)} · ${pill(t.status)} ${t.status==='open'&&['admin','manager'].includes(state.user.role)?b('assign','明确交接',`data-id="${t.id}"`):''}</p>`).join(''));return h;
}
function addonSend(r,key,values,request_id){return api(`/api/addon-orders/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values}});}
async function addonNew(){const c=await api('/api/addon-orders/catalog');if(c.source_total>10000)throw new Error('原销售超过本版可选择范围，请按门店整理档案后扩展检索。');for(let page=2;c.orders.length<c.source_total;page++){const next=await api('/api/addon-orders/catalog?source_page='+page);if(!next.orders.length)break;c.orders.push(...next.orders);}const options=c.orders.map(x=>x.id+' · '+x.number+' · '+x.title),request_id=requestKey();if(!options.length)throw new Error('请先建立本店明确客户的销售原单。');await formDialog('建立销售加装',[F('source','原销售','select',true,options),F('blocking','实际约定','select',true,['明确约定交车前完成','允许交车后办理']),F('due_date','约定完成日期','date'),F('reason','本次加装申请','textarea')],{source:options[0],blocking:'明确约定交车前完成',due_date:day()},v=>{const s=c.orders[options.indexOf(v.source)];return api('/api/addon-orders',{method:'POST',body:{request_id,source_order_id:s.id,source_version:s.version,delivery_blocking:v.blocking==='明确约定交车前完成',due_date:v.due_date,reason:v.reason}}).then(r=>go('addon-orders/'+r.id));});}
async function addonQuote(){const r=state.addonOrder,c=state.addonCatalog,request_id=requestKey(),rows=[...r.lines,null,null];if(c?.item_total>10000)throw new Error('物资超过本版可选择范围，请先按门店目录扩展检索。');for(let page=2;c&&c.items.length<c.item_total;page++){const next=await api('/api/addon-orders/catalog?page='+page);if(!next.items.length)break;c.items.push(...next.items);}if(!c?.items.length||!c.work_items.length)throw new Error('请先配置本店物资及安装作业项目。');modal('加装报价与授权增项',`<form>${await memberPriceField(r.id)}<p>原已授权行保持商品、数量和收费，新增项目另加行。折扣只分配本次新增行；安装费保留须来自实际安装批次。新零价行（含全额优惠后为零）须填赠送原因，并明确本销售门店承担商品及安装成本。</p>${rows.map((l,i)=>`<fieldset data-addon-line data-key="${E(l?.line_key||'line'+(i+1))}"><legend>${l?E(l.name):'新增加装项目'}</legend><label>商品<select name="item"><option value="">本行不使用</option>${c.items.map(x=>`<option value="${x.id}"${l?.item_id===x.id?' selected':''}>${E(x.name)} · 可用 ${number(x.available_milli/1000)}</option>`).join('')}</select></label><label>安装项目<select name="work">${c.work_items.map(x=>`<option value="${x.id}"${l?.work_item_id===x.id?' selected':''}>${E(x.name)}</option>`).join('')}</select></label><label>数量<input name="quantity" inputmode="decimal" value="${l?l.quantity_milli/1000:1}"></label><label>商品单价（元）<input name="goods" inputmode="decimal" value="${l?l.goods_unit_cents/100:0}"></label><label>安装单价（元）<input name="installation" inputmode="decimal" value="${l?l.installation_unit_cents/100:0}"></label><label>零价赠送原因（收费行留空）<textarea name="gift_reason" maxlength="1000">${E(l?.gift?.reason||'')}</textarea></label><label>赠送成本承担<select name="gift_cost_bearer"><option value="">本行不作为赠送</option><option value="selling_store"${l?.gift?' selected':''}>本销售门店承担商品及安装成本</option></select></label></fieldset>`).join('')}<label>本次新增行优惠（元）<input name="discount" inputmode="decimal" value="0"></label><label>本版核价说明<textarea name="reason" required minlength="2"></textarea></label><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">冻结本版报价</button></div></form>`,async form=>{const lines=[...form.querySelectorAll('[data-addon-line]')].filter(e=>e.querySelector('[name=item]').value).map(e=>({line_key:e.dataset.key,item_id:Number(e.querySelector('[name=item]').value),work_item_id:Number(e.querySelector('[name=work]').value),quantity_milli:repairScaled(e.querySelector('[name=quantity]').value,3),goods_unit_cents:repairScaled(e.querySelector('[name=goods]').value,2),installation_unit_cents:repairScaled(e.querySelector('[name=installation]').value,2),gift_reason:e.querySelector('[name=gift_reason]').value,gift_cost_bearer:e.querySelector('[name=gift_cost_bearer]').value||null}));await addonSend(r,'quote',{lines,...memberPricePayload(form),discount_cents:repairScaled(form.elements.discount.value,2),reason:form.elements.reason.value},request_id);closeModal();await render();});}
async function addonAction(key,e){if(key==='quote')return addonQuote();const r=state.addonOrder,request_id=requestKey(),fields=[],initial={},extra={};
 if(['authorize','accept'].includes(key))extra.quote_id=r.quote.id;
 if(key==='approve'){fields.push(F('minimum','本次明确最低合计（元）','money'),F('allow','低价例外','select',true,['不允许低于最低额','明确批准本版低价']),F('reason','独立核价原因','textarea'));initial.minimum='0';initial.allow='不允许低于最低额';if(Object.keys(r.quote?.gift_terms||{}).length){fields.push(F('gift_approval','本版赠送与成本承担','select',true,['尚未确认赠送条款','明确批准本版赠送及本销售门店成本承担']));initial.gift_approval='尚未确认赠送条款';}}
 if(key==='dispatch'){const lines=r.lines.filter(l=>l.held_milli>0);fields.push(F('line','本次实际领出项目','select',true,lines.map(l=>l.line_key+' · '+l.name)),F('quantity','实际领出数量','quantity'),F('checked_vin','实际核对原车VIN'));initial.line=lines[0]?.line_key+' · '+lines[0]?.name;initial.quantity=lines[0]?.held_milli/1000;initial.checked_vin=r.target?.vin||'';}
 if(key==='install'){extra.dispatch_id=Number(e.dataset.dispatch);const d=r.dispatches.find(x=>x.id===extra.dispatch_id);fields.push(F('quantity','本批实际安装数量','quantity'));initial.quantity=d.uninstalled_milli/1000;}
 if(key==='quality'){extra.installation_id=Number(e.dataset.installation);fields.push(F('outcome','实际检查结果','select',true,['合格','不合格']));initial.outcome='合格';}
 if(key==='rectify')extra.inspection_id=Number(e.dataset.inspection);
 if(key==='resolution'){fields.push(F('kind','实际处置方式','select',true,Object.values(addonKinds)),F('original','原项目或安装批次','select',true,[...r.lines.filter(l=>l.held_milli>0).map(l=>'未领:'+l.line_key+' · '+l.name),...r.dispatches.filter(d=>d.uninstalled_milli>0).map(d=>'未装:'+d.id+' · 原出库'+d.id),...r.installations.filter(i=>i.remaining_milli>0).map(i=>'已装:'+i.id+' · 安装批次'+i.id)]),F('quantity','本次原数量','quantity'),F('gift','随车移交约定','select',true,['不选择无偿移交','明确商品不退款并无偿移交']),F('reason','客户实际需求与保留费依据','textarea'));initial.kind=addonKinds.return;initial.gift='不选择无偿移交';}
 if(e.dataset.plan){extra.resolution_id=Number(e.dataset.plan);const p=r.plans.find(p=>p.id===extra.resolution_id);if(key==='resolution_consent'&&p.kind==='vehicle_gift'){fields.push(F('gift','本版客户明确约定','select',true,['未取得该同意','明确商品不退款并无偿移交']));initial.gift='未取得该同意';}}
 if(key==='return_receive'){fields.push(F('outcome','实际可售检查结果','select',true,['合格','不合格']));initial.outcome='合格';}
 if(['install','quality','rectify','resolution_approve','resolution_consent','resolution_cancel','resolution_reject','return_receive','return_rectify','return_handback'].includes(key))fields.push(F('result','本人实际办理结果','textarea'));
 if(key==='cancel')fields.push(F('reason','取消未授权申请的原因','textarea'));
 if(['receive','refund'].includes(key)){fields.push(F('amount','本次实际金额（元）','money'));if(key==='refund'){const sources=[...r.payments.filter(p=>p.direction==='in'&&p.available_cents>0).map(p=>'现金:'+p.id+' · 原款'+p.id+' '+money(p.amount_cents)+'元'),...(r.credits||[]).filter(p=>p.amount_cents>0).map(p=>'预收:'+p.id+' · 原抵用'+p.id+' '+money(p.amount_cents)+'元')];fields.push(F('original','原资金路径','select',true,sources));}fields.push(F('account_id','原收付款账户','account',key==='receive'),F('reference','本次独立流水或凭证号','text',key==='receive'));}
 if(key!=='cancel')fields.push(F('evidence_id','本单本次实际原件','file'));
 await formDialog(addonNames[key],fields,initial,v=>{const body={...extra,...v};if(body.quantity!==undefined){body.quantity_milli=repairScaled(body.quantity,3);delete body.quantity;}if(body.amount!==undefined){body.amount_cents=repairScaled(body.amount,2);delete body.amount;}if(key==='approve'){body.minimum_cents=repairScaled(body.minimum,2);body.allow_below_minimum=body.allow==='明确批准本版低价';delete body.minimum;delete body.allow;if(body.gift_approval){body.confirm_gift=body.gift_approval==='明确批准本版赠送及本销售门店成本承担';delete body.gift_approval;}}if(body.outcome){body.passed=body.outcome==='合格';delete body.outcome;}if(body.gift){body.confirm_no_goods_refund=body.gift==='明确商品不退款并无偿移交';delete body.gift;}if(key==='dispatch'){body.lines=[{line_key:body.line.split(' · ')[0],quantity_milli:body.quantity_milli}];delete body.line;delete body.quantity_milli;}if(key==='resolution'){body.kind=Object.keys(addonKinds).find(k=>addonKinds[k]===body.kind);const [type,id]=body.original.split(' · ')[0].split(':');const line={quantity_milli:body.quantity_milli};if(type==='未领')line.line_key=id;else if(type==='未装')line.dispatch_id=Number(id);else{line.installation_id=Number(id);line.dispatch_id=r.installations.find(i=>i.id===Number(id)).dispatch_id;}body.lines=[line];delete body.original;delete body.quantity_milli;}if(key==='refund'){const [kind,id]=body.original.split(' · ')[0].split(':');body.kind=kind==='现金'?'cash':'advance';body.original_id=Number(id);delete body.original;if(body.kind==='advance'){delete body.account_id;delete body.reference;}else body.account_id=Number(body.account_id);}return addonSend(r,key,body,request_id);},{caseId:r.id,notice:key==='resolution'?'已安装部分保留其冻结安装费。随车无偿移交不退商品款、不恢复物资库存，也不自动增加车辆成本。客户要求商品退款须实际拆回验收。':'只登记当前岗位真实核对的事实，批准和客户同意不会自动生成库存或现金。'});
}
document.addEventListener('click',async event=>{const e=event.target.closest('[data-act]');if(!e?.dataset.act.startsWith('addon-'))return;try{if(e.dataset.act==='addon-new')await addonNew();if(e.dataset.act==='addon-action')await addonAction(e.dataset.key,e);}catch(error){toast(error.message,true);}});
