'use strict';
const aftercareNames={execution:'确认服务履约与终止',plan:'提交费用与原路方案',approve:'主管批准方案',reject:'主管拒绝方案',cancel_plan:'撤销未确认方案',customer_confirm:'确认客户同意当前方案',cancel:'取消尚未生效售后',apply:'核实事实并应用纠正',refund:'登记原款实际退款',collect:'登记保留费实际收款'};
const aftercareScenarios={sale_termination:'已履约退订',vehicle_return:'提车后退车',repair_refund:'维修客户退费'};
const aftercareTenderNames={cash:'原现金退款',principal:'原集团本金',benefit:'原权益单位',advance:'原预收抵用',repair_package:'原维修套餐组件'};
function aftercareQuantity(v){const s=String(v).trim();if(!/^\d+(\.\d{1,3})?$/.test(s))throw new Error('套餐组件数量最多三位小数。');const [a,b='']=s.split('.');const n=Number(a)*1000+Number(b.padEnd(3,'0'));if(!Number.isSafeInteger(n))throw new Error('套餐组件数量超出范围。');return n;}
function aftercareReturnUnits(t){return t.kind==='repair_package'?String(t.units/1000)+' 原组件数量':t.kind==='benefit'?t.units+' 原单位':money(t.units)+' 元';}
function aftercareReturnAvailable(t){return t.kind==='repair_package'?'原组件可退数量 '+String(t.remaining_units/1000)+'，对应原抵扣 '+money(t.remaining_credit_cents)+' 元；部分退回按原数量分摊计算':t.kind==='benefit'?'每原单位抵 '+money(t.credit_per_unit)+' 元，可退 '+t.remaining_units+' 单位':'可退 '+money(t.remaining_units)+' 元';}
function aftercareAmount(v){return moneyFen(v,{label:'金额',allowZero:true});}
async function aftercarePage(id){
 if(!id){const d=await api('/api/aftercare/orders?page='+state.page);return heading('售后纠正','',canWrite()&&['admin','sales','service'].includes(state.user.role)?b('aftercare-new','申请售后纠正','','primary'):'')+storeNotice()+panel('售后申请',table(['原业务／售后','类型','当前状态',''],d.items.map(r=>[E(r.title)+'<br>'+E(r.number),E(aftercareScenarios[r.scenario]),pill(r.state),b('open','办理',`data-route="aftercare/${r.id}"`)])))+pager(d.total);}
 const r=await api('/api/aftercare/orders/'+id);state.aftercareOrder=r;state.row=await api('/api/flow/cases/'+id);
 const allowed=k=>canWrite()&&r.actions.includes(k),button=(k,source='')=>b('aftercare-action',aftercareNames[k],`data-key="${k}" data-id="${source}"`),actions=[];
 const choices=r.state==='pending'?['plan','cancel']:r.state==='approval'?['approve','reject','cancel_plan','cancel']:r.state==='authorization'?['customer_confirm','cancel_plan','cancel']:r.state==='working'&&!r.applied?['apply','cancel']:[];
 choices.filter(allowed).forEach(k=>actions.push(button(k)));
 let h=heading(aftercareScenarios[r.scenario]+' · '+r.number,r.reason,b('open','返回申请列表','data-route="aftercare"'))+storeNotice();
 h+=actionPanel(`<p>${pill(r.state)} · ${r.state==='completed'?'费用、实物和原路收退款已核对完成':r.applied?'费用纠正已应用，核对余下真实收退款':'尚未应用费用纠正'}</p><div class="row">${actions.join('')||(['completed','cancelled','rejected'].includes(r.state)?'本次售后已结束。':'等待相关岗位办理。')}</div><p>取消只能结束尚未生效申请。实际收车、已履约服务和已登记退款不会被删除。</p>`);
 for(const s of r.sources){h+=panel('原业务 · '+s.number,`<p>${E(s.kind==='order'?'整车':s.kind==='repair'?'客户维修承担':s.kind==='addon'?'加装':s.kind==='insurance'?'保险':'代办')} · 原流程历史状态 ${pill(s.state)}</p>`+(s.original_cents!==undefined?`<div class="cards">${[['原承担',s.original_cents],['当前净收费',s.net_cents],['实际净结算',s.paid_cents],['尚欠保留费',s.due_cents],['尚待退款',s.refund_cents]].map(([label,value])=>`<div class="card"><span>${label}（元）</span><strong>${money(value)}</strong></div>`).join('')}</div>`:'')+s.execution.map(x=>`<p>履约：${E({not_started:'尚未执行',stopped:'已停止继续履约',completed:'已完成履约'}[x.outcome])} · ${E(x.result)}${x.external_result==='terminated'?' · 已核对外部终止结果':''}</p>`).join('')+(r.state==='pending'&&s.kind!=='order'&&s.kind!=='repair'&&!s.execution.length&&allowed('execution')&&(state.user.role==='admin'||(s.kind==='addon'?state.user.role==='technician':state.user.role==='service'))?button('execution',s.id):'')+(r.applied&&s.due_cents&&allowed('collect')?button('collect',s.id):''));}
 if(r.vehicle_return){const p=r.vehicle_return;h+=panel('原VIN退回实物',`<p>${p.physically_received?'已实际接收隔离':'尚未实际接收'} · ${p.accepted?'检查通过并形成新库存批次':'尚未完成最终验收入库'}</p><p>退车检查与新库存批次办理完成后，财务才可应用本方案。</p>`+(p.operation_case_id?b('open','办理原VIN隔离验收',`data-route="vehicle-operation/${p.operation_case_id}"`):''));}
 for(const p of r.plans){h+=panel('冻结售后方案第 '+p.revision+' 版',`<p>${p.cancelled?'本版已撤销':p.customer_confirmed?'客户已确认本版':p.approved?'主管已批准，待客户确认':'待主管批准'} · ${E(p.reason)}</p>`+(p.lines?table(['原单','减免（元）','保留（元）','原路待退（元）'],p.lines.map(l=>[E(r.sources.find(s=>s.id===l.source_id)?.number),money(l.credit_cents),money(l.retained_cents),money(l.refund_cents)]))+p.returns.map(t=>`<div class="taskitem"><div class="description"><strong>${E(aftercareTenderNames[t.kind])} · ${money(t.credit_cents)} 元</strong><p>原记录 ${t.original_id} · ${aftercareReturnUnits(t)} · ${t.kind==='cash'?'已实际退 '+money(t.paid_cents)+' 元':'应用时原路恢复，保留原规则与到期日'}</p>${p.id===r.plan_id&&r.applied&&t.kind==='cash'&&t.paid_cents<t.credit_cents&&allowed('refund')?button('refund',t.id):''}</div></div>`).join(''):''));}
 if(state.catalog?.capabilities?.repair_packages&&['admin','manager','finance','auditor','service','sales','inventory'].includes(state.user.role))h+=await repairPackageReturnPanel(r);
 h+=panel('本售后单实际凭据',(canWrite()?b('upload','上传实际凭据'):'')+'<p>主管和客户各自使用本售后单的“客户授权”类别文件；财务使用本售后单的收退款凭据。原单旧签回件不能替代本次事实。</p>'+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.label)} · ${E(f.security?.label||'待检查')}</p><div class="row">${b('filescaninfo','检查状态',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'检查通过后可用'}</div></div></div>`).join(''));
 h+=panel('岗位交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&canWrite()&&['admin','manager'].includes(state.user.role)?b('assign','明确交接',`data-id="${t.id}"`):''}</div></div>`).join(''));return h;
}
async function aftercareNew(){
 let sources=[];for(let page=1;page<=100;page++){const d=await api('/api/aftercare/orders/sources?page='+page);sources.push(...d.items);if(d.items.length<30)break;}
 if(!sources.length)throw new Error('没有可申请的执行中销售或已接车维修客户承担。');const labels=sources.map(s=>`${s.id} · ${s.number} · ${aftercareScenarios[s.scenario]} · ${s.title}`),request_id=requestKey();
 await formDialog('申请独立售后纠正',[F('source','原业务','select',true,labels),F('reason','本次售后诉求与事实','textarea')],{},v=>{const s=sources[labels.indexOf(v.source)];return api('/api/aftercare/orders',{method:'POST',body:{request_id,source_case_id:s.id,source_version:s.version,scenario:s.scenario,reason:v.reason}}).then(r=>{go('aftercare/'+r.id);return r;});},{notice:'原业务执行入口暂时冻结；须逐项核对关联服务。旧版维修单不自动转为本版售后。'});
}
async function aftercarePlan(){
 const r=state.aftercareOrder,request_id=requestKey();
 const lines=r.sources.map(s=>`<section data-aftercare-line data-id="${s.id}"><h3>${E(s.number)}</h3><p>当前净收费 ${money(s.net_cents)} 元；实际净结算 ${money(s.paid_cents)} 元。</p><label>本次减免（元）<input name="credit" value="0.00" inputmode="decimal" required></label>${s.kind==='insurance'?`<label>本次佣金减免（元；原剩余 ${money(s.commission_cents)}）<input name="commission" value="0.00" inputmode="decimal" required></label>`:''}<p>保留费用＝当前净收费－本次减免。原路退回合计须等于超出保留费用的已付金额。</p>${s.eligible_returns.map(t=>`<label data-aftercare-tender data-kind="${t.kind}" data-id="${t.entry_id}">${E(t.name)} · ${E(aftercareReturnAvailable(t))}<input name="units" value="0" inputmode="decimal"></label>`).join('')}</section>`).join('');
 modal('冻结费用与原路退回方案',`<form>${lines}<label>保留费用及退款安排说明<textarea name="reason" required></textarea></label><p>原券包按整数份退回；混合维修套餐按原组件数量退回，不能自行折现。已经领出的配件须由库管核实实物退回，不因费用减免自动回库。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">提交主管审批</button></div></form>`,async form=>{
  const values={reason:form.elements.reason.value,lines:[...form.querySelectorAll('[data-aftercare-line]')].map(el=>({source_id:Number(el.dataset.id),...(el.querySelector('[name=commission]')?{commission_credit_cents:aftercareAmount(el.querySelector('[name=commission]').value)}:{}),credit_cents:aftercareAmount(el.querySelector('[name=credit]').value),returns:[...el.querySelectorAll('[data-aftercare-tender]')].map(t=>{const text=t.querySelector('[name=units]').value.trim();let units;if(t.dataset.kind==='benefit'){if(!/^\d+$/.test(text))throw new Error('权益必须退原整数单位，不能折现。');units=Number(text);}else if(t.dataset.kind==='repair_package')units=aftercareQuantity(text);else units=aftercareAmount(text);return {kind:t.dataset.kind,original_id:Number(t.dataset.id),units};}).filter(t=>t.units>0)}))};
  await api(`/api/aftercare/orders/${r.id}/actions/plan`,{method:'POST',body:{request_id,version:r.version,source_versions:Object.fromEntries(r.sources.map(s=>[s.case_id,s.version])),values}});closeModal();await render();
 });
}
async function aftercareAction(key,id){
 if(key==='plan')return aftercarePlan();const r=state.aftercareOrder,fields=[],initial={},values={};
 if(['approve','reject','cancel_plan','cancel'].includes(key))fields.push(F('reason','本次决定与原因','textarea'));
 if(key==='execution'){values.source_id=id;fields.push(F('outcome','实际履约','select',true,['尚未执行','已经停止继续履约','已经完成履约']),F('external_result','外部办理结果','select',true,['无需外部终止','已取得外部终止结果']),F('result','本人核对的实际情况','textarea'));}
 if(['refund','collect'].includes(key)){if(key==='refund'){values.tender_id=id;const t=r.plans.flatMap(p=>p.returns||[]).find(t=>t.id===id);initial.amount=((t.credit_cents-t.paid_cents)/100).toFixed(2);}else{values.source_id=id;initial.amount=(r.sources.find(s=>s.id===id).due_cents/100).toFixed(2);}fields.push(F('amount','实际金额（元）','money'),F('account_id',key==='refund'?'原收款资金账户':'实际收款资金账户','account'),F('reference','实际流水／凭证号'));}
 if(!['reject','cancel_plan','cancel'].includes(key))fields.push(F('evidence_id',['approve','customer_confirm'].includes(key)?'本售后单客户授权类别凭据':['apply','refund','collect'].includes(key)?'本售后单收退款类别凭据':'本售后单实际履约凭据','file'));
 const request_id=requestKey();await formDialog(aftercareNames[key],fields,initial,v=>{Object.assign(values,v);if(v.amount!==undefined){values.amount_cents=aftercareAmount(v.amount);delete values.amount;}if(key==='execution'){values.outcome={'尚未执行':'not_started','已经停止继续履约':'stopped','已经完成履约':'completed'}[v.outcome];values.external_result=v.external_result==='已取得外部终止结果'?'terminated':'not_required';}return api(`/api/aftercare/orders/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,source_versions:Object.fromEntries(r.sources.map(s=>[s.case_id,s.version])),values}});},{caseId:r.id,notice:key==='apply'?'应用费用减免及已批准的原权益回转。真实现金退款仍由随后独立待办逐笔登记，车辆退回须先完成实物验收。':key==='customer_confirm'?'客户确认须对应本页冻结方案。不得借主管批准文件或原业务旧签回件代替本次客户确认。':'只确认本人实际核对的事实。原单及售后版本变化时，先刷新核对再办理。'});
}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el?.dataset.act.startsWith('aftercare-'))return;try{if(el.dataset.act==='aftercare-new')await aftercareNew();else if(el.dataset.act==='aftercare-action')await aftercareAction(el.dataset.key,Number(el.dataset.id));}catch(error){toast(error.message,true);}});
