'use strict';
const BR_BASIC_COLORS=['红','橙','黄','绿','青','蓝','紫','白','灰','黑'];
function brChoice(values){return values.map(value=>({value,label:value}));}
function brSubmissionFields(){return [F('vehicle_invoice_price','机动车开票价（元）','money_zero',false),F('registration_fee','上牌服务费（元）','money_zero',false),F('payment_method','付款方式','select',true,brChoice(['全款','贷款'])),F('installment_fee','分期服务费（元）','money_zero',false),F('total_loss_product_description','全损换新（如一年）','text',false),F('trade_in_subsidy','置换补贴（元）','money_zero',false),F('used_car_commission','二手车佣金（元）','money_zero',false),F('finance_excess','金融超价（元）','money_zero',false),F('registration_excess','上牌费超价（元）','money_zero',false),F('transfer_store','调拨店端','text',false),F('towing_cost','拖车成本（元）','money_zero',false),F('department','所在部门','text',false)];}
function brSubmissionValues(data){return Object.fromEntries(brSubmissionFields().map(f=>[f.key,f.type==='money_zero'?brInputAmount(data?.[f.key+'_cents']):data?.[f.key]??(f.key==='payment_method'?'全款':'')]));}
function brSubmissionPayload(values){return Object.fromEntries(brSubmissionFields().map(f=>[f.type==='money_zero'?f.key+'_cents':f.key,f.type==='money_zero'?(values[f.key]===''?null:moneyFen(values[f.key],{label:f.label,allowZero:true})):values[f.key]]));}
function brGiftList(terms){
 if(!terms)return '';const monetary=Object.hasOwn(terms,'gift_total_cents');
 return `<div class="br-gift-summary">${table(['赠品','数量',...(monetary?['单价','金额']:[])],(terms.gifts_snapshot||[]).map(g=>[E(g.name),E(g.quantity),...(monetary?[brAmount(g.unit_price_cents),brAmount(g.amount_cents)]:[])]))}${monetary?`<p class="br-gift-total">赠品金额合计 <strong>${E(brAmount(terms.gift_total_cents))}</strong></p>`:''}</div>`;
}
function brSpecialFacts(r){const t=r.terms,p=t.price_snapshot||{},s=t.submission_data||{};return brFacts([['销售顾问',r.salesperson_name],['客户姓名',r.customer_name],['客户联系电话',r.customer_phone],['销售车型及配置',r.model],['车身 / 内饰颜色',[r.form_data?.exterior_color,r.form_data?.interior_color].filter(Boolean).join(' / ')],['VIN',r.vin],['指导价',brAmount(p.guide_price_cents)],['集团限价 / 销售管控价',brAmount(p.control_price_cents)],['优惠金额',brAmount(t.discount_cents)],['提交纯车价',brAmount(r.sale_price_cents)],['低于限价',brAmount(t.price_below_cents)],['机动车开票价',brAmount(s.vehicle_invoice_price_cents)],...brSubmissionFields().filter(f=>!['vehicle_invoice_price'].includes(f.key)).map(f=>[f.label.replace('（元）',''),f.type==='money_zero'?brAmount(s[f.key+'_cents']):s[f.key]]),...(Object.hasOwn(t,'gift_excess_cents')?[['赠送成本超价（经理填写）',brAmount(t.gift_excess_cents)]]:[]),['其他说明',t.special_note||s.note],['限价版本',p.batch_id],['限价发布时间',p.published_at?time(p.published_at):'']]);}
async function brNewContractV210(edit=false){
 const r=edit?brState.detail:null;if(edit&&!r)throw new Error('请重新打开合同。');if(r&&r.workflow_version!=='trial-v210')return brNewContractLegacy(edit);
 const context=brContext(),catalog=await brPricingCatalog(r?.id);if(context!==brContext())return;
 const profile=catalog.profile||{},vehicles=catalog.vehicles||[],gifts=catalog.gifts||[],people=state.recordCatalog.sales_people||[],sellers=profile.sellers||[];
 if(!vehicles.length||!profile.brand||!sellers.length)throw new Error('本店车型限价、车辆品牌或卖方公司资料尚未维护，请联系销售经理或内勤。');
 const main=[F('customer_name','客户姓名'),F('customer_phone','客户联系电话'),F('salesperson_id','所属销售顾问','select',true,people.map(p=>({value:p.id,label:p.label}))),F('contract_date','合同日期','date'),F('brand','车辆品牌'),F('vehicle_price_id','车系 / 年款 / 车型配置','select',true,[{value:'',label:'请选择车型'},...vehicles.map(v=>({value:v.id,label:[v.family,v.series,v.model].filter(Boolean).join(' / ')}))]),F('vin','车辆识别号 VIN'),F('sale_price','纯车销售金额（元）','money')];
 const extra=brContractExtraFields().filter(f=>!['quantity','payment_method'].includes(f.key)).map(f=>{
  if(f.key==='seller_name')return F(f.key,'卖方公司','select',true,sellers.map(s=>({value:s.name,label:s.name})));
  if(f.key==='buyer_document_name')return F(f.key,'买方证件类型','select',true,brChoice(['身份证','护照','驾照']));
  if(['exterior_color','interior_color'].includes(f.key))return F(f.key,f.label,'select',true,[{value:'',label:'请选择基础色'},...brChoice(BR_BASIC_COLORS)]);
  return f;
 });
 const giftFields=gifts.flatMap(g=>[F('gift_selected_'+g.id,g.name,'bool',false),F('gift_quantity_'+g.id,g.name+' · 数量','int',false)]),submission=brSubmissionFields(),initial={...r?.form_data,...r,brand:profile.brand,seller_name:r?.form_data?.seller_name||sellers[0]?.name,buyer_document_name:r?.form_data?.buyer_document_name||'身份证',buyer_agent:r?.form_data?.buyer_agent||'',sale_price:brInputAmount(r?.sale_price_cents),vehicle_price_id:r?.terms?.price_snapshot?.id||'',salesperson_id:r?.salesperson_id||(state.user.role==='sales'?state.user.id:people.length===1?people[0].id:''),signature_date:r?.form_data?.signature_date||day(),...brSubmissionValues(r?.terms?.submission_data)};
 for(const g of gifts){const selected=r?.terms?.gifts_snapshot?.find(x=>x.price_id===g.id);initial['gift_selected_'+g.id]=Boolean(selected);initial['gift_quantity_'+g.id]=selected?.quantity??1;}
 const dialog=await brForm(edit?'修改销售合同':'预填销售合同',[{title:'客户与车辆',fields:main},{title:'合同双方及交付约定',fields:extra},{title:'选择赠品',fields:giftFields},{title:'价格与特殊申请参考资料',fields:submission}],initial,(v,request_id)=>{
  const vehicle=vehicles.find(x=>x.id===Number(v.vehicle_price_id));if(!vehicle)throw new Error('请选择已发布限价中的车型。');
  const form_data=Object.fromEntries(extra.map(f=>[f.key,String(v[f.key]??'')]));form_data.quantity='1';form_data.payment_method=v.payment_method;
  if(!form_data.buyer_agent)form_data.buyer_agent=v.customer_name;
  for(const f of extra.filter(f=>f.type==='money_zero'))if(form_data[f.key]!=='')form_data[f.key]=brInputAmount(moneyFen(form_data[f.key],{label:f.label,allowZero:true}));
  const gift_items=gifts.filter(g=>v['gift_selected_'+g.id]).map(g=>{const quantity=v['gift_quantity_'+g.id];if(!Number.isInteger(quantity)||quantity<1||quantity>10000)throw new Error(g.name+'数量须为 1 至 10000 的整数。');return {price_id:g.id,quantity};});
  return api(BR_API+'/contracts'+(r?'/'+r.id:''),{method:r?'PUT':'POST',body:{request_id,...(r?{version:r.version}:{}),customer_name:v.customer_name,customer_phone:v.customer_phone,salesperson_id:Number(v.salesperson_id),contract_date:v.contract_date,brand:profile.brand,model:vehicle.series+' '+vehicle.model,vin:v.vin,sale_price_cents:moneyFen(v.sale_price,{label:'纯车销售金额'}),gift_description:'',form_data,vehicle_price_id:vehicle.id,gift_items,submission_data:brSubmissionPayload(v)}});
 },{draftKey:r?'contract-'+r.id:'contract',submit:'提交销售经理审批',notice:'低于销售管控价会进入特殊审批；赠品由销售经理查看金额并判断。批准后可打印，已提交合同保留当前限价及赠品版本。',nextRoute:result=>'records-sales/'+result.id});
 const form=$('form',dialog);for(const key of ['brand','seller_phone','seller_address','seller_agent'])form.elements[key].readOnly=true;
 const defaults=()=>{const person=people.find(p=>p.id===Number(form.elements.salesperson_id.value)),seller=sellers.find(s=>s.name===form.elements.seller_name.value);form.elements.seller_agent.value=person?.label||'';form.elements.seller_phone.value=profile.sales_contacts?.[String(person?.id)]||'';form.elements.seller_address.value=seller?.address||profile.address||'';};defaults();form.elements.salesperson_id.addEventListener('change',defaults);form.elements.seller_name.addEventListener('change',defaults);
 const priceNotice=document.createElement('p');priceNotice.className='notice';form.elements.sale_price.closest('label').after(priceNotice);
 const priceCheck=()=>{const v=vehicles.find(x=>x.id===Number(form.elements.vehicle_price_id.value));if(!v){priceNotice.textContent='选择车型后显示销售管控价。';return;}let below=false;try{below=moneyFen(form.elements.sale_price.value,{label:'纯车销售金额'})<v.control_price_cents;}catch(_){}priceNotice.className='notice'+(below?' br-special':'');priceNotice.textContent='销售管控价 '+brAmount(v.control_price_cents)+(below?' · 低于限价，将走特殊审批。':' · 赠品金额不抵扣车价。');};priceCheck();form.elements.vehicle_price_id.addEventListener('change',priceCheck);form.elements.sale_price.addEventListener('input',priceCheck);
 let agentAutomatic=!r?.form_data?.buyer_agent;form.elements.buyer_agent.placeholder='本人办理，可填写其他代理人';form.elements.buyer_agent.addEventListener('input',()=>{agentAutomatic=false;});form.elements.customer_name.addEventListener('input',()=>{if(agentAutomatic)form.elements.buyer_agent.value=form.elements.customer_name.value;});
 for(const g of gifts){const check=form.elements['gift_selected_'+g.id],quantity=form.elements['gift_quantity_'+g.id];quantity.min='1';quantity.max='10000';quantity.step='1';const enable=()=>{quantity.disabled=!check.checked;if(check.checked&&!quantity.value)quantity.value='1';};check.addEventListener('change',enable);enable();if(catalog.can_view_gift_amounts){const label=check.closest('label'),note=document.createElement('small');note.className='br-caption';note.textContent='单价 '+brAmount(g.unit_price_cents);label.append(note);}}
}
async function brContractV210(id){
 const epoch=renderId,r=await api(BR_API+'/contracts/'+id);if(epoch!==renderId)return '';if(r.workflow_version!=='trial-v210')return brContractLegacy(id);brState.detail=r;
 const t=r.terms||{},special=t.special,labels={edit:'修改合同',manager_approve:'销售经理审核 / 提交申请',approve:special?'总经理同意，提交集团副总经理':'总经理审批通过',deputy_approve:'集团副总经理审批通过',reject:'退回合同',print:'下载 / 打印合同',office_edit:'填写 / 核对内勤资料',office_submit:'提交资料审批',office_approve:'资料审批通过',office_reject:'退回内勤资料'};
 const button=a=>brButton('contract-action',labels[a],`data-action="${a}"`,['approve','deputy_approve','manager_approve','print','office_edit','office_approve','office_submit'].includes(a)?'primary':'');
 const actions=(r.actions||[]).filter(a=>labels[a]&&!a.startsWith('office_')).map(button).join(''),officeActions=(r.actions||[]).filter(a=>labels[a]&&a.startsWith('office_')).map(button).join(''),stage=['submitted','rejected'].includes(r.status)?1:r.status==='manager_approved'?2:r.status==='deputy_pending'?3:4;
 const steps=[['销售预填',true],['销售经理审批',stage>1],['总经理审批',special?stage>2:r.status==='approved'],...(special?[['集团副总经理审批',r.status==='approved']]:[]),['财务确认交车',Boolean(r.delivery_state?.delivery)],['内勤延伸资料 / 总经理审核',r.office_status==='approved']];
 const invoice=await brInvoiceSection(r);if(epoch!==renderId)return '';
 return heading('销售合同 '+r.number,[r.customer_name,r.brand,r.model].join(' · '),(r.customer_id?brLink('records-customers/'+r.customer_id,'客户档案'):'')+brLink('records-sales','返回销售业务'))+
 `<div class="br-steps">${steps.map(([label,done],i)=>`<span class="${done?'complete':''}">${i+1}. ${E(label)}</span>`).join('')}</div><section class="panel ${special?'br-special-panel':''}"><div class="panelhead spread"><div><h2>${special?'<span class="br-special-label">特殊审批</span>':'普通审批'} · ${E(r.status_label||BR_STATUS[r.status])}</h2><p class="br-caption">${special?'销售经理 → 总经理 → 集团副总经理，全部通过后可打印。':'销售经理 → 总经理，通过后可打印。'}</p></div><div class="row">${actions}</div></div><div class="panelbody">${r.status==='approved'?'<p class="notice">已批准合同锁档；变更内容请另建合同重新审批。</p>':''}${t.price_snapshot?brSpecialFacts(r):''}</div><div class="panelhead"><h2>赠品及赠送项目</h2></div>${brGiftList(t)}</section>`+
 `<details class="panel br-disclosure"><summary>合同双方与交付约定</summary>${brFacts(brContractExtraFields().filter(f=>f.key!=='quantity').map(f=>[f.label,r.form_data?.[f.key]]))}</details>`+
 `<section class="panel"><div class="panelhead spread"><h2>申请证据附件</h2>${['submitted','rejected'].includes(r.status)&&(r.actions||[]).some(a=>['edit','manager_approve'].includes(a))?brFlowButton('contract-attachment','补充附件'):''}</div>${table(['文件','状态','操作'],(t.attachments||[]).map(f=>[E(f.filename),f.available?'可查阅':'文件检查中',f.available?brFlowButton('pricing-download','下载',`data-file="${f.id}" data-name="${E(f.filename)}"`):'—']))}</section>`+
 invoice+brDeliverySection(r)+brOfficeSectionV210(r,officeActions)+`<details class="panel br-disclosure"><summary>完整流转记录</summary>${table(['时间','操作人','动作','说明'],(r.events||[]).map(e=>[time(e.created_at),E(e.actor_name),E(labels[e.action]||e.action),E(e.note||'—')]))}</details>`;
}
async function brManagerApproval(){
 const r=brState.detail,t=r.terms,fields=[...brSubmissionFields(),F('gift_excess','赠送成本超价（元，由销售经理判断）','money_zero'),F('note','其他说明 / 特殊申请理由','textarea',false)],values={...brSubmissionValues(t.submission_data),gift_excess:brInputAmount(t.gift_excess_cents??0),note:t.special_note||t.submission_data?.note||''};
 const dialog=await brForm('销售经理审核 · 销售超限价政策申请',[{title:'审批申请表',fields}],values,(v,request_id)=>{
  const excess=moneyFen(v.gift_excess,{label:'赠送成本超价',allowZero:true});if((t.price_below_cents>0||excess>0)&&!v.note.trim())throw new Error('特殊审批须填写其他说明 / 申请理由。');
  return api(BR_API+'/contracts/'+r.id+'/manager-approve',{method:'POST',body:{request_id,version:r.version,gift_excess_cents:excess,note:v.note,submission_data:{...brSubmissionPayload(v),note:v.note}}});
 },{draftKey:'manager-special-'+r.id+'-'+r.version,submit:'确认审核并提交总经理',notice:'车价低于销售管控价，或您填写的赠送成本超价大于零，将转特殊审批：总经理 → 集团副总经理。金融费及上牌费不触发自动超限。'});
 const form=$('form',dialog),facts=document.createElement('div');facts.className='br-special-review';facts.innerHTML=brSpecialFacts(r)+`<h3>赠送成本超价参考 · 已选赠品清单</h3>`+brGiftList(t);form.querySelector('fieldset').before(facts);
}
async function brContractActionV210(action){
 const r=brState.detail;if(r?.workflow_version!=='trial-v210')return brContractActionLegacy(action);
 if(!r.actions?.includes(action))throw new Error('合同状态或岗位权限已变化，请刷新后办理。');
 if(action==='edit')return brNewContractV210(true);if(action==='manager_approve')return brManagerApproval();if(action==='office_edit')return brOfficeEditV210();
 if(action==='print')return download(BR_API+'/contracts/'+r.id+'/print',r.number+'.pdf');
 const specs={approve:['总经理审批',r.terms?.special?'本次同意后交集团副总经理终审，尚不能打印。':'本次批准后可正常打印合同。'],deputy_approve:['集团副总经理审批','特殊申请终审通过后可正常打印合同。'],reject:['退回合同','填写退回原因，由原销售顾问修改。'],office_submit:['提交内勤延伸资料','未核实项目保留待补齐；本次提交总经理审核。'],office_approve:['通过内勤资料审核','审批结果进入延伸统计，不改变财务交车事实。'],office_reject:['退回内勤资料','请说明待修改的内容。']};
 const spec=specs[action];if(!spec)throw new Error('不支持的合同动作。');return brForm(spec[0],[{title:r.number,fields:[F('note',action.includes('reject')?'退回原因':'审批说明','textarea',action.includes('reject'))]}],{},(v,request_id)=>api(BR_API+'/contracts/'+r.id+'/'+action.replaceAll('_','-'),{method:'POST',body:{request_id,version:r.version,note:v.note}}),{draftKey:action+'-'+r.id+'-'+r.version,submit:spec[0],notice:spec[1]});
}
async function brContractAttachment(){const r=brState.detail,context=brContext(),requestId=requestKey();modal('补充申请证据',`<form><label>附件<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg" required></label><p class="notice">附件随本单审批留存。提交销售经理审核后不能替换审批依据。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">上传附件</button></div></form>`,async form=>{if(context!==brContext())throw new Error('账号或门店已切换。');const body=new FormData(form);body.set('request_id',requestId);body.set('version',r.version);await api(BR_API+'/contracts/'+r.id+'/attachments',{method:'POST',body});if(context!==brContext())return;closeModal();await render();toast('申请附件已保存');});}
function brDeliverySection(r){
 const s=r.delivery_state;if(!s)return '';const d=s.delivery,actions=s.actions||[],gift=s.gift_document;
 return `<section class="panel"><div class="panelhead spread"><div><h2>财务交车与盖章赠品单</h2><p class="br-caption">发票核对后由财务确认交车，抄送总经理；统计归属发票上传日。</p></div><div class="row">${r.status==='approved'?brFlowButton('gift-print','打印无价格赠品单'):''}${actions.includes('upload_gift_document')?brFlowButton('gift-upload',gift?'追加更正盖章赠品单':'上传盖章赠品单'):''}${actions.includes('confirm_delivery')?brFlowButton('delivery-confirm','财务确认交车','','primary'):''}</div></div><div class="panelbody">${brFacts([['交车事实',d?'财务已确认交车':'尚未确认交车'],['交车确认时间',d?time(d.confirmed_at):''],['核算日期',d?.accounting_on],['对应发票金额',d?brAmount(d.invoice_amount_cents):'待确认'],['盖章赠品单',gift?.filename||'待上传'],['内勤资料条件',s.materials_ready?'材料齐备，可填报延伸资料':'等待发票、交车及盖章赠品单材料']])}${gift?.available&&['admin','finance','clerk','manager','general_manager','group_deputy_manager','chairman','store_admin'].includes(state.user.role)?brFlowButton('gift-download','下载当前盖章赠品单',`data-file="${gift.id}" data-name="${E(gift.filename)}"`):''}</div></section>`+
 `<section class="panel"><div class="panelhead spread"><h2>退车与退款记录</h2>${actions.includes('request_return')?brFlowButton('return-request','销售顾问申请退车'):''}</div><div class="panelbody">${(s.returns||[]).map(item=>`<article class="br-return-card">${brFacts([['退车状态',({submitted:'待总经理批准',requested:'待总经理批准',pending:'待总经理批准',approved:'已批准退车',rejected:'已退回'})[item.status]||item.status],['申请原因',item.note],['请求退款金额',brAmount(item.requested_refund_cents)],['退车批准日',item.approved_on],['另行记录退款合计',brAmount(item.refunded_amount_cents)]])}<div class="row">${(item.actions||[]).map(a=>brFlowButton('return-'+a,({approve:'总经理批准退车',reject:'退回退车申请',refund:'记录已发生退款'})[a],`data-return="${item.id}"`)).join('')}</div>${item.refunds?.length?table(['退款日期','金额','说明'],item.refunds.map(x=>[E(x.refunded_on),brAmount(x.amount_cents),E(x.note)])):''}</article>`).join('')||'<p class="br-caption">暂无退车申请。退车在批准月份冲减，退款另行记录。</p>'}</div></section>`;
}
async function brDeliveryAction(action,button){
 const r=brState.detail,context=brContext(),s=r.delivery_state;if(!s)throw new Error('请刷新合同。');
 if(action==='gift-print')return download(BR_API+'/contracts/'+r.id+'/gift-document/print',r.number+'-赠品单.pdf');
 if(action==='gift-download')return download(BR_API+'/contracts/'+r.id+'/gift-document/files/'+button.dataset.file+'/download',button.dataset.name);
 if(action==='gift-upload'){const requestId=requestKey();modal('上传盖章赠品单',`<form><label>盖章后的赠品单<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg" required></label><p class="notice">先打印赠品单并线下盖章，再上传本单文件。上传不会自动确认交车。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">上传并关联本合同</button></div></form>`,async form=>{if(context!==brContext())throw new Error('门店已切换。');const body=new FormData(form);body.set('request_id',requestId);body.set('version',r.version);await api(BR_API+'/contracts/'+r.id+'/gift-document',{method:'POST',body});if(context!==brContext())return;closeModal();await render();toast('盖章赠品单已保存');});return;}
 let title,fields,path,version=r.version,notice;
 if(action==='delivery-confirm'){title='财务确认交车';fields=[F('note','交车确认说明','textarea',false)];path='/delivery-confirm';notice='确认后结束合同交付部分，并抄送总经理。基础销量按对应发票上传日统计，不记录实际到账。';}
 else if(action==='return-request'){title='申请退车';fields=[F('amount','请求退款金额（元）','money_zero',false),F('note','退车原因','textarea')];path='/returns';notice='退车申请交总经理批准；批准当月冲减，原销售事实保留。';}
 else{const item=s.returns.find(x=>x.id===Number(button.dataset.return));if(!item)throw new Error('退车记录已变化。');version=item.version;const suffix=action.slice(7);path='/returns/'+item.id+'/'+suffix;title=({approve:'总经理批准退车',reject:'退回退车申请',refund:'记录已发生退款'})[suffix];fields=suffix==='refund'?[F('amount','实际退款金额（元）','money'),F('refunded_on','实际退款日期','date'),F('note','退款说明','textarea',false)]:[F('note',suffix==='reject'?'退回原因':'审批说明','textarea',suffix==='reject')];notice=suffix==='refund'?'仅记录已经发生的退款事实，系统不执行支付。':'审批结果追加留痕，原合同和交车记录继续保留。';}
 return brForm(title,[{title:r.number,fields}],{},(v,request_id)=>{const body={request_id,version,note:v.note};if(action==='delivery-confirm')body.invoice_version=s.invoice_version;if(action==='return-request')body.requested_refund_cents=v.amount===''?null:moneyFen(v.amount,{allowZero:true});if(action==='return-refund'){body.amount_cents=moneyFen(v.amount);body.refunded_on=v.refunded_on;}return api(BR_API+'/contracts/'+r.id+path,{method:'POST',body});},{draftKey:action+'-'+r.id+'-'+version,submit:title,notice});
}
async function brDeliveryNotices(){const context=brContext(),result=await api(BR_API+'/delivery-notices');if(context!==brContext())return;modal('财务交车抄送 · 总经理查阅',`<p class="notice">财务已确认的交车事实。此处为抄送查阅，不增加交车审批。</p>${table(['合同','车型','核算日期','财务确认时间'],result.items.map(x=>[brLink('records-sales/'+x.contract_id,x.number),E(x.model),E(x.accounting_on),time(x.confirmed_at)]))}`);}
function brProfitPanel(calculation){
 if(!calculation)return '<div class="br-profit-panel"><h3>核定单车大毛利</h3><p>填写延伸资料后自动汇总原表利润。</p></div>';
 const complete=calculation.status==='complete';return `<section class="br-profit-panel"><div class="br-profit-head"><div><h3>核定单车大毛利</h3><p>${complete?'全部计算项已核实':'待补齐 · '+calculation.missing.length+' 项尚未填写'}</p></div><strong class="br-profit-number">${complete?E(brAmount(calculation.total_cents)):'待补齐'}</strong></div>${!complete?`<p class="br-profit-subtotal">已填项目小计：${E(brAmount(calculation.known_subtotal_cents))}（不是最终利润）</p>`:''}<div class="br-profit-items">${calculation.items.map(item=>`<div class="${item.amount_cents==null?'br-profit-missing':''}"><span class="br-profit-sign">${item.sign<0?'−':'+'}</span><span>${E(item.label)}<small>原表 ${E(item.source_column)} 列</small></span><strong>${item.amount_cents==null?'待补齐':E(brAmount(item.amount_cents))}</strong></div>`).join('')}</div><p class="br-caption">按本车对应原表公式汇总；返佣和小产品净额由销售内勤填写，赠品金额来自合同冻结清单，各项精确到分。</p></section>`;
}
function brOfficeSectionV210(r,actions){const data=r.office_data||{};if(!r.office_status&&!r.office_data)return '';return `<section class="panel br-office-panel"><div class="panelhead spread"><div><h2>销售内勤延伸信息</h2><p class="br-caption">${E(BR_OFFICE_STATUS[r.office_status]||'等待财务材料')} · 独立交总经理审核</p></div><div class="row">${actions}</div></div><div class="panelbody">${brFacts([['车型',r.model],['客户',r.customer_name],['核算日期',r.delivery_state?.delivery?.accounting_on],['发票金额',brAmount(data.invoice_amount_cents??r.delivery_state?.delivery?.invoice_amount_cents)],['核对说明',data.note]])}${brInternalRead()?brProfitPanel(data.profit_calculation):''}${data.values?`<details class="br-disclosure"><summary>查看已填原表项目</summary>${table(['项目','填写值'],(brReportDefinitions().find(s=>s.key===data.report_key)?.columns||[]).filter(c=>data.values[c.key]!=null).map(c=>[E(c.label),E(data.values[c.key])]))}</details>`:''}</div></section>`;}
async function brOfficeEditV210(reportKey){
 const r=brState.detail;if(r?.workflow_version!=='trial-v210')return brOfficeEditLegacy(reportKey);if(!r.actions?.includes('office_edit'))throw new Error('请先完成财务交车及材料上传。');
 const existing=r.office_data||{},definitions=brReportDefinitions().filter(s=>s.supports_contract),key=existing.report_key||reportKey;
 if(!key){modal('选择本车原始明细表',`<div class="br-report-picker">${definitions.map(s=>brButton('office-report-select',s.title,`data-report="${E(s.key)}"`)).join('')}</div>`);return;}
 const spec=definitions.find(x=>x.key===key);if(!spec)throw new Error('当前岗位无法填写此表。');const context=brContext(),prefill=await api(BR_API+'/report-prefill?'+new URLSearchParams({report_key:key,contract_id:r.id}));if(context!==brContext())return;
 const values={...prefill.values,...existing.values},computed=await api(BR_API+'/contracts/'+r.id+'/profit-preview',{method:'POST',body:{report_key:key,values}});if(context!==brContext())return;
 const locked=new Set(prefill.locked_fields||[]),hidden=new Set([computed.profit_calculation.output_key,...(['vehicle_details','hail_vehicle_details'].includes(key)?['c06']:[])]);
 const columns=spec.columns.filter(c=>!hidden.has(c.key)&&!['序号','台数','车系','保险出单数量','延保出单数量'].includes(c.label)&&!locked.has(c.key));
 const groups=brOfficeGroups(columns).map(group=>({...group,fields:group.fields.map(f=>{const c=columns.find(c=>'value_'+c.key===f.key);if(c?.label==='订单类型')return F(f.key,c.label,'select',false,[{value:'',label:'待填写'},...brChoice(['自然进店成交','线上客户成交'])]);if(c?.label==='现金或三方')return F(f.key,'现金或三方','select',false,[{value:'',label:'待核对'},...brChoice(['全款','贷款','现金','三方'])]);return f;})}));
 const cashField=F('cash_consumption','全款车消化金额（元，人工核实）','money_zero',false),noteField=F('note','核对说明 / 待补资料','textarea',false);
 const initial={note:existing.note||'',cash_consumption:brInputAmount(existing.cash_consumption_cents),...Object.fromEntries(Object.entries({...values,...computed.values}).map(([k,v])=>['value_'+k,v??'']))},allFields=[cashField,noteField,...groups.flatMap(g=>g.fields)];
 const collect=v=>Object.fromEntries(spec.columns.map(c=>[c.key,locked.has(c.key)?prefill.values[c.key]??null:hidden.has(c.key)?null:v['value_'+c.key]??values[c.key]??null]));
 const dialog=await brForm('销售内勤核对 · '+spec.title,[{title:'全款车及资料核对',fields:[cashField,noteField]},...groups],initial,(v,request_id)=>api(BR_API+'/contracts/'+r.id+'/office-review',{method:'PUT',body:{request_id,version:r.version,report_key:key,note:v.note,cash_consumption_cents:v.cash_consumption===''?null:moneyFen(v.cash_consumption,{label:'现金车消化金额',allowZero:true}),values:collect(v)}}),{draftKey:'office-'+r.id+'-'+key+'-'+r.version,submit:'保存延伸资料',notice:'发票上传日作为核算日。返佣、小产品净额自行核算填写，空值表示待补齐；明确没有该项时填 0。最终单车利润由系统汇总。'});
 const form=$('form',dialog),top=document.createElement('div');if(r.terms?.submission_data?.payment_method!=='全款'){form.elements.cash_consumption.closest('label').hidden=true;form.elements.cash_consumption.value='';}top.className='br-office-fact-head';top.innerHTML=brFacts([['客户 / 车型',r.customer_name+' / '+r.model],['核算日期',prefill.period||r.delivery_state?.delivery?.accounting_on],['付款方式',r.terms?.submission_data?.payment_method],['财务核对发票金额',brAmount(r.delivery_state?.delivery?.invoice_amount_cents)],['自动带入赠品金额',brAmount(computed.gift_cost_cents)]]);form.querySelector('fieldset').before(top);
 const profit=document.createElement('div');profit.dataset.profitPreview='';profit.innerHTML=brProfitPanel(computed.profit_calculation);form.querySelector('.modalfoot').before(profit);
 let timer=null,sequence=0;form.addEventListener('input',()=>{clearTimeout(timer);const run=++sequence;timer=setTimeout(async()=>{if(!form.isConnected||context!==brContext())return;try{const result=await api(BR_API+'/contracts/'+r.id+'/profit-preview',{method:'POST',body:{report_key:key,values:collect(formValues(form,allFields))}});if(run!==sequence||!form.isConnected||context!==brContext())return;profit.innerHTML=brProfitPanel(result.profit_calculation);}catch(error){if(run===sequence&&form.isConnected)profit.innerHTML=`<div class="notice warn">利润待核对：${E(error.message)}</div>`;}},450);});
}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-br-flow]');if(!el||el.disabled||state.storeSwitch)return;const a=el.dataset.brFlow;if(!['delivery-notices','contract-attachment','pricing-download','gift-print','gift-upload','gift-download','delivery-confirm','return-request','return-approve','return-reject','return-refund'].includes(a))return;el.disabled=true;try{if(a==='delivery-notices')await brDeliveryNotices();else if(a==='contract-attachment')await brContractAttachment();else if(a==='pricing-download')await download(BR_API+'/pricing/files/'+el.dataset.file+'/download',el.dataset.name);else await brDeliveryAction(a,el);}catch(error){toast(error.message,true);}finally{if(el.isConnected)el.disabled=false;}});
