'use strict';
let brDashboardTimer=null;
function brCanDashboard(){return !['sales','finance','service'].includes(state.user?.role);}
function brDashboardHome(){return brCanDashboard()?'records-dashboard':state.user?.role==='finance'?'records-finance':state.user?.role==='service'?'records-after-sales':'records-sales';}
function brDashboardPanelFilter(panel){const composition=brState.dashboardComposition||'all';return composition==='all'||(composition==='sales'?['sales_trend','orders_trend','sales_comparison','cash_trend','cash_amount'].includes(panel.panel_id):composition==='extended'?['trade_in','warranty','products'].includes(panel.panel_id):panel.panel_id==='profit');}
async function brRealtimeDashboard(mode='daily'){
 if(!brCanDashboard())return heading('当前岗位工作台','请从业务入口办理您的工作。',brLink(brDashboardHome(),'进入业务'));
 const epoch=renderId,context=brContext(),selected=brState.dashboardDay||day(),month=brState.reportMonth||day().slice(0,7),range=brState.liveRange||{date_from:day().slice(0,8)+'01',date_to:day()};
 const query=new URLSearchParams({mode:mode==='daily'?'daily':'monthly',day:selected,group_by:brState.dashboardGroup||(state.store==='all'?'store':'salesperson')});
 if(mode==='monthly'){const [y,m]=month.split('-').map(Number);query.set('date_from',month+'-01');query.set('date_to',month+'-'+new Date(y,m,0).getDate());}
 if(mode==='range'){query.set('date_from',range.date_from);query.set('date_to',range.date_to);}
 const result=await api(BR_API+'/dashboard-panels?'+query);if(epoch!==renderId||context!==brContext())return '';brState.liveDashboard=result;brState.liveDashboardMode=mode;brState.liveDashboardQuery=query.toString();
 const panels=result.panels.filter(brDashboardPanelFilter),tools=brLink('records-dashboard/history','已确认日报 / 修订')+(brCaps().record_statistics?brFlowButton('daily-observation','填写每日观察'):'')+((brCaps().manage_targets||brInternalRead())?brLink('records-dashboard/targets','月度目标'):'')+brFlowButton('dashboard-fullscreen','全屏');
 return `<div id="br-live-dashboard">${heading(mode==='monthly'?'月度经营看板':mode==='range'?'范围经营看板':'每日经营看板','打开即显示权限内经营数据；资料保存后更新，缺项保持待补齐。',tools)}<form class="br-live-controls" id="br-live-controls">${mode==='monthly'?`<label>查看月份<input type="month" name="month" value="${E(month)}" required></label>`:mode==='range'?`<label>开始日期<input type="date" name="date_from" value="${E(range.date_from)}" required></label><label>结束日期<input type="date" name="date_to" value="${E(range.date_to)}" required></label>`:`<label>核算日期<input type="date" name="day" value="${E(selected)}" required></label>`}<label>比较维度<select name="group">${brOptions([{value:'salesperson',label:'销售顾问'},{value:'store',label:'授权门店'},{value:'brand',label:'品牌'}],query.get('group_by'))}</select></label><label>展示组合<select name="composition">${brOptions([{value:'all',label:'全部经营概览'},{value:'sales',label:'销售与现金车'},{value:'extended',label:'置换与延伸业务'},...(brInternalRead()?[{value:'profit',label:'核定毛利'}]:[])],brState.dashboardComposition||'all')}</select></label>${brFlowButton('dashboard-refresh','刷新数据')}<span class="br-live-stamp"><i></i>实时数据 · ${E(time(result.updated_at))}</span></form><p class="br-caption">${E(result.notice)}</p><section class="br-live-overview" aria-label="当日经营概览">${result.overview.map(item=>`<article><span>${E(item.label)}</span><strong>${item.value==null?'待补齐':E(number(item.value))}<small>${item.value==null?'':E(item.unit)}</small></strong><p>${E(item.note||(item.value==null?'等待对应业务或内勤资料':'按所选核算范围汇总'))}</p></article>`).join('')}</section><div class="br-live-panels">${panels.map((p,i)=>`<section class="panel br-live-panel ${i===0?'br-live-primary':''}"><div class="panelhead spread"><div><h2>${E(p.panel_title||p.title)} <small class="br-panel-status">${E(({known:'已知数据',no_source:'暂无来源',incomplete:'待补齐',awaiting_approval:'待审批'})[p.data_status]||'待核对')}</small></h2><p class="br-caption">${E(p.period_basis||'')} · ${E(result.date_from)} 至 ${E(result.date_to)}</p></div><button type="button" data-br-flow="dashboard-detail" data-panel="${E(p.panel_id)}">明细与导出</button></div><div class="br-live-chart" data-live-chart="${E(p.panel_id)}" role="img" aria-label="${E(p.panel_title||p.title)}"></div>${p.notice?.length?`<p class="br-caption br-chart-notice">${E(Array.isArray(p.notice)?p.notice.join('；'):p.notice)}</p>`:''}</section>`).join('')}</div></div>`;
}
function mountRealtimeDashboard(){
 const root=$('#br-live-dashboard'),data=brState.liveDashboard;if(!root||!data)return;
 for(const panel of data.panels){const chart=root.querySelector(`[data-live-chart="${panel.panel_id}"]`);if(!chart)continue;RecordsCharts.render(chart,{type:panel.group_by==='day'?'line':panel.panel_id==='sales_comparison'||panel.panel_id==='profit'?'rank':'bar',title:panel.panel_title||panel.title,unit:panel.unit,precision:panel.precision??2,items:panel.series||[],interval:'day',scope:'summary',compact:true});}
 const controls=$('#br-live-controls'),context=brContext(),route=state.route;controls.onsubmit=e=>e.preventDefault();controls.onchange=()=>{const v=Object.fromEntries(new FormData(controls));if(v.date_from&&v.date_to&&v.date_from>v.date_to){toast('开始日期不能晚于结束日期。',true);return;}if(v.day)brState.dashboardDay=v.day;if(v.month)brState.reportMonth=v.month;if(v.date_from)brState.liveRange={date_from:v.date_from,date_to:v.date_to};brState.dashboardGroup=v.group;brState.dashboardComposition=v.composition;render();};
 clearTimeout(brDashboardTimer);brDashboardTimer=setTimeout(async()=>{if(context!==brContext()||route!==state.route||!root.isConnected)return;if($('#modal').open||document.hidden){mountRealtimeDashboard();return;}try{const fresh=await api(BR_API+'/dashboard-panels?'+brState.liveDashboardQuery);if(context!==brContext()||route!==state.route||!root.isConnected)return;brState.liveDashboard=fresh;for(const card of root.querySelectorAll('.br-live-overview article')){const index=Array.from(card.parentElement.children).indexOf(card),item=fresh.overview[index];if(item){card.querySelector('span').textContent=item.label;card.querySelector('strong').innerHTML=item.value==null?'待补齐':E(number(item.value))+`<small>${E(item.unit)}</small>`;card.querySelector('p').textContent=item.note||(item.value==null?'等待对应业务或内勤资料':'按所选核算范围汇总');}}root.querySelector('.br-live-stamp').innerHTML='<i></i>实时数据 · '+E(time(fresh.updated_at));mountRealtimeDashboard();}catch(error){if(root.isConnected){root.querySelector('.br-live-stamp').textContent='自动刷新失败，保留上次结果：'+error.message;mountRealtimeDashboard();}}},60000);
}
function leaveRealtimeDashboard(){clearTimeout(brDashboardTimer);brDashboardTimer=null;document.querySelectorAll('[data-live-chart]').forEach(node=>RecordsCharts.dispose(node));}
function brLiveTable(panel,view){
 const summary=view==='summary',columns=(summary?panel.summary_columns:panel.columns)||[],all=(summary?panel.summary_rows:panel.rows)||[],pages=brState.livePanelPages||(brState.livePanelPages={}),key=panel.panel_id+'-'+view,page=Math.min(pages[key]||1,Math.max(1,Math.ceil(all.length/100))),rows=all.slice((page-1)*100,page*100);
 return table(columns.map(c=>c.label+(c.unit?'（'+c.unit+'）':'')),[...rows,...(summary&&panel.grand_total?[panel.grand_total]:[])].map(row=>columns.map(c=>!summary&&['number','contract_number'].includes(c.key)&&row.contract_id?brLink('records-sales/'+row.contract_id,row[c.key]||'查看合同'):E(row[c.key]??'—'))))+`<div class="pagination"><span>${all.length} 条 · 第 ${page} 页</span><div class="row">${brFlowButton('dashboard-page','上一页',`data-panel="${E(panel.panel_id)}" data-view="${view}" data-page="${page-1}" ${page<=1?'disabled':''}`)}${brFlowButton('dashboard-page','下一页',`data-panel="${E(panel.panel_id)}" data-view="${view}" data-page="${page+1}" ${page*100>=all.length?'disabled':''}`)}</div></div>`;
}
function brDashboardPanelDetail(id){const panel=brState.liveDashboard?.panels.find(p=>p.panel_id===id);if(!panel)return;modal(panel.panel_title||panel.title,`<p class="notice">${E(panel.period_basis||'')}。明细与图表使用同一门店、日期及人员范围。</p><div class="row">${brFlowButton('dashboard-export','导出统计表',`data-panel="${E(id)}" data-view="summary"`)}${brFlowButton('dashboard-export','导出来源明细',`data-panel="${E(id)}" data-view="details"`)}</div><details open class="br-disclosure"><summary>同口径汇总</summary><div data-live-table="summary">${brLiveTable(panel,'summary')}</div></details><details class="br-disclosure"><summary>业务来源明细</summary><div data-live-table="details">${brLiveTable(panel,'details')}</div></details>`);}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-br-flow]');if(!button||button.disabled||state.storeSwitch)return;const action=button.dataset.brFlow;if(!['dashboard-fullscreen','dashboard-refresh','dashboard-detail','dashboard-export','dashboard-page','daily-observation'].includes(action))return;button.disabled=true;try{if(action==='dashboard-fullscreen'){if(document.fullscreenElement)await document.exitFullscreen();else await $('#br-live-dashboard').requestFullscreen();}if(action==='dashboard-refresh')await render();if(action==='dashboard-detail')brDashboardPanelDetail(button.dataset.panel);if(action==='dashboard-page'){const panel=brState.liveDashboard.panels.find(p=>p.panel_id===button.dataset.panel),view=button.dataset.view;(brState.livePanelPages||(brState.livePanelPages={}))[panel.panel_id+'-'+view]=Number(button.dataset.page);document.querySelector('[data-live-table="'+view+'"]').innerHTML=brLiveTable(panel,view);}if(action==='dashboard-export'){const panel=brState.liveDashboard.panels.find(p=>p.panel_id===button.dataset.panel);const query=new URLSearchParams(Object.entries({...panel.query,view:button.dataset.view}).filter(([,v])=>v!=null&&v!==''));await download(BR_API+'/reports/export?'+query,panel.panel_title+'.csv');}if(action==='daily-observation')await brNewManual('daily_operations');}catch(error){toast(error.message,true);}finally{if(button.isConnected)button.disabled=false;}});
