'use strict';
const claimNames={assess:'核损与核价版本',approve:'独立复核核价',transmit:'确认外部提交／补件',result:'核对实际外部结果',bind:'绑定原维修承担',resolution:'提出第三方调减方案',resolution_approve:'独立批准责任调整',thirdparty_refund:'实际退回原第三方款',resolution_apply:'生效责任调整',reimbursement_approve:'独立批准客户报销',direct_confirm:'确认第三方已付客户',pass_receive:'确认报销款实际到店',pass_pay:'按原到账转付客户',return_plan:'申请原报销返还',return_approve:'独立批准报销返还',return_cancel:'取消未实际返还方案',direct_return:'确认客户已退原第三方',customer_return:'确认客户原款退回门店',party_return:'按原账户退给第三方',unused_refund:'未转付原款退第三方',close:'核对剩余额度并结案',cancel:'取消尚无实际资金申请'};
const claimRoutes={repair_receivable:'原维修第三方应收',customer_direct:'第三方直接报销给客户',customer_via_store:'第三方经门店转付客户',internal:'内部承担核价'};
const claimOutcomes={approved:'全部核准',partial:'部分核准',rejected:'拒赔',need_documents:'要求补件'};
const claimCashNames={thirdparty_refund:'退原第三方款',pass_receive:'报销款到店',pass_pay:'转付客户',customer_return:'客户退回门店',party_return:'原路退第三方',unused_refund:'未转付报销款原退'};
async function claimsPage(id){
 if(!id){const d=await api('/api/claims?page='+state.page);return heading('理赔索赔与客户报销','经办核对外部文件，财务确认实际款项；批准金额不会自动变成到账。',canWrite()&&['admin','service'].includes(state.user.role)?b('claim-new','建立核赔申请','','primary'):'')+storeNotice()+panel('本店核赔业务',table(['核赔申请','路径','状态',''],d.items.map(r=>[`${E(r.number)}<br>${E(r.title)}`,E(claimRoutes[r.order.payment_route]),E(r.phase_label),b('open','办理',`data-route="claims/${r.id}"`)])))+pager(d.total);}
 const r=await api('/api/claims/'+id);state.claimOrder=r;state.row=await api('/api/flow/cases/'+id);
 const can=k=>canWrite()&&r.actions.includes(k),button=(k,extra='')=>can(k)?b('claim-action',claimNames[k],`data-key="${k}" ${extra}`):'',buttons=[];
 if(['assessment','approval','send','supplement','ready'].includes(r.phase)&&!r.resolutions.length&&!r.bindings.length&&!r.reimbursement_approvals.length)buttons.push(button('assess'));
 if(r.phase==='approval')buttons.push(button('approve'));
 if(['send','supplement'].includes(r.phase))buttons.push(button('transmit'));
 if(r.phase==='waiting')buttons.push(button('result'));
 if(r.phase==='ready'){if(['repair_receivable','internal'].includes(r.order.payment_route)){buttons.push(button('bind'));if(r.order.payment_route!=='internal')buttons.push(button('resolution'));}else buttons.push(button('reimbursement_approve'));}
 if(r.phase==='resolution_review')buttons.push(button('resolution_approve'));
 if(r.phase==='resolution_execute')buttons.push(button('thirdparty_refund'),button('resolution_apply'));
 if(r.phase==='reimbursement')buttons.push(...(r.order.payment_route==='customer_direct'?[button('direct_confirm')]:[button('pass_receive'),button('pass_pay')]));
 const payouts=r.order.payment_route==='customer_direct'?r.customer_payments.filter(x=>x.purpose==='reimbursement'):r.cash.filter(x=>['pass_pay','pass_receive'].includes(x.purpose));
 if(payouts.length&&r.phase!=='cancelled')buttons.push(button('return_plan'));
 if(!['completed','cancelled'].includes(r.phase))buttons.push(button('close'),button('cancel'));
 let h=heading(r.title,r.number,b('open','返回理赔','data-route="claims"'))+storeNotice()+`<div class="notice">${E(r.phase_label)} · ${E(claimRoutes[r.order.payment_route])}<br>上传文件只作原件关联，经办或财务需确认实际结果；系统不认证外部文件真实性。</div>`;
 h+=panel('原维修及本次路径',`<p>${E(r.source_number)} · ${E(r.order.source_snapshot.plate)} · ${E(r.order.party_name)}</p><p>${E(r.order.reason)}</p>`+b('open','核对原维修',`data-route="repair-orders/${r.source_id}"`)+(r.order.payment_route.startsWith('customer_')?`<p>本单报销有效占额／已报销净额 ${money(r.reimbursement_usage_cents)} 元；扣除其他案件后原客户实际现金净付款 ${money(r.customer_available_cents)} 元。</p><p>会员核销不折现报销。直接付客户不产生公司现金，经店转付分别记录实际到账和实际支付。</p>`:''));
 h+=panel('本次办理',`<div class="row">${buttons.filter(Boolean).join('')||(['completed','cancelled'].includes(r.phase)?'本次已办结；后续原路返还按其独立方案与待办办理。':'等待其他岗位或下一项实际结果。')}</div>`);
 for(const a of r.assessments)h+=panel('核价第 '+a.revision+' 版',`<p>${E(a.reason)} · 核价 ${money(a.amount_cents)} 元</p>`+table(['原项目','申请数量','申请金额（元）'],a.lines.map(l=>[E(l.name),number(l.quantity_milli/1000),money(l.amount_cents)])));
 h+=panel('外部提交及结果',r.transmissions.map(t=>{const result=r.results.find(x=>x.transmission_id===t.id);return `<div class="taskitem"><div class="description"><strong>${E(t.external_reference)}</strong><p>${E(t.submitted_on)} · ${t.supplement_result_id?'追加补件':'首次提交'}</p>${result?`<p>${E(claimOutcomes[result.outcome])} · ${money(result.amount_cents)} 元</p><p>${E(result.result)}</p>`:'等待实际外部核赔结果'}</div></div>`;}).join('')||'<p>内部核价不伪造外部核赔记录；外部业务尚未提交。</p>');
 for(const resolution of r.resolutions)h+=panel('第三方调减与内部吸收',`<p>原承担 ${money(resolution.original_cents)} 元，调减 ${money(resolution.reduction_cents)} 元，由 ${E(resolution.internal_bearer)} 等额承担。</p><p>须实际退原第三方款 ${money(resolution.refund_cents)} 元。原维修报价和原承担保留，生效时追加调整。</p><p>${E(resolution.reason)}</p>`);
 h+=panel('实际款项',r.customer_payments.map(p=>`<p>${p.purpose==='return'?'客户已实际退给第三方':'第三方已直接报销给客户'} ${money(p.amount_cents)} 元 · ${E(p.business_date)} · 原记录 ${p.original_id||p.id}（不产生公司现金）</p>`).join('')+r.cash.map(p=>`<div class="taskitem"><div class="description"><strong>${E(claimCashNames[p.purpose])} ${money(p.amount_cents)} 元</strong><p>${E(p.reference)} · ${E(p.business_date)} · 原记录 ${p.original_id||'首次到账'}</p></div></div>`).join(''));
 for(const plan of r.return_plans){const active=plan.approved&&!plan.cancelled&&plan.returned_external_cents<plan.amount_cents;h+=panel('原报销返还方案 '+plan.id,`<p>${plan.cancelled?'已撤销':plan.approved?'已独立批准':'待独立批准'} · 原路返还 ${money(plan.amount_cents)} 元</p><p>${plan.original_purposes.includes('pass_receive')?(plan.original_purposes.includes('pass_pay')?'本方案实际返还合计':'未转付款已原退'):'客户已返还'} ${money(plan.returned_cents)} 元；已回到原第三方 ${money(plan.returned_external_cents)} 元。</p><p>${E(plan.reason)}</p><div class="row">${!plan.approved&&!plan.cancelled?button('return_approve',`data-plan="${plan.id}"`):''}${!plan.cancelled&&!plan.returned_cents?button('return_cancel',`data-plan="${plan.id}"`):''}${active?(r.order.payment_route==='customer_direct'?button('direct_return',`data-plan="${plan.id}"`):(plan.original_purposes.includes('pass_pay')?button('customer_return',`data-plan="${plan.id}"`)+button('party_return',`data-plan="${plan.id}"`):'')+(plan.original_purposes.includes('pass_receive')?button('unused_refund',`data-plan="${plan.id}"`):'')):''}</div>`);}
 h+=panel('本理赔单原件',b('upload','上传本次实际凭据')+'<p>核损、核价、外部提交和批准使用“客户授权”类别；实际报销、收付和责任生效使用“收款凭据”类别。不得借用原维修旧文件。</p>'+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.label)} · ${E(f.security?.label||'等待检查')}</p><div class="row">${b('filescaninfo','检查记录',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'扫描通过后可用'}</div></div></div>`).join(''));
 h+=panel('岗位交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&['admin','manager'].includes(state.user.role)?b('assign','明确交接',`data-id="${t.id}"`):''}</div></div>`).join(''));return h;
}
async function claimsNew(sourceId){
 let sources=[];for(let p=1;p<=100;p++){const d=await api('/api/claims/sources?page='+p);sources.push(...d.items);if(d.items.length<50)break;}
 const [insurers,references]=await Promise.all([repairAll('/api/masters/insurers?active=true'),repairAll('/api/flow/master/references?page_size=100')]);
 const parties=[...insurers.map(x=>({key:'insurer:'+x.id,label:'保险 · '+x.name})),...references.filter(x=>x.active&&x.category==='厂家').map(x=>({key:'manufacturer:'+x.id,label:'厂家 · '+x.name})),{key:'internal:0',label:'内部承担'}];
 const labels=sources.map(x=>x.id+' · '+x.number+' · '+x.title),request_id=requestKey();if(!sources.length)throw new Error('请先建立本店维修明细报价。');
 await formDialog('建立原维修核赔申请',[F('source','原维修','select',true,labels),F('party','核赔单位','select',true,parties.map(x=>x.label)),F('route','实际结算路径','select',true,Object.values(claimRoutes)),F('internal_name','内部承担主体（外部路径留空）','text',false),F('reason','核损核赔申请原因','textarea')],{source:labels[sources.findIndex(x=>x.id===sourceId)]||labels[0]},v=>{const s=sources[labels.indexOf(v.source)],[party_type,id]=parties.find(x=>x.label===v.party).key.split(':');return api('/api/claims',{method:'POST',body:{request_id,source_case_id:s.id,source_version:s.version,party_type,payer_id:Number(id)||null,payer_name:v.internal_name||'',payment_route:Object.keys(claimRoutes).find(k=>claimRoutes[k]===v.route),reason:v.reason}}).then(r=>go('claims/'+r.id));},{notice:'请选择真实原维修与付款路径。直接报销客户不会登记成本店保险收款。'});
}
function claimSend(r,key,values,request_id){return api(`/api/claims/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,source_version:r.source_version,values}});}
async function claimLinesDialog(key){
 const r=state.claimOrder,a=r.assessments.at(-1),request_id=requestKey(),lines=key==='assess'?r.source_lines:a.lines;
 const files=state.row.files.filter(f=>!f.generated&&f.category==='authorization'&&f.security?.can_use);
 modal(claimNames[key],`<form><p>逐项选择原维修明细与本次金额；数量和金额不能超过原行。拒赔／补件结果请取消全部明细，不产生批准额。</p>${key==='result'?`<label>实际核赔结果<select name="outcome">${Object.entries(claimOutcomes).map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label>`:''}${lines.map(l=>`<fieldset data-claim-line data-id="${l.line_id||l.id}"><legend>${E(l.name)}</legend><label><input name="selected" type="checkbox" checked>本次包含此原项目</label><div class="formgrid"><label>数量<input name="quantity" inputmode="decimal" value="${(l.quantity_milli/1000).toFixed(3)}"></label><label>金额（元）<input name="amount" inputmode="decimal" value="${(l.amount_cents/100).toFixed(2)}"></label></div></fieldset>`).join('')}<label>${key==='result'?'实际结果及差异说明':'诊断和本次核价原因'}<textarea name="reason" required minlength="2"></textarea></label>${key==='result'?`<label>实际结果日期<input name="result_on" type="date" required value="${day()}"></label><label>本次外部结果原件<select name="evidence_id" required>${files.map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label>`:''}<div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">提交本次事实</button></div></form>`,async form=>{
  const selected=[...form.querySelectorAll('[data-claim-line]')].filter(e=>e.querySelector('[name=selected]').checked).map(e=>({line_id:Number(e.dataset.id),quantity_milli:repairScaled(e.querySelector('[name=quantity]').value,3),amount_cents:repairScaled(e.querySelector('[name=amount]').value,2)}));
  const values=key==='assess'?{lines:selected,reason:form.elements.reason.value}:{lines:selected,transmission_id:r.transmissions.at(-1).id,outcome:form.elements.outcome.value,result:form.elements.reason.value,result_on:form.elements.result_on.value,evidence_id:Number(form.elements.evidence_id.value)};
  await claimSend(r,key,values,request_id);closeModal();await render();
 });
}
async function claimSelectionDialog(key){
 const r=state.claimOrder,request_id=requestKey(),items=key==='resolution'?r.source_payments.filter(p=>r.source_allocations.find(a=>a.id===p.allocation_id)?.payer_type===r.order.party_type):r.order.payment_route==='customer_direct'?r.customer_payments.filter(p=>p.purpose==='reimbursement'):r.cash.filter(p=>['pass_pay','pass_receive'].includes(p.purpose)),files=state.row.files.filter(f=>!f.generated&&f.category==='authorization'&&f.security?.can_use);
 modal(claimNames[key],`<form><p>${key==='resolution'?'选择实际已收超过新核准金额的原第三方款，退款合计必须恰好覆盖超收部分。未到账部分只作责任调减。':'选择原实际报销记录及本次原路径返还金额；不能把同一笔报销重复退回。'}</p>${key==='resolution'?'<label>差额实际内部承担主体<input name="internal_bearer" required maxlength="120"></label>':''}${items.map(p=>`<label data-claim-selection data-id="${p.id}">${p.purpose==='pass_receive'?'未转付第三方到账':'原客户报销'} ${p.id} · ${E(p.reference||p.business_date)} · 原额 ${money(p.amount_cents)} 元<input name="selected_amount" inputmode="decimal" placeholder="本次金额，未选择留空"></label>`).join('')}<label>本次处理原因<textarea name="reason" required minlength="2"></textarea></label><label>方案事实原件<select name="evidence_id" required>${files.map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">提交独立复核</button></div></form>`,async form=>{
  const selected=[...form.querySelectorAll('[data-claim-selection]')].filter(e=>e.querySelector('input').value.trim()).map(e=>({original_id:Number(e.dataset.id),amount_cents:repairScaled(e.querySelector('input').value,2)}));
  await claimSend(r,key,{reason:form.elements.reason.value,evidence_id:Number(form.elements.evidence_id.value),...(key==='resolution'?{internal_bearer:form.elements.internal_bearer.value,refunds:selected}:{selections:selected})},request_id);closeModal();await render();
 });
}
async function claimAction(key,planId){
 if(['assess','result'].includes(key))return claimLinesDialog(key);if(['resolution','return_plan'].includes(key))return claimSelectionDialog(key);
 const r=state.claimOrder,request_id=requestKey(),fields=[],initial={},extra={},moneyKeys=['thirdparty_refund','direct_confirm','pass_receive','pass_pay','direct_return','customer_return','party_return','unused_refund'];
 if(['approve','resolution_approve','reimbursement_approve','close','cancel','return_cancel'].includes(key))fields.push(F('reason','本人核对及办理原因','textarea'));
 if(['return_approve','return_cancel','direct_return','customer_return','party_return','unused_refund'].includes(key))extra.plan_id=planId;
 if(key==='return_approve')fields.splice(0);
 if(key==='transmit'){fields.push(F('external_reference','实际外部受理单号'),F('submitted_on','实际提交日期','date'));initial.submitted_on=day();if(r.phase==='supplement')extra.supplement_result_id=r.results.at(-1).id;}
 let options=[];
 if(key==='thirdparty_refund')options=r.resolutions[0].refunds.map(x=>({id:x.original_id,label:'原收款 '+x.original_id+' · 计划退 '+money(x.amount_cents)+' 元'}));
 if(key==='pass_pay')options=r.cash.filter(x=>x.purpose==='pass_receive'&&x.remaining_cents>0).map(x=>({id:x.id,label:'原到账 '+x.id+' · 尚可转付 '+money(x.remaining_cents)+' 元'}));
 if(['direct_return','customer_return','unused_refund'].includes(key))options=r.return_plans.find(p=>p.id===planId).selections.map(x=>({id:x.original_id,label:'原报销 '+x.original_id+' · 本方案 '+money(x.amount_cents)+' 元'}));
 if(key==='party_return')options=r.cash.filter(x=>x.purpose==='customer_return'&&x.return_plan_id===planId&&x.remaining_cents>0).map(x=>({id:x.id,label:'客户实际退回 '+x.id+' · 尚待退第三方 '+money(x.remaining_cents)+' 元'}));
 if(['thirdparty_refund','pass_pay','direct_return','customer_return','party_return','unused_refund'].includes(key)){if(!options.length)throw new Error('尚无本步骤可用的原实际款项；请先核对前置事实。');fields.push(F('original','原款记录','select',true,options.map(x=>x.label)));}
 if(moneyKeys.includes(key))fields.push(F('amount','本次实际金额（元）','money'));
 if(moneyKeys.includes(key)&&!['direct_confirm','direct_return'].includes(key))fields.push(F('account_id','本次原路径账户','account'),F('reference','本次独立流水／凭证号'));
 fields.push(F('evidence_id','本理赔单本次实际原件','file'));
 await formDialog(claimNames[key],fields,initial,v=>{const values={...v,...extra};if('original'in values){values.original_id=options.find(x=>x.label===values.original).id;delete values.original;}if('amount'in values){values.amount_cents=repairScaled(values.amount,2);delete values.amount;}return claimSend(r,key,values,request_id);},{caseId:r.id,notice:key==='direct_confirm'||key==='direct_return'?'财务核对第三方与客户间的实际付款原件，本步骤不生成公司现金。':'仅确认本人实际核对的结果。原报价、原收款和已记录外部结果都会保留。'});
}
document.addEventListener('click',async event=>{const e=event.target.closest('[data-act]');if(!e?.dataset.act.startsWith('claim-'))return;try{if(e.dataset.act==='claim-new')await claimsNew(Number(e.dataset.source)||null);if(e.dataset.act==='claim-action')await claimAction(e.dataset.key,Number(e.dataset.plan)||null);}catch(error){toast(error.message,true);}});
