'use strict';
const gateStatus={planned:'待实际进厂',inside:'已实际进厂',departed:'已实际离场',cancelled:'安排已取消',voided:'错误登记已独立撤销',handed_over:'已沿原进厂转维修'};
const gateActionNames={arrive:'确认实际进厂',leave:'确认实际离场',cancel:'取消未进厂安排',handoff:'沿本次进厂转维修',correct:'申请原事实纠正'};
const gateCorrectionKinds={arrive_time:'纠正原进厂时间',leave_time:'纠正原离场时间',void_visit:'撤销错误进出厂登记'};
const gateReviewStatus={pending:'待独立复核',approved:'已批准',rejected:'未通过',cancelled:'申请已撤销'};
function gateFilesField(){const fs=(state.row?.files||[]).filter(f=>f.security?.can_use&&!f.generated);return `<label>本人核实的本单凭据<select name="evidence_id" required>${intakeOptions(fs,f=>f.name+' · '+f.label)}</select></label><p class="fieldhelp">只可使用本单检查通过的实际上传凭据。没有凭据请先关闭窗口，上传后再办理。</p>`;}
function gateReasonField(){return '<label>本人核实的事实及依据<textarea name="reason" required minlength="2" maxlength="1000"></textarea></label>';}
function gateActualFields(){return `<label>现场逐位核对 VIN<input name="checked_vin" required minlength="17" maxlength="17" pattern="[A-HJ-NPR-Za-hj-npr-z0-9]{17}" autocomplete="off"></label><label>实际发生时间<input type="datetime-local" name="actual_at" required value="${intakeLocal(new Date())}"></label>${gateFilesField()}${gateReasonField()}<label class="checkrow"><input type="checkbox" name="confirmed" required>我已核实本车和凭据，确认本次进出厂已实际发生，不是预约或业务状态推断。</label>`;}
function gateActualValues(form){return {checked_vin:form.elements.checked_vin.value.trim().toUpperCase(),actual_at:new Date(form.elements.actual_at.value).toISOString(),evidence_id:Number(form.elements.evidence_id.value),reason:form.elements.reason.value,confirmed:form.elements.confirmed.checked};}
function gateForm(body,label){return `<form>${body}<div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">${E(label)}</button></div></form>`;}
async function gateVisitsPage(id){
 if(state.user.aggregate_scope)return heading('实际进出厂','集团汇总隐藏车辆身份；原单办理请选择本店。',b('open','查看同源汇总','data-route="visit-activity"'));
 const front=intakeRole(['admin','manager','service','reception','customer_service']);
 if(!id){const d=await api(`/api/gate-visits?page=${state.page}`);return heading('非维修实际进出厂','先登记来访安排，再据实确认。预约、采购库存和业务取消不代替车辆实际进出。',front?b('gate-new','登记本次来访安排','','primary'):'')+storeNotice()+panel('本店来访',table(['车辆与来由','状态','实际时间',''],d.items.map(r=>[`${E(r.title)}<br>${E(r.vin)}<br>${E(r.purpose_label)}`,E(gateStatus[r.status]),`${r.arrived_at?time(r.arrived_at):'尚无进厂事实'}${r.left_at?'<br>'+time(r.left_at):''}`,b('open','办理',`data-route="gate-visits/${r.id}"`)])))+pager(d.total)+b('open','查看同源进出厂统计','data-route="visit-activity"');}
 const r=await api('/api/gate-visits/'+id);state.gateVisit=r;state.row=await api('/api/flow/cases/'+r.case_id);
 const actions=r.actions.filter(k=>canWrite()).map(k=>b('gate-action',gateActionNames[k],`data-key="${k}"`,['arrive','leave'].includes(k)?'primary':''));
 if(r.handoff_appointment_id)actions.push(b('open','继续原进厂维修接待',`data-route="service-intake/appointments/${r.handoff_appointment_id}"`));
 const reviews=r.corrections.map(c=>[E(gateCorrectionKinds[c.kind]),E(gateReviewStatus[c.status]),c.actual_at?time(c.actual_at):'不编造离场事实',E(c.reason),[c.can_review&&canWrite()?b('gate-review','批准','data-key="approve" data-id="'+c.id+'"')+b('gate-review','不通过','data-key="reject" data-id="'+c.id+'"'):'',c.can_cancel&&canWrite()?b('gate-review','撤回申请','data-key="cancel" data-id="'+c.id+'"'):''].join('')]);
 return heading(r.title,r.number,b('open','返回列表','data-route="gate-visits"'))+storeNotice()+panel('当前可办理',`<p>${E(gateStatus[r.status])} · ${E(r.purpose_label)}</p><p class="fieldhelp">原 VIN：${E(r.vin)}</p><p>${E(r.description)}</p><p>当前有效进厂：${r.arrived_at&&!r.voided?time(r.arrived_at):'无'}<br>当前有效离场：${r.left_at&&!r.voided?time(r.left_at):'无'}</p><div class="row">${actions.join('')||'当前岗位等待前置办理或独立复核。'}</div>`)+intakeFiles()+panel('保留的原始事实',table(['事实','原发生时间','本人记录','凭据编号'],r.facts.map(f=>[f.direction==='arrive'?'实际进厂':'实际离场',time(f.actual_at),E(f.reason),E(String(f.evidence_id))])))+panel('独立纠正与复核',`<p class="fieldhelp">申请不覆盖原记录；批准后同源统计按有效事实重算。转维修后不得在此绕过原维修链纠正。</p>${table(['纠正范围','状态','新时间','申请依据',''],reviews)}`)+panel('岗位交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&intakeRole(['admin','manager'])?b('assign','交接给其他员工',`data-id="${t.id}"`):''}</div></div>`).join(''));
}
async function gateNew(){const c=await api('/api/gate-visits/catalog'),request_id=requestKey();modal('登记本次非维修来访安排',gateForm(`<p class="fieldhelp">保存后仍须现场核对并确认实际进厂，不增加进出厂统计。</p><label>客户车辆<select name="customer_vehicle_id" required>${intakeOptions(c.vehicles,v=>v.customer_name+' · '+v.plate+' · '+v.vin)}</select></label><label>本次来由<select name="purpose">${Object.entries(c.purposes).map(([k,v])=>`<option value="${k}">${E(v)}</option>`).join('')}</select></label><label>本次安排说明<textarea name="description" required minlength="2" maxlength="1000"></textarea></label>`,'保存来访安排'),async form=>{const r=await api('/api/gate-visits',{method:'POST',body:{request_id,customer_vehicle_id:Number(form.elements.customer_vehicle_id.value),purpose:form.elements.purpose.value,description:form.elements.description.value}});closeModal();go('gate-visits/'+r.id);await render();});}
async function gateAction(key){
 if(key==='correct')return gateCorrection();if(key==='handoff')return gateHandoff();const r=state.gateVisit,request_id=requestKey();
 modal(gateActionNames[key],gateForm(key==='cancel'?gateReasonField():gateActualFields(),gateActionNames[key]),async form=>{const values=key==='cancel'?{reason:form.elements.reason.value}:gateActualValues(form);await api(`/api/gate-visits/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values}});closeModal();await render();});
}
async function gateCorrection(){const r=state.gateVisit,request_id=requestKey(),kinds=r.left_at?['arrive_time','leave_time','void_visit']:['arrive_time','void_visit'];modal('申请原事实独立纠正',gateForm(`<p class="fieldhelp">其他主管独立核对后生效。待复核期间暂停本次实际离场或转维修，原事实保留。</p><label>纠正范围<select name="kind" id="gate-correction-kind">${kinds.map(k=>`<option value="${k}">${E(gateCorrectionKinds[k])}</option>`).join('')}</select></label><label id="gate-correction-time">核实后的原实际时间<input type="datetime-local" name="actual_at" required value="${intakeLocal(r.arrived_at)}"></label>${gateFilesField()}${gateReasonField()}`,'提交独立复核'),async form=>{const kind=form.elements.kind.value;await api(`/api/gate-visits/${r.id}/corrections`,{method:'POST',body:{request_id,version:r.version,values:{kind,actual_at:kind==='void_visit'?null:new Date(form.elements.actual_at.value).toISOString(),evidence_id:Number(form.elements.evidence_id.value),reason:form.elements.reason.value}}});closeModal();await render();});$('#gate-correction-kind').onchange=e=>{const input=$('#gate-correction-time input'),voided=e.target.value==='void_visit';$('#gate-correction-time').hidden=voided;input.required=!voided;input.disabled=voided;if(!voided)input.value=intakeLocal(e.target.value==='leave_time'?r.left_at:r.arrived_at);};}
async function gateReview(id,key){const r=state.gateVisit,c=r.corrections.find(x=>x.id===id),request_id=requestKey(),label=key==='approve'?'独立批准纠正':key==='reject'?'记录复核未通过':'撤回本人申请';if(!c)throw new Error('申请已变化，请刷新页面。');modal(label,gateForm(`<p>${E(gateCorrectionKinds[c.kind])} · ${c.actual_at?time(c.actual_at):'撤销错误登记，不补造离场'}</p>${key==='cancel'?'':gateFilesField()}${gateReasonField()}`,label),async form=>{const values={reason:form.elements.reason.value};if(key!=='cancel')values.evidence_id=Number(form.elements.evidence_id.value);await api(`/api/gate-visits/corrections/${id}/actions/${key}`,{method:'POST',body:{request_id,version:c.version,values}});closeModal();await render();});}
async function gateHandoff(){const r=state.gateVisit,c=await api('/api/gate-visits/catalog'),request_id=requestKey();modal('沿本次原进厂转维修',gateForm(`<p class="fieldhelp">复用本次实际进厂与原凭据，不重复登记到店，不自动施工或结算。</p><label>再次逐位核对 VIN<input name="checked_vin" required minlength="17" maxlength="17" pattern="[A-HJ-NPR-Za-hj-npr-z0-9]{17}"></label><label>现场里程（公里）<input type="number" name="odometer_km" required min="0" step="1"></label><label>服务工位<select name="resource_id" required>${intakeOptions(c.resources.filter(x=>x.active),x=>x.name)}</select></label><label>计划开始<input type="datetime-local" name="starts_at" required value="${intakeLocal(new Date())}"></label><label>计划结束<input type="datetime-local" name="ends_at" required value="${intakeLocal(new Date(Date.now()+3600000))}"></label><label>本次维修诉求<textarea name="problem" required minlength="2" maxlength="1000"></textarea></label>${gateFilesField()}`,'交维修接待继续办理'),async form=>{const r2=await api(`/api/gate-visits/${r.id}/actions/handoff`,{method:'POST',body:{request_id,version:r.version,values:{checked_vin:form.elements.checked_vin.value.trim().toUpperCase(),odometer_km:Number(form.elements.odometer_km.value),resource_id:Number(form.elements.resource_id.value),starts_at:new Date(form.elements.starts_at.value).toISOString(),ends_at:new Date(form.elements.ends_at.value).toISOString(),problem:form.elements.problem.value,evidence_id:Number(form.elements.evidence_id.value)}}});closeModal();go('service-intake/appointments/'+r2.handoff_appointment_id);await render();});}
async function gateRepairExit(){const r=state.repairOrder,request_id=requestKey();state.row=await api('/api/flow/cases/'+r.id);modal('确认已取消维修车辆实际离场',gateForm('<p class="fieldhelp">取消不代表车辆离场。此处只记录本人核实的实际离场，不恢复维修或修改收退款。</p>'+gateActualFields(),'确认本次实际离场'),async form=>{await api(`/api/gate-visits/repair-orders/${r.id}/departure`,{method:'POST',body:{request_id,version:r.version,values:gateActualValues(form)}});closeModal();await render();});}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el?.dataset.act.startsWith('gate-'))return;try{switch(el.dataset.act){case'gate-new':await gateNew();break;case'gate-action':await gateAction(el.dataset.key);break;case'gate-review':await gateReview(Number(el.dataset.id),el.dataset.key);break;case'gate-repair-exit':await gateRepairExit();break;}}catch(error){toast(error.message,true);}});
