'use strict';
const insuranceNames={quote:'提交保险报价',review:'独立核价',authorize:'客户本版授权',quote_cancel:'撤回当前报价',submit:'实际投保或补件',result:'保险公司实际结果',receive:'实际代收保费',disburse:'按原款实际代缴',insurer_return:'保险公司原路退回',direct_paid:'客户直付证明',direct_return:'保险公司直退客户',termination:'撤保及原款方案',termination_review:'独立复核撤保',termination_consent:'客户同意本版撤保',termination_apply:'生效已批准撤保',termination_cancel:'撤回未生效撤保',refund:'原路退客户保费',commission:'确认实际累计佣金',commission_review:'独立复核实际佣金',commission_receive:'实际佣金到账',commission_return:'退回原超收佣金',cancel:'取消未执行保险申请'};
function clearInsuranceSession(){delete state.insuranceOrder;delete state.insuranceCatalog;}
async function insuranceOrdersPage(id){
 if(!id){const d=await api('/api/insurance-orders?page='+state.page);return heading('保险核价与结算','客户保费、保险公司代缴和佣金实际结算分别记录。',canWrite()&&['admin','sales','service'].includes(state.user.role)?b('insurance-new','建立保险单','','primary'):'')+storeNotice()+panel('本店保险',table(['保险单','状态',''],d.rows.map(r=>[`${E(r.number)}<br>${E(r.title)}`,pill(r.state),b('open','办理',`data-route="insurance-orders/${r.id}"`)])));}
 const r=await api('/api/insurance-orders/'+id);state.insuranceOrder=r;state.row=await api('/api/flow/cases/'+id);state.insuranceCatalog=await api('/api/insurance-orders/catalog?customer_id='+r.customer_id);
 const s=r.summary,q=r.quote,history=r.quote_history.find(h=>h.quote.id===q?.id),pending=r.plans.find(p=>!p.cancelled&&!p.applied&&p.review?.decision!=='rejected'),commissionPending=r.commissions.find(c=>!c.review),confirmed=r.commissions.filter(c=>c.review?.decision==='approved').at(-1);
 const button=(key,extra='')=>canWrite()&&r.actions.includes(key)?b('insurance-action',insuranceNames[key],`data-key="${key}" ${extra}`):'',actions=[];
 if(!r.tenders.length&&!r.direct_entries.length&&!r.submissions.length&&!s.terminated&&!pending){actions.push(button('quote'));if(q)actions.push(button('quote_cancel'));actions.push(button('cancel'));}
 if(q&&!history?.review)actions.push(button('review'));
 if(history?.review?.decision==='approved'&&!history.authorized)actions.push(button('authorize'));
 if(history?.authorized&&!pending&&!s.terminated){if(s.customer_due_cents)actions.push(button('receive'));if(s.direct_due_cents)actions.push(button('direct_paid'));actions.push(button('termination'));}
 if(history?.authorized&&s.terminated&&!pending&&!s.customer_refund_cents&&!s.insurer_return_due_cents)actions.push(button('termination'));
 let h=heading(r.title,r.number,b('open','返回保险列表','data-route="insurance-orders"'))+storeNotice()+`<div class="notice">${pill(r.state)} · VIN ${E(r.order.vin)}<br>${r.order.delivery_blocking?'本单明确约定交车前保单及保费办结。':'按保险单独进度办理，未设置交车前条件。'}佣金后续核对。<br>实际投保、出保、到账和退款各有凭据，不会因批准自动生成现金。</div>`;
 h+=panel('本次办理',`<div class="row">${actions.join('')||'请由当前对应岗位接手待办。'}</div>`);
 h+=panel('保费与原款',`<div class="formgrid">${[['当前保费',s.premium_cents],['门店客户款净收',s.customer_paid_cents],['扣占额客户尚欠',s.customer_due_cents],['原款待退客户',s.customer_refund_cents],['实际净代缴保险公司',s.insurer_paid_cents],['保险公司尚须退回',s.insurer_return_due_cents],['门店持有本单本金',s.held_principal_cents],['客户直付净额（无门店现金）',s.direct_net_cents]].map(([n,a])=>`<div>${E(n)}<strong>${money(a)} 元</strong></div>`).join('')}</div>`);
 if(q)h+=panel('当前报价第 '+q.revision+' 版',`<p>${E(q.insurer_snapshot.name)} · ${q.collection_mode==='store_collect'?'门店代收并代缴':'客户直接支付保险公司'}</p><p>保险期间 ${E(q.start_date)} 至 ${E(q.end_date)}；本版确认截止 ${E(q.valid_until)}</p>${table(['险种','保费（元）'],q.lines.map(l=>[E(l.name),money(l.premium_cents)]))}<p>${E(q.terms)}</p>${q.collection_mode==='store_collect'?`<p>冻结保险公司收款户：${E(q.insurer_snapshot.account_name)}<br>账户或缴费识别：${E(q.insurer_snapshot.account_reference)}</p>`:''}<p>${history?.review?history.review.decision==='approved'?'另一主管已批准':'主管已拒绝':'等待独立核价'}；${history?.authorized?'客户已授权本版':'尚无客户本版授权'}</p>`);
 const last=r.submissions.at(-1),result=last?r.results.find(x=>x.submission_id===last.id):null;
 h+=panel('实际投保与出保',`<div class="row">${history?.authorized&&!pending&&!s.terminated&&!s.issued&&(!last||result)?button('submit'):''}${last&&!result?button('result'):''}</div>${r.results.map(x=>`<p><strong>${E({issued:'已实际出保',rejected:'保险公司拒绝',need_documents:'保险公司要求补件'}[x.outcome])}</strong> · ${E(x.policy_number||'')}<br>${E(x.business_date)} · ${E(x.result)}</p>`).join('')||'<p>尚无保险公司实际结果。</p>'}`);
 h+=panel('原客户资金',r.tenders.map(t=>`<div class="taskitem"><div class="description"><strong>${t.payment_link_id?'原现金':'原预收抵用'} ${t.id} · ${money(t.amount_cents)} 元</strong><p>未退 ${money(t.unrefunded_cents)} 元；实际净代缴 ${money(t.spent_cents)} 元；本店原款余 ${money(t.available_cents)} 元</p>${!pending&&!s.terminated&&s.insurer_due_cents&&t.available_cents>0?button('disburse',`data-tender="${t.id}"`):''}</div></div>`).join('')||'<p>尚无门店代收款；客户直付不会产生本表记录。</p>');
 h+=panel('保险公司实际代收付',r.pass_entries.map(e=>`<div class="taskitem"><div class="description"><strong>${e.purpose==='disburse'?'实际代缴':'原代缴退回'} ${money(e.amount_cents)} 元</strong><p>${E(e.business_date)} · ${E(e.reference)}</p>${e.purpose==='disburse'&&e.amount_cents>r.pass_entries.filter(x=>x.original_id===e.id).reduce((n,x)=>n+x.amount_cents,0)?button('insurer_return',`data-original="${e.id}"`):''}</div></div>`).join('')||'<p>尚无门店与保险公司的保费实际现金。</p>');
 if(q?.collection_mode==='customer_direct')h+=panel('客户与保险公司直接结算',r.direct_entries.map(e=>`<p>${e.purpose==='paid'?'客户直付':'保险公司直退'} ${money(e.amount_cents)} 元 · ${E(e.external_reference)}<br>${e.purpose==='paid'&&s.direct_return_due_cents?button('direct_return',`data-original="${e.id}"`):''}</p>`).join('')||'<p>尚无直付凭据，不计门店现金。</p>');
 for(const p of r.plans){h+=panel('撤保方案第 '+p.revision+' 版',`<p>${p.cancelled?'已撤回':p.applied?'已生效':p.review?.decision==='rejected'?'主管拒绝':p.consented?'客户已同意，待生效':p.review?'主管已批准，待客户确认':'等待独立复核'}；保留保费 ${money(p.retained_cents)} 元</p><p>${E(p.reason)}</p><div class="row">${!p.review&&!p.cancelled?button('termination_review',`data-plan="${p.id}"`):''}${p.review?.decision==='approved'&&!p.consented&&!p.cancelled?button('termination_consent',`data-plan="${p.id}"`):''}${p.consented&&!p.applied&&!p.cancelled?button('termination_apply',`data-plan="${p.id}"`):''}${!p.applied&&!p.cancelled&&p.review?.decision!=='rejected'?button('termination_cancel',`data-plan="${p.id}"`):''}</div>`+p.returns.map(x=>{const done=p.refunds.filter(f=>f.original_tender_id===x.tender_id).reduce((n,f)=>n+f.amount_cents,0);return `<p>原款 ${x.tender_id}：本方案退 ${money(x.amount_cents)} 元，实际已退 ${money(done)} 元</p>${p.applied&&done<x.amount_cents?button('refund',`data-plan="${p.id}" data-tender="${x.tender_id}"`):''}`;}).join(''));}
 if(r.financial_visible&&['admin','manager','finance','auditor'].includes(state.user.role))h+=panel('佣金发票',b('open','查看开票与冲红记录','data-route="invoices"')+(canWrite()&&['admin','finance'].includes(state.user.role)&&confirmed?.target_cents>0&&!commissionPending?b('invoice-new','申请佣金开票',`data-source="${r.id}"`):'')+'<p>仅按另一主管已确认的佣金开票，购买方为原保险公司；保费、到账、开票结果分别核对。</p>');
 if(r.financial_visible)h+=panel('实际佣金结算',`<div class="formgrid">${[['预计佣金（非收入）',s.expected_commission_cents],['已独立确认累计佣金',s.confirmed_commission_cents],['实际到账净额',s.actual_commission_cents],['已确认未到账',s.commission_due_cents],['原超收待退佣金',s.commission_return_due_cents]].map(([n,a])=>`<div>${E(n)}<strong>${money(a)} 元</strong></div>`).join('')}</div><div class="row">${(s.issued||s.terminated)&&!commissionPending?button('commission'):''}${commissionPending?button('commission_review',`data-confirmation="${commissionPending.id}"`):''}${!commissionPending&&s.commission_due_cents?button('commission_receive',`data-confirmation="${confirmed.id}"`):''}</div>${r.commissions.map(c=>`<p>结算第 ${c.revision} 版：累计 ${money(c.target_cents)} 元，${c.review?c.review.decision==='approved'?'另一主管已确认':'主管拒绝':'待独立复核'}。${E(c.reason)}</p>`).join('')}${r.commission_payments.map(e=>`<p>${e.direction==='in'?'实收佣金':'原佣金退回'} ${money(e.amount_cents)} 元 · ${E(e.reference)}${!commissionPending&&e.direction==='in'&&s.commission_return_due_cents?'<br>'+button('commission_return',`data-confirmation="${confirmed.id}" data-original="${e.id}"`):''}</p>`).join('')}`);
 if(r.order.renewal_task_id||r.order.previous_policy_id)h+=panel('明确续保来源',`<p>原保单记录 ${r.order.previous_policy_id||'未关联'}；续保任务 ${r.order.renewal_task_id||'未关联'}。实际新保单登记保险期限，不替员工自动结案。</p>${r.order.renewal_task_id?b('open','查看原续保任务',`data-route="customer-service/${r.order.renewal_task_id}"`):''}`);
 const openTasks=state.row.tasks.filter(t=>t.status==='open'),doneTasks=state.row.tasks.filter(t=>t.status!=='open'),files=state.row.files;
 h+=panel('原件与岗位交接',b('upload','上传本次实际凭据')+'<p>核价、客户同意、投保与外部结果使用“客户授权”；实际保费、佣金及生效使用“收款凭据”。同一原件不得冒作另一办理事实。</p>'+taskList(openTasks)+`<details><summary>查看本单 ${files.length} 份实际原件</summary>${fileList(files)}</details>`+(doneTasks.length?`<details><summary>查看 ${doneTasks.length} 项已办交接记录</summary>${taskList(doneTasks)}</details>`:''));
 h+=panel('历史报价',`<details><summary>查看 ${r.quote_history.length} 个版本</summary>${r.quote_history.map(x=>`<p>第 ${x.quote.revision} 版 · ${E(x.quote.insurer_snapshot.name)} · 保费 ${money(x.quote.premium_cents)} 元 · ${x.cancelled?'已撤回':x.authorized?'客户已授权':'未授权'}<br>${E(x.quote.terms)}</p>`).join('')}</details>`);return h;
}
async function insuranceOrderNew(sourceId){
 const source=sourceId?await api('/api/flow/cases/'+sourceId):null;
 async function choose(query=''){
  const c=await api('/api/insurance-orders/catalog?'+(source?'customer_id='+source.customer_id:'q='+encodeURIComponent(query)));
  if(!c.customers.length)throw new Error('没有匹配的本店客户，请先建立或确认客户归属。');
  modal('选择保险客户',`<form>${!source?'<label>按姓名或电话缩小范围<input name="search" value="'+E(query)+'"></label><button type="button" data-insurance-search>查找客户</button>':''}<label>本店客户<select name="customer">${c.customers.map(x=>`<option value="${x.id}">${E(x.name)} · ${E(x.phone)}</option>`).join('')}</select></label><p>当前显示 ${c.customers.length} / ${c.total} 位，客户不在列表时请先查找。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">下一步选择车辆</button></div></form>`,async form=>{const selected=Number(form.elements.customer.value);closeModal();await create(selected);});
  document.querySelector('[data-insurance-search]')?.addEventListener('click',async()=>{const query=document.querySelector('#modal [name=search]').value;closeModal();await choose(query);});
 }
 async function create(customerId){
  const c=await api('/api/insurance-orders/catalog?customer_id='+customerId),vehicles=['不另选客户车辆',...c.vehicles.map(x=>x.id+' · '+x.vin+' · '+x.plate)],sources=['不关联销售',...c.sources.map(x=>x.id+' · '+x.number)],policies=['首次投保或未关联原保单',...c.policies.map(x=>x.id+' · '+x.policy_number+' · '+x.vin)],renewals=['不关联续保任务',...c.renewals.map(x=>x.id+' · '+x.title)],request_id=requestKey();
  await formDialog('建立保险单',[F('vehicle','客户车辆','select',true,vehicles),F('source','可选销售原单','select',true,sources),F('previous','续保原保单','select',true,policies),F('renewal','明确原续保任务','select',true,renewals),F('blocking','是否约定交车前办结','select',true,['按保险独立进度','明确交车前保费办结']),F('due_date','办理期限','date'),F('reason','客户投保需求','textarea')],{vehicle:vehicles[c.vehicles.length?1:0],source:source?sources[c.sources.findIndex(x=>x.id===source.id)+1]:sources[0],previous:policies[0],renewal:renewals[0],blocking:'按保险独立进度',due_date:day()},v=>{const original=c.sources[sources.indexOf(v.source)-1],renewal=c.renewals[renewals.indexOf(v.renewal)-1];return api('/api/insurance-orders',{method:'POST',body:{request_id,customer_id:customerId,customer_vehicle_id:c.vehicles[vehicles.indexOf(v.vehicle)-1]?.id||null,source_order_id:original?.id||null,source_version:original?.version||null,previous_policy_id:c.policies[policies.indexOf(v.previous)-1]?.id||null,renewal_task_id:renewal?.id||null,renewal_version:renewal?.version||null,delivery_blocking:v.blocking==='明确交车前保费办结',due_date:v.due_date,reason:v.reason}}).then(r=>go('insurance-orders/'+r.id));},{notice:'必须明确客户车辆，或已有实际 VIN 的销售原单。同客户续保不自动更改原任务结果。'});
 }
 return choose();
}
function insuranceSend(r,key,values,request_id){return api(`/api/insurance-orders/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values}});}
async function insuranceQuote(){
 const r=state.insuranceOrder,c=state.insuranceCatalog,q=r.quote,request_id=requestKey();if(!c.insurers.length)throw new Error('请先配置本店启用保险公司。');
 const row=(l={})=>`<div data-insurance-line class="formgrid"><label>险种名称<input name="line_name" value="${E(l.name||'')}"></label><label>本险种保费（元）<input name="line_amount" inputmode="decimal" value="${l.premium_cents===undefined?'':(l.premium_cents/100).toFixed(2)}"></label></div>`;
 modal('本版保险核价',`<form><label>保险公司<select name="insurer">${c.insurers.map(x=>`<option value="${x.id}"${q?.insurer_id===x.id?' selected':''}>${E(x.name)} · ${E(x.license_number)}</option>`).join('')}</select></label><label>保费支付方式<select name="mode"><option value="store_collect">本店代收并代缴</option><option value="customer_direct"${q?.collection_mode==='customer_direct'?' selected':''}>客户直接付保险公司</option></select></label><div data-insurance-lines>${(q?.lines||[{},{}]).map(row).join('')}</div><button type="button" data-insurance-add>增加险种</button><label>预计佣金（元；非已确认收入）<input name="expected" inputmode="decimal" value="${q?(q.expected_commission_cents/100).toFixed(2):'0.00'}" required></label><label>保险公司实际收款户名（代缴必填）<input name="payee" value="${E(q?.insurer_snapshot.account_name||'')}"></label><label>保险公司账户或缴费识别号（代缴必填）<input name="payee_reference" value="${E(q?.insurer_snapshot.account_reference||'')}"></label><div class="formgrid"><label>保险开始日<input name="start" type="date" value="${q?.start_date||day()}" required></label><label>保险截止日<input name="end" type="date" value="${q?.end_date||''}" required></label></div><label>本版确认有效期<input name="expiry" type="date" value="${q?.valid_until||day()}" required></label><label>本版约定<textarea name="terms" required minlength="2">${E(q?.terms||'')}</textarea></label><label>本次核价原因<textarea name="reason" required minlength="2"></textarea></label><p>每版核价须另一主管批准并取得客户同版授权。保费与佣金分账，不按比例自动推定公司佣金。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">提交独立核价</button></div></form>`,async form=>{const insurer=c.insurers.find(x=>x.id===Number(form.elements.insurer.value));const lines=[...form.querySelectorAll('[data-insurance-line]')].filter(e=>e.querySelector('[name=line_name]').value||e.querySelector('[name=line_amount]').value).map(e=>({name:e.querySelector('[name=line_name]').value,premium_cents:repairScaled(e.querySelector('[name=line_amount]').value,2)}));await insuranceSend(r,'quote',{insurer_id:insurer.id,insurer_version:insurer.version,collection_mode:form.elements.mode.value,payee_account_name:form.elements.payee.value,payee_account_reference:form.elements.payee_reference.value,lines,expected_commission_cents:repairScaled(form.elements.expected.value,2),start_date:form.elements.start.value,end_date:form.elements.end.value,valid_until:form.elements.expiry.value,terms:form.elements.terms.value,reason:form.elements.reason.value},request_id);closeModal();await render();});
 document.querySelector('[data-insurance-add]').addEventListener('click',()=>{if(document.querySelectorAll('[data-insurance-line]').length<40)document.querySelector('[data-insurance-lines]').insertAdjacentHTML('beforeend',row());});
}
async function insuranceTermination(){
 const r=state.insuranceOrder,request_id=requestKey(),files=state.row.files.filter(f=>!f.generated&&f.category==='authorization'&&f.security?.can_use);
 modal('撤保及原款方案',`<form><p>先核对保险公司真实终止或未出保结果。保留保费是保险公司实际不退的部分，不能填预计佣金；尚在保险公司的原款须追回后才可退客户。</p><label>保险公司保留保费（元）<input name="retained" inputmode="decimal" value="${(r.summary.premium_cents/100).toFixed(2)}" required></label>${r.tenders.map(t=>`<label data-insurance-return="${t.id}">原${t.payment_link_id?'现金':'预收'} ${t.id}，未退 ${money(t.unrefunded_cents)} 元，本次退回（元）<input name="amount" inputmode="decimal" placeholder="不退此原款时留空"></label>`).join('')}<label>本人核对的保险公司实际结果<select name="result"><option value="not_issued">保险公司确认未出保或投保失败</option><option value="terminated"${r.summary.issued?' selected':''}>已有保单的实际退保结果</option></select></label><label>实际结果与保留原因<textarea name="reason" required minlength="2"></textarea></label><label>本次实际原件<select name="evidence_id" required>${files.map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">提交独立复核</button></div></form>`,async form=>{const returns=[...form.querySelectorAll('[data-insurance-return]')].filter(e=>e.querySelector('input').value.trim()).map(e=>({tender_id:Number(e.dataset.insuranceReturn),amount_cents:repairScaled(e.querySelector('input').value,2)}));await insuranceSend(r,'termination',{retained_cents:repairScaled(form.elements.retained.value,2),returns,external_result:form.elements.result.value,reason:form.elements.reason.value,evidence_id:Number(form.elements.evidence_id.value)},request_id);closeModal();await render();});
}
async function insuranceOrderAction(key,e){
 if(key==='quote')return insuranceQuote();if(key==='termination')return insuranceTermination();
 const r=state.insuranceOrder,fields=[],initial={},fixed={},request_id=requestKey(),plan=r.plans.find(p=>p.id===Number(e.dataset.plan)),tender=r.tenders.find(t=>t.id===Number(e.dataset.tender));
 if(plan)fixed.plan_id=plan.id;if(tender)fixed.tender_id=tender.id;if(e.dataset.original)fixed.original_id=Number(e.dataset.original);if(e.dataset.confirmation)fixed.confirmation_id=Number(e.dataset.confirmation);
 if(['review','termination_review','commission_review'].includes(key)){fields.push(F('decision','独立复核结果','select',true,['批准','拒绝']),F('reason','本人独立核对的理由','textarea'));initial.decision='批准';}
 if(key==='authorize'){fixed.quote_id=r.quote.id;fixed.digest=r.quote.digest;}
 if(key==='termination_consent')fixed.digest=plan.digest;
 if(key==='submit')fields.push(F('external_reference','实际受理或补件编号'));
 if(key==='result'){fixed.submission_id=r.submissions.at(-1).id;fields.push(F('outcome','保险公司实际结果','select',true,['实际出保','拒绝投保','需要补件']),F('policy_number','实际保单号（出保必填）','text',false),F('result','本人核对的实际结果','textarea'));}
 if(['quote_cancel','termination_cancel','cancel'].includes(key))fields.push(F('reason','明确撤回原因','textarea'));
 const monetary=['receive','disburse','insurer_return','direct_paid','direct_return','refund','commission_receive','commission_return'].includes(key),direct=key.startsWith('direct_'),creditRefund=key==='refund'&&tender?.credit_link_id;
 if(monetary){fields.push(F('amount','本次实际金额（元）','money'));if(direct)fields.push(F('external_reference','保险公司实际收退款凭证号'));else if(!creditRefund)fields.push(F('account_id','本店实际原资金账户','account'),F('reference','本次独立银行流水或凭证号'));if(tender&&!creditRefund)initial.account_id=tender.account_id;if(key==='insurer_return')initial.account_id=r.pass_entries.find(x=>x.id===fixed.original_id)?.account_id;if(key==='commission_return')initial.account_id=r.commission_payments.find(x=>x.id===fixed.original_id)?.account_id;}
 if(key==='commission'){fields.push(F('target','本保单累计实际应得佣金（元）','money_zero'),F('reason','保险公司实际结算依据与变化原因','textarea'));initial.target=(r.summary.confirmed_commission_cents/100).toFixed(2);}
 if(monetary||['submit','result','commission_review'].includes(key)){fields.push(F('business_date','实际发生日期','date'));initial.business_date=day();}
 if(!['quote_cancel','termination_cancel','cancel'].includes(key))fields.push(F('evidence_id','本单本次实际原件','file'));
 await formDialog(insuranceNames[key],fields,initial,v=>{const body={...v,...fixed};if('amount'in body){body.amount_cents=repairScaled(body.amount,2);delete body.amount;}if('target'in body){body.target_cents=repairScaled(body.target,2);delete body.target;}if(body.decision)body.decision=body.decision==='批准'?'approved':'rejected';if(body.outcome)body.outcome={实际出保:'issued',拒绝投保:'rejected',需要补件:'need_documents'}[body.outcome];return insuranceSend(r,key,body,request_id);},{caseId:r.id,notice:creditRefund?'本步只退回原本店预收余额，不产生现金。':key==='authorize'||key==='termination_consent'?'请核对当前版金额、期间、条款与实际客户原件。本次提交绑定完整本版摘要。':'仅登记本人已核对的实际事实，保费和佣金分别核对。'});
}
document.addEventListener('click',event=>{const e=event.target.closest('[data-act]');if(!e)return;const actions={'insurance-new':()=>insuranceOrderNew(e.dataset.source?Number(e.dataset.source):null),'insurance-action':()=>insuranceOrderAction(e.dataset.key,e)};if(actions[e.dataset.act])actions[e.dataset.act]().catch(err=>toast(err.message));});
