'use strict';
let materialValueState={};
function clearMaterialValueSession(){materialValueState={};}
function mvContext(){const key=String(state.user?.id)+':'+state.store;if(materialValueState.key!==key)materialValueState={key,filters:{},options:{}};return materialValueState;}
function mvFilters(){const s=mvContext();return `<form id="material-value-filters" class="filterbar">`+[['source','业务来源','sources'],['item_id','物资','items'],['case_id','相关原单','cases']].map(([key,label,options])=>`<label>${label}<select name="${key}"><option value="">全部</option>${(s.options[options]||[]).map(o=>`<option value="${E(o.id)}" ${String(s.filters[key])===String(o.id)?'selected':''}>${E(o.label)}</option>`).join('')}</select></label>`).join('')+`<button class="primary" type="submit">查询实际收入成本</button>${b('mv-clear','清除筛选')}</form>`;}
function mvTable(key,t){const rows=t.rows.slice((state.page-1)*20,state.page*20),open=r=>r.route?.type==='case'?b('open','查看原单',`data-route="case/${r.route.id}"`):'汇总只读';return panel(t.title,b('mv-export','导出本表',`data-key="${key}"`)+`<div class="work-table">${table([...t.headers,'原单'],rows.map(r=>[...r.values.map(E),open(r)]))}</div><div class="work-cards">${rows.map(r=>`<article class="card">${t.headers.map((h,i)=>`<p><span class="muted">${E(h)}：</span>${E(r.values[i])}</p>`).join('')}${open(r)}</article>`).join('')}</div>`+(t.rows.length?pager(t.rows.length,state.page,20):empty('当前范围没有实际记录')));}
async function materialValuePage(){const s=mvContext();let d;try{d=await api('/api/material-value?'+new URLSearchParams({...state.dates,...s.filters}));s.options=d.options;}catch(error){if([404,409,413,422].includes(error.status))return heading('物资收入成本对照','修正范围或核对原单后重查。')+storeNotice()+dateFilters()+mvFilters()+`<div class="notice error" role="alert">${E(error.message)}</div>`;throw error;}
 return heading('物资收入成本对照','用实际履约与领退料原记录核对，整单减免另列。')+storeNotice()+dateFilters()+mvFilters()+`<div class="notice">商品表是所选物资；原单核对表保留相关原单全部商品、服务及未分配调整。不能将未分配减免后的整单结果当作单品利润。</div><p class="muted">${E(d.definition)}</p><p class="muted">查询时点：${time(d.as_of)}</p>`+d.charts.map(c=>panel(c.title,chartSVG(c)+`<p class="muted">${E(c.caption)}</p>`+b('mv-export','导出此图原始行',`data-key="${c.table}"`))).join('')+Object.entries(d.tables).map(([key,t])=>mvTable(key,t)).join('');}
document.addEventListener('submit',event=>{if(event.target.id!=='material-value-filters')return;event.preventDefault();mvContext().filters=Object.fromEntries([...new FormData(event.target)].filter(([,v])=>v!==''));state.page=1;render();});
document.addEventListener('click',async event=>{if(event.target.closest('[data-act=mv-clear]')){mvContext().filters={};state.page=1;render();return;}const button=event.target.closest('[data-act=mv-export]');if(!button)return;button.disabled=true;try{await download('/api/material-value/export/'+button.dataset.key+'?'+new URLSearchParams({...state.dates,...mvContext().filters}),'huakangos_物资收入成本.csv');}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
