'use strict';
const membershipNames={topup:'集团本金充值',benefit_issue:'权益发行',card_issue:'发行会员卡',card_loss:'会员卡挂失',card_replace:'会员卡换补',renew:'会员续会',tier_change:'会员等级调整',renew_refund:'未生效续会退款',points_adjust:'积分办理'};
const membershipStates={draft:'待办理',review:'待复核',approved:'已批准待办理',completed:'已完成',cancelled:'已撤销'};
const membershipManager=()=>canWrite()&&['admin','manager'].includes(state.user.role);
const membershipFinance=()=>canWrite()&&['admin','finance'].includes(state.user.role);
const membershipFront=()=>canWrite()&&['admin','manager','finance','sales','service','reception','customer_service'].includes(state.user.role);
const membershipRuleLabel=r=>`${r.id} · ${r.name} · 版本${r.rule_version}`;
async function membershipPage(customerId){
 if(state.store==='all')return heading('会员卡与续会')+storeNotice();
 if(!customerId){const [customers,orders]=await Promise.all([api(`/api/flow/master/customers?q=${encodeURIComponent(state.q)}&page=${state.page}`),api('/api/membership/orders')]);return heading('会员卡与续会','选择本店客户，独立办理会员卡、续会、充值及权益。',b('membership-card-lookup','按卡号识别客户')+(state.user.role==='admin'?b('open','集团规则配置','data-route="membership-rules"'):''))+searchBar()+panel('本店客户',table(['客户','联系号码','办理'],customers.items.map(c=>[E(c.name),E(c.phone),b('open','查看会员',`data-route="membership/${c.id}"`)]))+pager(customers.total))+panel('本店最近办理',table(['业务','状态','操作'],orders.items.map(r=>[E(r.title),E(membershipStates[r.state]||r.state),b('open','查看待办与凭据',`data-route="membership-order/${r.id}"`)])));}
 const d=await api('/api/membership/members?customer_id='+customerId);state.membershipMember={...d,customerId};
 let html=heading('会员卡与续会',d.customer.name,b('open','返回客户列表','data-route="membership"')+b('open','本金及退款记录',`data-route="group/${customerId}"`)+b('open','集团权益记录',`data-route="benefits/${customerId}"`)+b('open','组合充值与原路退款',`data-route="recharge-bundles/${customerId}"`));
 if(!d.member)return html+panel('先核对集团身份','<p>会员办理前，请明确关联本店客户与集团身份并开通会员。</p>'+b('open','核对并开通会员',`data-route="group/${customerId}"`,'primary'));
 if(membershipFront())html+=panel('独立办理',`<div class="row">${b('membership-create','本金充值','data-key="topup"')}${b('membership-create','购买券或套餐','data-key="purchase"')}${b('membership-create','申请续会','data-key="renew"')}${b('membership-create','申请等级调整','data-key="tier_change"')}${membershipManager()?b('membership-create','明确赠送权益','data-key="grant"'):''}</div>`);
 html+=panel('会员识别卡',`<p>卡号只用于识别会员。实际消费、退款仍须本店权限与客户授权凭据。</p>${!d.cards.length&&membershipFront()?b('membership-create','发行第一张会员卡','data-key="card_issue"','primary'):''}`+d.cards.map(c=>`<div class="notice"><strong>第${c.generation}张 · ${E({active:'有效',lost:'已挂失',replaced:'已换补作废'}[c.status])}</strong><p>识别卡号：${E(c.number).match(/.{1,8}/g).join('<wbr>')}</p>${membershipFront()&&c.status!=='replaced'?`<div class="row">${c.status==='active'?b('membership-create','挂失原卡',`data-key="card_loss" data-id="${c.id}"`):''}${b('membership-create','换补新卡',`data-key="card_replace" data-id="${c.id}"`)}</div>`:''}</div>`).join(''));
 html+=panel('等级与有效期间',d.periods.length?d.periods.map(p=>`<div class="notice"><strong>${E(p.rule.name)} · 版本${p.rule.rule_version}${p.id===d.active_period_id?' · 当前有效':''}</strong><p>${p.starts_on} 至 ${p.ends_on}</p>${p.case_id&&p.kind==='renew'&&p.starts_on>day()&&p.rule.fee_cents>0&&p.rule.refund_policy==='before_start'&&membershipFront()?b('membership-create','申请未生效退款',`data-key="renew_refund" data-id="${p.id}"`):p.case_id?b('open','查看原办理',`data-route="membership-order/${p.case_id}"`):'他店已登记期间'}</div>`).join(''):empty('暂无有效期间','可先申请明确规则的会员续会。'));
 html+=panel('消费积分',`<p>原消费退款待追回积分：<strong>${number(d.points_debt_units)}</strong>。${d.points_debt_units?'真实退款可继续办理；后续新增积分先抵原欠额，当前不能新增积分消费或兑换。':'积分按原消费冻结规则和实际履约净额记录。未启用规则不自动赠分。'}</p>${membershipFront()?b('membership-create','积分兑换券包','data-key="exchange"'):''}${d.points_debt_units&&membershipFront()?b('membership-create','使用现有积分抵扣原欠额','data-key="settle_debt"'):''}${membershipManager()?b('membership-create','说明原因扣减积分','data-key="adjust"'):''}`);
 return html;
}
async function membershipOrderPage(id){
 if(state.store==='all')return heading('会员业务办理')+storeNotice();
 const d=await api('/api/membership/orders/'+id),source=await api('/api/flow/cases/'+id);state.membershipOrder=d;state.row=source;
 const o=d.order,buttons=[];const review=['renew','tier_change','renew_refund'].includes(o.purpose);
 if(o.status==='draft'&&review&&membershipManager()&&o.requested_by!==state.user.id)buttons.push(b('membership-action','独立复核批准','data-key="approve"','primary'),b('membership-action','退回申请','data-key="reject"'));
 const assigned=source.tasks.some(t=>t.key==='membership_execute'&&t.status==='open'&&(state.user.role==='admin'||t.assignee_id===state.user.id));
 if((o.status==='approved'||o.status==='draft'&&!review)&&membershipFront()&&assigned)buttons.push(b('membership-action','确认本次实际办理','data-key="execute"','primary'));
 if(['draft','approved'].includes(o.status)&&membershipFront())buttons.push(b('membership-action','撤销未完成办理','data-key="cancel"'));
 let facts=`<p>${E(membershipNames[o.purpose])} · ${E(membershipStates[o.status])}</p>`;
 if(o.values.amount_cents)facts+=`<p>本金充值 ${money(o.values.amount_cents)} 元</p>`;
 if(o.values.units)facts+=`<p>本次权益 ${number(o.values.units)} 单位；规则或原批次已经冻结。</p>`;
 if(o.purpose==='renew')facts+=`<p>本次续会收费 ${money(d.case.amount_cents)} 元。收费依据使用申请时已选规则，到账后生效或顺延有效期。</p>`;
 return heading('会员业务办理',d.case.title,buttons.join('')+b('open','返回会员',`data-route="membership/${d.case.customer_id}"`))+panel('已确认申请',facts)+panel('本单凭据',`<div class="filetools">${membershipFront()?b('upload','上传本次凭据','','primary'):''}</div>${fileList(source.files)}`)+panel('责任与待办',table(['事项','负责人','状态'],source.tasks.map(t=>[E(t.title),E(t.assignee_name||t.assignee_id),E({open:'待办理',done:'已完成',cancelled:'已结束'}[t.status]||t.status)])))+panel('办理记录',table(['时间','动作／依据'],d.events.map(e=>[time(e.occurred_at),`${E({create:'建立申请',approve:'独立批准',execute:'实际办理',cancel:'撤销',reject:'退回',topup:'本金到账',grant:'赠送权益',purchase:'购买权益',adjust:'积分扣减',exchange:'积分兑换',fee_refund_basis:'原款退款依据已冻结'}[e.action]||e.action)}<br>${E(e.reason)}`])));
}
async function membershipCreate(key,id){
 const context=state.membershipMember,fields=[],initial={},fixed={},request_id=requestKey();let purpose=key,notice='本次申请只建立独立办理单，真实凭据请在申请创建后上传。';
 if(key==='topup')fields.push(F('amount','本金充值金额（元）','money'));
 if(['card_loss','card_replace'].includes(key))fixed.card_id=id;
 if(key==='renew_refund')fixed.period_id=id;
 if(['renew','tier_change'].includes(key)){const rules=(await api('/api/membership/rules')).items;const latest=rules.filter(r=>r.enabled&&!rules.some(x=>x.code===r.code&&x.rule_version>r.rule_version));if(!latest.length)throw new Error('尚无适用本店的启用会员规则，请由集团管理员明确配置。');fields.push(F('rule','会员等级及冻结规则','select',true,latest.map(membershipRuleLabel)));context.rules=latest;notice+=' '+latest.map(r=>`${r.name}：${r.validity_months}个月，续会${money(r.fee_cents)}元。`).join('；');}
 if(['purchase','grant'].includes(key)){purpose='benefit_issue';fixed.action=key;const rules=(await api('/api/group/benefits/rules')).items.filter(r=>r.issuer_store_id===Number(state.store)&&(key==='purchase'?r.sale_cents_per_unit>0:r.sale_cents_per_unit===0));fields.push(F('rule','明确权益规则','select',true,rules.map(membershipRuleLabel)),F('units','本次份数／积分数','int'));context.rules=rules;}
 if(['exchange','adjust','settle_debt'].includes(key)){purpose='points_adjust';fixed.action=key;const d=await api('/api/group/benefits/members?customer_id='+context.customerId);const wallets=d.wallets.filter(w=>w.rule.kind==='points'&&w.available_units>0);fields.push(F('wallet','原积分批次','select',true,wallets.map(w=>`${w.id} · ${w.rule.name} · 可用${w.available_units}`)),F('units','本次积分数量','int'));if(key==='exchange'){const rules=(await api('/api/group/benefits/rules')).items.filter(r=>r.exchange_points_per_unit>0&&r.sale_cents_per_unit===0&&r.issuer_store_id===Number(state.store));fields.push(F('rule','兑换目标券包','select',true,rules.map(membershipRuleLabel)));context.rules=rules;}}
 fields.push(F('reason','已核对客户申请与办理原因','textarea'));
 await formDialog(membershipNames[purpose],fields,initial,async v=>{const values={...fixed};if(v.amount)values.amount_cents=groupFen(v.amount);if(v.units)values.units=v.units;if(v.rule)values[key==='exchange'?'target_rule_id':'rule_id']=Number(v.rule.split(' · ')[0]);if(v.wallet)values.wallet_id=Number(v.wallet.split(' · ')[0]);const d=await api('/api/membership/orders',{method:'POST',body:{request_id,customer_id:context.customerId,purpose,values,reason:v.reason}});go('membership-order/'+d.case.id);},{notice});
}
async function membershipAction(key){
 const d=state.membershipOrder,o=d.order,fields=[];const needsCash=key==='execute'&&(o.purpose==='topup'||o.purpose==='renew_refund'||o.purpose==='renew'&&d.case.amount_cents>0||o.purpose==='benefit_issue'&&o.values.action==='purchase');
 if(needsCash)fields.push(F('account_id','本店真实收退款账户','account'),F('reference','真实银行流水或收款凭证号'));
 if(['execute','approve'].includes(key))fields.push(F('evidence_id','本单客户确认／实际办理凭据','file'));fields.push(F('reason','本人核对的事实与办理依据','textarea'));
 const request_id=requestKey();await formDialog({execute:'确认实际办理',approve:'独立复核批准',reject:'退回申请',cancel:'撤销申请'}[key],fields,{},async values=>{if(key==='execute'&&o.purpose==='points_adjust'){const balances=await api('/api/group/benefits/members?customer_id='+d.case.customer_id);const w=balances.wallets.find(w=>w.id===o.values.wallet_id);if(!w)throw new Error('原积分批次不存在，请核对。');values.wallet_version=w.version;}await api(`/api/membership/orders/${d.case.id}/actions/${key}`,{method:'POST',body:{request_id,version:o.version,case_version:d.case.version,member_version:d.member.version,values}});},{caseId:d.case.id,notice:needsCash?'只有真实资金收付完成后才能登记。系统不会调用银行转账。':key==='approve'?'须由不同于申请人的主管独立复核；卡号不代表财务授权。':'仅确认本次自身办理事实；换补后原卡作废，会员本金及已发行权益保持原账。'});
}
async function membershipCardLookup(){await formDialog('按卡号识别本店客户',[F('number','完整会员识别卡号')],{},async v=>{const d=await api('/api/membership/cards/lookup?number='+encodeURIComponent(v.number));go('membership/'+d.customer.id);},{notice:'只识别有效卡及本店已经确认关联的客户；没有本店关系的卡不会显示外店客户资料。'});}
async function membershipRulesPage(){const d=await api('/api/membership/rules');state.membershipRules=d.items;return heading('集团会员规则','规则发布为新版本；收费及积分比例必须由公司明确配置。',state.user.role==='admin'?b('membership-rule','发布新规则版本','','primary'):'')+table(['等级／版本','有效期／续会金额','启用／消费积分'],d.items.map(r=>[`${E(r.name)} · ${E(r.code)} · 版本${r.rule_version}`,`${r.validity_months}个月 · ${money(r.fee_cents)}元`,`${r.enabled?'启用':'关闭'} · ${r.points_enabled?`${r.points_denominator_fen}分消费获${r.points_numerator}积分`:'不自动赠分'}`]));}
async function membershipRule(){const points=(await api('/api/group/benefits/rules')).items.filter(r=>r.kind==='points'),stores=state.stores.filter(s=>s.active!==false),request_id=requestKey();const fields=[F('code','规则编号（同编号发布新版本）'),F('name','会员级别名称'),...stores.map(s=>F('store_'+s.id,'适用门店：'+s.name,'bool',false)),F('validity_months','有效自然月数','int'),F('fee','续会金额（元，允许0）','money_zero'),F('refund_policy','退款规则','select',true,['不提供退款','未生效期间整笔原款退款']),F('enabled','启用新申请','bool',false),F('points_enabled','启用后续实际消费积分','bool',false),F('points_rule','关联冻结积分权益规则','select',false,points.map(membershipRuleLabel)),F('points_denominator_fen','每多少分实际消费','int'),F('points_numerator','对应积分数','int')];
 await formDialog('发布集团会员规则',fields,{enabled:false,points_enabled:false,refund_policy:'不提供退款'},v=>api('/api/membership/rules',{method:'POST',body:{request_id,values:{code:v.code,name:v.name,allowed_store_ids:stores.filter(s=>v['store_'+s.id]).map(s=>s.id),validity_months:v.validity_months,fee_cents:String(v.fee)==='0'?0:groupFen(v.fee),fee_owner:'collecting_store',refund_policy:v.refund_policy==='未生效期间整笔原款退款'?'before_start':'none',enabled:v.enabled,points_enabled:v.points_enabled,points_numerator:v.points_numerator,points_denominator_fen:v.points_denominator_fen,points_benefit_rule_id:v.points_rule?Number(v.points_rule.split(' · ')[0]):null}}}),{notice:'续会收费按收款门店经营主体记录。未生效期间退款须独立审批后整笔退回原账户。积分默认关闭，不追赠未冻结规则的历史消费。'});
}
function clearMembershipSession(){for(const key of ['membershipMember','membershipOrder','membershipRules'])delete state[key];}
