'use strict';
const memberPriceStacks={member_then_benefits:'先会员价，再按剩余容量使用券包赠金',exclusive_benefits:'会员价不与券包赠金叠用；本金仍可付款'};
const memberPriceComponents={'repair:work':'维修作业工时','repair:part':'维修配件','retail:goods':'精品商品','retail:installation':'精品安装','addon:goods':'销售加装商品','addon:installation':'销售加装施工'};
async function memberPricingPage(id){
 const manage=canWrite()&&['admin','manager'].includes(state.user.role);
 if(!id){const d=await api('/api/member-pricing/rules?page='+state.page);return heading('会员价格规则','',manage?b('member-price-new','提出本店价格规则','','primary'):'')+storeNotice()+panel('本店价格版本',table(['规则','等级原版本','生效期','状态',''],d.items.map(r=>[E(r.name)+' · 第'+r.rule_version+'版',E(r.membership_snapshot.name)+' · '+r.membership_snapshot.rule_version,E(r.starts_on)+' 至 '+E(r.ends_on),pill(r.state),b('open','查看',`data-route="member-pricing/${r.id}"`)]))+pager(d.total));}
 const r=await api('/api/member-pricing/rules/'+id);state.memberPriceRule=r;state.row=await api('/api/flow/cases/'+r.case_id);const action=(key,title)=>manage?b('member-price-action',title,`data-key="${key}"`):'';
 let h=heading('会员价格规则',r.number+' · 第 '+r.rule_version+' 版',b('open','返回规则','data-route="member-pricing"'))+storeNotice();
 h+=panel('本版独立价格依据',`<p>${E(r.name)} · ${E(r.code)}</p><p>集团会期等级：${E(r.membership_snapshot.name)} · 原规则第${r.membership_snapshot.rule_version}版</p><p>${E(r.starts_on)} 至 ${E(r.ends_on)} · ${r.enabled?'批准后启用':'批准后停用本规则'}</p><p>${E(memberPriceStacks[r.stack_mode])}</p><p>${E(r.reason)}</p>${r.reference_tier_id?`<p>仅参考本店等级主档：${E(r.reference_tier_snapshot.name)} · 第${r.reference_tier_snapshot.version}版 · ${r.reference_tier_snapshot.discount_basis_points}万分数；实际比例以下列逐项批准为准。</p>`:''}<div class="row">${r.state==='draft'?action('submit','提交实际规则依据'):''}${r.state==='approval'?action('approve','独立批准本版')+action('reject','退回核对'):''}${['draft','approval'].includes(r.state)?action('cancel','取消未生效申请'):''}</div>`);
 h+=panel('明确适用范围',table(['业务项目','实际来源','比例','套装范围'],r.scopes.map(s=>[E(memberPriceComponents[s.business_kind+':'+s.component]),E(s.source_snapshot.name)+' · '+E(s.source_snapshot.code),E(s.basis_points)+' / 10000',s.bundle_rule_id?E(s.bundle_snapshot.name)+' · 仅此套装原版本':'独立商品或项目']))+'<p>原责任返修行、已经购买的套餐合同组件不再次享用折扣。正价按比例舍入为零会拒绝，仍需既有赠送授权。已授权业务不因等级或价格规则变化重算。</p>');
 h+=panel('原件与独立复核',b('upload','上传本人本次实际依据')+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.security?.label||'待扫描')}</p>${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'扫描通过后可用'}</div></div>`).join('')+r.decisions.map(d=>`<p>${E({submitted:'申请人提交',approved:'另一主管批准',rejected:'主管退回',cancelled:'取消未生效申请'}[d.decision])} · ${E(d.reason)}</p>`).join(''));
 h+=actionPanel(state.row.tasks.map(t=>`<p>${E(t.title)} · ${E(t.assignee_name)} · ${pill(t.status)} ${t.status==='open'&&manage?b('assign','明确交接',`data-id="${t.id}"`):''}</p>`).join(''));return h;
}
async function memberPriceNew(){
 const d=await api('/api/member-pricing/catalog');for(let p=2;p<=Math.ceil(Math.max(d.tiers_total,d.items_total,d.works_total,d.bundles_total)/50);p++){const more=await api('/api/member-pricing/catalog?page='+p);for(const k of ['tiers','items','works','bundles'])d[k].push(...more[k]);}
 const request_id=requestKey();const sources=type=>(['work','installation'].includes(type)?d.works:d.items).map(x=>`<option value="${x.id}">${E(x.code)} · ${E(x.name)}</option>`).join('');
 const scope=()=>`<div class="panel" data-member-price-scope><label>业务项目<select name="component">${Object.entries(memberPriceComponents).map(([k,v])=>`<option value="${k}">${E(v)}</option>`).join('')}</select></label><label>本店明确项目<select name="source" required><option value="">请选择</option>${sources('work')}</select></label><label>实际结算比例（万分数；9000即九折）<input name="basis_points" required inputmode="numeric" placeholder="填写公司明确比例，1至10000"></label><label>仅对明确精品套装生效（普通商品留空）<select name="bundle"><option value="">独立项目，未授权套装</option>${d.bundles.map(x=>`<option value="${x.id}">${E(x.name)} · ${E(x.code)}</option>`).join('')}</select></label><button type="button" data-member-scope-remove>移除此范围</button></div>`;
 modal('提出本店会员价格规则',`<form><p>${E(d.reference_notice)}</p><label>本店规则编号<input name="code" required pattern="[A-Za-z0-9_-]+" maxlength="40"></label><label>规则名称<input name="name" required minlength="2"></label><label>集团会期等级原版本<select name="membership_rule" required><option value="">请选择明确等级版本</option>${d.memberships.map(x=>`<option value="${x.id}">${E(x.name)} · ${E(x.code)} · 第${x.rule_version}版</option>`).join('')}</select></label><label>本店等级参考来源（可选）<select name="tier"><option value="">不引用参考主档</option>${d.tiers.map(x=>`<option value="${x.id}">${E(x.name)} · 参考 ${x.discount_basis_points}/10000</option>`).join('')}</select></label><label>本版批准后的状态<select name="enabled" required><option value="">请选择</option><option value="true">启用明确价格</option><option value="false">停用本规则</option></select></label><label>生效日期<input name="starts_on" type="date" value="${day()}" required></label><label>结束日期<input name="ends_on" type="date" required></label><label>公司明确的叠用方式<select name="stack_mode" required><option value="">请选择已核对规则</option>${Object.entries(memberPriceStacks).map(([k,v])=>`<option value="${k}">${E(v)}</option>`).join('')}</select></label><div data-member-price-scopes>${scope()}</div><button type="button" data-member-scope-add>增加明确项目</button><label>本人核对的公司依据<textarea name="reason" required minlength="2"></textarea></label><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">建立待批准版本</button></div></form>`,async form=>{const e=form.elements,tier=d.tiers.find(t=>t.id===Number(e.tier.value));const scopes=[...form.querySelectorAll('[data-member-price-scope]')].map(box=>{const [business_kind,component]=box.querySelector('[name=component]').value.split(':');return {business_kind,component,source_id:Number(box.querySelector('[name=source]').value),basis_points:Number(box.querySelector('[name=basis_points]').value),bundle_rule_id:Number(box.querySelector('[name=bundle]').value)||null};});const r=await api('/api/member-pricing/rules',{method:'POST',body:{request_id,code:e.code.value,name:e.name.value,enabled:e.enabled.value==='true',membership_rule_id:Number(e.membership_rule.value),reference_tier_id:tier?.id||null,reference_tier_version:tier?.version||null,starts_on:e.starts_on.value,ends_on:e.ends_on.value,stack_mode:e.stack_mode.value,scopes,reason:e.reason.value}});closeModal();go('member-pricing/'+r.id);});
 const form=document.querySelector('#modal form');form.addEventListener('change',event=>{if(event.target.name==='component'){const box=event.target.closest('[data-member-price-scope]');box.querySelector('[name=source]').innerHTML='<option value="">请选择</option>'+sources(event.target.value.split(':')[1]);box.querySelector('[name=bundle]').value='';}if(event.target.name==='tier'){const tier=d.tiers.find(t=>t.id===Number(event.target.value));if(tier)form.querySelectorAll('[name=basis_points]').forEach(e=>{if(!e.value)e.value=String(tier.discount_basis_points);});}});form.addEventListener('click',event=>{if(event.target.matches('[data-member-scope-add]')){const box=form.querySelector('[data-member-price-scopes]');if(box.children.length>=200)return;box.insertAdjacentHTML('beforeend',scope());}if(event.target.matches('[data-member-scope-remove]'))event.target.closest('[data-member-price-scope]').remove();});
}
async function memberPriceAction(key){const r=state.memberPriceRule,request_id=requestKey();const fields=[F('reason','本人核对的规则依据或原因','textarea')];if(key!=='cancel')fields.push({...F('evidence_id','本申请本次实际依据','file'),file_category:'evidence'});await formDialog({submit:'提交规则依据',approve:'独立批准本版规则',reject:'退回本版规则',cancel:'取消未生效申请'}[key],fields,{},v=>api(`/api/member-pricing/rules/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.case_version,values:v}}),{caseId:r.case_id});}
async function memberPriceField(caseId,customerId){if(!state.catalog?.capabilities?.member_pricing)return '';const p=new URLSearchParams(caseId?{case_id:caseId}:{customer_id:customerId});const d=await api('/api/member-pricing/candidates?'+p);return `<label>本次明确使用的会员价<select name="member_pricing_rule"><option value="">不使用会员折扣，沿普通价格授权</option>${d.items.map(r=>`<option value="${r.id}" data-version="${r.rule_version}">${E(r.name)} · ${E(r.membership_name)} · ${E(memberPriceStacks[r.stack_mode])}</option>`).join('')}</select></label><p>会员等级、适用项目和叠用方式将在本版价格中冻结。授权前状态变化需重新报价；原责任返修与已购买套餐不重复折扣。</p>`;}
function readMemberPrice(form){if(form.querySelector('[data-member-price-field][data-loading]'))throw new Error('请等当前客户会员价格核对完成，再提交报价');const el=form.querySelector('[name=member_pricing_rule]');return el?.value?{rule_id:Number(el.value),rule_version:Number(el.selectedOptions[0].dataset.version)}:null;}
function memberPriceSummary(value){return value?`<p>原会员价格：${E(value.rule_name)} · 第${value.rule_version}版；会员折让 ${money(value.member_discount_cents)} 元；${E(memberPriceStacks[value.stack_mode])}。</p>`:'';}
document.addEventListener('click',async event=>{const e=event.target.closest('[data-act]');if(!e?.dataset.act.startsWith('member-price-'))return;try{if(e.dataset.act==='member-price-new')await memberPriceNew();if(e.dataset.act==='member-price-action')await memberPriceAction(e.dataset.key);}catch(error){toast(error.message,true);}});
async function bindMemberPriceCustomer(form){const customer=form.querySelector('[name=customer]'),box=form.querySelector('[data-member-price-field]');if(!customer||!box)return;customer.addEventListener('change',async()=>{const selected=customer.value;box.dataset.loading='true';box.innerHTML='<p>正在核对本客户适用会员价格…</p>';try{const html=await memberPriceField(null,Number(selected));if(form.isConnected&&customer.value===selected){box.innerHTML=html;delete box.dataset.loading;}}catch(error){if(customer.value===selected){box.innerHTML='<p>适用会员价尚未核对完成，请重新选择客户。</p>';toast(error.message,true);}}});}

function memberPricePayload(form){const value=readMemberPrice(form);return value?{member_pricing:value}:{};}
