'use strict';
let observationCorrectionsState={};
function clearObservationCorrectionsSession(){observationCorrectionsState={};}
function ocContext(){const key=String(state.user?.id)+':'+state.store;if(observationCorrectionsState.key!==key)observationCorrectionsState={key};return observationCorrectionsState;}
const ocKinds={delivery:'实际交付',odometer:'实际里程',maintenance:'已做保养',first_service:'已做首保',insurance:'保险期限',warranty:'保修期限'};
const ocActions={submit:'提交原件复核',approve:'独立批准本次纠正',reject:'拒绝本次纠正',cancel:'撤回尚未生效申请'};
function ocValues(o){return `<p>实际日期：${E(o.observed_date||'—')}</p><p>实测里程：${o.odometer_km==null?'未取得实际读数':E(number(o.odometer_km))+' 公里'}</p>${o.valid_until?`<p>截止日：${E(o.valid_until)}</p>`:''}<p class="fieldhelp">来源：${E(o.source_reference||'—')}</p>`;}
function ocOpen(route){if(location.hash.slice(1)===route)render();else location.hash=route;}
async function observationCorrectionsPage(section='vehicles',id){
 const ctx=ocContext();section=section||'vehicles';
 if(section==='cases'){
  const r=await api(`/api/observation-corrections/cases/${id}`);ctx.row=r;state.row={id:r.id,files:r.files};
  return heading('日期里程原观察纠正',r.number,b('oc-vehicle','返回本车原观察',`data-id="${r.vehicle_id}"`))+storeNotice()+panel('本次申请',`<p>${pill(r.state,r.state_label)} · ${E(r.plate)}</p><p class="fieldhelp">VIN：${E(r.vin)}</p><p>原观察：${r.observation_id} · ${E(ocKinds[r.original.kind])}</p><p>${E(r.reason)}</p><div class="row">${r.actions.map(a=>b('oc-action',ocActions[a],`data-key="${a}"`)).join('')||'本次无可办理动作，原事实和审批记录保留。'}</div>`)+panel('申请时有效值',ocValues(r.original))+panel(r.operation==='retract'?'本次请求撤销误登记':'本次替代值',r.operation==='retract'?'<p>批准后该原观察不再作为有效基准；原记录不会删除。</p>':ocValues(r.proposed))+panel('目前有效版本',`<p>${r.current.active?'有效':'已失效'} · ${r.current.effect_id?'纠正版本 '+r.current.effect_id:'原登记版本'}</p>${ocValues(r.current)}`)+panel('本次原件',`<p class="fieldhelp">请核对原件并填写复核结果。</p>${canWrite()&&state.user.role!=='auditor'?b('oc-upload','上传本次核对原件'):''}${r.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.security?.label||'等待检查')}</p>${f.security?.can_use?b('download','下载本单原件',`data-id="${f.id}"`):'<p>隔离文件不能用于复核。</p>'}</div></div>`).join('')}`)+panel('独立办理记录',r.events.map(e=>`<article class="card"><p>${E({create:'建立申请',...ocActions}[e.action])} · ${time(e.created_at)}</p><p>${E(e.reason)}</p><p>经办员工编号 ${e.actor_id}${e.evidence_id?' · 原件 '+e.evidence_id:''}</p></article>`).join(''))+(r.invalidated_reminder_ids.length?panel('保留的原提醒',r.invalidated_reminder_ids.map(key=>b('open','查看原提醒 '+key,`data-route="customer-service/${key}"`)).join('')):'');
 }
 const catalog=await api('/api/observation-corrections/catalog');ctx.catalog=catalog;
 if(id)ctx.vehicleId=Number(id);else if(!ctx.vehicleId&&catalog.vehicles.length)ctx.vehicleId=catalog.vehicles[0].id;
 const pick=`<form id="oc-vehicle-select" class="filterbar"><label>本店获权客户车辆<select name="vehicle_id" required><option value="">请选择车辆</option>${catalog.vehicles.map(v=>`<option value="${v.id}" ${v.id===ctx.vehicleId?'selected':''}>${E(v.label)}</option>`).join('')}</select></label><button type="submit" class="primary">查看原观察</button></form>`;
 let html=heading('日期里程原观察纠正','按原资料纠正误登记，保留旧提醒与批准依据。',catalog.can_generate?b('oc-generate','按有效来源检查提醒'):'')+storeNotice()+pick+`<div class="notice">${E(catalog.notice)}</div>`;
 if(!ctx.vehicleId)return html+empty('先选择已确认的客户车辆');
 const value=await api(`/api/observation-corrections/vehicles/${ctx.vehicleId}`);ctx.vehicle=value;
 html+=panel('当前实际里程',`<p>${E(value.vehicle.plate)}</p><p class="fieldhelp">VIN：${E(value.vehicle.vin)}</p><p>${value.vehicle.odometer_km==null?'尚无独立实际里程来源':E(number(value.vehicle.odometer_km))+' 公里 · '+E(value.vehicle.observed_date)}</p><p class="fieldhelp">保险办理带入的历史数值不作为实测里程。</p>`);
 html+=panel('原观察及有效版本',value.observations.map(o=>`<article class="card"><h3>${E(ocKinds[o.kind])} · 原观察 ${o.id}</h3><p>${o.active?'目前有效':'已失效'} · ${o.effect_id?'纠正版本 '+o.effect_id:'原登记版本'}</p>${ocValues(o)}<div class="row">${o.source_type==='insurance_result'?'<p>实际保险业务来源，不能人工改保期或补造里程。</p>'+b('open','核对保险原单',`data-route="insurance-orders/${o.source_case_id}"`):value.can_create?b('oc-new','纠正本条原观察',`data-id="${o.id}"`):''}</div></article>`).join('')||empty('尚无原观察，不能凭空创建纠正'));
 html+=panel('本车纠正申请',value.corrections.map(r=>`<article class="card"><p>${E(r.number)} · ${E(r.state_label)}</p><p>${E(r.reason)}</p>${b('oc-case','查看申请与原件',`data-id="${r.id}"`)}</article>`).join('')||empty('暂无纠正申请'));
 return html;
}
async function ocNew(id){const ctx=ocContext(),v=ctx.vehicle.vehicle,o=ctx.vehicle.observations.find(x=>x.id===id),key=requestKey();
 modal('有据纠正原观察',`<form><p>${E(ocKinds[o.kind])} · 原观察 ${o.id}</p><p class="fieldhelp">${E(v.plate)} · ${E(v.vin)}</p><label>处理方式<select name="operation"><option value="replace">以原件替代误登记数值</option>${o.active?'<option value="retract">撤销误登记，不填替代事实</option>':''}</select></label><div id="oc-replacement"><label>原实际日期<input type="date" name="observed_date" required max="${day()}" value="${E(o.observed_date)}"></label><label>原实际仪表公里数<input type="number" name="odometer_km" required min="0" max="3000000" step="1" value="${o.odometer_km}"></label>${['insurance','warranty'].includes(o.kind)?`<label>原资料正确截止日<input type="date" name="valid_until" required value="${E(o.valid_until)}"></label>`:''}<label>原资料来源编号<input name="source_reference" minlength="3" maxlength="180" required value="${E(o.source_reference)}"></label></div><label>误录原因与核对说明<textarea name="reason" minlength="3" maxlength="1000" required></textarea></label><p class="fieldhelp">不能变更原种类；修改公里数不会生成已做保养。提交后由另一位主管复核。</p><div class="formerror" role="alert"></div><button type="submit" class="primary">建立本次申请</button></form>`,async form=>{
  const f=Object.fromEntries(new FormData(form));const proposed=f.operation==='replace'?{observed_date:f.observed_date,odometer_km:Number(f.odometer_km),valid_until:f.valid_until||null,source_reference:f.source_reference}:null;
  const result=await api('/api/observation-corrections/cases',{method:'POST',body:{request_id:key,vehicle_id:v.id,vehicle_version:v.version,observation_id:o.id,base_digest:o.digest,operation:f.operation,proposed,reason:f.reason}});closeModal();ocOpen('observation-corrections/cases/'+result.case.id);
 });
 $('[name=operation]',$('#modal')).onchange=event=>{const disabled=event.target.value==='retract';$('#oc-replacement').hidden=disabled;$$('input',$('#oc-replacement')).forEach(e=>e.disabled=disabled);};
}
function ocAction(action){const r=ocContext().row,key=requestKey(),files=r.files.filter(f=>!f.generated&&f.security?.can_use);
 modal(ocActions[action],`<form><p>${E(r.number)} · ${E(r.state_label)}</p>${action!=='cancel'?`<label>本单已核对原件<select name="evidence_id" required><option value="">请选择本单原件</option>${files.map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label><p class="fieldhelp">文件上传人和本次复核人分别留痕；批准人不能是申请人。</p>`:''}${action!=='submit'?'<label>本次核对或撤回原因<textarea name="reason" required minlength="3" maxlength="1000"></textarea></label>':''}<div class="formerror" role="alert"></div><button type="submit" class="primary">确认本次办理</button></form>`,async form=>{const f=Object.fromEntries(new FormData(form));if(f.evidence_id)f.evidence_id=Number(f.evidence_id);await api(`/api/observation-corrections/cases/${r.id}/actions/${action}`,{method:'POST',body:{request_id:key,version:r.version,values:f}});closeModal();await render();});
}
function ocUpload(){const r=ocContext().row;modal('上传本次核对原件','<form><label>本次原件文件<input type="file" name="file" required></label><p class="fieldhelp">沿用本店附件隔离与扫描，未通过的文件不能办理复核。</p><div class="formerror" role="alert"></div><button type="submit" class="primary">上传并检查</button></form>',async form=>{const data=new FormData(form);data.append('category','evidence');await api(`/api/flow/cases/${r.id}/files`,{method:'POST',body:data});closeModal();await render();});}
document.addEventListener('submit',event=>{if(event.target.id!=='oc-vehicle-select')return;event.preventDefault();ocOpen('observation-corrections/vehicles/'+new FormData(event.target).get('vehicle_id'));});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-act^="oc-"]');if(!button)return;button.disabled=true;try{switch(button.dataset.act){case 'oc-case':ocOpen('observation-corrections/cases/'+button.dataset.id);break;case 'oc-vehicle':ocOpen('observation-corrections/vehicles/'+button.dataset.id);break;case 'oc-new':await ocNew(Number(button.dataset.id));break;case 'oc-action':ocAction(button.dataset.key);break;case 'oc-upload':ocUpload();break;case 'oc-generate':{const r=await api('/api/observation-corrections/reminders/generate',{method:'POST',body:{request_id:requestKey()}});toast(`本次新增 ${r.created.length} 条有效提醒；未发送客户消息。`);await render();break;}}}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
