'use strict';
const deploymentLabels={timezone:'业务时区',session_hours:'登录有效时长（小时）',inventory_aging_days:'库存库龄提醒（天）',repair_overdue_days:'维修超期提醒（天）',receivable_grace_days:'应收宽限（天）',low_margin_percent:'低毛利提醒（%）',large_cash_yuan:'大额收支提醒（元）',discount_review_percent:'折扣复核提醒（%）',daily_report_hour:'每日日报时刻（小时）',daily_report_minute:'每日日报时刻（分钟）'};
async function parametersPage(){
 const data=await api('/api/parameters/catalog');
 const entries=data.entries.map(item=>panel(item.label,`${b('open','设置',`data-route="${E(item.route)}"`)}`)).join('');
 const deployment=data.deployment?panel('部署参数（只读）',facts(Object.fromEntries(Object.entries(data.deployment).filter(([key])=>Object.hasOwn(deploymentLabels,key)).map(([key,value])=>[deploymentLabels[key],String(value)])))+'<p class="fieldhelp">这些部署级参数由部署负责人在 .env 中维护并重启服务生效。业务规则在上方各自原页面修改，不接受任意键值配置。</p>'):'';
 return heading('参数与个人密码','规则留在原业务中管理，避免重复配置与历史数据被倒改。')+storeNotice()+panel('个人密码',`<p>验证原密码后设置新密码；其他登录会话失效。</p>${b('password','修改本人密码','','primary')}`)+(state.user.can_users?panel('登录图片',`<img class="brand-photo-preview" src="/api/branding/photo" alt="当前登录图片"><div class="row">${b('brand-photo','更换图片')}${b('brand-photo-reset','恢复默认')}</div>`):'')+(data.aggregate_scope?'<p class="notice">请切换到具体门店查看原业务配置入口。</p>':`<div class="chartgrid">${entries}</div>`)+(deployment?'<details class="mux-setting-detail"><summary>部署负责人查看：技术参数</summary>'+deployment+'</details>':'');
}

async function brandPhotoDialog(){modal('更换登录图片',`<form><label>图片<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required></label><p>图片将显示在登录页，请勿上传客户资料。最大8MB。</p><div class="formerror" role="alert"></div><div class="modalfoot">${b('close','取消')}<button type="submit" class="primary">保存</button></div></form>`,async form=>{await api('/api/branding/photo',{method:'POST',body:new FormData(form)});closeModal();await render();toast('图片已更换');});}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!['brand-photo','brand-photo-reset'].includes(a))return;try{if(a==='brand-photo')await brandPhotoDialog();else{await api('/api/branding/photo',{method:'DELETE'});await render();toast('已恢复默认图片');}}catch(err){toast(err.message,true);}});
