'use strict';
const procurementNames={approve:'批准采购',reject:'退回采购',cancel:'取消未执行采购',receive:'分批验收到货',pay:'登记实际付款',close_receiving:'终止剩余到货',return_request:'申请退货',return_approve:'批准退货',return_cancel:'撤销未发出退货',return_dispatch:'确认退货实物发出',refund:'登记供应商实际退款'};
Object.assign(procurementNames,{prepay_request:'申请预付款',prepay_approve:'独立批准预付款',prepay_reject:'拒绝预付款',prepay_cancel:'取消未付余量',prepay_expire:'结束过期申请',prepay_pay:'登记实际预付款'});
function purchaseScaled(value,digits){const s=String(value).trim();if(!new RegExp('^\\d+(\\.\\d{1,'+digits+'})?$').test(s))throw new Error('请核对数值格式：金额最多两位小数，数量最多三位。');const [a,b='']=s.split('.');const n=Number(a)*10**digits+Number(b.padEnd(digits,'0'));if(!Number.isSafeInteger(n)||n<0)throw new Error('数值超出范围。');return n;}
const purchaseQty=n=>number(n/1000);
const purchaseStatus=row=>pill(row.state,row.state==='receiving'&&row.receiving_closed?'待结算／退货':'');
function procurementRefundOptions(row){
 return row.payments.filter(p=>p.direction==='out'&&(!row.prepayments||row.prepayments.original_cash.some(c=>c.payment_id===p.id&&c.available_cents>0))).map(p=>{
  const available=row.prepayments?row.prepayments.original_cash.find(c=>c.payment_id===p.id)?.available_cents:p.amount_cents-row.payments.filter(r=>r.direction==='in'&&r.original_id===p.id).reduce((sum,r)=>sum+r.amount_cents,0);
  const parts=[p.business_date,p.reference?'凭证 '+p.reference:'',p.account_name,'原付 '+money(p.amount_cents)+' 元',Number.isSafeInteger(available)?'本笔剩余 '+money(Math.max(0,available))+' 元':'','付款 '+p.id];
  return {value:String(p.id),label:parts.filter(Boolean).join(' · ')};
 });
}
async function procurementAll(path){let items=[],page=1;for(;;){const d=await api(path+(path.includes('?')?'&':'?')+'page='+page);items.push(...d.items);if(items.length>=d.total)return items;if(++page>100)throw new Error('主档数量超过本版选择上限，请缩小主档范围。');}}
async function procurementPage(id){
 if(!id){const d=await api('/api/procurement/orders?page='+state.page);return heading('采购与供应商结算','申请不增加库存；到货、退货和资金分别由实际经办岗位确认。',canWrite()&&['admin','manager','inventory'].includes(state.user.role)?b('procurement-new','申请多行采购','','primary'):'')+storeNotice()+panel('采购业务',table(['单号／供应商','状态','当前应付（元）','供应商应退（元）',''],d.items.map(r=>[`${E(r.number)}<br>${E(r.supplier_name)}`,purchaseStatus(r),money(r.totals?.payable_cents),money(r.totals?.supplier_refund_due_cents),b('open','办理',`data-route="procurement/${r.id}"`)])))+pager(d.total)+(full()?panel('供应商结算',b('procurement-export','导出当前对账CSV')+'<p>应付只来自实际验收到货，扣除退货与已付净额；供应商应退单列，不与其他供应商抵销。</p>'):'');}
 const row=await api('/api/procurement/orders/'+id);state.procurement=row;state.row=await api('/api/flow/cases/'+id);
 const can=key=>canWrite()&&row.actions.includes(key),button=(key,extra='')=>b('procurement-action',procurementNames[key],`data-key="${key}" ${extra}`);
 let buttons=[];if(row.state==='approval'){for(const k of ['approve','reject','cancel'])if(can(k))buttons.push(button(k));}
 if(['receiving','completed'].includes(row.state)){if(!row.receiving_closed)for(const k of ['receive','close_receiving'])if(can(k))buttons.push(button(k));if(row.receipts.some(r=>r.returnable_milli>0)&&can('return_request'))buttons.push(button('return_request'));if(row.totals?.payable_cents&&can('pay'))buttons.push(button('pay'));if(row.totals?.supplier_refund_due_cents&&can('refund'))buttons.push(button('refund'));if(!row.receipts.length&&can('cancel'))buttons.push(button('cancel'));}
 if(['receiving','completed'].includes(row.state)&&row.flow_version===3&&!row.receiving_closed&&can('prepay_request')&&(row.prepayments||!row.payments.length))buttons.push(button('prepay_request'));
 let html=heading(row.supplier_name+' · 采购办理',row.number,b('open','返回采购','data-route="procurement"'))+storeNotice()+`<div class="row">${purchaseStatus(row)}<span>${row.receiving_closed?'到货已关闭':row.state==='approval'?'审批后安排到货':['cancelled','rejected'].includes(row.state)?'本申请已结束':'等待分批到货'}</span></div>`;
 if(row.totals){const t=row.totals;html+=`<div class="kpis"><div class="kpi"><div class="label">实际验收（元）</div><div class="value">${money(t.received_cents)}</div></div><div class="kpi"><div class="label">实际退货（元）</div><div class="value">${money(t.returned_cents)}</div></div><div class="kpi"><div class="label">当前应付（元）</div><div class="value">${money(t.payable_cents)}</div></div><div class="kpi"><div class="label">供应商应退（元）</div><div class="value">${money(t.supplier_refund_due_cents)}</div></div></div>`;}
 html+=panel('本次可以办理',buttons.length?`<div class="row">${buttons.join('')}</div>`:'<p>当前岗位没有本步骤的操作。待办显示下一接手员工。</p>');
 if(row.prepayments){
  html+=panel('原采购预付款',`<p>有效采购约定 ${money(row.totals.commitment_cents)} 元；有效预付 ${money(row.totals.prepaid_cents)} 元；已抵到货 ${money(row.totals.applied_cents)} 元；未付申请占额 ${money(row.totals.prepayment_reserved_cents)} 元。</p><p>申请与独立批准不会发起银行付款。终止未到余量或实际退货后，才按原付款未抵用额度登记供应商实际退款。</p>`+table(['申请','申请/实际已付（元）','有效期','状态','操作'],row.prepayments.requests.map(r=>{const acts=[];if(r.status==='pending'&&!r.expired)for(const key of ['prepay_approve','prepay_reject'])if(can(key)&&r.requested_by!==state.user.id)acts.push(button(key,`data-id="${r.id}"`));if(r.status==='approved'&&!r.expired&&can('prepay_pay'))acts.push(button('prepay_pay',`data-id="${r.id}"`));if(['pending','approved'].includes(r.status)){const key=r.expired?'prepay_expire':'prepay_cancel';if(can(key))acts.push(button(key,`data-id="${r.id}"`));}return[r.id,`${money(r.amount_cents)} / ${money(r.paid_cents)}`,E(r.valid_until),E({pending:'待独立复核',approved:'待实际付款',paid:'批准额度已付',rejected:'已拒绝',cancelled:'未付余量已取消',expired:'已结束过期申请'}[r.status]),acts.join('')||'—'];})));
  html+=panel('原款与到货抵用',table(['原付款','到货批次','抵用/冲回（元）','原关联'],row.prepayments.allocations.map(a=>[a.payment_id,a.receipt_id,money(a.amount_cents),a.original_id?'冲回原抵用 '+a.original_id:'原付款抵用']))+table(['原付款','尚未抵用及退回（元）'],row.prepayments.original_cash.map(p=>[p.payment_id,money(p.available_cents)])));
 }
 html+=panel('已确认采购明细',table(['物资','约定数量','累计验收','单价（元）','约定金额（元）'],row.lines.map(l=>[`${E(l.sku)} · ${E(l.item_name)}<br>${E(l.unit)}`,purchaseQty(l.quantity_milli),purchaseQty(l.received_milli),money(l.unit_cost_cents),money(l.amount_cents)])));
 html+=panel('实际到货批次',table(['批次','物资','本批验收','尚未退回','批次价值（元）'],row.receipts.map(r=>[r.id,E(row.lines.find(l=>l.id===r.line_id)?.item_name),purchaseQty(r.quantity_milli),purchaseQty(r.returnable_milli),money(r.value_cents)])));
 html+=panel('退货申请与实物交接',table(['退货申请','原因','状态','明细','办理'],row.returns.map(r=>{let acts=[];if(r.status==='requested'&&can('return_approve'))acts.push(button('return_approve',`data-id="${r.id}"`));if(['requested','approved'].includes(r.status)&&can('return_cancel'))acts.push(button('return_cancel',`data-id="${r.id}"`));if(r.status==='approved'&&can('return_dispatch'))acts.push(button('return_dispatch',`data-id="${r.id}"`));return[r.id,E(r.reason),E({requested:'待主管复核',approved:'待实物发出',dispatched:'实物已发出',cancelled:'已撤销'}[r.status]),r.lines.map(l=>`批次${E(l.receipt_id)}：${purchaseQty(l.quantity_milli)}`).join('<br>'),`<div class="row">${acts.join('')||'—'}</div>`];})));
 if(row.totals)html+=panel('实际付款与退款',table(['原款关联','类型','金额（元）','凭证号'],row.payments.map(p=>[p.original_id?'原付款 '+p.original_id:'付款 '+p.id,p.direction==='out'?'付款':'供应商退款',money(p.amount_cents),E(p.reference)])))+panel('分批到货应付期限',table(['批次','到期日','未付金额（元）'],row.totals.due_rows.map(r=>[r.receipt_id,E(r.due_date),money(r.amount_cents)])));
 if(row.return_costs?.length)html+=panel('原单冲款与库存成本', '<p>供应商按原采购批次冲款；库存按实际退货时的本店均价扣减。差额＝原单冲款－库存成本，单独核对，不是额外现金收支。</p>'+table(['原退货','原验收批次','数量','供应商冲款（元）','库存扣减（元）','退货差额（元）'],row.return_costs.map(r=>[r.id,r.receipt_id,purchaseQty(r.quantity_milli),money(r.supplier_credit_cents),money(r.inventory_cost_cents),money(r.variance_cents)])));
 html+=panel('本单文件',canWrite()?b('upload','上传验收、退货或资金凭据'):'');
 html+=panel('已有凭据',state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.label)} · ${E(f.security?.label||'等待检查')}</p><div class="row">${b('filescaninfo','检查记录',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'检查通过后可使用'}</div></div></div>`).join('')||'<p>请上传本单实际凭据。</p>');
 html+=panel('岗位交接',table(['待办','接手员工','状态'],state.row.tasks.map(t=>[E(t.title),E(t.assignee_name),pill(t.status)])));
 return html;
}
async function procurementNew(){
 const [suppliers,items]=await Promise.all([procurementAll('/api/masters/suppliers?active=true'),procurementAll('/api/flow/master/items?page_size=100')]);
 const active=items.filter(i=>i.active);if(!suppliers.length||!active.length)throw new Error('请先配置启用的供应商主档和物资。');
 const options=active.map(i=>`<option value="${i.id}">${E(i.sku)} · ${E(i.name)}（${E(i.unit)}）</option>`).join('');state.purchaseItemOptions=options;
 const row=()=>`<div class="panelbody" data-purchase-line><label>物资<select name="item" required data-search-select>${options}</select></label><div class="formgrid"><label>约定数量<input name="quantity" inputmode="decimal" required placeholder="最多三位小数"></label><label>单价（元）<input name="cost" inputmode="decimal" required placeholder="最多两位小数"></label></div>${b('procurement-remove-line','删除这一行')}</div>`;
 const request_id=requestKey();modal('申请多行采购',`<form><label>供应商<select name="supplier" required data-search-select>${suppliers.map(s=>`<option value="${s.id}">${E(s.code)} · ${E(s.name)}</option>`).join('')}</select></label><label>采购原因<textarea name="reason" required minlength="2" maxlength="500"></textarea></label><div id="purchase-lines">${row()}</div>${b('procurement-add-line','增加物资行')}<div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">提交主管复核</button></div></form>`,async form=>{
  const lines=[...form.querySelectorAll('[data-purchase-line]')].map(el=>({item_id:Number(el.querySelector('[name=item]').value),quantity_milli:purchaseScaled(el.querySelector('[name=quantity]').value,3),unit_cost_cents:purchaseScaled(el.querySelector('[name=cost]').value,2)}));
  const result=await api('/api/procurement/orders',{method:'POST',body:{request_id,supplier_id:Number(form.elements.supplier.value),reason:form.elements.reason.value,lines}});closeModal();go('procurement/'+result.id);
 });state.purchaseLineHtml=row();
}
async function procurementAction(key,returnId){
 const row=state.procurement,request_id=requestKey(),send=values=>api(`/api/procurement/orders/${row.id}/actions/${key}`,{method:'POST',body:{request_id,version:row.version,values}});
 if(key.startsWith('prepay_')){
  const fields=[],initial={},extra={};const request=row.prepayments?.requests.find(r=>r.id===returnId);
  if(request)Object.assign(extra,{funds_request_id:request.id,funds_version:request.version});
  if(key==='prepay_request')fields.push(F('amount','申请金额（元）','money'),F('valid_until','付款申请有效至','date'));
  if(key!=='prepay_pay')fields.push(F('reason','本次依据或原因','textarea'));
  if(['prepay_request','prepay_approve','prepay_reject','prepay_pay'].includes(key))fields.push(F('evidence_id',key==='prepay_pay'?'本单实际收付款凭据':'本单真实合同或财务凭据','file'));
  if(key==='prepay_pay'){
   fields.push(F('amount','本次实际付款（元）','money'),F('account_id','实际付款账户','account'),F('reference','银行流水号或现金凭证号'),F('confirmed','本人已核对实际付款及原始凭据','bool'));
   initial.amount=money(request.unpaid_cents).replaceAll(',','');initial.confirmed=false;
  }
  await formDialog(procurementNames[key],fields,initial,v=>{const values={...v,...extra};if(v.amount!==undefined){values.amount_cents=purchaseScaled(v.amount,2);delete values.amount;}return send(values);},{caseId:row.id,notice:'按原采购办理，申请人不能自批；系统仅登记真实业务事实，不发起银行转账。有效期后须明确结束原未付余量。'});return;
 }
 if(['receive','return_request'].includes(key)){
  const options=(key==='receive'?row.lines.filter(l=>l.quantity_milli>l.received_milli).map(l=>({id:l.id,item_id:l.item_id,label:l.item_name,max:l.quantity_milli-l.received_milli})):row.receipts.filter(r=>r.returnable_milli>0).map(r=>({id:r.id,label:'到货批次 '+r.id+' · '+row.lines.find(l=>l.id===r.line_id)?.item_name,max:r.returnable_milli})));
  const files=state.row.files.filter(f=>!f.generated&&f.security?.can_use);let warehouse;
  const dialog=modal(procurementNames[key],`<form><p>仅填写本次实际办理的行，留空表示本次不办理。${key==='return_request'?'申请后由主管复核，再由库管确认实物发出。':''}</p>${options.map(o=>`<label>${E(o.label)} · 最多 ${purchaseQty(o.max)}<input name="quantity_${o.id}" inputmode="decimal" placeholder="本次数量"></label>`).join('')}<label>本单凭据</label>${caseFilePickerHTML('evidence',row.id,files)}${key==='return_request'?'<label>退货原因<textarea name="reason" required minlength="2" maxlength="500"></textarea></label>':''}<div class="formerror" role="alert"></div><div class="modalfoot">${b('close','取消')}<button type="submit" class="primary">确认本次办理</button></div></form>`,async form=>{
   if(warehouse)await warehouse.assertReady();
   const lines=options.filter(o=>form.elements['quantity_'+o.id].value.trim()).map(o=>({[key==='receive'?'line_id':'receipt_id']:o.id,quantity_milli:purchaseScaled(form.elements['quantity_'+o.id].value,3)}));
   await send({lines,evidence_id:Number(form.elements.evidence.value),...(key==='return_request'?{reason:form.elements.reason.value}:{})});closeModal();await render();
  });if(key==='receive')warehouse=mountWarehousePreparation(dialog.querySelector('form'),{caseId:row.id,purpose:'procurement_receipt',source:row,getVersion:()=>row.version,setVersion:v=>{row.version=v;},readSource:()=>api('/api/procurement/orders/'+row.id),getLines:form=>options.filter(o=>form.elements['quantity_'+o.id].value.trim()).map(o=>({item_id:o.item_id,label:o.label,quantity_milli:purchaseScaled(form.elements['quantity_'+o.id].value,3)}))});return;
 }
 const fields=[],initial={},extra={};if(['reject','cancel','close_receiving','return_approve','return_cancel'].includes(key))fields.push(F('reason','办理原因','textarea'));
 if(key.startsWith('return_')){const r=row.returns.find(r=>r.id===returnId);Object.assign(extra,{return_id:r.id,return_version:r.version});}
 if(['pay','refund'].includes(key)){fields.push(F('amount','本次实际金额（元）','money'),F('account_id','实际资金账户','account'),F('reference','银行流水号或凭证号'));initial.amount=money(key==='pay'?row.totals.payable_cents:row.totals.supplier_refund_due_cents).replaceAll(',','');}
 if(key==='refund')fields.push({...F('original_payment_id','退回哪笔付款','select',true,procurementRefundOptions(row)),searchable:true});
 if(['pay','refund','return_dispatch'].includes(key))fields.push(F('evidence_id','本单实际凭据','file'));
 await formDialog(procurementNames[key],fields,initial,v=>{const values={...v,...extra};if(v.amount!==undefined){values.amount_cents=purchaseScaled(v.amount,2);delete values.amount;}if(v.original_payment_id)values.original_payment_id=Number(v.original_payment_id);return send(values);},{caseId:row.id,notice:['pay','refund'].includes(key)?'请核对真实到账凭据；系统不会自动发起银行转账。':key==='return_dispatch'?'仅在原批次实物已经发出并有交接凭据时确认。新单按原采购额冲减应付，按实际库存均价扣减库存，差额单独留账。':'确认后保留经办人与原始申请，不覆盖历史。'});
}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el?.dataset.act.startsWith('procurement-'))return;try{const act=el.dataset.act;if(act==='procurement-new')await procurementNew();else if(act==='procurement-action')await procurementAction(el.dataset.key,Number(el.dataset.id));else if(act==='procurement-add-line'){$('#purchase-lines').insertAdjacentHTML('beforeend',state.purchaseLineHtml);}else if(act==='procurement-remove-line'){if(document.querySelectorAll('[data-purchase-line]').length<=1)throw new Error('采购至少需要一行物资。');el.closest('[data-purchase-line]').remove();}else if(act==='procurement-export'){const blob=await api('/api/procurement/payables/export',{raw:true});const url=URL.createObjectURL(await blob.blob());const a=document.createElement('a');a.href=url;a.download='huakangos-供应商对账.csv';a.click();URL.revokeObjectURL(url);}}catch(error){toast(error.message,true);}});
