'use strict';
const reconciliationSources={transfer_goods_searches:'实际原退运查找',transfer_goods_search_reviews:'原查找独立复核',transfer_goods_search_outcomes:'原查找结束结果',transfer_goods_reappearances:'再次找到的原查找关联',cash_entries:'实际现金',flow_payment_links:'原单收款关联',flow_stock_moves:'物资库存账',flow_member_entries:'旧门店会员账',group_entries:'集团本金账',benefit_entries:'集团权益单位账',procurement_payments:'采购付款',procurement_receipts:'采购到货',procurement_return_postings:'采购退货',group_settlement_entries:'集团本金内部往来',benefit_settlements:'集团权益内部往来',material_transfer_settlements:'物资调拨往来',vehicle_transfer_settlements:'整车调拨往来',interstore_clearing_cash:'实际店间现金',interstore_clearing_offsets:'店间往来核销',receivable:'当前未收款'};
Object.assign(reconciliationSources,{vehicle_purchase_payments:'整车采购付款',vehicle_purchase_receipts:'整车采购到货',vehicle_purchase_movements:'整车采购出入库',retail_payments:'精品收退款关联',retail_dispatches:'精品实际出库',retail_return_postings:'精品实际退货'});
Object.assign(reconciliationSources,{group_reservations:'当前本金消费占额',group_refund_requests:'当前本金退款申请',benefit_reservations:'当前权益消费占额',benefit_refunds:'当前权益退款申请'});
Object.assign(reconciliationSources,{invoice_results:'实际外部发票',warehouse_entries:'库位配对流水',warehouse_balances:'当前库位及在途',membership_fees:'会员续会实际收退费',membership_points_changes:'消费积分目标变动',membership_points_debt_payments:'积分待追回抵补',membership_points_claims:'当前原业务积分依据',invoice_corrections:'当前原业务待冲红差额',membership_points_debts:'当前尚待追回积分'});
Object.assign(reconciliationSources,{transfer_loss_postings:'运输损失原库存成本',transfer_loss_settlements:'运输损失店间承担往来',transfer_recovery_claims:'运输损失追偿来源',transfer_recovery_plans:'追偿目标版本',transfer_recovery_reviews:'追偿独立确认',transfer_recovery_cancellations:'未生效追偿方案撤回',transfer_recovery_payments:'追偿实际收退关联'});
Object.assign(reconciliationSources,{transfer_goods_facts:'找回实物观察（不是库存入账）',transfer_goods_postings:'找回原成本实际恢复',transfer_goods_reviews:'找回独立复核',transfer_goods_settlements:'找回反向店间往来',transfer_goods_terms:'找回后的原追偿约定',transfer_goods_refunds:'找回后的原款退回关联（不重复计现金）'});
Object.assign(reconciliationSources,{retail_group_scopes:'本店已批准商品适用范围',retail_group_plans:'精品原付款授权',retail_group_tenders:'原付款批次 C/P/S',retail_group_units:'原可恢复单位 C/P/S',retail_group_allocations:'原商品/安装份额 C/P/S',retail_group_reservations:'原集团占额关联',retail_group_captures:'原集团实际核销关联',retail_group_closures:'未核销原份额释放',retail_group_returns:'实际原退货关联',retail_group_return_parts:'原退对价及待恢复份额',retail_group_restores:'原本金/权益恢复关联',retail_group_settlements:'原退负债与恢复抵消（非现金）',retail_group_cash_allocations:'实际原款分摊（不重复计现金）'});
Object.assign(reconciliationSources,{"vehicle_transport_exceptions": "原整车运输差异", "vehicle_transport_observations": "原VIN实际观察", "vehicle_transport_plans": "原损失及找回方案", "vehicle_transport_reviews": "两店独立复核", "vehicle_transport_withdrawals": "原方案撤回", "vehicle_transport_disposals": "在手原车实际处置", "vehicle_transport_found_unavailable": "找回后实际无法接收", "vehicle_transport_losses": "原车原成本损失", "vehicle_transport_loss_settlements": "原车损失承担往来", "vehicle_transport_found_receipts": "原车实际找回入库", "vehicle_transport_found_settlements": "原车找回净往来", "vehicle_transport_claims": "本店原车外部追偿", "vehicle_transport_claim_plans": "原车赔付目标版本", "vehicle_transport_claim_reviews": "原赔付独立复核", "vehicle_transport_claim_withdrawals": "原赔付方案撤回", "vehicle_transport_claim_payments": "原赔付实际收退关联"});
const reconcileLabels={issue:'记录本条差异',resolve:'记录差异处理结果',submit:'提交独立店长复核',seal:'复核封存',recalculate:'重算为新版本',reopen:'注明原因并复开',pay:'确认本店实际付款',receive:'确认本店实际到账',difference:'记录未到账或其他差异',cancel:'撤销未付款申请',reject:'拒绝未付款申请'};
const reconcileFinance=()=>canWrite()&&['admin','finance'].includes(state.user.role);
const reconcileManager=()=>canWrite()&&['admin','manager'].includes(state.user.role);
async function reconciliationPage(id){
 if(state.store==='all')return heading('业务对账与月结')+storeNotice();
 if(!id){const d=await api('/api/reconciliation/batches');return heading('业务对账与月结','冻结来源、核对差异、独立复核；月结清单不代替实际收款。',(reconcileFinance()?b('reconcile-new','新建期间对账','','primary'):'')+b('open','店间实际清算','data-route="clearing"'))+table(['期间／版本','状态','操作'],d.items.map(r=>[`${r.start} 至 ${r.end} · 版本${r.revision}`,E({draft:'财务对账中',review:'待店长封存',sealed:'已封存',superseded:'已有重算版本'}[r.status]),b('open','查看来源与差异',`data-route="reconciliation/${r.id}"`)]));}
 const r=await api('/api/reconciliation/batches/'+id);state.reconciliation=r;
 const buttons=[];if(reconcileFinance()&&!r.successor_id&&['draft','review'].includes(r.status)){buttons.push(b('reconcile-action','重算新版本','data-key="recalculate"'));if(r.status==='draft')buttons.push(b('reconcile-action','提交独立复核','data-key="submit"','primary'));}
 if(reconcileManager()&&!r.successor_id&&r.status==='review')buttons.push(b('reconcile-action','独立复核封存','data-key="seal"','primary'));
 if(reconcileManager()&&!r.successor_id&&r.status==='sealed')buttons.push(b('reconcile-action','复开新版本','data-key="reopen"'));
 let html=heading('业务对账与月结',`${r.start} 至 ${r.end} · 版本${r.revision} · ${r.status_label}`,buttons.join('')+b('open','本批凭据与待办',`data-route="case/${r.case_id}"`));
 if(r.definition_version>=9)html+='<div class="notice">自第 9 版起区分实物观察、实际恢复原成本、反向店间往来及原款退回关联。观察数量不等于入库量，往来及退款关联不再次计入现金。</div>';
 if(r.definition_version>=10)html+='<div class="notice">自第 10 版起保留精品原批次与逐件付款分摊。C 为抵扣面额、P 为原发行对价、S 为内部结算；原关联按生成时点冻结，实际现金仍只取原现金账。不同来源表的金额不能相加。</div>';
 if(r.definition_version>=11)html+='<div class="notice">自第 11 版起保留本店原退运查找、独立复核、实际结束结果及再次找到关联。它们采用生成时点口径，不增加第二笔损失、库存或现金。</div>';
 if(r.definition_version>=12)html+='<div class="notice">自第12版起保留本店原整车差异、双方独立复核、原损失、实际找回、原赔付与原款关联。实车观察不等于入库，目标不等于现金；各来源表不得合并相加。</div>';
 if(r.definition_version===1)html+='<div class="notice">本批次沿用历史核对范围，不含新增的库位、续会及专用发票明细。需要扩展核对时，请保留原版并重算或复开新版本。</div>';
 if(r.source_changed)html+='<div class="notice">原来源已有晚到、冲正或当前未收款变化。历史快照保持原样；提交或封存前须重算。已封存版本可由店长复开。</div>';
 if(r.successor_id)html+=panel('后继版本',b('open','打开最新后继',`data-route="reconciliation/${r.successor_id}"`));
 html+=panel('核对要点',`<p>期间真实收入 ${money(r.summary.period_cash_in_cents)} 元，期间真实支出 ${money(r.summary.period_cash_out_cents)} 元。当前未收款 ${money(r.summary.current_receivable_cents)} 元。</p><p>本金、权益、库存和往来各自核对，不能与现金直接相加。处理差异须先在原业务完成必要纠正，再重算本期来源；备注不会替代真实账务。</p>${b('reconcile-action','下载本版本完整来源 CSV','data-key="export"')}`);
 if(r.definition_version>=10)html+=panel('原单位待恢复负债（冻结时点）',table(['原单／原单位','种类／原有效期','C 面额 / P 对价 / S 结算（元）','可办理状态'],(r.summary.retail_group_pending_original_units||[]).map(x=>[b('open','查看原精品单',`data-route="retail/${x.case_id}"`)+` · 原单位${x.unit_id}`,E({principal:'本金',bonus:'赠金',coupon:'券',package:'套餐'}[x.kind]||x.kind)+` · ${E(x.original_expires_on||'不适用')}`,`${money(x.credit_cents)} / ${money(x.consideration_cents)} / ${money(x.settlement_cents)}`,x.restorable?'已具备原路恢复条件；恢复后仍用原有效期':'待后续实际退回凑齐原单位；当前不可消费、无需重复催办'])));
 html+=panel('逐项差异',table(['原条目／差异','依据与处理','操作'],r.issues.map(i=>[`${E(reconciliationSources[i.line_key.split(':')[0]]||'来源')} #${E(i.line_key.split(':')[1])}<br>${money(i.difference_cents)} 元`,`${E(i.reason)}<br>${i.status==='resolved'?E(i.resolution):'待核对处理'}`,i.status==='open'&&reconcileFinance()&&r.status==='draft'?b('reconcile-action','记录处理凭据',`data-key="resolve" data-id="${i.id}"`):E(i.status==='resolved'?'已记录处理结果':'待处理')])));
 const sources=r.manifest.slice(0,200);
 html+=panel('冻结来源条目',table(['来源／原条目','金额与事实','核对'],sources.map(x=>{const d=x.data;const amount=d.amount_cents??d.value_cents;return [`${E(reconciliationSources[x.source]||x.source)}<br><span class="muted">#${E(x.source_id)} · ${x.basis==='period'?'所选期间':'生成时点'}</span>`,Array.isArray(d.values)?E(d.values.join(' · ')):`${amount!==undefined?money(amount)+' 元':''}${d.quantity_milli!==undefined?' · 数量 '+(d.quantity_milli/1000):''}${d.units!==undefined?' · 原单位 '+d.units:''}${d.credit_cents!==undefined?' · C '+money(d.credit_cents)+' / P '+money(d.consideration_cents)+' / S '+money(d.settlement_cents)+' 元':''}<br>${E(d.reference||d.voucher_no||({transfer_in:'跨店调入',transfer_out:'跨店调出',purchase_in:'采购入库'}[d.purpose]||d.purpose)||d.side||d.status||'')}`,`<div class="stack">${x.case_id?b('open','查看原单',`data-route="case/${x.case_id}"`):''}${reconcileFinance()&&r.status==='draft'&&!r.successor_id?b('reconcile-action','记录差异',`data-key="issue" data-line="${E(x.key)}"`):''}</div>`];})));
 if(r.manifest.length>200)html+='<p class="muted">页面显示前200条，完整冻结条目请下载CSV。</p>';return html;
}
async function reconciliationCreate(){
 const now=new Date(),day=now.toLocaleDateString('en-CA'),start=day.slice(0,7)+'-01',request_id=requestKey();
 await formDialog('新建业务期间对账',[F('start','期间开始','date'),F('end','期间结束','date'),F('reason','核对范围与依据','textarea')],{start,end:day},async v=>{const r=await api('/api/reconciliation/batches',{method:'POST',body:{request_id,...v}});go('reconciliation/'+r.id);},{notice:'冻结已记录的期间现金、库存、会员及往来，并列出当前应收；不生成实际收款。'});

}
async function reconciliationAction(key,id,lineKey){
 const r=state.reconciliation;if(key==='export')return download('/api/reconciliation/batches/'+r.id+'/export','huakangos-业务对账.csv');const fields=[];if(key==='issue')fields.push(F('difference','待核对差额（元，正负或0）','text'));
 if(['issue','resolve','seal'].includes(key))fields.push(F('evidence_id','本批核对／处理凭据','file'));
 fields.push(F('reason',key==='resolve'?'实际核对及处理结果':'办理依据与原因','textarea'));
 const request_id=requestKey();await formDialog(reconcileLabels[key],fields,{},async v=>{
  const values={reason:v.reason};if(v.evidence_id)values.evidence_id=v.evidence_id;
  if(key==='issue'){const s=String(v.difference).trim(),negative=s.startsWith('-');values.difference_cents=s==='0'?0:(negative?-1:1)*groupFen(negative?s.slice(1):s);values.line_key=lineKey;}
  if(key==='resolve'){const issue=r.issues.find(x=>x.id===id);values.issue_id=id;values.issue_version=issue.version;}
  const result=await api(`/api/reconciliation/batches/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,case_version:r.case_version,values}});if(result.id!==r.id)go('reconciliation/'+result.id);
 },{caseId:r.case_id,notice:key==='seal'?'封存前系统再次比较来源；必须由另一位店长或管理员独立核对。':'本次只记录自身核对事实。需要改账时请沿原业务办理；重算会新增版本，历史保持可查。'});

}
async function clearingPage(id){
 if(state.store==='all')return heading('店间实际清算')+storeNotice();
 if(!id){const [d,o]=await Promise.all([api('/api/reconciliation/clearing'),api('/api/reconciliation/origins')]);state.clearingOrigins=o.items;return heading('店间实际清算','按原条目分别确认本店实际支付与对方实际到账。',b('open','业务月结','data-route="reconciliation"'))+panel('本店未清调拨应付',table(['原条目／对方店','未占用／已占用／已结清','办理'],o.items.map(r=>[`${{material:'物资验收',material_loss:'物资运输损失',material_found:'原物资找回反向往来',vehicle:'整车',vehicle_loss:'原整车运输损失承担',vehicle_found:'原整车找回净往来'}[r.origin_kind]||'待核对来源'} ${r.origin_id} · ${E(r.counterparty_store_name)}`,`${money(r.available_cents)} / ${money(r.reserved_cents)} / ${money(r.settled_cents)} 元`,r.active_vehicle_exception_id?b('open','原车找回审批中，新增清算暂停',`data-route="vehicle-transport-exceptions/${r.active_vehicle_exception_id}"`):r.active_goods_recovery_id?b('open','找回处理中，新增清算暂停',`data-route="transfer-goods-recoveries/${r.active_goods_recovery_id}"`):r.available_cents>0&&reconcileFinance()?b('clearing-new','申请本次清算',`data-kind="${r.origin_kind}" data-id="${r.origin_id}"`):'—'])))+panel('双边清算进度',table(['清算号／角色','金额／状态','操作'],d.items.map(r=>[`${r.id} · ${r.side==='payer'?'本店付款':'本店收款'}`,`${money(r.amount_cents)} 元 · ${E(r.status_label)}`,b('open','核对与办理',`data-route="clearing/${r.id}"`)])));}
 const r=await api('/api/reconciliation/clearing/'+id);state.clearing=r;let buttons='';
 if(reconcileFinance()){if(r.status==='requested')buttons+=r.side==='payer'?((r.active_goods_recovery_id||r.active_vehicle_exception_id)?'':b('clearing-action','实际付款','data-key="pay"','primary'))+b('clearing-action','撤销未付款申请','data-key="cancel"'):b('clearing-action','拒绝未付款申请','data-key="reject"');if(r.status==='paid'&&r.side==='receiver')buttons+=b('clearing-action','实际到账确认','data-key="receive"','primary');if(['requested','paid'].includes(r.status))buttons+=b('clearing-action','记录差异','data-key="difference"');}
 return heading('店间实际清算',`清算${r.id} · ${money(r.amount_cents)}元 · ${r.status_label}`,buttons+b('open','本店凭据与待办',`data-route="case/${r.case_id}"`))+panel('双方办理',`${r.active_vehicle_exception_id?`<div class="notice">原车找回方案在办，新增付款暂停；原已付款的真实到账确认、未付款撤销仍可办理。${b('open','原车找回处理',`data-route="vehicle-transport-exceptions/${r.active_vehicle_exception_id}"`)}</div>`:''}${r.active_goods_recovery_id?`<div class="notice">原物资找回在办，新增付款暂停；已经实际付款的到账确认及未付款撤销仍可办理。${b('open','找回处理',`data-route="transfer-goods-recoveries/${r.active_goods_recovery_id}"`)}</div>`:''}<p>${E(r.payer_store_name)} → ${E(r.receiver_store_name)}。本次固定 ${money(r.amount_cents)} 元，约定日期 ${r.due_date}。</p><p>${E(r.reason)}</p>${r.goods_recovery_id?`<p>本次为找到原物资后的独立反向清算，原损失往来与原现金保持可查。</p>${b('open','找回原来源',`data-route="transfer-goods-recoveries/${r.goods_recovery_id}"`)}`:''}<p>每店只确认自己的真实现金。付款后尚未到账保持内部在途，不提前核销原往来；记录差异不会把未收到的钱变为已收。</p>`)+panel('本店实际现金',table(['方向','金额','流水号'],r.cash.map(c=>[c.direction==='out'?'支出':'收入',money(c.amount_cents),E(c.reference)])))+panel('本店办理与差异记录',table(['动作','说明'],r.events.map(e=>[E(reconcileLabels[e.action.replace('clearing_','')]||'创建清算'),E(e.reason)])));
}
async function clearingCreate(kind,id){
 const source=state.clearingOrigins.find(r=>r.origin_kind===kind&&r.origin_id===id),request_id=requestKey();
 await formDialog('申请部分或全部调拨清算',[F('amount','本次金额（元）','money'),F('due_date','约定日期','date'),F('reason','双方核对依据','textarea')],{amount:money(source.available_cents),due_date:new Date().toLocaleDateString('en-CA')},async v=>{const r=await api('/api/reconciliation/clearing',{method:'POST',body:{request_id,origin_kind:kind,origin_id:id,amount_cents:groupFen(v.amount),due_date:v.due_date,reason:v.reason}});go('clearing/'+r.id);},{notice:'申请只占原条目额度；实际出入款仍由双方各自财务确认。'});

}
async function clearingAction(key){
 const r=state.clearing,fields=[];if(['pay','receive'].includes(key))fields.push(F('account_id','本店实际账户','account'),F('reference','本店真实银行流水／凭证号'));
 if(['pay','receive','difference'].includes(key))fields.push(F('evidence_id','本店原清算单凭据','file'));fields.push(F('reason','实际办理事实与原因','textarea'));
 const request_id=requestKey();await formDialog(reconcileLabels[key],fields,{},v=>api(`/api/reconciliation/clearing/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,case_version:r.case_version,values:v}}),{caseId:r.case_id,notice:`本次固定金额 ${money(r.amount_cents)} 元。仅在真实银行或现金事实发生后登记；系统不会自动转账。`});
}
