'use strict';
const retailNames={approve:'主管价格授权',authorize:'记录客户报价确认',cancel:'取消未出库订单',dispatch:'确认整单实际出库',install:'确认实际安装',accept:'确认客户接收',receive:'登记实际收款',return_request:'申请原单部分退货',return_approve:'批准退货',return_cancel:'撤销未验收退货',return_receive:'检查退货可售性',return_rectify:'提交退货整改',refund:'登记原款实际退款',return_reject:'决定拒收并交回',return_handback:'确认拒收商品交回'};
const retailReturnNames={requested:'待主管复核',approved:'待可售验收',rectification:'验收不合格，待整改',reinspection:'待复检',accepted:'已验收入库',cancelled:'已撤销',handback:'拒收待实物交回',rejected:'已拒收并交回客户'};
function retailScaled(value,digits){
 const s=String(value).trim();
 if(![0,2,3].includes(digits))throw new Error('数值精度配置无效。');
 const pattern=digits===0?/^\d+$/:new RegExp('^\\d+(\\.\\d{1,'+digits+'})?$');
 if(!pattern.test(s))throw new Error(digits===0?'券和套餐须填写整数份数。':'金额最多两位、数量最多三位小数。');
 const [a,b='']=s.split('.'),n=Number(a)*10**digits+Number(b.padEnd(digits,'0'));
 if(!Number.isSafeInteger(n))throw new Error('数值超出范围。');return n;
}
async function retailAll(path){let items=[];for(let page=1;page<=100;page++){const d=await api(path+(path.includes('?')?'&':'?')+'page='+page);items.push(...d.items);if(items.length>=d.total)return items;}throw new Error('选择范围过大，请联系管理员。');}
async function retailPage(id){
 if(!id){const d=await api('/api/retail/orders?page='+state.page);return heading('精品销售与退货','商品、安装、客户接收和真实收退款分别留档。',canWrite()&&['admin','sales','service'].includes(state.user.role)?b('retail-new','新建精品订单','','primary'):'')+storeNotice()+panel('精品订单',table(['订单／客户','状态','应收（元）','应退（元）',''],d.items.map(r=>[`${E(r.number)}<br>${E(r.customer_name)}`,pill(r.state),r.totals?money(r.totals.receivable_cents):'—',r.totals?money(r.totals.refund_due_cents):'—',b('open','办理',`data-route="retail/${r.id}"`)])))+pager(d.total);}
 const r=await api('/api/retail/orders/'+id);state.retailOrder=r;state.row=await api('/api/flow/cases/'+id);
 const allowed=k=>canWrite()&&r.actions.includes(k),button=(k,extra='')=>b('retail-action',retailNames[k],`data-key="${k}" ${extra}`),buttons=[];
 if(r.state==='approval'&&allowed('approve'))buttons.push(button('approve'));
 if(r.state==='authorization'&&allowed('authorize'))buttons.push(button('authorize'));
 if(!r.data.dispatched&&!r.data.cancelled&&allowed('cancel'))buttons.push(button('cancel'));
 if(r.state==='pending'&&allowed('dispatch'))buttons.push(button('dispatch'));
 const active=r.returns.some(x=>!['accepted','cancelled','rejected'].includes(x.status));
 if(r.data.dispatched&&!r.data.installed&&!r.data.accepted_date&&!active&&r.lines.some(l=>l.work_item_id)&&allowed('install'))buttons.push(button('install'));
 if(r.data.dispatched&&!r.data.accepted_date&&!active&&allowed('accept'))buttons.push(button('accept'));
 if(r.data.approved&&!r.data.cancelled&&(r.totals?.cash_collectable_cents??r.totals?.receivable_cents)&&allowed('receive'))buttons.push(button('receive'));
 if(r.data.dispatched&&r.dispatches.some(s=>s.returned_milli<s.quantity_milli)&&allowed('return_request'))buttons.push(button('return_request'));
 if(r.totals?.refund_due_cents&&allowed('refund'))buttons.push(button('refund'));
 let html=heading('精品销售 · '+r.number,`${r.customer_name} · 冻结报价第 ${r.revision} 版`,b('open','返回订单',`data-route="retail"`))+storeNotice();
 html+=panel('当前办理',`<p>${pill(r.state)} · ${r.data.authorized?'客户已确认报价':'待客户确认'} · ${r.data.dispatched?'已实际出库':'商品已占用，尚未出库'} · ${r.data.installed?'已实际安装':'尚未确认安装'} · ${r.data.accepted_date?'客户已接收':'尚未确认接收'}</p><div class="row">${buttons.join('')||'等待相关岗位办理。'}</div>`);
 if(r.related_repair_id)html+=panel('维修附带销售',b('open','查看关联维修',`data-route="case/${r.related_repair_id}"`)+'<p>本精品单单独结算；维修与精品各自保留库存及收款原单。</p>');
 if(r.bundle)html+=panel('原套餐版本与退货规则',`<p><strong>${E(r.bundle.name)}</strong> · ${E(r.bundle.code)} · 第 ${r.bundle.rule_version} 版 · ${number(r.bundle.sets)} 套</p><p>${E(r.bundle.mandatory_terms)}</p><p>${E(r.bundle.refund_terms)}</p>`+(canWrite()&&r.amount_cents!==undefined?b('generatedoc','生成精品套餐报价确认单','data-kind="retail_quote"'):'')+'<p>请上传客户签回的报价单。</p>');
 html+=panel('冻结商品与安装报价',memberPriceSummary(r.member_pricing)+`<p>${E(r.installation_policy)}。改价须在出库前取消本单并重新开单。</p>`+table(['商品／安装','数量',...(r.amount_cents!==undefined?[r.bundle?'商品套餐分摊（元）':'商品金额（元）',r.bundle?'安装套餐分摊（元）':'安装金额（元）']:[])],r.lines.map(l=>[`${E(l.sku)} · ${E(l.name)}<br>${l.work_item_id?'安装：'+E(l.work_name):'无需安装'}`,number(l.quantity_milli/1000)+' '+E(l.unit),...(r.amount_cents!==undefined?[money(l.goods_cents),money(l.installation_cents)]:[])]))+(r.amount_cents!==undefined?`<p>原优惠 ${money(r.discount_cents)} 元，${r.bundle?'按每套冻结分摊乘购买套数':'按商品与安装原金额分摊'}；确认合计 ${money(r.amount_cents)} 元。</p>`:''));
 if(r.totals){const t=r.totals;html+=panel('精品收退款与当前应收',`<div class="cards">${[['当前应付',t.charge_cents],['结算净抵扣',t.net_paid_cents],['现金净收',t.cash_paid_cents],['尚欠',t.receivable_cents],['应退',t.refund_due_cents],['已履约安装保留费',t.retained_installation_cents]].map(([label,v])=>`<div class="card"><span>${label}（元）</span><strong>${money(v)}</strong></div>`).join('')}</div><p>退货须可售验收通过才减少应收。未收到的钱只减应收，不能登记现金退款。集团本金、赠金、券和套餐从原付款方案分别核销与恢复；不混退为现金。</p>`+r.payments.map(p=>`<div class="taskitem"><div class="description"><strong>${p.direction==='in'?'实际收款':'原款退款'} ${money(p.amount_cents)} 元</strong><p>收款关联 ${p.id}${p.original_id?' · 原收款 '+p.original_id:''} · ${E(p.business_date)}</p></div></div>`).join(''));}
 if(r.totals&&['admin','manager','sales','service','finance','auditor'].includes(state.user.role))html+=panel('集团原付款方案',b('open',r.totals.group_paid_cents===undefined?'核对集团付款资格':'办理原付款与原退',`data-route="retail-group/${r.id}"`)+'<p>仅客户实际接收且尚未收款的原单可新建混合方案；实际现金仍在本页按原份额办理。</p>');
 html+=panel('实际出库与原单退货',r.dispatches.length?r.dispatches.map(s=>`<div class="taskitem"><div class="description"><strong>${E(r.lines.find(l=>l.id===s.line_id)?.name)}</strong><p>原出库 ${s.id} · 出库 ${number(s.quantity_milli/1000)} · 已验收退回 ${number(s.returned_milli/1000)}</p></div></div>`).join(''):'<p>仅占用库存，尚未实际出库。</p>');
 html+=panel('退货办理',r.returns.map(x=>{let actions=[];for(const key of x.status==='requested'?['return_approve','return_cancel']:x.status==='approved'?['return_receive','return_cancel']:x.status==='rectification'?['return_rectify','return_reject']:x.status==='reinspection'?['return_receive','return_reject']:x.status==='handback'?['return_handback']:[])if(allowed(key))actions.push(button(key,`data-id="${x.id}"`));return `<div class="taskitem"><div class="description"><strong>退货 ${x.id} · ${E(retailReturnNames[x.status])}</strong><p>${E(x.reason)}</p>${x.lines.map(l=>{const s=r.dispatches.find(d=>d.id===l.dispatch_id);return `<p>${E(r.lines.find(p=>p.id===s?.line_id)?.name)} · ${number(l.quantity_milli/1000)}</p>`;}).join('')}<p>${x.retain_installation?'原单已履约安装费保留':'对应未履约安装费随实际验收退货减免'}</p><div class="row">${actions.join('')}</div></div></div>`;}).join('')||'<p>没有退货申请。</p>');
 html+=panel('本单凭据',(canWrite()?b('upload','上传实际凭据'):'')+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.label)} · ${E(f.security?.label||'待检查')}</p><div class="row">${b('filescaninfo','文件检查',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'检查通过后可引用'}</div></div></div>`).join(''));
 html+=panel('岗位交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&canWrite()&&['admin','manager'].includes(state.user.role)?b('assign','交接给其他员工',`data-id="${t.id}"`):''}</div></div>`).join(''));
 return html;
}
async function retailNew(){
 const [customers,items,works]=await Promise.all([retailAll('/api/flow/master/customers?page_size=100'),retailAll('/api/retail/items'),retailAll('/api/retail/installations')]);
 const parts=items.filter(x=>x.active);if(!customers.length||!parts.length)throw new Error('请先建立客户和商品主档，并完成实际库存入库。');
 const line=`<div class="panelbody" data-retail-line><label>商品<select name="item" required data-search-select>${parts.map(x=>`<option value="${x.id}">${E(x.sku)} · ${E(x.name)} · 可用 ${number(Number(x.available_quantity??x.quantity))}</option>`).join('')}</select></label><div class="formgrid"><label>数量<input name="quantity" value="1.000" inputmode="decimal" required></label><label>商品单价（元）<input name="price" inputmode="decimal" required></label></div><label>安装项目<select name="work" data-search-select><option value="">无需安装</option>${works.map(x=>`<option value="${x.id}">${E(x.code)} · ${E(x.name)}</option>`).join('')}</select></label><label>每单位商品安装费（元）<input name="install_price" value="0.00" inputmode="decimal" required></label>${b('retail-remove-line','删除此行')}</div>`;state.retailLineHtml=line;const request_id=requestKey();
 modal('新建精品订单',`<form><label>客户档案<select name="customer" required data-search-select>${customers.map(x=>`<option value="${x.id}">${E(x.name)} · ${E(x.phone||'')}</option>`).join('')}</select></label><div data-member-price-field>${await memberPriceField(null,customers[0].id)}</div><label>关联维修单（选填）<select name="related" data-search-select><option value="">不关联维修单</option></select></label><div data-related-status class="fieldhelp"></div><div id="retail-lines">${line}</div>${b('retail-add-line','增加商品行')}<label>整单优惠（元）<input name="discount" value="0.00" inputmode="decimal" required></label><p>已实际完成安装的对应安装费保留，未安装的对应费用随验收退货减免。下单即占用本店商品，提交后须主管批准和客户确认。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">冻结报价并申请审批</button></div></form>`,async form=>{
  const lines=[...form.querySelectorAll('[data-retail-line]')].map(el=>({item_id:Number(el.querySelector('[name=item]').value),quantity_milli:retailScaled(el.querySelector('[name=quantity]').value,3),unit_price_cents:retailScaled(el.querySelector('[name=price]').value,2),work_item_id:Number(el.querySelector('[name=work]').value)||null,installation_unit_price_cents:retailScaled(el.querySelector('[name=install_price]').value,2)}));
  const row=await api('/api/retail/orders',{method:'POST',body:{request_id,customer_id:Number(form.elements.customer.value),...memberPricePayload(form),related_repair_id:Number(form.elements.related.value)||null,discount_cents:retailScaled(form.elements.discount.value,2),lines}});closeModal();go('retail/'+row.id);
 });
 const form=document.querySelector('#modal form');bindMemberPriceCustomer(form);
 let relatedRevision=0;const context=storeContextVersion;
 const loadRepairs=async()=>{const revision=++relatedRevision,customerId=form.elements.customer.value,select=form.elements.related,status=form.querySelector('[data-related-status]');select.innerHTML='<option value="">不关联维修单</option>';status.textContent='';if(!customerId)return;
  try{const rows=await retailAll('/api/flow/cases?kind=repair&customer_id='+encodeURIComponent(customerId));requireStoreContext(context);if(!form.isConnected||revision!==relatedRevision)return;select.innerHTML='<option value="">不关联维修单</option>'+rows.map(r=>`<option value="${r.id}">${E(r.number)} · ${E(r.title)} · ${E(r.state_label)}</option>`).join('');status.textContent=rows.length?'':'该客户暂无可选维修单';}
  catch(error){if(form.isConnected&&revision===relatedRevision)status.textContent=error.message;}};
 form.elements.customer.addEventListener('change',loadRepairs);loadRepairs();
 form.addEventListener('change',event=>{if(event.target.name!=='work'||event.liveChoiceReason==='edit')return;const line=event.target.closest('[data-retail-line]'),value=event.target.value,previous=line.dataset.pricedWork||'';if(value===previous)return;line.dataset.pricedWork=value;const work=works.find(w=>w.id===Number(value));line.querySelector('[name=install_price]').value=((work?.standard_fee_cents||0)/100).toFixed(2);});
}
async function retailAction(key,id){
 const r=state.retailOrder,request_id=requestKey(),fields=[],initial={},extra={},ret=r.returns.find(x=>x.id===id);
 if(key==='approve'){fields.push(F('minimum','主管明确最低金额（元）','money_zero'),F('allow_below_minimum','明确批准低价例外','bool'),F('reason','价格确认及例外原因','textarea'));initial.minimum=(r.amount_cents/100).toFixed(2);}
 if(key==='cancel'||key==='return_approve'||key==='return_cancel'||key==='return_reject'||key==='return_request')fields.push(F('reason','办理原因','textarea'));
 if(key==='authorize')extra.revision=r.revision;
 if(key==='install'||key==='return_rectify'||key==='return_receive'||key==='return_handback')fields.push(F('result','本人实际办理情况','textarea'));
 if(key==='return_receive')fields.push(F('outcome','可售检查结果','select',true,['合格','不合格']));
 if(ret){extra.return_id=ret.id;extra.return_version=ret.version;}
 const sources=r.dispatches.filter(x=>x.quantity_milli>x.returned_milli),sourceLabels=sources.map(x=>`${x.id} · ${r.lines.find(l=>l.id===x.line_id)?.name} · 尚未退 ${number((x.quantity_milli-x.returned_milli)/1000)}`);
 if(key==='return_request')fields.push(F('source','原出库商品','select',true,sourceLabels),F('quantity','本次退货数量','quantity'));
 if(key==='receive'||key==='refund'){fields.push(F('amount','本次实际金额（元）','money'),F('account_id','实际资金账户','account'),F('reference','实际流水／凭证号'));initial.amount=key==='receive'?((r.totals.cash_collectable_cents??r.totals.receivable_cents)/100).toFixed(2):'';}
 const originals=r.payments.filter(p=>p.direction==='in'&&(p.refundable_cents===undefined||p.refundable_cents>0)&&p.amount_cents>r.payments.filter(x=>x.original_id===p.id).reduce((n,x)=>n+x.amount_cents,0)),paymentLabels=originals.map(p=>`${p.id} · 收款 ${money(p.amount_cents)} 元${p.refundable_cents===undefined?'':' · 本次原份额可退 '+money(p.refundable_cents)+' 元'}`);
 if(key==='refund')fields.push(F('original','原始收款','select',true,paymentLabels));
 if(!['approve','cancel','return_approve','return_cancel','return_reject'].includes(key))fields.push(F('evidence_id',key==='authorize'?'本单客户授权类别凭据':['receive','refund'].includes(key)?'本单收退款类别凭据':'本单实际凭据','file'));
 await formDialog(retailNames[key],fields,initial,v=>{const values={...v,...extra};if(v.minimum!==undefined){values.minimum_total_cents=retailScaled(v.minimum,2);delete values.minimum;}if(v.amount!==undefined){values.amount_cents=retailScaled(v.amount,2);delete values.amount;}if(v.source!==undefined){values.lines=[{dispatch_id:sources[sourceLabels.indexOf(v.source)].id,quantity_milli:retailScaled(v.quantity,3)}];delete values.source;delete values.quantity;}if(v.outcome!==undefined){values.passed=v.outcome==='合格';delete values.outcome;}if(v.original!==undefined){values.original_payment_id=originals[paymentLabels.indexOf(v.original)].id;delete values.original;}return api(`/api/retail/orders/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values}});},{caseId:r.id,notice:key==='authorize'?`客户确认须对应第 ${r.revision} 版报价及安装费用保留约定。`:key==='return_receive'?'不合格不会回到可售库存或增加退款额度。整改并复检通过后才按原单数量及价值入库。':key==='return_approve'?'授权按原出库商品金额比例退货；实际验收按剩余数量分摊，最后一次收尽余分。已完成安装的对应安装费保留。':'请只确认本人实际核对的事实；后台再次检查岗位、当前版本和原单关联。'});
}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el?.dataset.act.startsWith('retail-'))return;try{switch(el.dataset.act){case'retail-new':await retailNew();break;case'retail-action':await retailAction(el.dataset.key,Number(el.dataset.id));break;case'retail-add-line':$('#retail-lines').insertAdjacentHTML('beforeend',state.retailLineHtml);break;case'retail-remove-line':if(document.querySelectorAll('[data-retail-line]').length<=1)throw new Error('至少保留一行商品。');el.closest('[data-retail-line]').remove();break;}}catch(error){toast(error.message,true);}});
