'use strict';
const reworkGrantStates={pending:'待原店独立批准',approved:'已批准，待指定员工接收',consumed:'已建立本次返修',rejected:'已拒绝',cancelled:'已取消',revoked:'已撤销'};
const reworkScopes={original_liability:'原责任，免客户收费',customer_extra:'本次新增自费'};
async function reworkExtensionsPage(id){
 const advise=canWrite()&&['admin','service'].includes(state.user.role),manage=canWrite()&&['admin','manager'].includes(state.user.role);
 if(!id){const d=await api('/api/rework-extensions/grants');return heading('原责任与新增自费返修','',advise?b('rework-new','申请本次原责任授权','','primary'):'')+storeNotice()+panel('原责任授权',table(['原单与车辆','状态','原责任承担',''],d.items.map(g=>[`${E(g.source_number||'待原店批准')}<br>${E(g.vin||'')}`,E(reworkGrantStates[g.status]),`${E(g.responsible_name||'—')}<br>${g.original_liability_limit_cents===undefined?'—':money(g.original_liability_limit_cents)+' 元限额'}`,b('open','核对与办理',`data-route="rework-extensions/${g.id}"`)])));}
 const g=await api('/api/rework-extensions/grants/'+id);state.reworkGrant=g;
 const source=g.requested_by!==undefined,buttons=[];
 if(source&&g.status==='pending'&&manage&&g.requested_by!==state.user.id)buttons.push(b('rework-decide','独立批准原责任','data-key="approve"','primary'),b('rework-decide','拒绝','data-key="reject"'));
 if(source&&g.status==='pending'&&(manage||g.requested_by===state.user.id))buttons.push(b('rework-decide','取消待批授权','data-key="cancel"'));
 if(source&&g.status==='approved'&&(manage||g.requested_by===state.user.id))buttons.push(b('rework-decide','撤销未使用授权','data-key="revoke"'));
 if(g.can_receive&&advise)buttons.push(b('rework-receive','核对并建立本店返修申请','','primary'));
 return heading('核对原责任授权',g.source_number||'待原店确认',b('open','返回授权清单','data-route="rework-extensions"'))+storeNotice()+panel('本次授权',`<p>${E(reworkGrantStates[g.status])}</p><p>VIN：${E(g.vin||'待授权后核对')}</p><p>${E(g.responsible_name||'')} · ${g.original_liability_limit_cents===undefined?'':money(g.original_liability_limit_cents)+' 元原责任限额'}</p><p>接收期限：${time(g.expires_at)}</p><p>${E(g.reason||'')}</p>${table(['获准原责任项目','原项目数量'],(g.source_lines||[]).map(l=>[E(l.code)+' · '+E(l.name),number(l.quantity_milli/1000)]))}<p>批准仅记录本次责任依据。新增自费需独立取得当前报价客户授权；收付款按真实发生单独登记。</p><div class="row">${buttons.join('')}${source?b('open','查看原店本维修','data-route="repair-orders/'+g.source_case_id+'"'):''}${b('open','本店返修申请','data-route="service-intake/reworks"')}</div>`);
}
async function reworkNew(){
 const sources=(await repairAll('/api/service-intake/sources')).filter(s=>s.vin),request_id=requestKey();
 if(!sources.length)throw new Error('请先完成原维修交车及 VIN 核验。');
 let selected=sources[0],targets=[],files=[];
 modal('申请本次原责任授权',`<form><label>本店已交车原单<select name="source_case_id">${sources.map(s=>`<option value="${s.id}">${E(s.number)} · ${E(s.title)}</option>`).join('')}</select></label><div id="rework-source-details"></div><label>本次原责任最高金额（元）<input name="limit" inputmode="decimal" required></label><label>接收期限<input name="expires" type="datetime-local" required value="${intakeLocal(new Date(Date.now()+7*86400000))}"></label><label>原责任及本次范围说明<textarea name="reason" required minlength="2" maxlength="1000"></textarea></label><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">交原店另一名主管独立核对</button></div></form>`,async form=>{
  const ids=[...form.querySelectorAll('[name=source_line]:checked')].map(e=>Number(e.value));if(!ids.length)throw new Error('请选择具体原责任项目。');
  const current=await api('/api/repair-orders/'+selected.id);
  const g=await api('/api/rework-extensions/grants',{method:'POST',body:{request_id,source_case_id:selected.id,source_case_version:current.version,source_line_ids:ids,to_store_id:Number(form.elements.to_store_id.value),to_vehicle_id:Number(form.elements.to_vehicle_id.value),recipient_id:Number(form.elements.recipient_id.value),original_liability_limit_cents:repairScaled(form.elements.limit.value,2),evidence_id:Number(form.elements.evidence_id.value),reason:form.elements.reason.value,expires_at:new Date(form.elements.expires.value).toISOString()}});
  closeModal();go('rework-extensions/'+g.id);await render();
 });
 const targetFields=target=>`<label>同身份、同 VIN 客户车辆<select name="to_vehicle_id" required>${intakeOptions(target?.vehicles||[],v=>v.plate+' · '+v.vin,target?.vehicles[0]?.id)}</select></label><label>指定接收员工<select name="recipient_id" required>${intakeOptions(target?.recipients||[],u=>u.name)}</select></label>`;
 const load=async()=>{const [targetData,original]=await Promise.all([api('/api/rework-extensions/targets/'+selected.id),api('/api/flow/cases/'+selected.id)]);targets=targetData.items;files=original.files.filter(f=>!f.generated&&f.security?.can_use);$('#rework-source-details').innerHTML=`<p>原 VIN：${E(selected.vin)}</p><fieldset><legend>获准原责任项目</legend>${selected.lines.map(l=>`<label><input name="source_line" type="checkbox" value="${l.id}">${E(l.code)} · ${E(l.name)}</label>`).join('')}</fieldset><label>接收门店<select name="to_store_id" required>${targets.map(t=>`<option value="${t.store_id}">${E(t.store_name)}</option>`).join('')}</select></label><div id="rework-target-details">${targetFields(targets[0])}</div><label>原店本次责任核验凭据<select name="evidence_id" required>${intakeOptions(files,f=>f.name)}</select></label>${!files.length?'<p class="notice">请先到本维修原单上传并核验责任凭据，再重新申请。</p>':''}${!targets.length?'<p class="notice">暂无同共享客户身份及 VIN 的接收车辆，请接收店先核验车辆主档。</p>':''}`;$('#modal [name=to_store_id]').onchange=e=>{$('#rework-target-details').innerHTML=targetFields(targets.find(t=>t.store_id===Number(e.target.value)));};};
 $('#modal [name=source_case_id]').onchange=async e=>{try{selected=sources.find(s=>s.id===Number(e.target.value));await load();}catch(error){toast(error.message,true);}};await load();
}
async function reworkDecide(key){const g=state.reworkGrant,request_id=requestKey();await formDialog(key==='approve'?'独立批准本次原责任':'处理原责任授权',[F('reason','本人核对的责任与办理原因','textarea')],{},v=>api(`/api/rework-extensions/grants/${g.id}/actions/${key}`,{method:'POST',body:{request_id,version:g.version,values:v}}),{notice:'核对具体原项目、同身份 VIN、指定接收员工和本次责任限额。批准不产生实际收付款。'});}
async function reworkReceive(){const g=state.reworkGrant,c=await api('/api/service-intake/catalog'),resources=c.resources.filter(r=>r.active&&r.resource_type==='repair'),labels=resources.map(r=>r.name+' · '+r.code),request_id=requestKey();await formDialog('核对并建立本店返修申请',[F('resource','本次实际维修工位','select',true,labels),F('reason','本次原故障与新增需求','textarea')],{},async v=>{const r=await api('/api/rework-extensions/requests',{method:'POST',body:{request_id,grant_id:g.id,grant_version:g.version,resource_id:resources[labels.indexOf(v.resource)].id,reason:v.reason}});go('service-intake/reworks/'+r.id);return r;},{notice:'请核对原责任范围与客户身份。本次申请仍须本店另一名主管复核，实际到店另行登记。'});}
async function reworkQuoteDialog(row,stop){
 const q=repairCurrent(row),contract=row.service_intake.rework_extension,request_id=requestKey(),send=values=>api(`/api/rework-extensions/orders/${row.id}/quote`,{method:'POST',body:{request_id,version:row.version,values}});
 if(stop){await formDialog('协商返修停工保留费用',[F('retained','约定已履约保留金额（元）','money_zero'),F('reason','已履约、退料与保留费用说明','textarea')],{},v=>send({purpose:'stop',retained_amount_cents:repairScaled(v.retained,2),reason:v.reason,lines:[]}),{notice:'保留原分类和领退料；系统按原行分配保留费用，须重新取得当前客户授权。'});return;}
 const [work,parts]=await Promise.all([repairAll('/api/masters/work_items?active=true'),repairAll('/api/flow/master/items?page_size=100')]),sources=[...work.map(w=>({key:'work:'+w.id,name:w.code+' · '+w.name,price:w.standard_fee_cents})),...parts.filter(p=>p.active).map(p=>({key:'part:'+p.id,name:p.sku+' · '+p.name,price:0}))];
 for(const old of q?.lines||[]){const key=old.kind+':'+(old.work_item_id||old.item_id);if(!sources.some(s=>s.key===key))sources.push({key,name:old.code+' · '+old.name,price:old.unit_price_cents});}
 if(!sources.length)throw new Error('请先配置启用作业或物资主档。');
 const frozen=Boolean(q?.authorized),line=l=>`<div class="panelbody" data-rework-line data-line-key="${frozen&&l?E(l.line_key):''}"><label>项目／物资<select name="source" ${frozen&&l?'disabled':''}>${sources.map(s=>`<option value="${s.key}" ${l&&s.key===l.kind+':'+(l.work_item_id||l.item_id)?'selected':''}>${E(s.name)}</option>`).join('')}</select></label><label>责任类别<select name="charge_scope" ${frozen&&l?'disabled':''}>${Object.entries(reworkScopes).map(([k,n])=>`<option value="${k}" ${l?.charge_scope===k?'selected':''}>${E(n)}</option>`).join('')}</select></label><label>原责任项目（新增自费不使用）<select name="source_line_id" ${frozen&&l?'disabled':''}>${intakeOptions(contract.source_lines,s=>s.code+' · '+s.name,l?.source_line_id)}</select></label><label>数量<input name="quantity" inputmode="decimal" value="${l?(l.quantity_milli/1000).toFixed(3):'1.000'}" required></label><label>单价（元）<input name="price" inputmode="decimal" value="${l?(l.unit_price_cents/100).toFixed(2):(sources[0].price/100).toFixed(2)}" ${frozen&&l?'readonly':''} required></label>${!frozen||!l?b('rework-remove-line','删除此行'):''}</div>`;
 state.reworkLineHtml=line(null);
 modal('原责任与新增自费逐行报价',`<form>${await memberPriceField(row.id)}<p>原责任由 ${E(contract.responsible_name)} 承担，限额 ${money(contract.original_liability_limit_cents)} 元；客户只承担新增自费行。已有授权行分类不再改换。</p><div id="rework-lines">${q?q.lines.map(line).join(''):line(null)}</div>${b('rework-add-line','增加项目／物资')}<label>本次新增优惠（元）<input name="discount" inputmode="decimal" value="0.00" required></label><label>诊断与本次范围说明<textarea name="reason" required minlength="2"></textarea></label><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">冻结分类并提交本版审批</button></div></form>`,async form=>{
  const lines=[...form.querySelectorAll('[data-rework-line]')].map(el=>{const [kind,id]=el.querySelector('[name=source]').value.split(':'),scope=el.querySelector('[name=charge_scope]').value;return {kind,source_id:Number(id),...(el.dataset.lineKey?{line_key:el.dataset.lineKey}:{}),quantity_milli:repairScaled(el.querySelector('[name=quantity]').value,3),unit_price_cents:repairScaled(el.querySelector('[name=price]').value,2),charge_scope:scope,source_line_id:scope==='original_liability'?Number(el.querySelector('[name=source_line_id]').value):null};});
  await send({...memberPricePayload(form),reason:form.elements.reason.value,discount_cents:repairScaled(form.elements.discount.value,2),lines});closeModal();await render();
 });
}
async function reworkAllocate(row){const q=repairCurrent(row),scope=q.rework_scope,contract=row.service_intake.rework_extension,request_id=requestKey();if(!scope)throw new Error('当前报价缺少原责任与新增自费分类。');await formDialog('核对冻结行承担',[F('labor_cost','本次确认人工成本（元）','money_zero'),{...F('evidence_id','本次承担核对凭据','file'),file_category:'evidence'}],{},v=>api(`/api/repair-orders/${row.id}/actions/allocate`,{method:'POST',body:{request_id,version:row.version,values:{labor_cost_cents:repairScaled(v.labor_cost,2),evidence_id:v.evidence_id,allocations:[...(scope.original_liability_cents?[{payer_type:'internal',payer_name:contract.responsible_name,amount_cents:scope.original_liability_cents}]:[]),...(scope.customer_extra_cents?[{payer_type:'customer',amount_cents:scope.customer_extra_cents}]:[])]}}}),{caseId:row.id,notice:`原责任 ${money(scope.original_liability_cents)} 元由 ${contract.responsible_name} 承担；本次客户新增 ${money(scope.customer_extra_cents)} 元。金额来自冻结行，不能手动改配。`});}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el?.dataset.act.startsWith('rework-'))return;try{switch(el.dataset.act){case'rework-new':await reworkNew();break;case'rework-decide':await reworkDecide(el.dataset.key);break;case'rework-receive':await reworkReceive();break;case'rework-add-line':$('#rework-lines').insertAdjacentHTML('beforeend',state.reworkLineHtml);break;case'rework-remove-line':el.closest('[data-rework-line]').remove();break;}}catch(error){toast(error.message,true);}});
