'use strict';
const intakeStatus={scheduled:'待到店',arrived:'已实际到店',converted:'已转维修明细',cancelled:'已取消／离场',no_show:'核实未到',requested:'待责任审核',approved:'责任已批准',rejected:'责任未通过',completed:'本次返修已结束'};
const intakeProfiles={regular:'普通维修',wash:'快捷洗车',quick:'快捷项目',rework:'内部责任返修'};
const intakeActionNames={reschedule:'调整预约时段',cancel:'取消本次预约',no_show:'核实本次未到',arrive:'记录实际到店',leave:'记录未开单离场',convert:'建立本次维修明细',approve:'批准内部返修责任',reject:'拒绝本次责任申请'};
function intakeRole(roles){return canWrite()&&roles.includes(state.user.role);}
function intakeLocal(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function intakeEntryContext(){return String(state.user?.id)+':'+String(state.store)+':'+(typeof storeContextVersion==='undefined'?'':storeContextVersion);}
function intakeDefaultTimes(form,edited,now=Date.now()){
 const e=form.elements;if(!e.mode)return;
 if(!edited.starts_at)e.starts_at.value=intakeLocal(new Date(now+(e.mode.value==='walk_in'?0:3600000)));
 if(!edited.ends_at){const starts=new Date(e.starts_at.value).getTime();if(Number.isFinite(starts))e.ends_at.value=intakeLocal(new Date(starts+3600000));}
}
function intakeOptions(rows,label,selected){return '<option value="">请选择</option>'+rows.map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''}>${E(label(r))}</option>`).join('');}
function intakeFiles(){return panel('接待与责任凭据',(canWrite()?b('upload','上传本次实际凭据'):'')+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.label)} · ${E(f.security?.label||'等待检查')}</p><div class="row">${b('filescaninfo','检查记录',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'检查通过后可使用'}</div></div></div>`).join(''));}
async function serviceIntakePage(section='appointments',id){
 section=section||'appointments';if(!['appointments','reworks','resources'].includes(section))throw new Error('接待栏目不存在。');
 const front=intakeRole(['admin','service','reception','customer_service']),advisor=intakeRole(['admin','service']),manager=intakeRole(['admin','manager']);
 const tabs=`<div class="row">${b('open','预约与到店','data-route="service-intake/appointments"')}${['admin','manager','service','finance','auditor'].includes(state.user.role)?b('open','原单责任返修','data-route="service-intake/reworks"'):''}${manager?'<details class="mux-secondary-actions"><summary>工位与项目设置</summary>'+b('open','工位与快捷项目','data-route="service-intake/resources"')+'</details>':b('open','查看工位与快捷项目','data-route="service-intake/resources"')}${state.catalog?.capabilities?.rework_extensions&&['admin','manager','service','finance','auditor'].includes(state.user.role)?b('open','原责任与新增自费返修','data-route="rework-extensions"'):''}</div>`;
 if(!id){
  if(section==='resources'){
   const c=await api('/api/service-intake/catalog');state.intakeCatalog=c;
   return heading('工位与快捷项目','计划预约不代表到店；工位实际占用由技师开工和移出事实确认。',manager?b('intake-resource-new','新增服务工位','','primary')+b('intake-preset-new','新增快捷预填'):'' )+storeNotice()+tabs+panel('服务工位',table(['工位','类别','状态',''],c.resources.map(r=>[E(r.name)+'<br>'+E(r.code),r.resource_type==='wash'?'洗车':'维修',r.active?(r.in_use?'实际占用中':'启用'):'停用',manager?b('intake-active',r.active?'停用':'启用',`data-kind="resources" data-id="${r.id}"`):''])))+panel('快捷项目组合',table(['组合','类型','状态',''],c.presets.map(p=>[E(p.name)+'<br>'+E(p.code),E(intakeProfiles[p.profile]),p.active?'启用':'停用',manager?b('intake-active',p.active?'停用':'启用',`data-kind="presets" data-id="${p.id}"`):''])))+'<p class="fieldhelp">组合用于快捷填写项目。报价后仍需核价和客户确认；修改组合请新建并停用旧组合。</p>';
  }
  const d=await api(`/api/service-intake/${section}?page=${state.page}`);state.intakeList=d.items;
  return heading(section==='appointments'?'维修预约与到店':'原单责任返修',section==='appointments'?'按客户车辆安排时段，实际核对到店后再建立明细工单。':'主管核对原单责任；本次全部费用由明确的内部主体承担。',section==='appointments'&&front?b('intake-new','客户提前预约','data-mode="appointment"','primary')+b('intake-new','现场来访登记','data-mode="walk_in"'):section==='reworks'&&advisor?b('intake-rework-new','申请原单责任返修','','primary'):'')+storeNotice()+tabs+panel('本店接待',table(['客户／车辆','时段／原单','办理状态',''],d.items.map(r=>[`${E(r.title)}<br>${E(r.plate)}<br>${E(r.vin)}`,section==='appointments'?`${E(r.resource_name)}<br>${time(r.starts_at)}<br>至 ${time(r.ends_at)}`:E(r.source_number),E(intakeStatus[r.status]),b('open','办理',`data-route="service-intake/${section}/${r.id}"`)])))+pager(d.total);
 }
 const r=await api(`/api/service-intake/${section}/${id}`);state.intakeRecord=r;state.intakeSection=section;state.row=await api('/api/flow/cases/'+r.case_id);
 const task=k=>state.row.tasks.some(t=>t.key===k&&t.status==='open'&&(t.assignee_id===state.user.id||manager));
 const btn=k=>b('intake-action',intakeActionNames[k],`data-key="${k}"`),buttons=[];
 if(section==='appointments'){
  if(r.status==='scheduled'&&front){buttons.push(btn('reschedule'),btn('cancel'));if(new Date(r.ends_at)<new Date())buttons.push(btn('no_show'));if(task('intake_arrive'))buttons.unshift(btn('arrive'));}
  if(r.status==='arrived'){if(advisor&&task('intake_convert'))buttons.push(btn('convert'));if(front&&task('intake_convert'))buttons.push(btn('leave'));}
 }else{
  if(r.status==='requested'&&manager)buttons.push(btn('approve'),btn('reject'));
  if(['requested','approved'].includes(r.status)&&manager)buttons.push(b('intake-action','撤销未执行返修申请','data-key="cancel"'));
  if(r.status==='approved'&&advisor&&task('intake_rework_convert'))buttons.push(btn('convert'));
 }
 return heading(r.title,r.number,b('open','返回列表',`data-route="service-intake/${section}"`))+storeNotice()+`<div class="stack">`+panel('本次接待',`<p>${E(intakeStatus[r.status])} · ${E(r.plate)}</p><p class="fieldhelp">VIN：${E(r.vin)}</p>${section==='appointments'?`<p>${E(r.resource_name)}<br>${time(r.starts_at)} 至 ${time(r.ends_at)}</p><p>${E(r.problem)}</p>${r.arrived_at?`<p>实际到店：${time(r.arrived_at)}</p>`:''}`:`<p>原单：${E(r.source_number)}</p><p>${E(r.reason)}</p><p>责任项目：${r.source_lines.map(l=>E(l.name)).join('、')}</p>${r.internal_name?`<p>${r.rework_extension?'原责任承担':'全部费用承担'}：${E(r.internal_name)}</p>`:''}${r.rework_extension?`<p>原责任限额 ${money(r.rework_extension.original_liability_limit_cents)} 元，新增自费逐行报价并取得本版客户授权。</p>`:''}${r.source_case_id?b('open','查看维修原单',`data-route="repair-orders/${r.source_case_id}"`):''}`}<div class="row">${buttons.join('')||'当前岗位等待其他员工完成前置步骤。'}${r.repair_case_id?b('open','办理维修明细工单',`data-route="repair-orders/${r.repair_case_id}"`):''}</div>`)+intakeFiles()+panel('岗位交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&manager?b('assign','交接给其他员工',`data-id="${t.id}"`):''}</div></div>`).join(''))+'</div>';
}
async function intakeBook(reschedule=false,initialMode='appointment'){
 initialMode=initialMode==='walk_in'?'walk_in':'appointment';
 const context=intakeEntryContext(),r=reschedule?state.intakeRecord:null,c=await api('/api/service-intake/catalog');if(context!==intakeEntryContext())return;
 const request_id=requestKey(),start=r?.starts_at||new Date(Date.now()+(initialMode==='walk_in'?0:3600000)),end=r?.ends_at||new Date(new Date(start).getTime()+3600000);let saving=false;
 const dialog=modal(reschedule?'调整预约时段':initialMode==='walk_in'?'现场来访登记':'客户提前预约',`<form>${!reschedule?`<label>客户车辆<select name="customer_vehicle_id" required data-search-select data-search-placeholder="客户、车牌或 VIN">${intakeOptions(c.vehicles,v=>v.customer_name+' · '+v.plate+' · '+v.vin)}</select></label><label>接待方式<select name="mode"><option value="appointment" ${initialMode==='appointment'?'selected':''}>预约</option><option value="walk_in" ${initialMode==='walk_in'?'selected':''}>现场来访／当天排队</option></select></label>`:''}<label>服务工位<select name="resource_id" required data-search-select>${intakeOptions(c.resources.filter(x=>x.active),x=>x.name+(x.in_use?'（当前实际占用）':''),r?.resource_id)}</select></label><label>计划开始<input type="datetime-local" name="starts_at" required value="${intakeLocal(start)}"></label><label>计划结束<input type="datetime-local" name="ends_at" required value="${intakeLocal(end)}"></label>${!reschedule?`<label>快捷项目<select name="preset_id" data-search-select><option value="">普通维修</option>${c.presets.filter(p=>p.active).map(p=>`<option value="${p.id}">${E(p.name)} · ${E(intakeProfiles[p.profile])}</option>`).join('')}</select></label>`:''}<label>${reschedule?'改约原因':'客户诉求'}<textarea name="reason" required minlength="2" maxlength="1000">${reschedule?'':E(r?.problem||'')}</textarea></label><div class="formerror" role="alert"></div><div class="modalfoot">${b('close','取消')}<button type="submit" class="primary">${reschedule?'确认改约':'保存接待安排'}</button></div></form>`,async form=>{
  if(saving)return;if(context!==intakeEntryContext())throw new Error('门店已切换，请重新打开接待登记。');
  const values={resource_id:Number(form.elements.resource_id.value),starts_at:new Date(form.elements.starts_at.value).toISOString(),ends_at:new Date(form.elements.ends_at.value).toISOString()};
  saving=true;try{let result;if(reschedule){values.reason=form.elements.reason.value;result=await api(`/api/service-intake/appointments/${r.id}/actions/reschedule`,{method:'POST',body:{request_id,version:r.version,values}});}else{Object.assign(values,{customer_vehicle_id:Number(form.elements.customer_vehicle_id.value),mode:form.elements.mode.value,problem:form.elements.reason.value,preset_id:Number(form.elements.preset_id.value)||null});result=await api('/api/service-intake/appointments',{method:'POST',body:{request_id,...values}});}
   if(context!==intakeEntryContext())return;closeModal();go('service-intake/appointments/'+result.id);await render();
  }finally{saving=false;}
 });
 if(!reschedule){const form=dialog.querySelector('form'),edited={starts_at:false,ends_at:false};
  for(const event of ['input','change'])form.addEventListener(event,e=>{if(e.target.name in edited)edited[e.target.name]=true;});
  form.elements.mode.addEventListener('change',()=>intakeDefaultTimes(form,edited));
 }
}
async function intakeAction(key){
 if(key==='reschedule')return intakeBook(true);
 const r=state.intakeRecord,kind=state.intakeSection,fields=[],initial={},request_id=requestKey();
 if(['cancel','no_show','leave','approve','reject'].includes(key))fields.push(F('reason','本人核对的原因与结果','textarea'));
 if(key==='approve'&&!r.rework_extension)fields.push(F('internal_name','全部费用内部承担主体'));
 if(key==='approve'&&r.rework_extension)initial.internal_name=r.rework_extension.responsible_name;
 if(key==='arrive'||(kind==='reworks'&&key==='convert'))fields.push(F('checked_vin','现场逐位核对 VIN'),F('odometer_km','现场里程（公里）','int'));
 if(key==='convert')fields.push(F('due_date','预计交接日期','date'));
 if(['arrive','leave','approve'].includes(key)||(kind==='reworks'&&key==='convert'))fields.push(F('evidence_id','本次实际核验凭据','file'));
 await formDialog(intakeActionNames[key],fields,initial,v=>api(`/api/service-intake/${kind}/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values:{...v,...(key==='approve'&&r.rework_extension?{internal_name:r.rework_extension.responsible_name}:{})}}}),{caseId:r.case_id,notice:key==='convert'?'建立独立的本次明细。报价、主管审批、客户授权、施工及账款继续逐步办理。':key==='approve'?(r.rework_extension?'确认承接原店已批准的责任；新增自费只以本次冻结行和客户授权为准。':'确认原维修责任及全部内部承担。新增客户收费服务应另建普通维修单。'):'请只记录已核实的本次事实；重复提交与过期版本由系统拒绝。'});
}
async function intakeResourceNew(){const request_id=requestKey();await formDialog('新增服务工位',[F('code','工位代码'),F('name','工位名称'),F('type','工位类型','select',true,['维修','洗车'])],{},v=>api('/api/service-intake/resources',{method:'POST',body:{request_id,code:v.code,name:v.name,resource_type:v.type==='洗车'?'wash':'repair'}}));}
async function intakePresetNew(){
 const works=await repairAll('/api/masters/work_items?active=true'),request_id=requestKey();if(!works.length)throw new Error('请先配置启用的作业项目。');
 modal('新增快捷项目预填',`<form><label>组合代码<input name="code" required maxlength="60"></label><label>组合名称<input name="name" required minlength="2" maxlength="120"></label><label>类型<select name="profile"><option value="wash">快捷洗车</option><option value="quick">快捷维修项目</option></select></label><p>填写本组合需要的作业数量；不包含的项目留空。</p>${works.map(w=>`<label>${E(w.code)} · ${E(w.name)}<input data-work-id="${w.id}" inputmode="decimal" placeholder="数量，最多三位小数"></label>`).join('')}<div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">保存固定作业组合</button></div></form>`,async form=>{const lines=[...form.querySelectorAll('[data-work-id]')].filter(e=>e.value.trim()).map(e=>({work_item_id:Number(e.dataset.workId),quantity_milli:repairScaled(e.value,3)}));await api('/api/service-intake/presets',{method:'POST',body:{request_id,code:form.elements.code.value,name:form.elements.name.value,profile:form.elements.profile.value,lines}});closeModal();await render();});
}
async function intakeActive(kind,id){const row=state.intakeCatalog[kind].find(r=>r.id===id),request_id=requestKey();await formDialog(row.active?'停用配置':'启用配置',[F('reason','配置变更原因','textarea')],{},v=>api(`/api/service-intake/${kind}/${id}/active`,{method:'POST',body:{request_id,version:row.version,values:{...v,active:!row.active}}}),{notice:'有待到店预约或未完成的工位业务时不能停用。已有报价与历史组合保持不变。'});}
async function intakeReworkNew(){
 const sources=await repairAll('/api/service-intake/sources'),c=await api('/api/service-intake/catalog'),eligible=sources.filter(s=>s.vin),request_id=requestKey();
 if(!eligible.length)throw new Error('暂无已接车且核验 VIN 的原维修。旧明细请先由主管在原工单补核验凭据和车辆绑定。');
 const sourceFields=s=>`<p>原客户与 VIN：${E(s.title)} · ${E(s.vin)}</p><label>原责任项目<select name="source_line_id" required>${intakeOptions(s.lines,l=>l.code+' · '+l.name)}</select></label><label>客户车辆<select name="customer_vehicle_id" required>${intakeOptions(c.vehicles.filter(v=>v.customer_id===s.customer_id&&v.vin===s.vin),v=>v.customer_name+' · '+v.plate+' · '+v.vin,s.binding_customer_vehicle_id)}</select></label>`;
 modal('申请原单责任返修',`<form><label>已接车的维修原单<select name="source_case_id" id="intake-source">${eligible.map(s=>`<option value="${s.id}">${E(s.number)} · ${E(s.title)}</option>`).join('')}</select></label><div id="intake-source-fields">${sourceFields(eligible[0])}</div><label>本次维修工位<select name="resource_id" required>${intakeOptions(c.resources.filter(r=>r.active&&r.resource_type==='repair'),r=>r.name)}</select></label><label>原缺陷及本次诉求<textarea name="reason" required minlength="2" maxlength="1000"></textarea></label><p>主管确认责任后再记录实际到店，建立本次独立明细；本申请不复制原收款和原领料。</p><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">交主管核对返修责任</button></div></form>`,async form=>{const source=eligible.find(s=>s.id===Number(form.elements.source_case_id.value));const r=await api('/api/service-intake/reworks',{method:'POST',body:{request_id,source_case_id:source.id,source_version:source.version,customer_vehicle_id:Number(form.elements.customer_vehicle_id.value),resource_id:Number(form.elements.resource_id.value),source_line_ids:[Number(form.elements.source_line_id.value)],reason:form.elements.reason.value}});closeModal();go('service-intake/reworks/'+r.id);await render();});
 $('#intake-source').onchange=e=>{$('#intake-source-fields').innerHTML=sourceFields(eligible.find(s=>s.id===Number(e.target.value)));};
}
function serviceIntakeRepairPanel(row){
 const c=row.service_intake;if(!c)return row.data.released_date&&intakeRole(['admin','manager'])?panel('原单车辆核验',b('intake-bind','依据原始凭据核验 VIN')+'<p>旧维修仅有车牌，必须由主管核对原始凭据后追加不可变车辆绑定，方可申请责任返修。</p>'):'';
 const controls=[],tech=intakeRole(['admin','technician']);
 if(row.state==='cancelled'&&!c.cancelled_gate_exit_id&&intakeRole(['admin','manager','service']))controls.push(b('gate-repair-exit','确认取消后实际离场'));
 if(c.cancelled_gate_exit_id)controls.push('<span>取消后实际离场已有原凭据记录</span>');
 if(tech&&c.resource_occupied&&['quality','settling','credit_open','completed'].includes(row.state))controls.push(b('intake-resource','确认实际移出工位','data-key="release"'));
 if(tech&&!c.resource_occupied&&row.state==='working'&&row.data.started&&!row.data.stopping)controls.push(b('intake-resource','确认实际重新进位','data-key="acquire"'));
 if(['admin','manager','service','finance','auditor'].includes(state.user.role))controls.push(b('open','查看本次接待来源',`data-route="service-intake/${c.rework_id?'reworks/'+c.rework_id:'appointments/'+c.appointment_id}"`));
 return panel('客户车辆与实际工位',`<p>${E(intakeProfiles[c.profile])} · ${E(c.resource_name)}</p><p class="fieldhelp">冻结 VIN：${E(c.vin)}</p><p>${c.resource_occupied?'本车正在占用工位':c.resource_busy?'工位被其他实际业务占用':'本单当前未占用工位'}</p>${c.rework_extension?`<div class="notice">原责任由 ${E(c.rework_extension.responsible_name)} 承担，限额 ${money(c.rework_extension.original_liability_limit_cents)} 元。新增自费必须逐行确认本版客户授权。</div>`:''}${c.internal_only?`<div class="notice">本次责任返修全部由 ${E(c.internal_name)} 承担，不再收取原已付费用。新增收费服务另建普通工单。</div>`:''}<div class="row">${controls.join('')}</div>`);
}
async function intakeRepairResource(key){const r=state.repairOrder,request_id=requestKey();await formDialog(key==='release'?'确认实际移出工位':'确认实际重新进位',[F('reason','本人实际核对的进出位情况','textarea'),F('evidence_id','本次进出位凭据','file')],{},v=>api(`/api/service-intake/orders/${r.id}/resource/${key}`,{method:'POST',body:{request_id,version:r.version,values:v}}),{caseId:r.id,notice:'计划结束时间不会自动释放工位；只有实际移出后才能接续其他车辆。'});}
async function intakeBind(){const row=state.repairOrder,c=await api('/api/service-intake/catalog'),vehicles=c.vehicles.filter(v=>v.customer_id===row.customer_id),names=vehicles.map(v=>v.plate+' · '+v.vin),request_id=requestKey();await formDialog('依据原始凭据核验 VIN',[F('vehicle','原单客户车辆','select',true,names),F('checked_vin','逐位核对 VIN'),F('source_reference','原始凭据位置及核验依据','textarea'),F('evidence_id','原单 VIN 核验凭据','file')],{},v=>api('/api/service-intake/bindings',{method:'POST',body:{request_id,source_case_id:row.id,source_version:row.version,customer_vehicle_id:vehicles[names.indexOf(v.vehicle)].id,checked_vin:v.checked_vin,source_reference:v.source_reference,evidence_id:v.evidence_id}}),{caseId:row.id,notice:'不得仅凭相同车牌推断。车辆绑定后不可覆盖，原工单版本、收款、履约事实保留。'});}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el?.dataset.act.startsWith('intake-'))return;try{switch(el.dataset.act){case'intake-new':await intakeBook(false,el.dataset.mode);break;case'intake-action':await intakeAction(el.dataset.key);break;case'intake-resource-new':await intakeResourceNew();break;case'intake-preset-new':await intakePresetNew();break;case'intake-active':await intakeActive(el.dataset.kind,Number(el.dataset.id));break;case'intake-rework-new':await intakeReworkNew();break;case'intake-resource':await intakeRepairResource(el.dataset.key);break;case'intake-bind':await intakeBind();break;}}catch(error){toast(error.message,true);}});
