'use strict';
const serviceOrderNames={quote:'项目及报价版本',approve:'独立批准当前价格',authorize:'客户当前版授权',submit:'实际提交／补件',external_result:'实际外部结果',fulfill:'确认本项实际办结',receive:'客户实际到账',disburse:'按原本金实际代缴',thirdparty_return:'第三方原路退回',termination:'终止与原款退款方案',termination_approve:'独立批准终止方案',consent:'客户同意终止方案',termination_apply:'生效保留费及减免',refund:'实际退回原客户款',termination_cancel:'撤回未生效方案',cancel:'取消未办理申请'};
const serviceOrderBuckets={fee:'本店服务费',pass:'代收代缴本金'};
async function serviceOrdersPage(id){
 if(!id){const d=await api('/api/service-orders?page='+state.page);return heading('代办与其它客户服务','',canWrite()&&['admin','sales','service'].includes(state.user.role)?b('serviceorder-new','建立客户服务','','primary'):'')+storeNotice()+panel('本店服务',table(['服务单','类别','状态',''],d.rows.map(r=>[`${E(r.number)}<br>${E(r.title)}`,r.kind==='agency'?'代办服务':'其它客户服务',pill(r.state),b('open','办理',`data-route="service-orders/${r.id}"`)])))+(['admin','manager'].includes(state.user.role)?panel('服务基础资料',b('serviceorder-master','新增代缴单位','data-kind="payees"')+b('serviceorder-master','新增其它服务项目','data-kind="income-items"')):'');}
 const r=await api('/api/service-orders/'+id);state.serviceOrder=r;state.row=await api('/api/flow/cases/'+id);state.serviceOrderCatalog=await api('/api/service-orders/catalog');
 const can=k=>canWrite()&&r.actions.includes(k),button=(k,extra='')=>can(k)?b('serviceorder-action',serviceOrderNames[k],`data-key="${k}" ${extra}`):'';
 const pending=r.plans.find(p=>!p.cancelled&&!p.applied),terminated=r.plans.some(p=>p.applied),summary=r.summary,buttons=[];
 if(!pending&&!terminated)buttons.push(button('quote'));
 if(r.quote&&!r.quote_approved&&!pending)buttons.push(button('approve'));
 if(r.quote_approved&&!summary.authorized&&!pending)buttons.push(button('authorize'));
 if(summary.authorized&&!pending&&summary.customer_due_cents)buttons.push(button('receive'));
 if(summary.authorized&&!pending)buttons.push(button('termination'));
 if(!r.tenders.length&&!r.submissions.length&&!r.fulfillments.length)buttons.push(button('cancel'));
 let h=heading(r.title,r.number,b('open','返回服务列表','data-route="service-orders"'))+storeNotice()+`<div class="notice">${r.kind==='agency'?'代办服务':'其它客户服务'} · ${pill(r.state)}<br>${r.order.delivery_blocking?'本单已约定交车前办结。':'未约定交车前要求，按实际服务进度办理。'}<br>上传只关联原件，经办人与财务分别确认实际结果。本版不办理集团会员权益抵付。</div>`;
 h+=actionPanel(`<div class="row">${buttons.filter(Boolean).join('')||(r.state==='completed'?'本次服务已结清；需要纠正时保留原单并追加终止方案。':'请由对应岗位接手待办。')}</div>`);
 h+=panel('客户收费与代缴本金',`<div class="formgrid"><div>服务费净额<strong>${money(summary.fee_charge_cents)} 元</strong></div><div>代缴本金净额<strong>${money(summary.pass_charge_cents)} 元</strong></div><div>客户已付净额<strong>${money(summary.customer_paid_cents)} 元</strong></div><div>扣除预收占额尚欠<strong>${money(summary.customer_due_cents)} 元</strong></div><div>实际第三方净支付<strong>${money(summary.thirdparty_paid_cents-summary.thirdparty_returned_cents)} 元</strong></div><div>本店尚持有代缴本金<strong>${money(summary.pass_cash_balance_cents)} 元</strong></div></div><p>代缴支出不算客户退款，代缴本金不计本店服务收入。分笔收款按当前未付明细比例分配，末项保留整分余数。</p>`);
 if(r.order.source_order_id)h+=panel('原销售关联',b('open','核对原销售单',`data-route="case/${r.order.source_order_id}"`));
 if(r.order.vehicle_snapshot.vin)h+=panel('冻结客户车辆',`<p>${E(r.order.vehicle_snapshot.vin)} · ${E(r.order.vehicle_snapshot.plate)}</p>`);
 if(r.quote)h+=panel('报价第 '+r.quote.revision+' 版',`<p>${E(r.quote.reason)} · 服务费折扣 ${money(r.quote.discount_cents)} 元</p><p>${r.quote_approved?'主管已批准':'等待主管独立批准'} · ${summary.authorized?'客户已授权本版':'尚无客户当前版授权'}</p>`);
 if(r.quote_history?.length)h+=panel('报价与授权记录',`<details><summary>查看全部 ${r.quote_history.length} 个冻结版本</summary>${r.quote_history.map(x=>`<h3>报价第 ${x.quote.revision} 版</h3><p>服务费 ${money(x.quote.fee_cents)} 元；代缴本金 ${money(x.quote.pass_cents)} 元。${E(x.quote.reason)}</p>${table(['项目','数量','净金额（元）'],x.lines.map(l=>[E(l.name),number(l.quantity_milli/1000),money(l.amount_cents)]))}<p>${x.approval?'主管独立批准：最低服务费 '+money(x.approval.minimum_fee_cents)+' 元；'+(x.approval.allow_below_minimum?'明确允许本版低价':'不允许低于最低额')+'。'+E(x.approval.reason):'尚无主管批准'}</p><p>${x.authorization?'客户授权原件编号 '+x.authorization.evidence_id:'尚无本版客户授权'}</p>`).join('')}</details>`);
 for(const l of r.lines){const submissions=r.submissions.filter(s=>s.line_key===l.line_key),last=submissions.at(-1),result=last?r.results.find(x=>x.submission_id===last.id):null;let actions='';
  if(summary.authorized&&!pending&&!terminated&&!l.fulfilled){if(r.kind==='agency'){if(!last||result?.outcome==='need_documents')actions+=button('submit',`data-line="${l.line_key}"`);if(last&&!result)actions+=button('external_result',`data-line="${l.line_key}"`);if(result?.outcome==='approved')actions+=button('fulfill',`data-line="${l.line_key}"`);}else actions+=button('fulfill',`data-line="${l.line_key}"`);}
  h+=panel(l.name,`<p>${E(serviceOrderBuckets[l.bucket])} · ${number(l.quantity_milli/1000)} ${E(l.unit)} · 原报价 ${money(l.amount_cents)} 元</p><p>当前收费 ${money(l.charge_cents)} 元；已付 ${money(l.paid_cents)} 元。${l.fulfilled?'已实际办结':'未确认办结'}</p>${l.bucket==='pass'?`<p>原代缴单位：${E(l.payee_snapshot.name)}<br>冻结收款户：${E(l.payee_snapshot.account_name)} · ${E(l.payee_snapshot.account_reference)}</p>`:''}${result?`<p>实际外部结果：${E({approved:'批准',rejected:'拒绝',need_documents:'要求补件'}[result.outcome])} · ${E(result.result)}</p>`:''}<div class="row">${actions}</div>`);
 }
 h+=panel('原客户资金分配',r.tenders.filter(t=>t.amount_cents>0).map(t=>`<div class="taskitem"><div class="description"><strong>${E(serviceOrderBuckets[t.bucket])} · ${t.payment_link_id?'现金原款':'本店预收抵用'} ${t.id}</strong><p>原额 ${money(t.amount_cents)} 元；尚未退 ${money(t.unrefunded_cents)} 元；已代缴净额 ${money(t.spent_cents)} 元</p><p>扣除获准退款后可用 ${money(t.available_cents)} 元</p>${t.bucket==='pass'&&t.available_cents>0&&!pending&&!terminated&&!r.lines.find(l=>l.line_key===t.line_key)?.fulfilled?button('disburse',`data-tender="${t.id}"`):''}</div></div>`).join('')||'<p>暂无收款</p>');
 h+=panel('实际第三方收支',r.pass_entries.map(e=>`<div class="taskitem"><div class="description"><strong>${e.purpose==='disburse'?'实际代缴':'第三方原路退回'} ${money(e.amount_cents)} 元</strong><p>${E(e.business_date)} · ${E(e.reference)} · 原本金分配 ${e.tender_id}</p>${e.purpose==='disburse'&&e.amount_cents>r.pass_entries.filter(x=>x.original_id===e.id).reduce((a,x)=>a+x.amount_cents,0)?button('thirdparty_return',`data-original="${e.id}"`):''}</div></div>`).join('')||'<p>尚无实际第三方收支。</p>');
 for(const p of r.plans){h+=panel('终止方案 '+p.revision,`<p>${p.cancelled?'已撤回':p.applied?'已生效':p.consented?'客户已同意，待财务生效':p.approved?'主管已批准，待客户同意':'待独立批准'} · ${E(p.reason)}</p>`+table(['原项目','保留费用（元）','减免（元）'],p.lines.map(l=>[E(r.lines.find(x=>x.line_key===l.line_key)?.name||l.line_key),money(l.retained_cents),money(l.credit_cents)]))+`<div class="row">${!p.approved&&!p.cancelled?button('termination_approve',`data-plan="${p.id}"`):''}${p.approved&&!p.consented&&!p.cancelled?button('consent',`data-plan="${p.id}"`):''}${p.consented&&!p.applied&&!p.cancelled?button('termination_apply',`data-plan="${p.id}"`):''}${!p.applied&&!p.cancelled?button('termination_cancel',`data-plan="${p.id}"`):''}</div>`+p.returns.map(x=>{const done=p.refunds.filter(f=>f.original_tender_id===x.tender_id).reduce((a,f)=>a+f.amount_cents,0);return `<p>原款分配 ${x.tender_id}：计划退 ${money(x.amount_cents)} 元，实际已退 ${money(done)} 元</p>${p.applied&&done<x.amount_cents?button('refund',`data-plan="${p.id}" data-tender="${x.tender_id}"`):''}`;}).join(''));}
 h+=panel('本单原件',b('upload','上传本次实际凭据')+'<p>报价、客户同意、提交和结果使用“客户授权”；真实收支及费用生效使用“收款凭据”。文件只作实际原件关联，系统不认证外部文件真实性。</p>'+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.label)} · ${E(f.security?.label||'待检查')}</p><div class="row">${b('filescaninfo','检查记录',`data-id="${f.id}"`)}${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'扫描通过后可用'}</div></div></div>`).join(''));
 h+=panel('岗位交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&['admin','manager'].includes(state.user.role)?b('assign','明确交接',`data-id="${t.id}"`):''}</div></div>`).join(''));return h;
}
async function serviceOrderNew(){
 const c=await api('/api/service-orders/catalog'),customers=c.customers.map(x=>x.id+' · '+x.name),sources=['不关联销售',...c.sources.map(x=>x.id+' · '+x.number)],vehicles=['不关联车辆',...c.vehicles.map(x=>x.id+' · '+x.vin)],request_id=requestKey();
 if(!customers.length)throw new Error('请先明确建立或选择本店客户主档。');
 await formDialog('建立客户服务',[F('subtype','业务类型','select',true,['代办服务','其它客户服务']),F('customer','本店客户','select',true,customers),F('source','原销售（可选）','select',true,sources),F('vehicle','客户车辆（可选）','select',true,vehicles),F('blocking','交车前是否必须办结','select',true,['允许后续办理','明确约定交车前办结']),F('due_date','约定办理期限','date'),F('reason','客户实际服务申请','textarea')],{subtype:'代办服务',source:sources[0],vehicle:vehicles[0],blocking:'允许后续办理',due_date:day()},v=>{const source=c.sources[sources.indexOf(v.source)-1];return api('/api/service-orders',{method:'POST',body:{request_id,subtype:v.subtype==='代办服务'?'agency':'other_income',customer_id:c.customers[customers.indexOf(v.customer)].id,source_order_id:source?.id||null,source_version:source?.version||null,customer_vehicle_id:c.vehicles[vehicles.indexOf(v.vehicle)-1]?.id||null,delivery_blocking:v.blocking==='明确约定交车前办结',due_date:v.due_date,reason:v.reason}}).then(r=>go('service-orders/'+r.id));},{notice:'其它客户服务仅用于有依据的客户服务收入，不登记借款、资产处置等非客户收入。'});
}
function serviceOrderSend(r,key,values,request_id){return api(`/api/service-orders/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values}});}
async function serviceOrderQuote(){
 const r=state.serviceOrder,c=state.serviceOrderCatalog,request_id=requestKey(),options=[...(r.kind==='agency'?c.projects:c.income_items).map(x=>({value:'fee:'+x.id,label:'服务费 · '+x.name})),...c.payees.map(x=>({value:'pass:'+x.id,label:'代缴 · '+x.name}))],rows=[...r.lines,...Array.from({length:3},()=>null)];
 if(!options.length)throw new Error('请先配置本店代办项目或其它客户服务项目。');
 modal('项目及报价版本',`<form><p>每项收费明确为服务费或代缴本金。整单折扣只分配到服务费；已有实际办理或收款的原行保留，增项另加新行并重新授权。</p>${rows.map((l,i)=>`<fieldset data-service-line data-line-key="${E(l?.line_key||'line'+(i+1))}"><legend>${l?E(l.name):'新增项目 '+(i+1)}</legend><label>项目<select name="source"><option value="">本行不使用</option>${options.map(o=>`<option value="${o.value}"${l&&o.value===l.bucket+':'+(l.agency_project_id||l.income_item_id||l.payee_id)?' selected':''}>${E(o.label)}</option>`).join('')}</select></label><label>代缴事项（本金行填写）<input name="name" value="${E(l?.bucket==='pass'?l.name:'')}"></label><div class="formgrid"><label>数量<input name="quantity" inputmode="decimal" value="${l?(l.quantity_milli/1000).toFixed(3):'1.000'}"></label><label>单价（元）<input name="price" inputmode="decimal" value="${l?(l.unit_price_cents/100).toFixed(2):''}"></label></div><label>约定到账日<input name="due_date" type="date" value="${E(l?.due_date||r.due_date)}"></label></fieldset>`).join('')}<label>本次新增服务费折扣（元）<input name="discount" inputmode="decimal" value="0.00" required></label><label>报价与增项原因<textarea name="reason" required minlength="2"></textarea></label><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">提交当前报价</button></div></form>`,async form=>{
  const lines=[...form.querySelectorAll('[data-service-line]')].filter(e=>e.querySelector('[name=source]').value).map(e=>{const [bucket,id]=e.querySelector('[name=source]').value.split(':');return {line_key:e.dataset.lineKey,bucket,...(bucket==='pass'?{payee_id:Number(id),name:e.querySelector('[name=name]').value}:r.kind==='agency'?{agency_project_id:Number(id)}:{income_item_id:Number(id)}),quantity_milli:repairScaled(e.querySelector('[name=quantity]').value,3),unit_price_cents:repairScaled(e.querySelector('[name=price]').value,2),due_date:e.querySelector('[name=due_date]').value};});
  await serviceOrderSend(r,'quote',{lines,discount_cents:repairScaled(form.elements.discount.value,2),reason:form.elements.reason.value},request_id);closeModal();await render();
 });
}
async function serviceOrderTermination(){
 const r=state.serviceOrder,request_id=requestKey(),files=state.row.files.filter(f=>!f.generated&&f.category==='authorization'&&f.security?.can_use);
 modal('终止与原款退款方案',`<form><p>逐项明确已履约保留费。代缴仅保留第三方实际净支出，未用或已实际退回的本金退原客户。每行退款选择必须恰好等于本行已收超过保留费部分。</p>${r.lines.map(l=>`<label data-service-retained="${l.line_key}">${E(l.name)} · 当前 ${money(l.charge_cents)} 元，已收 ${money(l.paid_cents)} 元<input name="retained" inputmode="decimal" value="${(l.charge_cents/100).toFixed(2)}"></label>`).join('')}${r.tenders.filter(t=>t.amount_cents>0&&t.available_cents>0).map(t=>`<label data-service-return="${t.id}">原款 ${t.id} · ${E(serviceOrderBuckets[t.bucket])} · 可用 ${money(t.available_cents)} 元<input name="return_amount" inputmode="decimal" placeholder="本次退回金额，未选留空"></label>`).join('')}<label>实际办理、终止及保留费原因<textarea name="reason" required minlength="2"></textarea></label><label>本次方案原件<select name="evidence_id" required>${files.map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">提交独立复核</button></div></form>`,async form=>{const lines=[...form.querySelectorAll('[data-service-retained]')].map(e=>({line_key:e.dataset.serviceRetained,retained_cents:repairScaled(e.querySelector('input').value,2)})),returns=[...form.querySelectorAll('[data-service-return]')].filter(e=>e.querySelector('input').value.trim()).map(e=>({tender_id:Number(e.dataset.serviceReturn),amount_cents:repairScaled(e.querySelector('input').value,2)}));await serviceOrderSend(r,'termination',{lines,returns,reason:form.elements.reason.value,evidence_id:Number(form.elements.evidence_id.value)},request_id);closeModal();await render();});
}
async function serviceOrderAction(key,e){
 if(key==='quote')return serviceOrderQuote();if(key==='termination')return serviceOrderTermination();
 const r=state.serviceOrder,request_id=requestKey(),fields=[],values={},initial={},line=e.dataset.line,plan=Number(e.dataset.plan),tender=Number(e.dataset.tender),original=Number(e.dataset.original);
 if(line)values.line_key=line;if(plan)values.plan_id=plan;if(tender)values.tender_id=tender;if(original)values.original_id=original;
 if(key==='approve'){fields.push(F('minimum','本版最低服务费（元）','money'),F('allow','是否明确批准低于最低额','select',true,['不允许低于最低额','明确批准本版低价']),F('reason','主管核价与授权原因','textarea'));initial.minimum=(r.quote.fee_cents/100).toFixed(2);initial.allow='不允许低于最低额';}
 if(key==='authorize')values.quote_id=r.quote.id;
 if(key==='submit'){fields.push(F('external_reference','实际外部受理编号'),F('submitted_on','实际提交日期','date'));initial.submitted_on=day();const last=r.submissions.filter(x=>x.line_key===line).at(-1),result=last?r.results.find(x=>x.submission_id===last.id):null;if(result?.outcome==='need_documents')values.supplement_result_id=result.id;}
 if(key==='external_result'){values.submission_id=r.submissions.filter(x=>x.line_key===line).at(-1).id;fields.push(F('outcome','实际办理结果','select',true,['批准','拒绝','要求补件']),F('result','本人核对的实际外部结果','textarea'));}
 if(key==='fulfill')fields.push(F('result','本人实际办结及客户交接结果','textarea'));
 if(['cancel','termination_cancel'].includes(key))fields.push(F('reason','撤回原因','textarea'));
 const cash=['receive','disburse','thirdparty_return','refund'].includes(key),creditRefund=key==='refund'&&r.tenders.find(x=>x.id===tender)?.credit_link_id;
 if(cash){fields.push(F('amount','本次实际金额（元）','money'));if(!creditRefund)fields.push(F('account_id','原资金账户','account'),F('reference','本次独立流水或凭证号'));
  if(tender&&!creditRefund)initial.account_id=r.tenders.find(x=>x.id===tender)?.account_id;if(original)initial.account_id=r.pass_entries.find(x=>x.id===original)?.account_id;}
 if(!['cancel','termination_cancel'].includes(key))fields.push(F('evidence_id','本单本次实际原件','file'));
 await formDialog(serviceOrderNames[key],fields,initial,v=>{const body={...v,...values};if('amount'in body){body.amount_cents=repairScaled(body.amount,2);delete body.amount;}if('minimum'in body){body.minimum_fee_cents=repairScaled(body.minimum,2);delete body.minimum;body.allow_below_minimum=body.allow==='明确批准本版低价';delete body.allow;}if('outcome'in body)body.outcome={批准:'approved',拒绝:'rejected',要求补件:'need_documents'}[body.outcome];return serviceOrderSend(r,key,body,request_id);},{caseId:r.id,notice:creditRefund?'本步骤只将原抵用额恢复到原本店预收余额，不产生客户现金退款。':'仅确认本人已实际核对的结果。审批与客户授权都不会自动记录现金。'});
}
async function serviceOrderMaster(kind){
 const fields=[F('code','本店稳定编码'),F('name','名称')],request_id=requestKey();
 if(kind==='payees')fields.push(F('account_name','真实第三方收款户名'),F('account_reference','第三方收款账户或缴费识别号'));else fields.push(F('unit','计价单位'),F('standard_fee','标准服务费（元）','money'));
 await formDialog(kind==='payees'?'新增代缴单位':'新增其它客户服务项目',fields,{},v=>{const values={...v};if(kind==='income-items'){values.standard_fee_cents=repairScaled(values.standard_fee,2);delete values.standard_fee;}return api('/api/service-orders/'+kind,{method:'POST',body:{request_id,...values}});});
}
document.addEventListener('click',async event=>{const e=event.target.closest('[data-act]');if(!e?.dataset.act.startsWith('serviceorder-'))return;try{if(e.dataset.act==='serviceorder-new')await serviceOrderNew();if(e.dataset.act==='serviceorder-master')await serviceOrderMaster(e.dataset.kind);if(e.dataset.act==='serviceorder-action')await serviceOrderAction(e.dataset.key,e);}catch(error){toast(error.message,true);}});
