'use strict';
let transferExceptionContext=null;
function clearTransferExceptionsSession(){transferExceptionContext=null;}
const transferExceptionStages={outbound:'发出后尚未验收',rejected:'已拒收、尚未退回发运',returning:'已退回发运、尚未入库'};
const transferExceptionActions={observe:'本人追加实物核对',plan:'拟定双方成本承担',approve:'独立批准本版方案',reject_plan:'退回重新核对',dispose:'确认本店实际处置',post_loss:'确认原在途损失',cancel:'取消未生效差异',recovery_create:'确认实际追偿目标',recovery_plan:'追加赔付目标版本',recovery_approve:'独立批准追偿目标',recovery_reject:'拒绝本版追偿目标',recovery_cancel:'撤回未生效追偿目标',recovery_receive:'登记实际赔款到账',recovery_refund:'退回原超收赔款'};
const transferObservationNames={dispatch_verified:'本人核对原发运',return_dispatch_verified:'本人核对退回发运',missing:'本人核对尚未收到',held_damaged:'本人核对在手坏件'};
const transferRecoveryStates={pending:'待独立复核',approve:'已批准',reject:'已拒绝',cancelled:'未生效已撤回'};
function transferExceptionMoney(value){return moneyFen(value,{label:'金额',allowZero:true});}
function transferExceptionFiles(files,financial){const allowed=financial?['receipt','procurement_contract']:['evidence','inspection','authorization'];return files.filter(f=>!f.generated&&allowed.includes(f.category)&&f.security?.can_use);}
function transferExceptionProof(files,financial){return `<label>本店实际${financial?'财务凭据或协议':'实物凭据'}<select name="evidence_id" required><option value="">请选择本单已通过文件检查的原件</option>${transferExceptionFiles(files,financial).map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label>`;}
async function transferExceptionsPage(id){
 if(state.store==='all')return heading('物资调拨运输差异')+storeNotice()+'<div class="notice">请选择本店。双方各自确认实物和资金，集团汇总不办理原单。</div>';
 if(!id){const d=await api('/api/transfer-exceptions');return heading('物资调拨运输差异','',canWrite()&&['admin','inventory'].includes(state.user.role)?b('transfer-exception-new','选择原调拨核对','','primary'):'')+panel('本店差异',table(['原调拨','物资与数量','状态',''],d.items.map(r=>[E(r.transfer_number),`${E(r.item_name)}<br>${transferQuantity(r.quantity_milli)} ${E(r.unit)}`,E(r.status_label),b('open','办理',`data-route="transfer-exceptions/${r.id}"`)])));}
 const r=await api('/api/transfer-exceptions/'+id);transferExceptionContext=r;state.row=await api('/api/flow/cases/'+r.case_id);
 const actions=r.actions.filter(a=>a!=='recovery_create');
 return heading('调拨运输差异',r.transfer_number+' · '+r.item_name,b('open','返回差异','data-route="transfer-exceptions"'))+
 panel('本次原实物',`<strong>${E(r.status_label)}</strong><p>${E(transferExceptionStages[r.stage])} · ${r.finding==='missing'?'尚未收到':'在手坏件'} ${transferQuantity(r.quantity_milli)} ${E(r.unit)}</p><p>${E(r.reason)}</p>${r.paused?'<div class="notice">本调拨所有收发暂时暂停。完成本次差异或有据取消后恢复；已经入库的物资不在此减少。</div>':''}<div class="row">${b('open','原调拨',`data-route="transfers/${r.transfer_id}"`)}${b('open','本店原单任务',`data-route="case/${r.case_id}"`)}</div><div class="row">${canWrite()?actions.map(a=>b('transfer-exception-action',transferExceptionActions[a],`data-key="${a}"`,['approve','post_loss'].includes(a)?'primary':'')).join(''):''}</div>`)+
 panel('双方实际核对',table(['日期','本人核对范围','结果','凭据'],r.observations.map(o=>[E(o.business_date),E(transferObservationNames[o.observation]),E(o.result),o.evidence_id?b('downloadfile','本店原件',`data-id="${o.evidence_id}"`):'对方原件按其门店权限保管'])))+
 panel('承担方案与复核',r.plans.length?r.plans.map(p=>`<article class="transfer-mobile-line"><strong>方案第 ${p.revision} 版</strong>${p.source_bearer_cents===undefined?'':`<p>原损失 ${money(r.value_cents)} 元；调出店承担 ${money(p.source_bearer_cents)} 元，调入店承担 ${money(p.destination_bearer_cents)} 元。</p><p>${E(p.reason)}</p>`}<p>${p.reviews.map(v=>v.decision==='approve'?'一方主管已独立批准':'一方主管已退回核对').join('；')||'尚待主管复核'}</p></article>`).join(''):empty('等待双方核对','两个岗位分别确认后，调出店财务才能拟定成本承担。'))+
 (r.disposals.length?panel('真实处置',table(['日期','数量','实际结果'],r.disposals.map(d=>[E(d.business_date),transferQuantity(d.quantity_milli)+' '+E(r.unit),E(d.method)]))):'')+
 (full()&&r.status==='posted'?panel('本店外部追偿',`<p>本店本次原损失承担 ${money(r.recovery_cap_cents)} 元。只有承运人或保险公司已实际确认的赔付才能提交目标；批准应收不会生成现金。</p>${canWrite()&&r.actions.includes('recovery_create')?b('transfer-exception-action','确认实际追偿目标','data-key="recovery_create"'):''}${r.recoveries.map(c=>`<article class="transfer-mobile-line"><strong>${E(c.counterparty_name)}</strong><p>已确认目标 ${money(c.target_cents)} 元 · 已实收净额 ${money(c.paid_cents)} 元</p><p>尚待收 ${money(c.due_cents)} 元 · 应退原款 ${money(c.refund_cents)} 元${c.pending_plan_id?'；新目标在审，收退款暂停':''}</p>${c.plans.map(p=>`<p>目标第 ${p.revision} 版：${money(p.target_cents)} 元 · ${transferRecoveryStates[p.status]}<br>${E(p.reason)}</p>`).join('')}${c.payments.length?table(['实际日期','款项','金额（元）'],c.payments.map(p=>[E(p.business_date),p.direction==='in'?'真实赔款到账':'原赔款退回',money(p.amount_cents)])):''}<div class="row">${canWrite()?c.actions.map(a=>b('transfer-exception-action',transferExceptionActions[a],`data-key="${a}" data-claim="${c.id}"`)).join(''):''}</div></article>`).join('')}`):'')+
 (r.status==='posted'?panel('原物资找回',`${r.active_goods_recovery_id?'<div class="notice">原物资找回仍在处理，旧追偿入口暂停；原赔付条件及超收退款在找回页面办理。</div>':'<p>原损失不覆盖；实际找到原物资后，分别核对复验、原成本和实际赔付条件。</p>'}<div class="row">${canWrite()&&['admin','inventory'].includes(state.user.role)?b('transfer-goods-new','登记本人实际找到',`data-transfer="${r.transfer_id}"`):''}${(r.goods_recovery_ids||[]).map(id=>b('open','找回处理 '+id,`data-route="transfer-goods-recoveries/${id}"`)).join('')}</div>`):'')+
 panel('本店文件与凭据',`<div class="filetools">${canWrite()?b('upload','上传实际文件','','primary'):''}</div>${fileList(state.row.files)}`);
}
async function transferExceptionNew(transferId){
 if(!transferId){const d=await api('/api/transfers');const candidates=d.items.filter(t=>t.status==='transit');modal('选择尚在途的原调拨',`<form><label>本店原调拨<select name="transfer" required><option value="">请选择</option>${candidates.map(t=>`<option value="${t.id}">${E(t.number)} · ${E(t.side==='source'?t.to_store_name:t.from_store_name)}</option>`).join('')}</select></label><p>新运输差异只用于第三版新调拨；旧单保留原流程含义。</p><div class="formerror" role="alert"></div><button type="submit" class="primary">核对原批次</button></form>`,async form=>{const id=Number(form.elements.transfer.value);closeModal();await transferExceptionNew(id);});return;}
 const r=await api('/api/transfer-exceptions/origins/'+transferId);
 if(r.active_exception_id){go('transfer-exceptions/'+r.active_exception_id);return;}
 if(!r.origins.length)throw new Error('该调拨当前没有可核对的尚未处理原批次。');
 const own=await api('/api/flow/cases/'+r.case_id),request_id=requestKey();
 const dialog=modal('核对原调拨运输差异',`<form><p>${E(r.number)}。先记录实际合格入库或实际已退回部分，再提交剩余短缺或坏件。</p><label>本次原批次<select name="original" required>${r.origins.map(o=>`<option value="${o.id}">${E(o.name)} · ${E(transferExceptionStages[o.stage])} · 剩余 ${transferQuantity(o.remaining_milli)} ${E(o.unit)}</option>`).join('')}</select></label><label>本次尚未处理数量<input name="quantity" inputmode="decimal" required></label><label>本人实际核对结果<select name="finding"><option value="missing">尚未收到</option><option value="damaged">本店或对方在手坏件（已有实际拒收）</option></select></label><label>本人核对的发运、短缺或在手情况<textarea name="result" minlength="4" maxlength="1000" required></textarea></label><label>约定下一次核对日期<input name="due" type="date" value="${day()}" required></label>${transferExceptionProof(own.files,false)}<label><input type="checkbox" name="confirmed" required>我确认本店原实物与以上观察；不代另一门店作证。</label><p>调查期间本调拨收发暂停。没有实际处置或损失前，可有据取消。</p><div class="formerror" role="alert"></div><button class="primary" type="submit">提交本店实际观察</button></form>`,async form=>{const original=r.origins.find(x=>x.id===Number(form.elements.original.value));const finding=form.elements.finding.value;if(!original.findings.includes(finding))throw new Error('已到达坏件须先实际拒收，再选择拒收批次。');const quantity=transferQty(form.elements.quantity.value);if(quantity>original.remaining_milli)throw new Error('本次不能超过该原批次尚未处理数量。');const created=await api('/api/transfer-exceptions',{method:'POST',body:{request_id,transfer_id:r.transfer_id,version:r.version,case_version:r.case_version,original_id:original.id,quantity_milli:quantity,finding,result:form.elements.result.value,due_date:form.elements.due.value,evidence_id:Number(form.elements.evidence_id.value),confirmed:form.elements.confirmed.checked}});closeModal();go('transfer-exceptions/'+created.id);});
 const update=()=>{const o=r.origins.find(x=>x.id===Number(dialog.querySelector('[name=original]').value));dialog.querySelector('[name=quantity]').value=String(o.remaining_milli/1000);dialog.querySelector('[name=finding] option[value=damaged]').disabled=!o.findings.includes('damaged');dialog.querySelector('[name=finding]').value='missing';};dialog.querySelector('[name=original]').addEventListener('change',update);update();
}
async function transferExceptionAction(key,claimId){
 const r=await api('/api/transfer-exceptions/'+transferExceptionContext.id),own=await api('/api/flow/cases/'+r.case_id),request_id=requestKey();transferExceptionContext=r;
 const claim=claimId?r.recoveries.find(c=>c.id===Number(claimId)):null,financial=['plan','approve','reject_plan','post_loss'].includes(key)||key.startsWith('recovery_');
 let fields='',notice='',catalog=null;
 if(key==='plan'){fields=`<label>调出店承担（元）<input name="source" value="${(r.value_cents/100).toFixed(2)}" inputmode="decimal" required></label><label>调入店承担（元）<input name="destination" value="0.00" inputmode="decimal" required></label>`;notice=`两店合计必须等于原损失 ${money(r.value_cents)} 元。调入店承担产生双方往来，不是银行付款。`;}
 if(['observe','dispose'].includes(key))fields+='<label>本人实际核对或处置结果<textarea name="result" minlength="4" maxlength="1000" required></textarea></label>';
 if(['recovery_create','recovery_plan'].includes(key)){
  if(key==='recovery_create'){catalog=await api('/api/transfer-exceptions/recovery-catalog');fields+='<label>实际承担赔付的往来方<select name="party" required><option value="">请选择本店往来方</option>'+catalog.parties.map(p=>`<option value="${p.kind}:${p.id}">${p.kind==='carrier'?'承运单位':'保险公司'} · ${E(p.name)}</option>`).join('')+'</select></label>';}
  fields+=`<label>往来方实际确认的累计赔付目标（元）<input name="target" inputmode="decimal" value="${claim?(claim.target_cents/100).toFixed(2):''}" required></label><label>实际约定应收日期<input name="due" type="date" value="${day()}" required></label>`;
  notice='凭据须证明往来方实际确认，而非本店单方面索赔。减少目标须独立复核；已多收款项退回原账户后才释放可再追偿额度。';
 }
 if(['recovery_receive','recovery_refund'].includes(key)){
  catalog=await api('/api/transfer-exceptions/recovery-catalog');const refund=key==='recovery_refund';
  fields+=refund?`<label>本次退回的原实收<select name="original" required>${claim.payments.filter(p=>p.direction==='in'&&p.unreturned_cents>0).map(p=>`<option value="${p.id}">${E(p.business_date)} · 原实收 ${money(p.amount_cents)} 元 · 尚未退 ${money(p.unreturned_cents)} 元</option>`).join('')}</select></label>`:'';
  fields+=`<label>本次实际${refund?'退款':'到账'}（元）<input name="amount" inputmode="decimal" required></label><label>本店实际资金账户<select name="account" required><option value="">请选择</option>${catalog.accounts.map(a=>`<option value="${a.id}">${E(a.name)}</option>`).join('')}</select></label><label>实际银行流水<input name="reference" minlength="2" maxlength="100" required></label><label>实际发生日期<input name="actual" type="date" value="${day()}" max="${day()}" required></label>`;
  notice=refund?`本目标最多应退 ${money(claim.refund_cents)} 元，还须受该笔原实收未退额限制。原账户退回，不形成客户退款。`:`已确认尚待收 ${money(claim.due_cents)} 元；只登记已实际到账的原件，不把任务或批准当付款。`;
 }
 if(!['observe','dispose','post_loss','recovery_receive','recovery_refund'].includes(key))fields+='<label>本次事实与理由<textarea name="reason" minlength="4" maxlength="1000" required></textarea></label>';
 if(['observe','dispose','post_loss','recovery_receive','recovery_refund'].includes(key))fields+='<label><input name="confirmed" type="checkbox" required>本人已经核对本次实际事实与原件。</label>';
 modal(transferExceptionActions[key],`<form>${notice?`<p>${E(notice)}</p>`:''}<div class="formgrid">${fields}${transferExceptionProof(own.files,financial)}</div><div class="formerror" role="alert"></div><button type="submit" class="primary">${E(transferExceptionActions[key])}</button></form>`,async form=>{
  const v={evidence_id:Number(form.elements.evidence_id.value)};if(form.elements.reason)v.reason=form.elements.reason.value;if(form.elements.result)v.result=form.elements.result.value;if(form.elements.confirmed)v.confirmed=form.elements.confirmed.checked;
  if(key==='plan'){v.source_bearer_cents=transferExceptionMoney(form.elements.source.value);v.destination_bearer_cents=transferExceptionMoney(form.elements.destination.value);if(v.source_bearer_cents+v.destination_bearer_cents!==r.value_cents)throw new Error('双方承担合计必须恰好等于原批损失成本。');}
  if(['approve','reject_plan'].includes(key))v.plan_id=r.plans.at(-1).id;
  if(claim){v.claim_id=claim.id;v.claim_version=claim.version;}
  if(['recovery_approve','recovery_reject','recovery_cancel'].includes(key))v.plan_id=claim.pending_plan_id;
  if(['recovery_create','recovery_plan'].includes(key)){v.target_cents=transferExceptionMoney(form.elements.target.value);v.due_date=form.elements.due.value;if(key==='recovery_create'){const [kind,id]=form.elements.party.value.split(':');v.counterparty_kind=kind;v.counterparty_id=Number(id);}}
  if(['recovery_receive','recovery_refund'].includes(key)){v.amount_cents=transferExceptionMoney(form.elements.amount.value);v.account_id=Number(form.elements.account.value);v.reference=form.elements.reference.value;v.business_date=form.elements.actual.value;if(key==='recovery_refund')v.original_id=Number(form.elements.original.value);}
  await api(`/api/transfer-exceptions/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,transfer_version:r.transfer_version,case_version:r.case_version,values:v}});closeModal();await render();
 });
}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el||el.disabled)return;try{if(el.dataset.act==='transfer-exception-new')await transferExceptionNew(el.dataset.transfer?Number(el.dataset.transfer):null);if(el.dataset.act==='transfer-exception-action')await transferExceptionAction(el.dataset.key,el.dataset.claim);}catch(error){toast(error.message,true);}});
