'use strict';
let transferGoodsContext=null;
function clearTransferGoodsRecoverySession(){transferGoodsContext=null;}
const transferGoodsActions={match:'本人核对原损失关联',inspect:'本人实际复验',ship:'确认本店实际发回',receive:'确认实际收到并复验',plan:'核对原成本恢复方案',approve:'独立批准本版方案',reject:'退回补充核对',dispose:'确认本店实际处置坏件',restore:'确认合格原物资入库',finish_bad:'核对处置并保留原损失',cancel:'撤回误关联的找回',terms:'登记往来方新的实际条件',terms_approve:'独立确认本版赔付条件',terms_reject:'拒绝本版赔付条件',terms_cancel:'撤回本版赔付条件',pending_cancel:'撤回原未批准赔付目标',refund:'登记原赔款实际退回',trace_open:'申报原退运查找结果',trace_approve:'独立同意结束本次查找',trace_reject:'退回继续核对',refind:'登记该次物资再次找到'};
const transferGoodsFacts={found:'本人实际找到',match:'本人核对原损失关联',inspect:'本人实际复验',ship:'本店实际发回',receive:'原店实际收到并复验',dispose:'本店实际处置坏件',cancel:'原关联有据撤回'};
const transferGoodsTerms={pending:'待独立复核',approve:'已独立确认',reject:'已拒绝',cancelled:'未生效已撤回'};
function transferGoodsProof(files,financial){const allowed=financial?['receipt','procurement_contract']:['evidence','inspection','authorization'];return `<label>本店实际${financial?'财务原件或协议':'实物原件'}<select name="evidence_id" required><option value="">请选择本单通过文件检查的实际原件</option>${files.filter(f=>!f.generated&&allowed.includes(f.category)&&f.security?.can_use).map(f=>`<option value="${f.id}">${E(f.name)}</option>`).join('')}</select></label>`;}
async function transferGoodsRecoveryPage(id){
 if(state.store==='all')return heading('损失后找到原物资')+storeNotice()+'<div class="notice">请选择门店</div>';
 if(!id){const d=await api('/api/transfer-goods-recoveries');return heading('损失后找到原物资','',canWrite()&&['admin','inventory'].includes(state.user.role)?b('transfer-goods-new','登记实际找到','','primary'):'')+panel('本店找回记录',table(['原调拨','本次物资','状态',''],d.items.map(r=>[E(r.transfer_number),`${E(r.item_name)}<br>${transferQuantity(r.quantity_milli)} ${E(r.unit)}`,E(r.status_label),b('open','办理',`data-route="transfer-goods-recoveries/${r.id}"`)])));}
 const r=await api('/api/transfer-goods-recoveries/'+id);transferGoodsContext=r;state.row=await api('/api/flow/cases/'+r.case_id);
 return heading('损失后找到原物资',r.transfer_number+' · '+r.item_name,b('open','返回找回记录','data-route="transfer-goods-recoveries"'))+
 panel('本次实际找回',`<strong>${E(r.status_label)}</strong><p>${E(r.found_store_name)} 实际找到 ${transferQuantity(r.quantity_milli)} ${E(r.unit)}；${r.custody_store_name?'当前保管：'+E(r.custody_store_name):r.status==='unlocated'?'本次查找已结束，仍未实际找到':'实际退运中，尚未收到'}。</p><p>${E(r.reason)}</p><div class="notice">原损失保留。实际找到与复验不自动变成可用库存；赔款按往来方明确条件处理，批准不代表实际退款。</div><div class="row">${b('open','原调拨',`data-route="transfers/${r.transfer_id}"`)}${b('open','原运输差异',`data-route="transfer-exceptions/${r.exception_id}"`)}${b('open','本店原单任务',`data-route="case/${r.case_id}"`)}</div><div class="row">${canWrite()?r.actions.map(a=>b('transfer-goods-action',transferGoodsActions[a],`data-key="${a}"`,['approve','restore'].includes(a)?'primary':'')).join(''):''}</div>`)+
 panel('双方本人事实',r.facts.map(f=>`<article class="transfer-mobile-line"><strong>${E(transferGoodsFacts[f.kind])}</strong><p>${E(f.business_date)} · ${E(f.store_name)} · ${transferQuantity(f.quantity_milli)} ${E(r.unit)}${f.passed===null?'':f.passed?' · 复验合格':' · 复验不合格'}</p><p>${E(f.result)}</p>${f.evidence_id?b('downloadfile','查看本店原件',`data-id="${f.evidence_id}"`):'<p class="muted">对方原件由其门店保管</p>'}</article>`).join(''))+
 (r.searches?.length?panel('原退运查找与后续找到',`<div class="notice">结束查找不再登记第二笔损失，不自动产生库存、现金或赔款。后来实际找到另记原关联，原退运与复核保留。</div>${r.previous_recovery_id?b('open','查看上一次原查找',`data-route="transfer-goods-recoveries/${r.previous_recovery_id}"`):''}${r.searches.map(s=>`<article class="transfer-mobile-line"><strong>查找第 ${s.revision} 版 · ${E(s.status_label)}</strong><p>${E(s.business_date)} · ${E(s.reason)}</p>${s.evidence_id?b('downloadfile','本店查找原件',`data-id="${s.evidence_id}"`):'<p class="muted">另一门店原件不随关联公开</p>'}${s.reviews.map(v=>`<p>${v.is_local?'本店':'另一门店'}：${v.decision==='end_search'?'同意结束本次查找':'退回继续核对'} · ${E(v.reason)} ${v.evidence_id?b('downloadfile','本店复核原件',`data-id="${v.evidence_id}"`):''}</p>`).join('')}</article>`).join('')}${r.status==='unlocated'?`<p>该次尚可关联的再次找到量：${transferQuantity(r.reappearance_remaining_milli)} ${E(r.unit)}；不等于在手库存。</p>`:''}${(r.reappearances||[]).map(link=>b('open','查看再次找到 '+transferQuantity(link.quantity_milli)+' '+r.unit,`data-route="transfer-goods-recoveries/${link.recovery_id}"`)).join('')}`):r.previous_recovery_id?panel('上一次原查找',b('open','查看该物资原退运查找',`data-route="transfer-goods-recoveries/${r.previous_recovery_id}"`)):'')+
 panel('原成本方案及独立复核',r.plans.length?r.plans.map(p=>`<article class="transfer-mobile-line"><strong>第 ${p.revision} 版</strong><p>${p.restored_quantity_milli?'本版拟恢复合格原物资 '+transferQuantity(p.restored_quantity_milli)+' '+E(r.unit):'坏件实际处置，不恢复库存及承担'}</p>${p.value_cents===undefined?'':`<p>原成本恢复 ${money(p.value_cents)} 元；${E(r.source_store_name)} 承担冲回 ${money(p.source_reverse_cents)} 元，${E(r.destination_store_name)} 承担冲回 ${money(p.destination_reverse_cents)} 元。</p><p>${E(p.reason)}</p>`}<p>${p.reviews.map(v=>`${E(v.store_name)}：${v.decision==='approve'?'已独立批准':'已退回核对'}`).join('<br>')||'尚待两店分别复核'}</p></article>`).join(''):empty('等待实际核对与复验','合格物资必须实际回到原调出店，才可拟定原成本恢复。'))+
 (r.claims?panel('本店原赔付处理',`<p>找回后本店剩余原承担 ${money(r.remaining_burden_cents)} 元。原实收继续占用额度，先明确往来方真实条件，再登记原账户实际退回；不因为找到就猜测应退金额。</p>${r.claims.length?r.claims.map(c=>`<article class="transfer-mobile-line"><strong>${E(c.counterparty)}</strong><p>当前累计目标 ${money(c.target_cents)} 元 · 原实收净额 ${money(c.paid_cents)} 元 · 原款待退 ${money(c.refund_cents)} 元</p>${c.pending_plan_id?'<p class="notice">有尚未独立确认的条件；实际退款须等本版明确。</p>':''}${c.terms.map(t=>`<p>原赔付第 ${t.revision} 版：${money(t.target_cents)} 元 · ${transferGoodsTerms[t.status]}<br>${E(t.reason)}</p>`).join('')}${c.payments.length?table(['实际日期','原款事实','金额（元）'],c.payments.map(p=>[E(p.business_date),p.direction==='in'?'原实际到账':'原赔款实际退回',money(p.amount_cents)])):''}<div class="row">${canWrite()?c.actions.map(a=>b('transfer-goods-action',transferGoodsActions[a],`data-key="${a}" data-claim="${c.id}"`)).join(''):''}</div></article>`).join(''):'<p>本店没有与本损失关联的原追偿条目。</p>'}`):'')+
 panel('本店原件',`<div class="filetools">${canWrite()?b('upload','上传实际文件','','primary'):''}</div>${fileList(state.row.files)}`);
}
async function transferGoodsRecoveryNew(transferId,previousId=null){
 if(!transferId){const d=await api('/api/transfers'),rows=d.items.filter(t=>t.flow_version===3&&t.lines.some(l=>l.lost_milli>0));modal('选择原已核销损失',`<form><label>本店原调拨<select name="transfer" required><option value="">请选择含已确认原损失的调拨</option>${rows.map(t=>`<option value="${t.id}">${E(t.number)} · ${E(t.from_store_name)} → ${E(t.to_store_name)}</option>`).join('')}</select></label><div class="formerror" role="alert"></div><button type="submit" class="primary">核对原损失批次</button></form>`,async form=>{const id=Number(form.elements.transfer.value);closeModal();await transferGoodsRecoveryNew(id);});return;}
 const d=await api('/api/transfer-goods-recoveries/origins/'+transferId);
 if(d.active_recovery_id){go('transfer-goods-recoveries/'+d.active_recovery_id);return;}
 const choices=d.items.filter(i=>i.available_quantity_milli>0&&(!previousId||(i.prior_recoveries||[]).some(r=>r.recovery_id===previousId)));
 if(!choices.length)throw new Error('该原损失或原查找没有尚可关联的找到量，请刷新核对；已处理批次不能再次入库。');
 const own=await api('/api/flow/cases/'+d.case_id),request_id=requestKey();
 const dialog=modal('登记本店实际找到',`<form><p>本次只登记可以辨认的一份实际原物资；存在之前的退运查找时，请明确是哪个原记录，不以通知或照片代替实到。</p><label>原损失批次<select name="loss" required>${choices.map(i=>`<option value="${i.loss_id}">${E(i.name)} · 尚可核对 ${transferQuantity(i.available_quantity_milli)} ${E(i.unit)}</option>`).join('')}</select></label><label>本次找到与原查找的关系<select name="previous" required></select></label><p class="muted" data-found-limit></p><label>本人实际找到数量<input name="quantity" inputmode="decimal" required></label><label>本人找到地点、暂管及原物资关联<textarea name="result" minlength="4" maxlength="1000" required></textarea></label><label>下次核对日期<input name="due" type="date" value="${day()}" required></label>${transferGoodsProof(own.files,false)}<label><input name="confirmed" type="checkbox" required>本人已核对实际找到及暂管事实；不代另一门店作证。</label><div class="formerror" role="alert"></div><button type="submit" class="primary">提交本人实际找到</button></form>`,async form=>{
  const item=choices.find(i=>i.loss_id===Number(form.elements.loss.value)),qty=transferQty(form.elements.quantity.value),prior=form.elements.previous.value;
  if(!prior)throw new Error('请明确本次与原查找的关系。');
  const original=prior==='new'?null:item.prior_recoveries.find(r=>r.recovery_id===Number(prior));
  if(prior!=='new'&&!original)throw new Error('原查找来源已变化，请刷新。');
  const limit=Math.min(item.available_quantity_milli,original?original.available_quantity_milli:item.available_quantity_milli);
  if(qty>limit)throw new Error('本次找到量超过原损失或该次原查找尚可关联量。');
  const body={request_id,transfer_id:d.transfer_id,loss_id:item.loss_id,version:d.version,case_version:d.case_version,quantity_milli:qty,result:form.elements.result.value,evidence_id:Number(form.elements.evidence_id.value),due_date:form.elements.due.value,confirmed:form.elements.confirmed.checked};
  if(original)body.previous_recovery_id=original.recovery_id;
  const row=await api('/api/transfer-goods-recoveries',{method:'POST',body});closeModal();go('transfer-goods-recoveries/'+row.id);
 });
 const source=dialog.querySelector('[name=previous]'),loss=dialog.querySelector('[name=loss]');
 const limit=()=>{const item=choices.find(i=>i.loss_id===Number(loss.value)),prior=(item.prior_recoveries||[]).find(r=>r.recovery_id===Number(source.value));dialog.querySelector('[data-found-limit]').textContent='原关联最多尚可核对 '+transferQuantity(Math.min(item.available_quantity_milli,prior?prior.available_quantity_milli:item.available_quantity_milli))+' '+item.unit+'；请填写本次实际找到量，不自动补满。';};
 const update=()=>{const item=choices.find(i=>i.loss_id===Number(loss.value)),prior=item.prior_recoveries||[];source.innerHTML=(previousId?'':'<option value="">请选择本次实际来源</option><option value="new">新找到的原损失物资，不属于已结束的原退运查找</option>')+prior.filter(r=>!previousId||r.recovery_id===previousId).map(r=>`<option value="${r.recovery_id}">原找回记录 ${r.recovery_id} · 已结束查找，尚可关联 ${transferQuantity(r.available_quantity_milli)} ${E(item.unit)}</option>`).join('');if(previousId)source.value=String(previousId);else if(!prior.length)source.value='new';dialog.querySelector('[name=quantity]').value='';limit();};
 loss.addEventListener('change',update);source.addEventListener('change',limit);update();
}
async function transferGoodsRecoveryAction(action,claimId){
 if(action==='refind'){const row=await api('/api/transfer-goods-recoveries/'+transferGoodsContext.id);await transferGoodsRecoveryNew(row.transfer_id,row.id);return;}
 const r=await api('/api/transfer-goods-recoveries/'+transferGoodsContext.id),own=await api('/api/flow/cases/'+r.case_id),claim=claimId?r.claims.find(c=>c.id===Number(claimId)):null,request_id=requestKey();
 const financial=['plan','approve','reject','finish_bad','terms','terms_approve','terms_reject','terms_cancel','pending_cancel','refund'].includes(action);
 const physical=['match','inspect','ship','receive','dispose','cancel'].includes(action);let fields='',notice='';
 if(physical)fields+='<label>本人本次实物事实与原关联<textarea name="result" minlength="4" maxlength="1000" required></textarea></label>';
 if(['inspect','receive'].includes(action))fields+='<label>本人实际复验结果<select name="passed" required><option value="">请选择明确检查结果</option><option value="yes">整份复验合格</option><option value="no">整份复验不合格，保留坏件事实</option></select></label>';
 if(['plan','approve','reject','terms','terms_approve','terms_reject','terms_cancel','pending_cancel','trace_open','trace_approve','trace_reject'].includes(action))fields+='<label>本次核对事实及原件说明<textarea name="reason" minlength="4" maxlength="1000" required></textarea></label>';
 if(action==='terms'){notice='必须有原承运人或保险公司的实际处理条件。逐条明确新的累计赔付目标；其他原款仍未退回不代表本笔不能先确认减额。';fields+=`<label>往来方实际确认的新累计目标（元）<input name="target" inputmode="decimal" value="${(Math.min(claim.target_cents,r.remaining_burden_cents)/100).toFixed(2)}" required></label><label>实际约定核对日期<input name="due" type="date" value="${day()}" required></label>`;}
 if(action==='refund'){const catalog=await api('/api/transfer-exceptions/recovery-catalog');notice=`本条原款最多应退 ${money(claim.refund_cents)} 元，且受所选原实收尚未退额限制；只能从原账户退回。`;fields+=`<label>本次对应的原实收<select name="original" required>${claim.payments.filter(p=>p.direction==='in'&&p.unreturned_cents>0).map(p=>`<option value="${p.id}">${E(p.business_date)} · 原实收 ${money(p.amount_cents)} 元 · 尚未退 ${money(p.unreturned_cents)} 元</option>`).join('')}</select></label><label>本次实际退回（元）<input name="amount" inputmode="decimal" required></label><label>原本店资金账户<select name="account" required><option value="">请选择实际原账户</option>${catalog.accounts.map(a=>`<option value="${a.id}">${E(a.name)}</option>`).join('')}</select></label><label>实际银行流水<input name="reference" minlength="2" maxlength="100" required></label><label>实际退回日期<input name="actual" type="date" value="${day()}" max="${day()}" required></label>`;}
 if(action==='plan')notice='只按原损失可恢复成本及累计尾差核对；两店承担冲回之和等于实际恢复成本。无须员工重新手算或输入分摊金额。';
 if(['restore','finish_bad'].includes(action))notice=action==='restore'?'确认本店实际将批准的合格原物资入库。原损失保留，库存与恢复原成本只登记一次；赔付变化另行明确。':'确认实际坏件处置已有原件。不会恢复库存、成本或承担，也不凭此制造退款。';
 if(['trace_open','trace_approve','trace_reject'].includes(action))notice='请根据本店实际查找记录独立核对。只有两店不同且未参与原实物办理的主管均批准，才结束本次查找；不重复记损失。仍在查找时实际到货，请走实际接收。';
 if(physical||['restore','finish_bad','refund','trace_open','trace_approve','trace_reject'].includes(action))fields+='<label><input name="confirmed" type="checkbox" required>本人已经核对以上实际事实与原件。</label>';
 modal(transferGoodsActions[action],`<form>${notice?`<p>${E(notice)}</p>`:''}<div class="formgrid">${fields}${transferGoodsProof(own.files,financial)}</div><div class="formerror" role="alert"></div><button type="submit" class="primary">${E(transferGoodsActions[action])}</button></form>`,async form=>{
  const v={evidence_id:Number(form.elements.evidence_id.value)};for(const name of ['result','reason'])if(form.elements[name])v[name]=form.elements[name].value;if(form.elements.confirmed)v.confirmed=form.elements.confirmed.checked;
  if(form.elements.passed)v.passed=form.elements.passed.value==='yes';if(['approve','reject'].includes(action))v.plan_id=r.plans.at(-1).id;
  if(['trace_approve','trace_reject'].includes(action))v.search_id=r.searches.at(-1).id;
  if(claim){v.claim_id=claim.id;v.claim_version=claim.version;}if(['terms_approve','terms_reject','terms_cancel','pending_cancel'].includes(action))v.plan_id=claim.pending_plan_id;
  if(action==='terms'){v.target_cents=transferExceptionMoney(form.elements.target.value);v.due_date=form.elements.due.value;}
  if(action==='refund'){v.original_id=Number(form.elements.original.value);v.amount_cents=transferExceptionMoney(form.elements.amount.value);v.account_id=Number(form.elements.account.value);v.reference=form.elements.reference.value;v.business_date=form.elements.actual.value;}
  await api(`/api/transfer-goods-recoveries/${r.id}/actions/${action}`,{method:'POST',body:{request_id,version:r.version,transfer_version:r.transfer_version,case_version:r.case_version,values:v}});closeModal();await render();
 });
}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-act]');if(!button||button.disabled)return;try{if(button.dataset.act==='transfer-goods-new')await transferGoodsRecoveryNew(button.dataset.transfer?Number(button.dataset.transfer):null);if(button.dataset.act==='transfer-goods-action')await transferGoodsRecoveryAction(button.dataset.key,button.dataset.claim);}catch(error){toast(error.message,true);}});
