'use strict';
let vehicleTransferContext=null;
function clearVehicleTransferSession(){vehicleTransferContext=null;}
const vehicleTransferActions={approve:'批准本店安排',reject_request:'拒绝申请',cancel:'撤销未发出调拨',dispatch:'核对实车并发出',accept:'验收车辆入库',reject:'拒收车辆',return_ship:'确认退回发运',return_receive:'确认退回入库'};
const vehicleMoveLabels={dispatch:'发出',accept:'验收入库',reject:'拒收',return_ship:'退回发运',return_receive:'退回入库'};
async function vehicleTransfersPage(id){
 if(state.store==='all')return heading('整车跨店调拨')+storeNotice()+'<div class="notice">请选择本店办理调出和调入。集团汇总可在数据可视化中查询。</div>';
 if(!id){const d=await api('/api/vehicle-transfers');return heading('整车跨店调拨','申请即占用车辆；双方批准后发出，核对实车后入库。',['admin','manager','inventory'].includes(state.user.role)?b('vehicle-transfer-new','申请整车调拨','','primary'):'')+panel('本店调拨',table(['单号','车辆','方向','对方门店','状态',''],d.items.map(r=>[E(r.number),E(r.lines[0].model)+'<br>'+E(r.lines[0].vin),r.side==='source'?'调出':'调入',E(r.side==='source'?r.to_store_name:r.from_store_name),E(r.status_label),b('open','办理',`data-route="vehicle-transfers/${r.id}"`)])));}
 const r=await api('/api/vehicle-transfers/'+id);vehicleTransferContext=r;const car=r.lines[0];
 return heading('整车调拨',r.number,b('open','返回调拨','data-route="vehicle-transfers"'))+
 panel('车辆与交接',`<strong>${E(car.brand)} · ${E(car.model)}</strong><p>${E(car.color)}　<span class="tag">${E(r.status_label)}</span></p><p class="vin-line">VIN ${E(car.vin)}</p><p>${E(r.from_store_name)} → ${E(r.to_store_name)}</p><p>调出方${r.source_approved?'已批准':'待批准'} · 调入方${r.destination_approved?'已批准':'待批准'}</p><p>计划 ${E(r.due_date)} · ${E(r.reason)}</p>${car.cost_cents!==undefined?`<p>原库存价值 ${money(car.cost_cents)} 元</p>`:''}<div class="row">${r.actions.map(a=>b('vehicle-transfer-action',vehicleTransferActions[a],`data-key="${a}"`,['approve','dispatch','accept','return_receive'].includes(a)?'primary':'')).join('')}</div>`)+
 panel('原车运输差异与找回',`${r.can_open_exception&&canWrite()?b('vt-new','登记原车运输差异','','primary'):''}${(r.exception_ids||[]).map(eid=>b('open',eid===r.active_exception_id?'继续本次差异办理':'查看原差异与找回',`data-route="vehicle-transport-exceptions/${eid}"`)).join('')}${full()?b('open','原损失与找回统计','data-route="vehicle-transport-report"'):''}<p class="fieldhelp">错 VIN、损坏或失联先登记双方核对，不能改 VIN 强行接收。损失、后来找回和真实资金各自沿原记录办理。</p>`)+
 panel('本店凭据与责任',b('open','查看任务、转交或上传凭据',`data-route="case/${r.case_id}"`)+'<p class="muted">双方分别保管实际交接凭据。拒收后须完成退回发运和原店验收，才能恢复可用库存。</p>')+
 panel('本店实物流水',table(['日期','动作','数量变动','说明','凭据'],r.movements.map(m=>[E(m.business_date),E(vehicleMoveLabels[m.kind]),m.quantity,E(m.reason),b('downloadfile','下载',`data-id="${m.evidence_id}"`)])));
}
async function vehicleTransferNew(){
 const [destinations,lookup]=await Promise.all([api('/api/vehicle-transfers/destinations'),api('/api/flow/lookup/vehicle')]);const vehicles=lookup.items||lookup;
 modal('申请整车跨店调拨',`<form><div class="formgrid"><label class="wide">本店可用车辆<select name="vehicle_id" required><option value="">请选择并核对VIN</option>${vehicles.map(v=>`<option value="${v.id}">${E(v.label)}</option>`).join('')}</select></label><label>调入门店<select name="destination_store_id" required><option value="">请选择</option>${destinations.items.map(s=>`<option value="${s.id}">${E(s.name)}</option>`).join('')}</select></label><label>计划日期<input type="date" name="due_date" value="${day()}" required></label><label class="wide">申请原因<textarea name="reason" minlength="2" maxlength="500" required></textarea></label></div><p class="muted">提交后暂停此车配车；未发出前可以撤销。</p><div class="formerror" role="alert"></div><button type="submit" class="primary">提交双方审批</button></form>`,((request_id)=>async form=>{const r=await api('/api/vehicle-transfers',{method:'POST',body:{request_id,vehicle_id:Number(form.elements.vehicle_id.value),destination_store_id:Number(form.elements.destination_store_id.value),due_date:form.elements.due_date.value,reason:form.elements.reason.value}});closeModal();location.hash='vehicle-transfers/'+r.id;})(requestKey()));
}
async function vehicleTransferAction(key){
 const r=vehicleTransferContext;const physical=!['approve','reject_request','cancel'].includes(key);const fields=[F('reason','本次确认说明','textarea')];if(physical)fields.unshift(F('evidence_id','本单交接凭据','file'));
 const controls=(await Promise.all(fields.map(f=>fieldHTML(f,defaultValue(f),r.case_id)))).join('');let locations='';
 if(['accept','return_receive'].includes(key)){const d=await api('/api/masters/lookup/locations');locations=`<label class="wide">本店实际入库库位<select name="location_id" required><option value="">请选择整车库位</option>${(d.items||d).map(x=>`<option value="${x.id}">${E(x.label||x.name)}</option>`).join('')}</select></label>`;}
 const request_id=requestKey();modal(vehicleTransferActions[key],`<form><p>${E(r.lines[0].model)} · ${E(r.number)}</p><div class="formgrid">${controls}${physical?'<label class="wide">现场核对VIN<input name="vin" minlength="17" maxlength="17" autocomplete="off" required placeholder="请输入现场核对的17位VIN"></label>':''}${locations}</div><div class="formerror" role="alert"></div><button type="submit" class="primary">确认${E(vehicleTransferActions[key])}</button></form>`,async form=>{const values={reason:form.elements.reason.value};if(physical){values.evidence_id=Number(form.elements.evidence_id.value);values.vin=form.elements.vin.value.trim().toUpperCase();}if(form.elements.location_id)values.location_id=Number(form.elements.location_id.value);await api(`/api/vehicle-transfers/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,case_version:r.case_version,values}});closeModal();await render();});
}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-act]');if(!button||button.disabled)return;try{if(button.dataset.act==='vehicle-transfer-new')await vehicleTransferNew();if(button.dataset.act==='vehicle-transfer-action')await vehicleTransferAction(button.dataset.key);}catch(error){toast(error.message,true);}});
