'use strict';
// Original-case actions only. The API repeats all role, source and version checks.
let vehicleTransportContext=null;
function clearVehicleTransportSession(){vehicleTransportContext=null;}
const vtActions={observe:'登记本人原车核对',observe_found:'记录原车已实际找到',plan_resume:'提交继续原交接复核',plan_loss:'提交原损失承担复核',plan_found:'提交原车找回接收复核',approve:'独立批准本版方案',reject:'记录本版复核未通过',withdraw:'撤回本人未生效方案',dispose:'确认在手原车实际处置',post_loss:'确认原在途损失',found_receive:'核对原车并实际验收入库',found_unavailable:'记录本次找回无法接收',recovery_create:'申请本店外部赔付确认',recovery_plan:'申请原赔付目标调整',recovery_approve:'独立确认本版赔付目标',recovery_reject:'本版赔付复核未通过',recovery_cancel:'撤回未生效赔付版本',recovery_receive:'登记原赔付真实到账',recovery_refund:'退回原笔实际赔款'};
const vtKinds={missing:'原车失联',vin_mismatch:'现场 VIN 不符',damage:'原车损坏待核对'};
const vtPlanKinds={resume:'继续原交接',loss:'原损失与两店承担',found_receive:'原车找回接收'};
const vtPlanStatus={pending:'待两店独立复核',approved:'两店已批准',rejected:'未通过',withdrawn:'已撤回'};
const vtObservationKinds={dispatch_verified:'本人确认本段原车已发出',not_located:'按本段原 VIN 查找仍未定位',original_seen:'本人确认原车实际在场可交接',unusable_held:'本人确认原车在手但不可用',other_vin_seen:'本人看到的实车 VIN 与原车不符'};
function vtOptions(rows,label){return '<option value="">请选择并核对原来源</option>'+rows.map(r=>`<option value="${r.id}">${E(label(r))}</option>`).join('');}
function vtReason(){return '<label class="wide">本人核实的事实及依据<textarea name="reason" minlength="4" maxlength="1000" required></textarea></label>';}
function vtProof(financial=false){const kinds=financial?['receipt','procurement_contract']:['evidence','inspection','authorization'];const files=(state.row?.files||[]).filter(f=>!f.generated&&f.security?.can_use&&kinds.includes(f.category));return `<label class="wide">本店原单${financial?'财务协议／原款':'实车核对'}凭据<select name="evidence_id" required>${vtOptions(files,f=>f.name+' · '+f.label)}</select></label><p class="fieldhelp">只列出本单检查可用的实际上传文件。没有合适凭据时请先关闭窗口，在本页上传；不会自动引用对店文件或生成草稿。</p>`;}
function vtConfirmed(label){return `<label class="checkrow wide"><input type="checkbox" name="confirmed" required>${E(label)}</label>`;}
function vtVin(){return '<label class="wide">现场逐位核对 VIN<input name="vin" required minlength="17" maxlength="17" pattern="[A-HJ-NPR-Za-hj-npr-z0-9]{17}" autocomplete="off" placeholder="请输入现场实际核对的17位VIN"></label>';}
function vtAmount(name,label){return `<label>${E(label)}（元）<input type="text" inputmode="decimal" name="${name}" required autocomplete="off"></label>`;}
function vtFen(value){return moneyFen(value,{label:'金额',allowZero:true});}
function vtForm(body,label){return `<form><div class="formgrid">${body}</div><div class="formerror" role="alert"></div><div class="modalfoot"><button type="submit" class="primary">${E(label)}</button></div></form>`;}
function vtFile(id){return id?b('downloadfile','本店凭据',`data-id="${id}"`):'对店凭据由对店保管';}
async function vehicleTransportPage(id){
 if(state.user.aggregate_scope||state.store==='all')return heading('整车运输差异')+storeNotice()+'<p class="notice">原单办理请选择本店。集团只查询汇总，不跨店代确认。</p>';
 const r=await api('/api/vehicle-transport-exceptions/'+id);vehicleTransportContext=r;state.row=await api('/api/flow/cases/'+r.case_id);
 const buttons=(r.actions||[]).filter(()=>canWrite()).map(k=>b('vt-action',vtActions[k],`data-key="${k}"`,['approve','post_loss','found_receive'].includes(k)?'primary':''));
 let html=heading('整车运输差异与原车找回',r.number+' · '+r.status_label,b('open','原调拨交接',`data-route="vehicle-transfers/${r.transfer_id}"`))+storeNotice()+panel('当前可办理',`<p class="vin-line">原 VIN ${E(r.vin)}</p><p>${E(vtKinds[r.kind])} · ${E(r.reason)}</p><p class="fieldhelp">${E(r.definition)}</p>${r.notice?`<p class="notice">${E(r.notice)}</p>`:''}<div class="row">${buttons.join('')||'当前岗位等待前置核对或独立复核。'}</div>`)+intakeFiles();
 html+=panel('原车实际观察',table(['记录方／事实','本人核对 VIN','实际时间','事实说明','凭据'],r.observations.map(o=>[`${o.own_store?'本店':'对店'} · ${E(o.label)}`,E(o.vin),time(o.actual_at),E(o.reason),vtFile(o.evidence_id)])));
 html+=panel('逐版原方案与独立复核',r.plans.map(p=>`<article class="card"><h3>版本${p.revision} · ${E(vtPlanKinds[p.kind])} · ${E(vtPlanStatus[p.status])}</h3><p>${E(p.reason||'本岗位不显示财务协议内容')}</p>${r.can_money&&p.kind==='loss'?`<p>原调出方承担 ${money(p.source_bearer_cents)} 元；原调入方承担 ${money(p.destination_bearer_cents)} 元。这不是已收付款。</p>`:''}${p.kind==='found_receive'?`<p>原观察 #${p.found_observation_id} · ${p.receiving_own_store?'本店':'对店'}实际接收；批准不自动入库。</p>`:''}<p>${p.reviews.map(v=>`${v.own_store?'本店':'对店'}${v.decision==='approve'?'已独立批准':'复核未通过'}`).join(' · ')||'尚无独立批准'}</p>${p.evidence_id?vtFile(p.evidence_id):''}</article>`).join('')||'<p>先由双方分别核对，未形成原方案。</p>');
 if(r.loss)html+=panel('原损失事实',`<p>实际核销日期 ${E(r.loss.business_date)} · 原库存成本 ${money(r.loss.value_cents)} 元。</p><p>原发出已经出库，本次不再出库，也不自动生成赔付现金。</p>`);
 if(r.found)html+=panel('原车实际找回入库',`<p>${r.found.own_store?'本店':'对店'}已于 ${E(r.found.business_date)} 据实验收。${r.found.value_cents!==undefined?'恢复原成本 '+money(r.found.value_cents)+' 元。':''}</p><p>原损失、原赔款和旧店间清算保留；需要退款请独立调整原目标后沿原款办理。</p>${vtFile(r.found.evidence_id)}`);
 if(r.unavailable_findings.length)html+=panel('保留的找回接收失败',table(['原方案／观察','本人事实','凭据'],r.unavailable_findings.map(x=>[`#${x.plan_id} / #${x.observation_id}`,E(x.kind==='missing_again'?'接收前再次失联':'接收时确认不可用')+(x.reason?'<br>'+E(x.reason):''),vtFile(x.evidence_id)])));
 if(r.can_money){html+=panel('本店原外部赔付',r.claims.map(c=>`<article class="card"><h3>${E(c.counterparty_name)} · 原追偿 #${c.id}</h3><p>已批准目标 ${money(c.target_cents)} 元；实际净收 ${money(c.paid_cents)} 元；已确认应退 ${money(c.refund_cents)} 元。</p>${c.requires_found_adjustment?'<p class="notice">原车已经找回，请先独立确认原目标调整，再逐笔退原款；不得继续按旧目标收款。</p>':''}<div class="row">${c.actions.filter(()=>canWrite()).map(k=>b('vt-action',vtActions[k],`data-key="${k}" data-claim="${c.id}"`)).join('')}</div>${table(['原版本','独立状态','约定日期','目标（元）'],c.plans.map(p=>[p.revision,E({pending:'待独立复核',approve:'已确认',reject:'未通过',cancelled:'已撤回'}[p.status]),E(p.due_date),money(p.target_cents)]))}${table(['原实际款／方向','日期','金额（元）／原流水','本店凭据'],c.payments.map(p=>[`#${p.id} · ${p.direction==='in'?'真实到账':'原款退款'}`,E(p.business_date),`${money(p.amount_cents)} · ${E(p.reference)}`,vtFile(p.evidence_id)]))}</article>`).join('')||'<p>没有本店原外部赔付记录。店间承担另在原往来清算。</p>');html+=panel('同源财务核对',b('open','原损失、找回与原款统计','data-route="vehicle-transport-report"')+b('open','店间原往来实际清算','data-route="clearing"'));}
 return html+panel('岗位责任交接',state.row.tasks.map(t=>`<div class="taskitem"><div class="description"><strong>${E(t.title)}</strong><p>${E(t.assignee_name)} · ${pill(t.status)}</p>${t.status==='open'&&['admin','manager'].includes(state.user.role)?b('assign','明确交接负责人',`data-id="${t.id}"`):''}</div></div>`).join(''));
}
async function vehicleTransportNew(){const r=vehicleTransferContext,request_id=requestKey();if(!r?.can_open_exception)throw new Error('原交接状态已变化，请刷新。');state.row=await api('/api/flow/cases/'+r.case_id);modal('登记原整车运输差异',vtForm(`<p class="fieldhelp">登记后暂停原实物交接，双方先各自核对。不会直接核销、退款或修改VIN。</p><label>本次发现<select name="kind" required>${Object.entries(vtKinds).map(([k,v])=>`<option value="${k}">${E(v)}</option>`).join('')}</select></label>${vtProof()}${vtReason()}`,'提交双方原车核对'),async form=>{const x=await api('/api/vehicle-transport-exceptions',{method:'POST',body:{request_id,transfer_id:r.id,version:r.version,case_version:r.case_version,kind:form.elements.kind.value,evidence_id:Number(form.elements.evidence_id.value),reason:form.elements.reason.value}});closeModal();go('vehicle-transport-exceptions/'+x.id);});}
async function vehicleTransportAction(key,claimId){
 const r=vehicleTransportContext,c=claimId?r.claims.find(x=>x.id===claimId):null,plan=r.plans.at(-1),request_id=requestKey();
 if(!(c?c.actions:r.actions).includes(key))throw new Error('当前动作或负责人已变化，请刷新。');
 const recovery=key.startsWith('recovery_'),financial=recovery||['plan_loss','plan_found','post_loss'].includes(key)||(['approve','reject','withdraw'].includes(key)&&plan?.kind!=='resume');
 const physical=['observe','observe_found','dispose','found_receive','found_unavailable'].includes(key);let body='';
 if(key==='observe'){const sender=(r.side==='source')!==(r.origin_status==='return_transit');const kinds=sender?['dispatch_verified']:['not_located','original_seen','unusable_held','other_vin_seen'];body+=`<label class="wide">本人核对结果<select name="kind" required><option value="">请选择实际观察</option>${kinds.map(k=>`<option value="${k}">${E(vtObservationKinds[k])}</option>`).join('')}</select></label>`;}
 if(physical)body+=vtVin();
 if(['observe','observe_found'].includes(key))body+=`<label>实际核对时间<input name="actual_at" type="datetime-local" required value="${intakeLocal(new Date())}"></label>`;
 if(key==='plan_loss'){const parent=await api('/api/vehicle-transfers/'+r.transfer_id);body+=`<p class="notice">原车原成本 ${money(parent.lines[0].cost_cents)} 元。两店承担须合计原成本；这里只提出真实协议，不自动转账。</p><label>原车结论<select name="loss_method" required><option value="">请选择已核实结论</option><option value="missing">原车失联</option><option value="destroyed">在手原车不可用，实际处置后核销</option></select></label>`+vtAmount('source_amount','原调出方承担')+vtAmount('destination_amount','原调入方承担');}
 if(key==='plan_found'){const retired=new Set(r.unavailable_findings.map(x=>x.observation_id));const candidates=r.observations.filter(o=>o.kind==='found_usable'&&!retired.has(o.id)).slice(-1);body+=`<label class="wide">最新仍有效的原车在场观察<select name="found_observation_id" required>${vtOptions(candidates,o=>`原观察 #${o.id} · ${o.own_store?'本店':'对店'} · ${o.vin}`)}</select></label><p class="fieldhelp">实际接收店固定为原观察人在场的门店；两店批准后仍须本人真实入库。</p>`;}
 if(key==='found_receive'){const d=await api('/api/masters/lookup/locations');body+=`<label>本店实际整车库位<select name="location_id" required>${vtOptions(d.items||d,x=>x.label||x.name)}</select></label>`;}
 if(key==='found_unavailable')body+='<label class="wide">本人核实的接收失败<select name="kind" required><option value="">请选择实际原因</option><option value="missing_again">接收前再次失联</option><option value="not_usable">接收时确认原车不可用</option></select></label><p class="fieldhelp">保留原损失，不增加第二笔损失或虚构入库；后来找到须追加新观察。</p>';
 if(key==='recovery_create'){const [suppliers,insurers]=await Promise.all([api('/api/masters/lookup/suppliers'),api('/api/masters/lookup/insurers')]);body+=`<label class="wide">本店已确认的原往来方<select name="counterparty" required><option value="">请选择明确原单位</option>${(suppliers.items||suppliers).map(x=>`<option value="carrier:${x.id}">承运供应商 · ${E(x.label||x.name)}</option>`).join('')}${(insurers.items||insurers).map(x=>`<option value="insurer:${x.id}">保险公司 · ${E(x.label||x.name)}</option>`).join('')}</select></label>`;}
 if(['recovery_create','recovery_plan'].includes(key))body+=vtAmount('target_amount','本版真实确认的赔付目标')+`<label>约定日期<input name="due_date" type="date" required value="${day()}"></label><p class="fieldhelp">目标变更须其他主管独立批准。找到原车后填明确的零目标，不抹掉原款；原退款另办。</p>`;
 if(['recovery_receive','recovery_refund'].includes(key)){
  body+=vtAmount('amount','本次实际款项')+`<label>实际银行流水／凭证号<input name="reference" required minlength="2" maxlength="100" autocomplete="off"></label><label>实际日期<input name="business_date" type="date" required value="${day()}"></label>`;
  if(key==='recovery_receive'){body+=await fieldHTML(F('account_id','本店实际收款账户','account'),null,r.case_id);}else{body+=`<label class="wide">本店原笔实际到账<select name="original_id" required>${vtOptions(c.payments.filter(p=>p.direction==='in'&&p.unreturned_cents>0),p=>`原款 #${p.id} · ${p.reference} · 尚未退 ${money(p.unreturned_cents)} 元`)}</select></label><p class="fieldhelp">退款固定原到账账户，金额还须受已批准应退额限制。不换账、不补造款项。</p>`;}
 }
 body+=vtProof(financial)+vtReason();if(physical||key==='post_loss'||['recovery_receive','recovery_refund'].includes(key))body+=vtConfirmed(key==='post_loss'?'我已核实两店原方案和实际事实，确认此笔原在途损失；不重复出库或制造现金。':physical?'我已逐位核对原VIN及凭据，确认上述事实已实际发生，不是预计或自动推断。':'我已核实本笔真实银行或现金事实与原凭据，不是仅提出收退款申请。');
 modal(vtActions[key],vtForm(body,vtActions[key]),async form=>{
  const v={reason:form.elements.reason.value,evidence_id:Number(form.elements.evidence_id.value)};
  if(form.elements.confirmed)v.confirmed=form.elements.confirmed.checked;if(physical)v.vin=form.elements.vin.value.trim().toUpperCase();
  if(form.elements.actual_at)v.actual_at=new Date(form.elements.actual_at.value).toISOString();if(form.elements.kind)v.kind=form.elements.kind.value;
  if(key==='plan_loss')Object.assign(v,{loss_method:form.elements.loss_method.value,source_bearer_cents:vtFen(form.elements.source_amount.value),destination_bearer_cents:vtFen(form.elements.destination_amount.value)});
  for(const field of ['found_observation_id','location_id'])if(form.elements[field])v[field]=Number(form.elements[field].value);
  if(['approve','reject','withdraw'].includes(key))v.plan_id=plan.id;
  if(c)Object.assign(v,{claim_id:c.id,claim_version:c.version});
  if(['recovery_approve','recovery_reject','recovery_cancel'].includes(key))v.plan_id=c.pending_plan_id;
  if(form.elements.target_amount)Object.assign(v,{target_cents:vtFen(form.elements.target_amount.value),due_date:form.elements.due_date.value});
  if(key==='recovery_create'){const [kind,id]=form.elements.counterparty.value.split(':');Object.assign(v,{counterparty_kind:kind,counterparty_id:Number(id)});}
  if(['recovery_receive','recovery_refund'].includes(key)){Object.assign(v,{amount_cents:groupFen(form.elements.amount.value),reference:form.elements.reference.value,business_date:form.elements.business_date.value});if(key==='recovery_receive')v.account_id=Number(form.elements.account_id.value);else{const original=c.payments.find(p=>p.id===Number(form.elements.original_id.value));if(!original)throw new Error('原到账已变化，请刷新。');Object.assign(v,{original_id:original.id,account_id:original.account_id});}}
  await api(`/api/vehicle-transport-exceptions/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,case_version:r.case_version,exception_version:r.exception_version,values:v}});closeModal();await render();
 });
}
async function vehicleTransportReportPage(){let d;try{d=await api('/api/inventory-reports/vehicle-transport?'+new URLSearchParams(state.dates));}catch(e){if(e.status===422)return irPeriodError('原车运输与找回核对',e);throw e;}return heading('原车运输与找回核对','原资产、两店承担、追偿目标、真实现金各自核对，不相加重复记账。')+storeNotice()+dateFilters()+panel('核对口径',d.definitions.map(x=>`<p class="fieldhelp">${E(x)}</p>`).join(''))+d.charts.map(c=>panel(c.title,chartSVG(c)+b('inventory-report-export','导出此图同源行',`data-kind="vehicle-transport" data-key="${c.table}"`))).join('')+Object.entries(d.tables).map(([key,t])=>irTable('vehicle-transport',key,t)).join('');}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-act]');if(!button||button.disabled||!button.dataset.act.startsWith('vt-'))return;button.disabled=true;try{if(button.dataset.act==='vt-new')await vehicleTransportNew();else if(button.dataset.act==='vt-action')await vehicleTransportAction(button.dataset.key,Number(button.dataset.claim)||null);}catch(e){toast(e.message,true);}finally{button.disabled=false;}});
