'use strict';
const vehicleIncomeActions={propose:'提出应收或目标修订',approve:'独立批准本版目标',reject:'退回本版依据',withdraw:'撤回未批准版本',receive:'登记厂家实际到账',refund:'按原款原账户退款',cancel:'取消未批准申请'};
const vehicleIncomeModes={store_invoice:'明确由本店对厂家或供应商开票',external_document:'按对方原票或结算凭据办理'};
async function vehicleIncomePage(id){
 if(!id){const d=await api('/api/vehicle-income?page='+state.page);return heading('厂家及供应商整车其他收入','',canWrite()&&['admin','manager','finance'].includes(state.user.role)?b('vehicle-income-new','建立其他收入','','primary'):'')+storeNotice()+panel('本店非客户收入',table(['原单','往来单位','结算编号','状态',''],d.items.map(r=>[E(r.number),E(r.supplier.name),E(r.external_reference),pill(r.state),b('open','办理',`data-route="vehicle-income/${r.id}"`)]))+pager(d.total));}
 const r=await api('/api/vehicle-income/'+id);state.vehicleIncome=r;state.row=await api('/api/flow/cases/'+id);
 const task=k=>r.tasks.some(t=>t.key==='vehicle_income_'+k),button=k=>canWrite()&&r.actions.includes(k)?b('vehicle-income-action',vehicleIncomeActions[k],`data-key="${k}"`):'',t=r.totals;
 let h=heading('厂家及供应商整车其他收入',r.number,b('open','返回收入列表','data-route="vehicle-income"'))+storeNotice();
 h+=panel('原往来依据',`<p>${E(r.supplier.name)} · ${E(r.supplier.code)}</p><p>对方结算编号：${E(r.external_reference)}</p><p>${E(r.reason)}</p><p>本单不使用客户预收或会员资金。厂家名称不决定开票方式，须核对本版真实结算依据。</p>`);
 h+=actionPanel(`<div class="row">${!r.pending_revision_id?button('propose'):''}${task('review')?button('approve')+button('reject')+button('withdraw'):''}${task('receive')?button('receive'):''}${task('refund')?button('refund'):''}${!r.current_revision_id?button('cancel'):''}</div><p>${pill(r.state)}</p>`);
 h+=panel('有效目标与实际资金',`<div class="formgrid"><div>已批准应收<strong>${money(t.target_cents)} 元</strong></div><div>实际净收<strong>${money(t.net_received_cents)} 元</strong></div><div>尚欠<strong>${money(t.receivable_cents)} 元</strong></div><div>超收待退<strong>${money(t.refund_due_cents)} 元</strong></div></div><p>目标修订不改写原款；未按车辆分配的批量结算保留原单总额，不自动摊入各车利润。</p>`);
 h+=panel('冻结原车辆来源',r.sources.map(s=>`<p>${E(s.number)}${s.vin?' · 原VIN '+E(s.vin):' · 原单汇总依据，未分配到VIN'}${s.entity_revision_id?'':' · 历史主体未知'}</p>`).join(''));
 h+=panel('应收原版本',r.revisions.map(x=>`<h3>第 ${x.revision} 版 · ${money(x.target_cents)} 元</h3><p>前目标 ${money(x.previous_cents)} 元；${E(vehicleIncomeModes[x.invoice_mode])}；到期 ${E(x.due_date)}</p><p>${E(x.reason)}</p><p>${x.decision?E({approved:'另一主管已批准',rejected:'主管已退回',withdrawn:'已撤回未批准版本'}[x.decision.decision])+'：'+E(x.decision.reason):'等待另一主管核对原件'}</p>`).join('')||'<p>尚未提出应收目标。</p>');
 h+=panel('唯一实际现金与原退款',r.payments.map(p=>`<p>${E(p.business_date)} · ${p.direction==='in'?'实际到账':'原款实际退回'} ${money(p.amount_cents)} 元；${E(p.account_snapshot.name)}；流水 ${E(p.reference)}${p.original_id?'；原到账 '+p.original_id:''}</p>`).join('')||'<p>尚无实际现金，申请或批准不会生成收款。</p>');
 h+=panel('原件与待办',b('upload','上传本次实际原件')+'<p>应收依据和复核选择业务凭据或原票；实际到账与原退款选择收款凭据。门店开票另从发票协同引用本单。</p>'+state.row.files.map(f=>`<div class="filerecord"><div class="filetext"><strong>${E(f.name)}</strong><p>${E(f.security?.label||'待扫描')}</p>${f.security?.can_use?b('download','下载',`data-id="${f.id}"`):'扫描通过后可用'}</div></div>`).join('')+state.row.tasks.map(t=>`<p>${E(t.title)} · ${E(t.assignee_name)} · ${pill(t.status)} ${t.status==='open'&&['admin','manager'].includes(state.user.role)?b('assign','明确交接',`data-id="${t.id}"`):''}</p>`).join(''));
 return h;
}
async function vehicleIncomeNew(){
 const c=await api('/api/vehicle-income/catalog');if(c.total>10000||c.supplier_total>10000)throw new Error('原来源超过当前选择范围，请按门店整理后扩展检索。');
 for(let page=2;page<=Math.ceil(Math.max(c.total,c.supplier_total)/50);page++){const next=await api('/api/vehicle-income/catalog?page='+page);c.items.push(...next.items);c.suppliers.push(...next.suppliers);}
 if(!c.items.length||!c.suppliers.length)throw new Error('请先配置真实厂家或供应商，并有本店已批准的原整车业务。');
 const options=c.items.map((s,i)=>({key:String(i),label:s.number+' · '+(s.vin||'原单汇总依据')})),request_id=requestKey();
 const sourceLine=(required=false)=>`<label data-vehicle-income-source>原车辆来源<select data-income-source${required?' required':''}><option value="">${required?'请选择原来源':'本行不使用'}</option>${options.map(o=>`<option value="${o.key}">${E(o.label)}</option>`).join('')}</select></label>`;
 modal('建立非客户整车收入',`<form><label>真实厂家或供应商<select name="supplier" required><option value="">请选择真实往来单位</option>${c.suppliers.map(s=>`<option value="${s.id}">${E(s.name)} · ${E(s.code)}</option>`).join('')}</select></label><label>对方原结算编号<input name="external_reference" required maxlength="120"></label><p>选择明确的原车辆业务；一个结算单可关联多个原单或VIN。最多可选100个来源，原单总额不会自动摊入各车。</p><div data-income-sources>${sourceLine(true)}</div><button type="button" data-income-add>再加一个原来源</button><label>约定应收到期日期<input name="due_date" type="date" value="${day()}" required></label><label>真实事项与原依据<textarea name="reason" required minlength="2"></textarea></label><div class="formerror" role="alert"></div><div class="modalfoot"><button class="primary" type="submit">建立原单</button></div></form>`,async form=>{const supplier=c.suppliers.find(s=>s.id===Number(form.elements.supplier.value));const sources=[...form.querySelectorAll('[data-income-source]')].map(e=>e.value).filter(v=>v!=='').map(v=>{const s=c.items[Number(v)];return {source_case_id:s.id,source_version:s.version,vehicle_id:s.vehicle_id};});const r=await api('/api/vehicle-income',{method:'POST',body:{request_id,supplier_id:supplier.id,supplier_version:supplier.version,external_reference:form.elements.external_reference.value,sources,due_date:form.elements.due_date.value,reason:form.elements.reason.value}});closeModal();go('vehicle-income/'+r.id);});
 const add=document.querySelector('#modal [data-income-add]');add.addEventListener('click',()=>{const box=document.querySelector('#modal [data-income-sources]');if(box.children.length>=100)throw new Error('一张结算单最多关联100个原来源');box.insertAdjacentHTML('beforeend',sourceLine());if(box.children.length>=100)add.disabled=true;});
}
async function vehicleIncomeAction(key){
 const r=state.vehicleIncome,request_id=requestKey(),fields=[],initial={},extra={};
 if(key==='propose'){fields.push(F('amount','本版厂家应付目标（元）','money'),F('mode','按真实结算依据选择开票方式','select',true,Object.values(vehicleIncomeModes)),F('due_date','约定应收到期日期','date'));initial.amount=String(r.totals.target_cents/100);initial.due_date=r.due_date;}
 if(['approve','reject','withdraw'].includes(key))extra.revision_id=r.pending_revision_id;
 if(['receive','refund'].includes(key)){fields.push(F('amount','本次实际金额（元）','money'),F('account_id','实际原资金账户','account'),F('reference','本次实际流水编号'),F('business_date','实际到账或退款日期','date'));initial.business_date=day();if(key==='refund'){fields.push(F('original','本单原实际到账','select',true,r.payments.filter(p=>p.direction==='in'&&p.available_cents>0).map(p=>p.id+' · '+p.account_snapshot.name+' · 原额 '+money(p.amount_cents)+' 元')));}}
 fields.push(F('reason','本人核对的依据或办理原因','textarea'));if(!['cancel','withdraw'].includes(key))fields.push({...F('evidence_id','本单本次实际原件','file'),file_category:['receive','refund'].includes(key)?'receipt':'evidence'});
 await formDialog(vehicleIncomeActions[key],fields,initial,v=>{const body={...extra,...v};if(body.amount!==undefined){body[key==='propose'?'target_cents':'amount_cents']=repairScaled(body.amount,2);delete body.amount;}if(body.mode){body.invoice_mode=Object.keys(vehicleIncomeModes).find(k=>vehicleIncomeModes[k]===body.mode);delete body.mode;}if(body.original){body.original_id=Number(body.original.split(' · ')[0]);delete body.original;}return api(`/api/vehicle-income/${r.id}/actions/${key}`,{method:'POST',body:{request_id,version:r.version,values:body}});},{caseId:r.id,notice:key==='propose'?'本版目标和开票依据须另一位主管独立核对。修订为零仍保留原收入与现金，超收交财务按原款退回。':'只登记本人实际核对的事实；批准不代表到账，退款不能改变原账户或超过已批准原额度。'});
}
document.addEventListener('click',async event=>{const e=event.target.closest('[data-act]');if(!e?.dataset.act.startsWith('vehicle-income-'))return;try{if(e.dataset.act==='vehicle-income-new')await vehicleIncomeNew();if(e.dataset.act==='vehicle-income-action')await vehicleIncomeAction(e.dataset.key);}catch(error){toast(error.message,true);}});
