'use strict';
let visitActivityState={};
function clearVisitActivitySession(){visitActivityState={};}
function vaContext(){const key=String(state.user?.id)+':'+state.store;if(visitActivityState.key!==key)visitActivityState={key,filters:{},options:{}};return visitActivityState;}
function vaFilters(){const ctx=vaContext();return `<form id="visit-activity-filters" class="filterbar"><label>接待、售前或维修原单<select name="case_id"><option value="">全部获权原单</option>${(ctx.options.cases||[]).map(o=>`<option value="${o.id}" ${String(ctx.filters.case_id)===String(o.id)?'selected':''}>${E(o.label)}</option>`).join('')}</select></label><button type="submit" class="primary">筛选实际记录</button>${b('va-clear','清除筛选')}</form>`;}
function vaTable(key,t){const rows=t.rows.slice((state.page-1)*25,state.page*25),link=r=>r.route?.type==='case'?b('open','查看原单',`data-route="case/${r.route.id}"`):'—';return panel(t.title,b('va-export','导出本表',`data-key="${key}"`)+`<div class="work-table">${table([...t.headers,'原单'],rows.map(r=>[...r.values.map(E),link(r)]))}</div><div class="work-cards">${rows.map(r=>`<article class="card">${t.headers.map((h,i)=>`<p><span class="muted">${E(h)}：</span>${E(r.values[i])}</p>`).join('')}${link(r)}</article>`).join('')}</div>`+(t.rows.length?pager(t.rows.length,state.page,25):empty('本表暂无实际记录')));}
async function visitActivityPage(){const ctx=vaContext();let d;try{d=await api('/api/visit-activity-reports?'+new URLSearchParams({...state.dates,...ctx.filters}));ctx.options=d.options;}catch(error){if([404,409,422].includes(error.status))return heading('跟进与进出厂统计','修改条件后重新查询。')+storeNotice()+dateFilters()+vaFilters()+`<div class="notice error" role="alert">${E(error.message)}</div>`;throw error;}
 return heading('跟进与进出厂统计','从原始沟通、到店和离场记录核对实际业务。')+storeNotice()+dateFilters()+vaFilters()+`<div class="notice ${d.complete?'':'error'}">${d.complete?'本次获权来源可核对；不代表未录入的历史完整。':'存在来源待核对；下表只统计具有明确来源的实际记录。'}</div><div class="kpis">${[['售前实际记录',d.metrics.presales_contact_events],['实际到店次数',d.metrics.service_actual_arrivals],['实际离场次数',d.metrics.service_actual_departures],['到店批次尚无离场记录',d.metrics.service_arrival_cohort_without_departure]].map(([name,value])=>`<article class="kpi"><div class="label">${E(name)}</div><div class="value">${value}<span class="unit">次</span></div></article>`).join('')}</div>`+`<p class="muted">查询快照：${time(d.as_of)}。尚无离场记录不能据此认定车辆仍在厂。</p>`+`<details class="definitions"><summary>查看实际来源与统计口径</summary>${d.definitions.map(s=>`<p class="muted">${E(s)}</p>`).join('')}</details>`+d.charts.map(c=>panel(c.title,chartSVG(c)+b('va-export','导出此图原始行',`data-key="${c.table}"`))).join('')+Object.entries(d.tables).map(([key,t])=>vaTable(key,t)).join('');}
document.addEventListener('submit',event=>{if(event.target.id!=='visit-activity-filters')return;event.preventDefault();vaContext().filters=Object.fromEntries([...new FormData(event.target)].filter(([,v])=>v!==''));state.page=1;render();});
document.addEventListener('click',async event=>{if(event.target.closest('[data-act=va-clear]')){vaContext().filters={};state.page=1;render();return;}const button=event.target.closest('[data-act=va-export]');if(!button)return;button.disabled=true;try{await download('/api/visit-activity-reports/export/'+button.dataset.key+'?'+new URLSearchParams({...state.dates,...vaContext().filters}),'huakangos_实际跟进与进出厂.csv');}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
